### ISSUE TITLE
Invisible files/unrecognised files

### ISSUE THREAD

**Issue by dominiongalactica** [inkstitch/inkstitch#1002]
Hello, 

I have no idea if I am in the right place. please delete if so.

I recently purchased a "Janome memory craft 9850 special edition" and I have spent days making a small "star trek" image, but every time I save the file to a USB drive, it is not recognised by the machine.

I had tested .jef files from the Janome website to check that the machine works, and they appear and I can access them.

When I use inkscape/ink stitch to "save as"  > .jef and move it to various drives (I have tested every drive that I have) they simply are not there when I attempt to access them.

Is it the case that my machine just doesnt work with inkstitch? 

thank you for any assistance you can provide in this area.

**Comment by MK-12-20MM** [comment]
Thoughts..
Have you tried formatting the usb from via the machine?  The usb should have a directory structure of emb/embf.  File names if too long wont show up ( 8 characters).  Do you have a bunch of files on the usb?  Make sure you are in Embroidery mode instead of ordinary.  

If you want or don't mind, zip up the svg and a jef and I can see what is does on mine. I don't have a 9850 but Janome is Janome for the most part.

**Comment by dominiongalactica** [comment]
Thank you for your suggestions. I have formatted the USB drive. At times I can see both the ord/emb folders and their ordf/embf nested folders but no files within.

I have placed a file called "trek" (only 4 characters) in each various folder and none of them appear.

I downloaded a .jef file from the Janome site and it appears and I can access it.

I am not in the frame of mind atm to continue any firther for fear of reaching breaking point, but thank you for your very kind offer to suss out the file. I will come back to this later when I am less overwhelmed. 

THank you again.

**Comment by MK-12-20MM** [comment]
If you want:
I have attached an test svg and jef file that my janome can read. If you want to try to see if if reads on your machine
[testjan.zip](https://github.com/inkstitch/inkstitch/files/5893406/testjan.zip)

The only other thing I can think of is that Janome can be fussy with hoops size vs design size vs origin.

**Comment by SignMyPublicKey** [comment]
I'd like to join the discussion if that's ok. I've tested the same thing, e.g. cannot read files with the machine, including the testjan.jef. My machine is a Janome MC 11k SE.

I can add a snippet of information. If I try to open the file with the AcuFillPrintTool from the MC11kTools, it gives the error 

`There is an error in a file. Quit Operation.` 

I have a similar issue with a design I made with InkStitch. Exported via the extensions *Embroider* function. The design passes all the sanity checks from the extension.

Thanks for any input you have to resolve the issue :)

**Comment by MK-12-20MM** [comment]
That test file is from sample files - https://inkstitch.org/tutorials/resources/samples/.  You would think it should work.. :)

BTW I am just a user - not a dev.  I have Janome and brother machines. My Janome is a 450e. Been a user for a couple years.   

Do any designs work at all, something simple created with Ink/stitch? I am going to assume that other designs sourced else where work with no issues? 

Hidden artifacts ? 

Duplication of layers?

Also try using saving as a jef instead of using the Embroider function. 

Designs right on the edge of the document size can cause a problem - I just had one of those. 

Any stops or trims added?

There is something in the file that the machine does not like. In a nutshell it's isolation or whittling down what the machine does not like. At least that is has been the case for me. 

I guess if you can make some simple design or basic shapes just for test and see if that works and if it does not post it here.. I can try it in my machine. 

Another thought would be to see if the file opens with HATCH .. I believe they still give free trials. I have used hatch to look at ink/stitch files when I had file error issues in the past and vs versa - designs created by hatch and opened with inkstitch just to see the difference.

That is all I can think of at the moment..

**Comment by ghittub** [comment]
The Janome software product to create and edit embroidery design files expects certain parameters to be included in the file, in order to be recognized by Janome machines.  The Janome Artistic Designer (about $1,000 retail) could open thos non-working files, re-save them and provide the requested info by the software and it will work -according to what i have read elsewhere.

**Comment by kaalleen** [comment]
I'll close the issue due to its age. Please open a new issue if the problem still persists.
