### ISSUE TITLE
Inkstitch/Inkscape for Ipad

### ISSUE THREAD

**Issue by badspeller64** [inkstitch/inkstitch#1035]
I was wondering if you guys have considered making an inkstitch/Inkscape for the iPad. I LOVE my iPad and use it exclusively for my designs and would love to have an inkstitch program that works on it so I could digitize my embroidery files on my ipad as well. I understand these digitizers require a lot of processing power, but the new Ipads are getting better and some of them are almost equivalent to small laptops. Just an idea.

**Comment by wwderw** [comment]
This, to my knowledge, would be highly dependent on the Inkscape project having builds for iOS, which I'm unaware of.  At one time, there was an individual that had versions of Inkscape and GIMP on Android, but that was using WINE which caused huge overhead on resources. 

I'm not even sure GTK itself will build on iOS/Android as well.  I think it's just for desktop UIs and that's the UI tookit that Inkscape uses.  The other major toolkit for UI, Qt, does have this ability, but I do not think GTK does.

I don't even know if there is an iOS/Android port for Electron.  The Electron part of Ink/Stitch would probably have to use Cordova/Phone Gap.  I do think you can run Electron on ARM, but not necessarily iOS/Android.  And I think with Cordova, the Electron project probably aren't going to go there since there is Cordova.

**Comment by kaalleen** [comment]
Since we depend on Inkscape for that. This is currently not planed.
When Inkscape is able to run on an Ipad, we will reconsider ;)
