### ISSUE TITLE
Auto Fill prevent gaps in enbroidery by overlapping rows 

### ISSUE THREAD

**Issue by Tina-Chris** [inkstitch/inkstitch#1068]
Dear Inkstitch developers
I would like to suggest the following improvement for auto fill area:

When digitizing with autofill the autofill function often comes from different directions to close all gaps. Sometimes, depending on the tissue and the shape you digitize, this will result in a gap between the rows at the end. I read that other softwares have a function to prevent that. It overlaps the last 1-2 rows with the previously stitched rows to eliminate the gaps. This is especially important for knit fabric as there is more shift even when hooped tightly.
In the facebook inkstitch helper groups the question about how to eliminate the gap comes up fairly regularly, indicating that alot of persons would benefit from this option. Therefore, I think this would be well invested time to improve the auto fill stitch with this, either as a tick on/off box or as build in.

Thanks! B-ellanna

**Comment by kaalleen** [comment]
@wwderw do you know an option like this?
Any idea how the stitches should be distributed on the additional rows?

**Comment by wwderw** [comment]
What this sounds like is an issue with what is known as "long stitches".

Which usually happens at the end of the design and its a result of the start/end points of the object relative to the stitch angle.

This is something that all digitizing software has an "issue" with.  And when one lets the software choose start/end points and the stitch angle, it is almost always going to result in this.

I only know the "manual" solution and that is to change the end point to the smallest area possible of the object (that would also facilitate good production time for long runs, mainly thinking of traveling stitch location to connect to the next object in the design, if applicable) and change the stitch angle accordingly to match it.  For instance, if it was a circle object, make the start/end points at 6 and 12 o'clock and a horizontal stitch angle.  Depending on the object, can't totally eliminate it (with your "simple" objects more then likely should be able to), but the goal is to minimize it's presence and hopefully hide it with stitching on top if that is apart of the design.

With the added issue of the knit fabric, it would also help to use a lattice motif underlay (in the same color as the substrate) or to use a solvy topping.  I tend to like to use the lattice fill extended a little bit following the contour of the overall design.

If that is what the OP is talking about, that's the solution that I am aware of, a more manual, but software agnostic approach.

**Comment by B-ellanna** [comment]
See here a image where you see what kind of gap I mean.![149254094_3811976548841533_5723692527343343630_o](https://user-images.githubusercontent.com/64272979/110211799-91bacf80-7e98-11eb-928a-dab784b40e2c.jpg)
The problem originates as the fill is complex and somewhere the last stitches have to meet. 
![overlapping_rows](https://user-images.githubusercontent.com/64272979/110211838-b44ce880-7e98-11eb-808b-f0fb5cd261ad.jpg)
So 1rst part travels i.e. in from the top (green) and 2nd part (blue) travels in from the bottom. My suggestion was meant in the following: would it be possibe to let blue travel over green for 2 rows. 
I'm well aware of the stitch angle and start and stop position "hacks". But for beginners and casual users it's quite a lot to grasp. I stand firm that this feature would make the program more accesable to a broader audience as beginners would not get disheartened in their first trys with using the fill stitch feature.

What is a lattice motif underlay? I'm not aware of this embroidery term. What is the distinction to the standard 3x spaced underlay?

Thanks
B-ellanna

**Comment by B-ellanna** [comment]
https://youtu.be/y1OoDWsHuug?t=118 From this john deer embroidery video and your previous reply I concur that in inkstitch we currently would need to do it as in (as he calls it) "the olden days". Which is quite time consuming and has a even steeper learning curve. In the position here of the same video: https://youtu.be/y1OoDWsHuug?t=335 I quote: "And the software does overlap a little bit between these areas so that you won't have gapping of stitching as well". So I would encourage to see if the fill stitch algorithm can be "convinced" to do a overlap automatically if threads travelling from the top and bottom meet.

**Comment by wwderw** [comment]
Yep, that is long stitches.

The method that I outlined is not actually that involved or with a steep learning curve.  It would actually take less time to do that then it would to digitize the cat.  The learning curve would only be to find out where it is in the software to do it.  Wilcom is going to be different then Ink/Stitch etc.

The concern that I would have is going over and adding more stitches in there, depending on where it is in the pattern, the fabric that is on there etc, that could lead to other issues, birds nesting, thread/needle breaks etc.  Depending on how the program does it all.  

Then stack on top of that, if something is going to be stitched out in that area, is it going to be adversely affected.  Raised slightly more due to the extra stitching etc.

It certainly won't be an issue all the time, but I'm always one of those that it's best to know the 'manual' way, just in case the auto way lets "you" down.

A hybrid may be the best thing in certain circumstances, using the auto way and then knowing how to fix it if something goes wrong for a specific pattern.

It doesn't help with the implementation of it programmatically, just a concern that I would have in the back of my mind.

**Comment by B-ellanna** [comment]
Okay I see. We need to educate our users better is the easiest solution.

**Comment by lexelby** [comment]
Ah, this problem.  I keep going back and forth on this in my mind.

This happens because of fabric distortion.  Ink/Stitch sews one part, then goes off and does other parts, and as it does, the fabric stretches and distorts due to the stitches.  When it comes back to fill in the rest of the shape, you can sometimes get that gap.  Better/more stabilizer and more underlay stitching can help.  Sometimes you add underlay and more stabilizer and it _still_ has a gap.

I'm torn as to whether to add overlap or not.  @wwderw is right that the extra rows could cause problems.  There's another problem: the extra rows could disrupt the fill stitch pattern.  Fill stitch is done in staggered rows, and those extra rows would not match the pattern.  You can see the pattern in the Simulator by enabling needle penetration points.  Your eye would be drawn right to the extra rows.

The biggest reason I haven't done it yet, is... I don't know how!  The fill stitch algorithm is quite complex, and it took me literally years to figure out how to write it.  It's not immediately clear to me how I could add those extra rows in. It's probably possible, but it would be quite difficult.  If someone wants to take a shot at it, that would be cool :)

**Comment by lexelby** [comment]
I gave this some thought and I have a possible idea for how to do the overlapping.

Here's an example shape:

![image](https://user-images.githubusercontent.com/4446653/211170990-c70bc44e-6c9b-41b2-b772-095696fb0a93.png)

The red areas are places I think gapping may occur.  I just picked spots where a row is stitched and then its neighbor is stitched much later.  How do we do the overlap?

Just going and stitching a couple more rows past the end of a section doesn't really work as far as I can tell.  There's no promise that you'll end up near where you started to do the overlapping.

Instead, how about this: after stitching the underlay, we do a first pass and stitch a few rows around those red spots at the beginning.  Then we go and sew the actual fill stitch like normal.  The spots where gaps would normally occur will already have stitching, so the gapping should be avoided.  I _think_ that the fill stitch pattern shouldn't be disrupted too much, but I'll have to give it a try.

The nice thing about this idea is that it's pretty easy to do, code-wise.  Not trivial, but totally doable.

**Comment by lexelby** [comment]
That looks something like this:

![image](https://user-images.githubusercontent.com/4446653/211171392-9d4ea679-93ff-45e3-a78a-0705345c6b92.png)

Of course, there would be stitches to travel between the yellow lines, but we don't have to be particularly careful about them because they will all be covered in the end.  Even if that travel stitching showed up in a gap, I'm pretty sure it would be completely unnoticeable.

**Comment by Tina-Chris** [comment]
I'd think that would be worth a try. I think an Embroidery on Jersey with
the new and old algorithm would quickly give us a suitable or not answer?
Tina

Am Sa., 7. Jan. 2023 um 22:46 Uhr schrieb Lex Neva ***@***.***

**Comment by lexelby** [comment]
I don't have any jersey fabric, but I'm pretty sure embroidering on knit without stabilizer would do the job.

**Comment by Tina-Chris** [comment]
Jersey is a kind of knit fabric. So, this sounds perfect

Lex Neva ***@***.***> schrieb am Mo., 9. Jan. 2023, 14:20:

**Comment by rlevine** [comment]
I inadvertently created an example sort of like @lexelby's solution. I had to put marker lines into my .svg while I was hand-editing in some pull comp to be able to know what stitch points to move, and left the lines visible when creating a .dst file. :) This stitch-out does have some pull comp, which is covering the gap, but the underlines are there.

![underlay](https://user-images.githubusercontent.com/2294569/220765525-451eaf9c-1878-44e9-b553-e34def2b9acf.jpg)

I don't think it'll work that well, unless the fill is really bullet-proof. The extra lines still telegraph through.

I haven't looked at the code, but is there a patch region stage where you can do the heavy lifting? Something like: Identify patches that share an edge; pick the second one stitched; determine the direction towards the earlier patch; and extend the polygon edge by an effective 0.1 or 0.2mm. The downstream stitcher won't know it's been jiggered. 

As I watch the machine create distortion, the pull doesn't seem to be about overlapping, although it may happen slightly; the first patch boundary stitches are pulled out of the way of the next stitches by the distortion. The second patch comes down on mostly clear fabric.

**Comment by lexelby** [comment]
> I inadvertently created an example sort of like @lexelby's solution. I had to put marker lines into my .svg while I was hand-editing in some pull comp to be able to know what stitch points to move, and left the lines visible when creating a .dst file. :) This stitch-out does have some pull comp, which is covering the gap, but the underlines are there.
> 

Hmm, I'm not sure what exactly you're referring to.  Are you saying you still see a line where the gap was, or are you saying you see the underpath showing through?

> I haven't looked at the code, but is there a patch region stage where you can do the heavy lifting? Something like: Identify patches that share an edge; pick the second one stitched; determine the direction towards the earlier patch; and extend the polygon edge by an effective 0.1 or 0.2mm. The downstream stitcher won't know it's been jiggered.

Alas, that's not quite how the algorithm works.  It builds a graph (as in graph theory) of lines of stitching, then finds an Eulerian path through it that includes all of the rows of stitches.  It constructs the path carefully so that it do the underpathing on sections that haven't been stitched yet.  There's no breaking the shape up into sub-regions in auto-fill, not anymore.  The only place we do that is in the legacy fill which is so old I really ought to just get rid of it.  Bottom line: we do what the graph tells us to do, so there are no sub-regions to extend. :)

**Comment by rlevine** [comment]
> Hmm, I'm not sure what exactly you're referring to. Are you saying you still see a line where the gap was, or are you saying you see the underpath showing through?

Apologies my photo doesn't show the understitching clearly. I don't think I have the stitch out any more :( but I've tried to point out the understitch areas in this version. I wouldn't treat this example as definitive, as I think the lines got beaned; they may be heavier than needed.

![underlay_annotated](https://user-images.githubusercontent.com/2294569/221370960-42e57907-f880-491e-b1dc-d40c582886e6.jpg)

**Comment by lexelby** [comment]
Ah, okay, so the areas with extra rows seem a little thicker.

Honestly, I think it's going to vary with the row spacing, the number of extra rows added, the fabric, and even the type and color of thread.  I suspect in most cases it won't be as obvious.

**Comment by wwderw** [comment]
What's the top layer going to be like on that fill?    Is the design such that instead of you digitizing one big fill, you digitize several fills, connect them where appropriate (again depend on what is/isn't going to be covered up with later stitching and how).  That way, those angles can be hidden in smaller areas of the design?

If that isn't an option, I notice that there are small areas of negative space going into the center line line of the fill in a couple of areas, is there going to be a satin outline that is going in that area or is it always going to be exposed negative space, if it's going to be eventually covered up, I would get rid of the negative space insets and make it one solid piece.  Ironically, if that was done for stitch count reduction, doing that may actually add to stitch count versus not having them in there.  Reason being is the underlay travel stitching may have to do more work to compensate for those areas versus not having them in there in the first place.  Not always the case, don't really know until try it both ways, it depends on objects shape, start and end points, as well as, stitch angle.

I don't know one way or the other, I'm just throwing that out there.

**Comment by lexelby** [comment]
I've made an attempt at gap filling in #2884!
