### ISSUE TITLE
G-CODE output not applying custom commands

### ISSUE THREAD

**Issue by R1N4x** [inkstitch/inkstitch#1104]
So I'm using ink/stitch for a few weeks now with a Singer machine and I'm happy with it.

But I'm looking into building my own machine and decided to play around with the g-code export in ink/stitch and came across a hiccup.

The dialog gives the possibility to enter custom g-code for some actions but those entries don't take place in the actual export?
 ![image](https://user-images.githubusercontent.com/29910692/112561444-85f66500-8dd5-11eb-8820-68af80e26a35.png)

![image](https://user-images.githubusercontent.com/29910692/112561456-8e4ea000-8dd5-11eb-9949-46dcd3a8c711.png)

![image](https://user-images.githubusercontent.com/29910692/112561476-97d80800-8dd5-11eb-9006-544ceaf7df21.png)

Have I done it wrong? I wasn't able to find any information on this feature sadly.

I was hoping just to replace the "G0 Zn" line with my own g-code in the export so I don't have to use external tools.

(Yes I'm using g-code from Marlin but that shouldn't make a difference, right?)

**Comment by kaalleen** [comment]
No, you haven't done something wrong. In the last official release we did not update a library which is necessary to apply your custom g-code. If you don't mind to run a development version, download it from here: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-lexelby-params-fixes
It is almost ready for a next release. We appreciate feedback on possible errors ;)

Since we are close to the next release and if you don't want to update your version all the time, it is also possible to wait for about a month until we release a new version of Ink/Stitch.

**Comment by R1N4x** [comment]
Ah okay, at least I can tinker around for now.

But right away: 
Are those coordinates gonna keep that enormous decimals when using custom commands?

![image](https://user-images.githubusercontent.com/29910692/112718977-a36f2000-8ef6-11eb-92bb-4af79999a7ad.png)

![image](https://user-images.githubusercontent.com/29910692/112719027-db766300-8ef6-11eb-9b23-57480210a9ea.png)

**Comment by kaalleen** [comment]
No, definitely not. Thanks for the hint!

**Comment by lexelby** [comment]
What, your machine isn't precise down to the trillionth of a millimeter?? ;)
