### ISSUE TITLE
macOS intallation: libc.dylib

### ISSUE THREAD

**Issue by brinandains** [inkstitch/inkstitch#1144]
We are having an issue with the libc.dylib file. This is preventing us being able to open params as it is "missing". We followed all the other steps and this is the last issue we are having. Are we missing something?

**Comment by kaalleen** [comment]
Which macOS version are you using?
We recently found out, that the 'big sur step' is now necessary on catalina as well.
https://inkstitch.org/docs/install-macos/#addtitional-steps-for-catalina--big-sur

I would update the documentation, but with the next update, this extra step isn't necessary anymore. Since we are close to our next release, I decided to not do that. Sorry, if this has been an issue to you.

**Comment by kaalleen** [comment]
Fixed in the newest release. Please reopen if problem still occurs.
