### ISSUE TITLE
Underlay problem 

### ISSUE THREAD

**Issue by yieselle4** [inkstitch/inkstitch#1162]
Hello, I was using Inkstitch and got everything sorted out but the black part that is supposed to be just the outline is shown as all of the bllack showing then the other colors on top. I have seperated the black part onto another layer but do not know what to do next. To clarify the black thread is sewing all throughout the bottom of the design and I just want it as an outline. I have attached a document. Thanks. 

[bubbles.zip](https://github.com/inkstitch/inkstitch/files/6361790/bubbles.zip)

<img width="1254" alt="Screen Shot 2021-04-22 at 4 37 27 PM" src="https://user-images.githubusercontent.com/81942055/115797560-0edacf00-a389-11eb-9b04-a85224f1a446.png">

**Comment by kaalleen** [comment]
This happens, because the shape is filled with a black color. In the fill and stroke panel you can deactivate it and only use the stroke.

But then you will only see the outer outline, which maybe isn't what you want. To get a good result you will have to put more work into it and create satin columns into the spaces of your colored elements. There are some videos out there on youtube how this is done.
