### ISSUE TITLE
Fonts - Amita

### ISSUE THREAD

**Issue by ghost** [inkstitch/inkstitch#1193]
For example the capital S instead of just Satin columns also has a fill which makes the stitch density inconsistent with the other letters. If the letters are on top a fill, can cause a huge issue and even up to needle breakage depending on the user design. IMHO somewhat destructive. 

In preview - Obviously Satin with underlay and a fill.

![image](https://user-images.githubusercontent.com/10312448/117440301-7f412e80-aef9-11eb-9a23-71ff7c415886.png)

Looking at the glyph 

![image](https://user-images.githubusercontent.com/10312448/117441073-7c930900-aefa-11eb-96e3-9d227300e829.png)

There are other glyphs with fills in this font.
 
Also - Most of the new fonts if not all have trims disabled or not selectable via "auto_satin": false in the font.json file for the font.
Not sure of the mindset of not letting the user decide in the lettering tool to apply trims, which at face value could frustrate users.  

Of course you can apply trims to the objects manually, which is additional workflow which defeats the purpose of having this option in the lettering tool in the 1st place. Not sure if trims should or could be be decoupled from auto_satin parameter to its own parameter in the font.json.  In any case the parameter can be edited to true in the font.json if you want the option for enabing trims (unless this has changed in the new release).

**Comment by Augusa** [comment]
Of course, we probably forgot an invisible object in the file of the letter. But if you valid the problem will disappear and the bad path is not embroidered. As you can see it is just the path6110. You can suppress it in the file if you want. It is not really a problem but we are disappointed to discover this error. We have created a lot of fonts for inkstitch. We hope you will enjoy.[cid:490cc019-8f3b-4d86-99ae-4a75b4d7f8ae]
________________________________
De : MK-12-20MM ***@***.***>
Envoyé : vendredi 7 mai 2021 13:41
À : inkstitch/inkstitch ***@***.***>
Cc : Subscribed ***@***.***>
Objet : [inkstitch/inkstitch] Fonts - Anita (#1193)


For example the capital S instead of just Satin columns also has a fill which makes the stitch density inconsistent with the other letters. If the letters are on top a fill, can cause a huge issue and even up to needle breakage depending on the user design. IMHO somewhat destructive.

In preview - Obviously Satin with underlay and a fill.

[image]<https://user-images.githubusercontent.com/10312448/117440301-7f412e80-aef9-11eb-9a23-71ff7c415886.png>

Looking at the glyph

[image]<https://user-images.githubusercontent.com/10312448/117441073-7c930900-aefa-11eb-96e3-9d227300e829.png>

There are other glyphs with fills in this font.

Also - Most of the new fonts if not all have trims disabled or not selectable via "auto_satin": false in the font.json file for the font.
Not sure of the mindset of not letting the user decide in the lettering tool to apply trims, which at face value could frustrate users.

Of course you can apply trims to the objects manually, which is additional workflow which defeats the purpose of having this option in the lettering tool in the 1st place. Not sure if trims should or could be be decoupled from auto_satin parameter to its own parameter in the font.json. In any case the parameter can be edited to true in the font.json if you want the option for enabing trims (unless this has changed in the new release).

**Comment by MK-12-20MM** [comment]
Yep.. Stitch plan does not show the fill.  That is good.  Lesser of an issue.  It still a problem from a user standpoint to cause confusion as preview is not consistent with actual output.. 

In any case, nice work on the fonts as I know is a lot of tedious work involved.

**Comment by kaalleen** [comment]
> lso - Most of the new fonts if not all have trims disabled or not selectable via "auto_satin": false in the font.json file for the font.
Not sure of the mindset of not letting the user decide in the lettering tool to apply trims, which at face value could frustrate users.

This was made that way, because the Ink/Stitch lettering tool only has code to insert trim commands through the auto-route algorithm. It surely makes sense to implement this capability for non-auto-route letters as well. It just hasn't been written up yet.

**Comment by MK-12-20MM** [comment]
Yes, I was aware previous to this release.  Thanks for the response.  Nice work on v2.0 as this is a huge milestone for Inkstitch.

**Comment by MK-12-20MM** [comment]
Just going to add this here - Learning curve font is missing the punctuation "!" glyph  in the  →.svg. It's defined in font.json for the font.  

Another minor thing - 2 fonts in the lettering tool - Descriptions are in french. The rest of the fonts Descriptions are in English.  Not a big deal to me but not sure if this piece or aspect should be locale driven for consistency.

**Comment by Augusa** [comment]
One created the json file and another one the embroidery. Yes it is possible!!!. But now you will create the embrodered ! and offer it to the community and everything will be perfect. Thanks. The embroider creates the glyph he chooses. Please note that a font always lacks a lot of characters, for example accented characters for other languages ​​and a choice is always to be made. It is the creator of the embroidered letters who decides.

**Comment by MK-12-20MM** [comment]
I don't know if you realize this, but your response (context) is very condescending and leans towards defensive.  I would suspect a language issue so I am not offended.  Just so you are aware - other people may understand.

**Comment by MK-12-20MM** [comment]
I don't have write access. 

new svg is in the zip .  Only modification was addition of the glyph for punctuation "!"
Comparison with the original font.  The "!" stitches the same as modeled by the "?"
  
![image](https://user-images.githubusercontent.com/10312448/119230230-f32a2c00-bae0-11eb-8195-80eddeac522a.png)


[learning_curve.zip](https://github.com/inkstitch/inkstitch/files/6526584/learning_curve.zip)

**Comment by Augusa** [comment]
Comment allez-vous réagir si je vous dis que votre ! est en point simple quand tout le reste de la police est en point triple? 
Je n'ai pas plus que vous de droit en écriture et je suppose qu'il faudra de toute façon attendre une prochaine version pour que ce soit éventuellement modifié.

**Comment by Marif91** [comment]
Bonsoir,
Il se trouve que j'ai transformé cette police en police de broderie avec l'accord de l'auteur, je serais ravie d'être informée si certains manquants vous semblent essentiels, je complèterai ainsi le travail démarré.

**Comment by Marif91** [comment]
Bonsoir,
J'ai préparé la broderie de cette police, elle est effectivement en point triple. Comme tous les caractères démarrent à quelques mm de la ligne de base, il y a d'abord un point droit pour rejoindre le haut du point d'interrogation, puis un point triple (bean stitch) pour faire le tracé. Effectivement le point d'exclamation proposé n'est pas conforme à la règle.
Je veux bien faire de nouveaux caractères si vous pensez qu'ils sont essentiels, mais je ne souhaite pas que ce fichier soit corrigé sans en être informée, ça me semble être une règle du travail en commun.
Bien cordialement,
Marif

**Comment by MK-12-20MM** [comment]
> How will you react if I tell you that your! is single point when all the rest of the font is triple point?
> I do not have more write rights than you and I suppose that we will have to wait for a next version anyway for this to be possibly modified.

I have no reaction other than Thank you! That is my mistake. At the same time I wouldn't put mixed stitching embedded into the font or let the users decide. User Machine, User thread, 

 Although somewhat this a moot point, if the user selects the character it and modifies the bean stitch, what is in the font will get overwritten anyway.  I did not notice the bean parameter as I would not of done this (if I was doing this font), extra work as the user can over write the work anyway.  Especially  the case of people doing redwork.  So what I think as far as design,  got into the way. Sorry

**Comment by MK-12-20MM** [comment]
> Good evening,
> I prepared the embroidery of this font, it is indeed in triple stitch. As all the characters start a few mm from the baseline, there is first a straight stitch to reach the top of the question mark, then a triple stitch (bean stitch) to make the path. Indeed, the proposed exclamation point does not comply with the rule.
> I am happy to make new characters if you think they are essential, but I do not want this file to be corrected without being informed, it seems to me to be a rule of the work together.
> Sincerely,
> Marif

Hi,

I wasn't attempting to be critical, just wanted to point out that the exclamation point was missing. All the punctuation is in the font.json, but missing from the SVG.  Maybe this is a language thing, and context is missing from translation, but exclamation point is just important as period and question mark. Definitely necessary.  At least in the states that will frustrate users and not use your font.  If you decided on no punctuation in the font - that would make sense versus having one missing.   I hope this translates right and makes sense..

**Comment by Augusa** [comment]
Did you noticed that the new fonts have letters for french, german, spannish, some also for italian who where really frustrated with six fonts only for english? I have to say also that the principe of lettering tool in an embroidery software is that fonts are ready to use. I don't know if you use other softwares. In Inkstitch you can change a lot of params and it is not always a good idea because it is not at all clear which params are consistent. For changing a simple runstitch font to a beanstitch one it is necessary to turn only top pathes to beanstitch and it is necessary to split a lot of pathes in underpathes and top pathes. Not so easy. If you want a font in simple runstitch try Sacramarif.  Hope you will find some font which you can use with pleasure.

**Comment by kaalleen** [comment]
@MK-12-20MM thanks for creating missing characters for existing fonts. This is how I believe open source works. If you want to get write access just inform us and I'll send you an invitation to join Ink/Stitch.

Write access means you will be able to create pull requests that then can be tested and corrected before they will be merged into the master branch. So everyone who is interested can test additions, discuss them, request corrections, approve or disapprove the changes. So original font authors will have a chance to see the changes before they will appear in an official release.

@Augusa has written a detailed tutorial how fonts for Ink/Stitch can be created. This tutorial has been translated into English and here is the link: https://inkstitch.org/tutorials/font-creation/ 

Maybe this sheds some light on the fact why the json file contains information about a lot of glyphs which are not present in the actual svg font file. The additional information has been kept in the json files just in case that the font will be extended at a later time.

**Comment by MK-12-20MM** [comment]
> Did you noticed that the new fonts have letters for french, german, spannish, some also for italian who where really frustrated with six fonts only for english? 

Yes, that great. I am well aware the original fonts were missing character sets for other languages. Not sure of relevancy of your comment as with the new fonts are missing characters which will frustrate english users.  Learning Curve is not the only one.    

I have to say also that the principe of lettering tool in an embroidery software is that fonts are ready to use. 

I understand. At the same time - introducing new fonts with missing characters - not so ready to use is it, for English users? 

I don't know if you use other softwares. In Inkstitch you can change a lot of params and it is not always a good idea because it is not at all clear which params are consistent. For changing a simple runstitch font to a beanstitch one it is necessary to turn only top pathes to beanstitch and it is necessary to split a lot of pathes in underpathes and top pathes. Not so easy. If you want a font in simple runstitch try Sacramarif. Hope you will find some font which you can use with pleasure.

I have been user of ink/stitch since almost day one and Inkscape for about 10 years. I have used other embroidery software. The beauty of it is the we can do what we want.  Just a point - What a user wants, and how it is done, and what is deemed necessary is very subjective and depends on desired output that the user wants.

**Comment by kaalleen** [comment]
Closing. I believe missing characters were added and the s has been corrected.
