### ISSUE TITLE
Make preview window resizable

### ISSUE THREAD

**Issue by X3msnake** [inkstitch/inkstitch#120]
@lexelby 

As it is at this moment even if you do a 10mm segment, the preview window extends to the full screen sometime making it hard to see the action.

Can you make the preview window resizable by the user?

**Comment by lexelby** [comment]
That'd be great, wouldn't it?

Right now, the preview code is "stack overflow driven development", essentially.  I learned just enough to cobble the pieces together and get it working, but I don't really know how to do more advanced things with the graphics rendering library.

I wonder, though... With the experimenting I've done for the Print PDF feature, I now know just how easy it is to pop up a window that contains an embedded web browser.  I could rewrite the preview using javascript that generated an SVG object right in the document.  It would add line segments slowly, mimicking the way the preview window works now.

This would be great because, well, it's _S_VG: it's scalable. It'd be super easy to make it so the user could scan and pan around the preview.  It would also be way easier to implement a "rewind" button that would let you go back in time and re-watch part of the preview.

Even cooler: depending on just how CPU-intensive the realistic rendering is (once we figure out the SVG filter effects), preview could possibly have the filter effects enabled, or at least have a button to enable them while the animation is paused.

**Comment by lexelby** [comment]
To answer your question: yes, I can make the preview window resizeable by the user.

**Comment by X3msnake** [comment]
@lexelby one other thing i was thinking while working on the CSS is that we might get away with realistic render using the openGL Css browser effects :)

It is something i am not sure but you can do some nasty effects with blends and inner shadows :)

**Comment by lexelby** [comment]
Oh hey, that's a pretty interesting idea!

**Comment by lexelby** [comment]
For my future reference: https://stackoverflow.com/a/25708292

**Comment by kaalleen** [comment]
Closing this. The preview window is resizable by now. Realistic rendering is realized in the print preview.
Please reopen if needed.
