### ISSUE TITLE
inkstitch 2.0, windows 10, inkscape 1.02. menus greyed out

### ISSUE THREAD

**Issue by buzzmandt** [inkstitch/inkstitch#1216]
I have a YouTube channel and promote inkstitch on it (/lowtechlinux). Works great on manjaro Linux btw.
I also show help for installing on windows 10. I can't get it to work on windows 10, all menus are greyed out.
I read the thread about antivirus. I don't have an antivirus installed with the possible exception of windows defender. 
I'm also getting several comments from users watching the channel that they're having the same issue. If it's a windows defender issue can you point me in the right direction to work around it?
Is there anything I can check for and help out?
I have tried both the user/extensions and inkscape extensions folder.
Great and fantastic project. Keep up the great work. V2.0 is awesome.

**Comment by kaalleen** [comment]
Hey there. Yes, we've heard of this often. Usually greyed out menues are caused by the virus programs as you already found out. I'm no windows user - so there might be better people to help - but is this link of help to you? https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26

**Comment by buzzmandt** [comment]
Thank you Kaalleen. Funniest part is I don't use windows either. I only use Linux. When I get into a windows session I'm totally lost if it's not something basic. 
Thank you for pointing me in the right direction. I'll see if I can do something with it. (Give me a linux terminal any day LOL)

**Comment by buzzmandt** [comment]
antivirus override workaround fixed this issue.
