### ISSUE TITLE
base.py: ensure_current_layer AttributeError

### ISSUE THREAD

**Issue by VikkiInWonderland** [inkstitch/inkstitch#1239]
Hello after the new upgrade here are the 2 messages I try to use the lettering tool The first is when I don't select an object and try to use the lettering tool , second is if I just randomly select any object. I saw some similar error messages on this board however idk if any of them were specific to the lettering tool. Anyone know what's going on here?thx☻☺♥
![4d339df4ccd94ca170d2c5a7438800ea224fede5-1](https://user-images.githubusercontent.com/85437374/121117366-df631300-c7cc-11eb-914c-2f26c863942d.jpg)
![2ab262c6304340bf72d86580bdd29110f771a889-1](https://user-images.githubusercontent.com/85437374/121117375-e427c700-c7cc-11eb-9480-de2b05f9dae8.jpg)

**Comment by kaalleen** [comment]
Thank you for your report. This is valuable for us. The second image is easy to explain. The Ink/Stitch lettering tool tries to parse the selected object as text which has been created with the lettering tool itself. If it cannot parse the text (e.g. because you selected a normale path or shape object) it will output this message.

The first image is very interesting and definitely a bug in Ink/Stitch. You shouldn't be seeing this message at all. I am not very sure though why it is happening. Ink/Stitch somehow seems not to be able to get the current layer into which it will paste the new text into. I tried to reproduce by creating an empty document with nothing in there, not even a layer. But I cannot reproduce. Do you experience this error message with every file and document or are you working on a special file when it is happening? If so, I would be very curious to have a look at that file. You can post it here or send it to send-us-files@inkstitch.org
