### ISSUE TITLE
What's the most feature-ful format?

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#1259]
Kind of a meta question, but: when I'm buying embroidery designs to pull into Ink/Stitch, what's the best format to pick? I've been picking PES just because that's the machine I had, but I just went in to update my Urban Threads profile for the larger format machine (I got a sweet deal on a used MC400e!) and suddenly went "oh should I set it to JEF or...?"

I know PES has trims in the file even though the PE800 doesn't (honestly the most exciting feature of the 400e for me, even above the larger frame size) but are there other features that the PES won't have that some other format will?

**Comment by wwderw** [comment]
Neither one of those ironically.

Your 2 most feature rich (in my opinion) are going to be your Barudan U?? files and your DST files.  The U?? file actually beats the DST file by one feature (my favorite), but it is limited to just Barudan machines.  That one feature is being able to insert slow/fast commands.  Now for some machines, that can be done using software that is directly connected to the machine and done on the fly, but what I am talking about is embedded in the file itself.  Even Ink/Stitch can do it for the U?? files (same method as I have to use to embed sequin information as well for my Barudan machine), but just not through the GUI extension.

Otherwise, feature for feature, DST and the U?? file are pretty much on equal footing (they both have trims by the way and in all honesty, how PES handles trims is not the most efficient as well).  The only thing that files like PES do that DST and U?? files don't, is that they have a simple color palette that will show up on screen, while the others won't.  But in the case of PES, that can lead to other production issues that need little quirky digitizing methods to compensate for.  So it all has it's pros and cons.

Now, of course, even if your machine can handle DST doesn't mean that it will be able to yoke all of the benefits of said format as well.  Not all Barudan machines read slow/fast commands or are able to handle sequin embroidery.  Just like Brother machines aren't able to handle a simple stop command like a DST file can.  Even though some Brother machines do support that format as well.

**Comment by wwderw** [comment]
Your 2 most feature rich (in my opinion) are going to be your Barudan U?? files and your DST files.  The U?? file actually beats the DST file by one feature (my favorite), but it is limited to just Barudan machines.  That one feature is being able to insert slow/fast commands.  Now for some machines, that can be done using software that is directly connected to the machine and done on the fly, but what I am talking about is embedded in the file itself.  Even Ink/Stitch can do it for the U?? files (same method as I have to use to embed sequin information as well for my Barudan machine), but just not through the GUI extension.

Otherwise, feature for feature, DST and the U?? file are pretty much on equal footing (they both have trims by the way and in all honesty, how PES handles trims is not the most efficient as well).  The only thing that files like PES do that DST and U?? files don't, is that they have a simple color palette that will show up on screen, while the others won't.  But in the case of PES, that can lead to other production issues that need little quirky digitizing methods to compensate for.  So it all has it's pros and cons.

Now, of course, even if your machine can handle DST doesn't mean that it will be able to yoke all of the benefits of said format as well.  Not all Barudan machines read slow/fast commands or are able to handle sequin embroidery.  Just like Brother machines aren't able to handle a simple stop command like a DST file can.  Even though some Brother machines do support that format as well.

**Comment by tyrosinase** [comment]
Nice, thanks. I'm guessing since they're mostly targeted at home and home-business embroiderers that they don't take advantage of the extremely high-end stuff (definitely no sequins). I've had my account set to buy PES and yeah, that color palette "feature" is definitely more trouble than it's worth, even in my early days with an Embroidex set of polyester Brother colors where the color numbers should have been correct.

In fact, that's part of why the format I buy from them doesn't really matter: I'm going to pull it into Inkscape, break it into single-color layers, set the colors (I have a custom Sulky palette with all the colors I have capitalized), and put a text object on the screen with the color for that layer on it (so if Ink/Stitch ever adds a text-to-Lettering automation I'm gonna be in trouble :laughing: ), and then Save As even if I'm going straight back to PES. Normally I'm merging the design with an ITH snap tray, or turning a FSL butterfly into individual wings, or whatever so it's really not quite as unnecessary-steps as it sounds. Plus it records the colors I used, since UE/EL uses Madeira.

(Here's both a tray and a butterfly wing. All of the dragons are ITH.)
![IMG_7468](https://user-images.githubusercontent.com/9473609/125666215-84038633-6c2d-4ed4-b627-eb950814c369.JPG)

**Comment by lexelby** [comment]
DST is the most well-understood format, and the one that Ink/Stitch can read the most accurately.  It's actually quite good at JEF too, since I used to own that exact machine (congrats!).  

Probably fine to just set your profile to JEF so that you get (semi-)accurate colors when you open in inkscape.  That just makes it easier to know which part of a design you're on, since you can follow along with the color sheet.  Plus, if you do decide to send a purchased design directly to your mc400e, it'll be the right format.

BTW, I found that I got a lot of thread tails on top of my designs after trims unless I wrapped the thread multiple times around the little metal thing at the start of the thread path.  Maybe that will save you some anguish?

**Comment by tyrosinase** [comment]
It does pull the thread tails on top, but that seems to be fine... manually trimming those with the other end free is a lot easier than trimming tiny jumps cleanly at both ends. Except when it gets run over by future stitching, at least. I'll try wrapping the thread more and see if that makes a difference, thanks.

**Comment by lexelby** [comment]
Yeah, it's that running over thing that got me :)
