### ISSUE TITLE
PES file for embroidery

### ISSUE THREAD

**Issue by emi0213** [inkstitch/inkstitch#1285]
i just downloaded inkspace and inkstich to digitize files. i tried saving my files as .pes but i keep getting this message

Ink/Stitch Version: v2.0.0 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex/base.py", line 141, in run
  File "lib/extensions/output.py", line 56, in effect
  File "lib/stitch_plan/stitch_plan.py", line 26, in patches_to_stitch_plan
IndexError: list index out of range

if anyone could please help, it would be greatly appreciated. thank you.

**Comment by kaalleen** [comment]
Thank you for posting your issue. We have come across this error message before. It usually happens, when you try to render only elements which Ink/Stitch cannot transform into embroidery. This could be a text or image element.

If it is an image, you may want to use image tracing in order to convert it to a vector graphic (`Path > Trace Bitmap...`). Sometimes you rather want to trace the image by hand with the bezier tool to get better results though.

If you have a text element you can run `Path > Object to Path`. Run `Extensions > Ink/Stitch > Fill Tools > Break apart fill objects..` afterwards. Ink/Stitch also comes with a lettering tool (`Extensions > Ink/Stitch > Lettering`). Here you will find a growing amount of pre-digitized fonts. They will look a lot nicer. It is recommended to stay within the given size range, so be careful when you resize these fonts.

Hope these tipps help you with your issue too.

**Comment by kaalleen** [comment]
Further discussion in issue #1307
