### ISSUE TITLE
Lettering has some hangups

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#1321]
I decided to make a sampler because I can't ever remember the relative sizes of the Ink/Stitch fonts, and I ran into some speed bumps. Hitting "apply" on a new font before the preview has started seems to confuse it, but not reliably. Thinking "dang, I didn't default to trims, I should at least trim in between so my (screen-only) preview looks nicer" reliably does it: select all the groups, apply a trim, and it pegs a core of my CPU and, so far, hasn't come back.

![image](https://user-images.githubusercontent.com/9473609/129619106-ff7f5600-766a-4b19-b17d-1ac4c5615018.png)

Ope, no, now it has crashed. So it's not just that my machine is slow. It's getting lost in the weeds somewhere.

(Also as I have just learned, if I select just one of the samples it will put a trim after every object in the group rather than a trim after the group at large. Which is probably how it's supposed to work but wasn't what I was hoping for. But it still shouldn't crash Inkscape, probably.)

**Comment by kaalleen** [comment]
I'll close this issue due to it's age.
If you still are seeing a crash on lettering we appreciate a new crash report :)

Btw. I don't think this exited back then, but on the website the font are listed in relative size: https://inkstitch.org/fonts/font-library/
Also we now have the font size filter which is pretty helpful I think.
