### ISSUE TITLE
Lettering tool sometimes doesn't recognize apostrophes

### ISSUE THREAD

**Issue by kaalleen** [inkstitch/inkstitch#1380]
If I type something with an apostrophe (as in je t'aime) directly in the dialog box of Lettering, the apostrophe is not recognized and ignored. My friends from the French group have solved this problem by typing in some editor first and then cut and paste in the dialog box, and then it is recognized.

_Originally posted by @claudinepeyrat06 in https://github.com/inkstitch/inkstitch/issues/1312#issuecomment-932484273_

**Comment by claudinepeyrat06** [comment]
I kept trying to understand, and after some reading came to the same conclusion. Yes,  it is the system guessing. And the reason why a cut/paste from a editor works is that this particular  editor also is guessing and substituting but the other way around.  
And yes ink/stitch does pick a substitude, but I do not want  a substitute. 

The  single quote is a very recent introduction in french printing, and besides typographers I'm not sure a lot of  French people are aware of the existence of two distinct characters. French language heavily use apostrophe, as it is the sign for elision. For instance  in  "Je t'aime " it stands for the e of te.

If you can disable the system guessing, it's great. But because editors are also substituting, I wonder whether it would not be possible to have inkstitch guessing as well : mabe by defining a set of  pairs of characters like ( ', ’) or ( " ,« ) and in case a  character of such a pair  is not in the list of character but the second one is, make the substitution.

I wonder if it could not also be useful for some character specific to a language, when a subsitution with one or two more common characters is possible (I read something about that, but the details did not stay in my memory).

Any way, typography is fascinating, I need at least to more lifes to begin to understand all the details.....

**Comment by ReenSpill** [comment]
I am new to InkStitch and have the same problem with apostrophes and quote marks missing when using the lettering tool. 

In this case I am trying to use Dejavu Serif and cannot type **That'll** because the apostrophe is missing. I have the same problem in several other lettering fonts. It seems to be included in the glyphs of the font. Is this a bug or user error :)

Any ideas for getting around it? Do I need to copy and paste from a text font and covert from a fill to a satin stitch?

Thanks

**Comment by claudinepeyrat06** [comment]
Problem is there are several glyphs looking very similar, but corresponding to different unicode.  single quote, curved single quote, apostrophe  are different unicode but glyphs are very similar. One of these, and only one  is in Deja Vu font.  Plus depending of the keyboard you are using, your "apostrophe" key is sending some unicode. Plus a lot of editor change that for you (including  the editor in the lettering window). In more recent fonts there are usually more than one apostrophe to help. 

The whatever glyph that looks like an apostrophe in DejaVu  is a very simple satin column.  You could simply draw a straight line and use Tools : Satin to convert it to satin column, then add a center overlay and you are all set.
<img width="252" alt="image" src="https://github.com/inkstitch/inkstitch/assets/88194877/9487d6fd-4ffc-431d-91e5-c2abdee76a7c">

**Comment by Augusa** [comment]
When the apostrophe is missing I use the comma and I move it a little.

**Comment by bkmgit** [comment]
One solution maybe to have a window appear with the characters available for a particular font.

**Comment by bkmgit** [comment]
> * if é is not part of the character set, I'd rather receive an e than the missing glyph (a lot of similar cases)

This could be done by converting to  NFKC form see https://docs.python.org/3/howto/unicode.html and https://dencode.com/en/string/unicode-normalization and then removing non ascii characters, but probably just having an option to see the available characters in the GUI would solve this problem and allow the user to apply their best judgement.
