### ISSUE TITLE
Manual install: Getting Attribute Errors when running commands?

### ISSUE THREAD

**Issue by hdacosta400** [inkstitch/inkstitch#1396]
This has happened for several commands, but here is the error  from the Simulation command:

` File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/elements/_base.py", line 165, in __getattr__
    raise AttributeError(f"Can't find attribute {self.typename}.{name}")
AttributeError: Can't find attribute Layer.specified_style`

I'm sure I did not miss any of the manual installation steps, so I'm not quite sure how to address this.

Also, is there any documentation for how to navigate the file system and add new features? Any direction on this would be greatly appreciated!

**Comment by hdacosta400** [comment]
Thanks for the response! Could it be related to this block of code in inkstitch.py? 

`
if getattr(sys, 'frozen', None) is None:
    # When running in development mode, we want to use the inkex installed by
    # pip install, not the one bundled with Inkscape which is not new enough.
    sys.path.remove('/usr/share/inkscape/extensions')
    sys.path.append('/usr/share/inkscape/extensions')
`
I commented it out because of the following error:
`  File "inkstitch.py", line 16, in <module>
    sys.path.remove('/usr/share/inkscape/extensions')
ValueError: list.remove(x): x not in list`

I'm very new to Inkscape, but does this mean that inkstitch is not getting put in the right extensions folder? I'm guessing that's not the case since I can run the extension from Inkscape itself. Thanks again!

**Comment by lexelby** [comment]
Oh interesting, /usr/share/inkscape/extensions wasn't in your pythonpath?  What operating system are you running on?  @kaalleen I guess this line needs some work...

Fear not, Ink/Stitch is in the right folder if you're seeing its menu items in the Inkscape Extensions menu.

The problem you're running into is that we require a very recent version of inkex, the python library used by Inkscape extensions.  The inkex version bundled with Inkscape is not new enough.  It should be that when you do `pip install -r requirements.txt`, inkex gets installed in `src/` in your inkstitch clone, as @kaalleen was saying up there.  But then we have to do that stuff on line 16 in inkstitch.py to make sure that _our_ version of inkex gets used, not the one bundled with Inkscape.  Since you had to comment that line out, it's using the wrong inkex version, and that's when you get the `specified_style` error.

Could you do us a favor and add something like `print("python path: " + repr(sys.path), file=sys.stderr)` to your inkex.py at line 16 and post the result here?  I'm curious what your python path looks like :)
