### ISSUE TITLE
inkstitch param preview not registering color from SVG

### ISSUE THREAD

**Issue by dagrimrippa** [inkstitch/inkstitch#1411]
I'm running into a problem where I import my svg file and open the param window but when the preview starts its all in black and white like its not registering the colors on the image, the one thing Ive seen that works is I have to go in and select each individual path to choose the same color it already has and THEN it'll start to register but that takes so long. Anyone have any insight
<img width="1311" alt="Screen Shot 2021-10-27 at 2 40 43 PM" src="https://user-images.githubusercontent.com/93287481/139135723-882abbf2-bad1-4015-9027-74b82b4fa234.png">
<img width="1680" alt="Screen Shot 2021-10-27 at 2 41 47 PM" src="https://user-images.githubusercontent.com/93287481/139135777-18971a88-90e6-4e17-ac61-5bd23d053d68.png">

?

**Comment by kaalleen** [comment]
We believe this behaviour will be fixed in the next release. If you want to run a test (this is only possible for Big Sur or Catalina - macOS versions) you could try to run a development build, e.g. https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-pin-shapely-version
The development build has to be installed the same way as the official release. If you actually run the test, we will be happy about feedback ;)

**Comment by kaalleen** [comment]
I'll close this issue. It should work fine in the upcoming release. Please reopen, if this happens again.
