### ISSUE TITLE
auto-route satin issue?

### ISSUE THREAD

**Issue by njlvr** [inkstitch/inkstitch#1439]
Hi InkStitch people

Maybe I am doing something wrong but I can't get _auto-route satin stitch_ to do what I think it should do ((:
I have 2 simple shards that touch each-other: [2 shards.zip](https://github.com/inkstitch/inkstitch/files/7532466/2.shards.zip)
When I let loose auto-route satin stitch on it I get this
![auto-route](https://user-images.githubusercontent.com/64724381/141653417-cc2ccf3d-285c-4a5d-80ce-b3886344b967.png)
I don't know if my simple design needs all this cutting-up but when I Param it, it gets worse
![Param](https://user-images.githubusercontent.com/64724381/141653487-907d1f48-9f09-4cf2-a006-775f3463a6eb.png)
I was used to the "old" version (with InkScape 0.92.4) which was able to stitch these shards together without any jump stitch.

I suppose I'm doing something wrong, but I don't know what.

I'm considering installing an older version of InkStitch to see whether that really worked better
Do you know what InkStitch version corresponds chronologically to InkScape 0.92.4?

Btw. it might we a good idea to scribble the InkStitch version in the svg files. InkScape includes their version.

Thanks for your help

**Comment by tyrosinase** [comment]
You know, I had auto-route do some weirdness with me the other day too, though instead of troubleshooting it further I went "ha HA I'm using the machine that trims, let the jumps fall where they may!" and let it stay manual.

(Yeah, it slows things down a lot, but when you're doing a VW that has FIFTY INDIVIDUAL VENT LINES on the back of it, what's a few trims between bumper segments?)

Anyway, it struck me as odd at the time because yeah, I was used to it Just Working. Maybe I should play with it more.

**Comment by njlvr** [comment]
`ha HA _You_ are using a machine that trims.`
Lucky you. I'm working on a design with 737 satin columns in 7 colours, very repetitive patterns, ideal for an auto-route function.

Anyway, what I said about the old version of InkStitch is not true.
This didn't work better in older versions of InkStitch.
I mixed it up with the Automatically routed fill stitch.
Same function for another stitch.

But what am I going to do now?
I can't do 737 satin columns manually.
Do I really need to look in the code of auto_stitch?

**Comment by tyrosinase** [comment]
I know it *has* worked for me in 2.0.0, so it's not that the new version is broken. Probably. I'm not sure I've done much with overlapping satin stitches, and so this is the first time I'm sure I've had Preserve-Order turned on.

I just went back and looked mine over, and I think my problem was that Preserve-Order was forcing it into something that there was no real solution to that didn't involve some seemingly-unnecessary jumps.

Auto-route does do some inexplicable things sometimes; I downloaded your design and modified it so the two shards break at the shared point. Auto-route started the first shard with an unnecessary running stitch, which it usually does, but then also did a running stitch so it could start out in the far side of the other shard; I feel like the algo ought to recognize that it literally doesn't need to do anything (bar maybe flipping rails) to have a good route.

I know there's been some talk about adding auto-routing to running stitches and I think it may have involved bringing in a different subsystem to do the satin routing as well; I'd look into those discussions before diving too deeply into code that may be replaced but other than that yes, I'm sure the devs would love it if you helped out with debugging.

**Comment by kaalleen** [comment]
It may be confusing, but params isn't able to display satins and running stitches at the same time. I think you will get a much better result, if you use the simulator to see the final routing.

**Comment by tyrosinase** [comment]
Oh, that's a good point, I didn't catch that it was the param display.

It still feels like it's doing a little bit of jumping (to get to the start of the running stitch in the second piece), but I guess it kind of always does that and usually doesn't show.

**Comment by njlvr** [comment]
Thanks guys for your help
I'm back to the drawing board _and_ back to school
I'm mixing up fill stitches and stain columns
I will be back on the subject later.

I'd like to see what a VW with 50 individual vent lines looks like though ((:

**Comment by tyrosinase** [comment]
Behold, the most recent draft (yes the camera adds a few last thread tails that need trimmed that I SWEAR were not there before I took the picture):

![IMG_0005](https://user-images.githubusercontent.com/9473609/141694827-b2f8c203-8d62-4fa7-af13-d17a795f5fa8.JPEG)

**Comment by njlvr** [comment]
Herbie! That's cute
50 vent lines indeed, very nice job indeed
Thanks for sharing

**Comment by tyrosinase** [comment]
Thanks!

He really needs a Pennsylvania plate since that's actually a specific Herbie that lives across the Delaware from me: https://www.instagram.com/lovebugtrumpshate/

This is a flat zipper pouch; I'm not ecstatic about the flat-sewn look at that size, but there's no way turning a vinyl pouch that shape is going to come out well. Think I'm gonna make a rectangular pouch with it instead for the final version, which means converting the undercarriage/tires into something embroidered.

If I'd done it on the non-trimming machine I think I'd've re-ordered those lines so the thing was making longish jumps, forcing tackdowns and giving me enough slack to trim them neatly (and eating up a ridiculous amount of thread). Somewhere I have a pre-trimming picture of the vents and it's a hot mess, fifty tails that sometimes got caught in the next line, etc. but it really does make it a lot easier to clean up than trying to clip out tiny taut stitches.
