### ISSUE TITLE
I received this on Inkscape/Inkstitch   please help so I can get this embroidered

### ISSUE THREAD

**Issue by annette2ya** [inkstitch/inkstitch#1443]
This is what it said to do.... so here is me requesting help.... and this is what the error posted, just trying to save it to a .pes format, if I cant save it... I cant embroider it... Thank you !!!

Ink/Stitch experienced an unexpected error.

If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below:

Ink/Stitch Version: v2.0.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\output.py", line 56, in effect
  File "lib\stitch_plan\stitch_plan.py", line 26, in patches_to_stitch_plan
IndexError: list index out of range

Ink/Stitch experienced an unexpected error.

If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below:

Ink/Stitch Version: v2.0.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\break_apart.py", line 59, in effect
  File "lib\extensions\break_apart.py", line 144, in polygons_to_nodes
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by Jaywavyfeliz** [comment]
Requesting help. Just trying to save my file as a .dst; if I cant save it, I cant embroider it. Please and thank you. 

lib/extensions/base.py:58: DeprecationWarning: inkex.etree was removed, use "from lxml import etree"
Ink/Stitch experienced an unexpected error.

If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below:

Ink/Stitch Version: v2.0.0 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex/base.py", line 141, in run
  File "lib/extensions/output.py", line 56, in effect
  File "lib/stitch_plan/stitch_plan.py", line 26, in patches_to_stitch_plan
IndexError: list index out of range

**Comment by annette2ya** [comment]
So... how do I undo the thread... you mean authorized... I'm gonna have to
redo everything because it's not doing what I want at all.... I know enough
to mess things up real good lol all I wanted was to make some text and bam
automatic embroidery... haha haha umm no, I didn't know I was gonna have to
go back to school to work a program... for a fricken birth announcement...
thank you...

Cuz my little brother embroidery machine has crap for software

**Comment by tyrosinase** [comment]
@annette2ya, instead of using Inkscape text (which is for printers) you want to use Ink/Stitch lettering (which is for embroidery machines): `Extensions > Ink/Stitch > Lettering`. If none of the lettering types suit, you can convert Inkscape text to embroidery but that's a more involved process: https://silverseams.com/2020/03/monogramming-without-a-font/

@Jaywavyfeliz, your problem may partially be the same thing but the deprecation warning is just a warning, and shouldn't affect actually saving the file. If you're trying to embroider a picture rather than text, then this will help you: https://silverseams.com/tutorials/digitizing-with-ink-stitch/ , otherwise the solution is the same as Annette's.

In both cases Ink/Stitch should be giving a more informative message rather than the error, and I think this is something the devs are working on for the next release.

**Comment by annette2ya** [comment]
Thank you!

**Comment by Jaywavyfeliz** [comment]
Thank you!

**Comment by kaalleen** [comment]
This bug should not appear in the upcoming version anymore. Therefore I'll close the issue. Please reopen, if you ever see this again.
