### ISSUE TITLE
The script did not receive an error, but this may indicate results will not be as expected.

### ISSUE THREAD

**Issue by Charity671** [inkstitch/inkstitch#1451]
lib\extensions\base.py:58: DeprecationWarning: inkex.etree was removed, use "from lxml import etree"

I get the above message when trying to save my file as a .pes

Everything works in Inkscape, params, virtual stitch out, export as PNG, etc.  The file actually saves on my USB stick, but it is not being recognized by my machine.  I have used Inkscape before and always work off on this exact USB stick.  I can see other files I have created in InkStitch that did not receive this warning.

I tried a fresh download of InkStitch and resaved the file with the fresh download and still received the same error.

I am at a loss now.

**Comment by tyrosinase** [comment]
I thiiiiink this has come up before (maybe someone has a better memory than I do) and I want to say the DeprecationWarning wasn't actually related to the problem (it *is* just a warning) in that case - if there's no other error message, that's not actually the problem.

But if that message goes on to say "Fill shape is not valid" then you need to do a `Extensions > Ink/Stitch > Fill tools > Break apart fill objects` and that should fix it.

If not, then are you perhaps using a nominally-4x4 machine and getting very close to the edge of the stitch field? The actual field size on that hoop is (IIRC) something like 98 x 102mm, and Brothers will just ignore files that don't fit on the machine. A 5x7 machine will show an oversized 4x4 grayed-out if you have the 4x4 hoop selected, but a 4x4 machine will just not show it at all. (A 5x7 will do the same no-show thing on a larger-than-5x7 file, but since the actual field *is* at least 5x7 in that case it doesn't come up often.)

**Comment by Charity671** [comment]
Thank you.  It is a 5x7 file and that is my largest hoop, so I will check to make sure it is fitting within the hoop size.  I didn't even think of that because of the message I was getting.  Thank you so much!

**Comment by tyrosinase** [comment]
Because that's 99% of the stuff I do, I actually have my Inkscape set to a 5x7 canvas size by default. I set the canvas to 5x7, did a Save Template, and I can't remember if I had to do something to make it my default template or if it just uses the last one by default. It doesn't actually limit the design size, but it makes it a little easier to catch overflow.

You can also set up new preset page sizes in Inkscape by editing pages.csv (in the same directory as preferences.xml, which shift-ctrl-p will show you the location of) and adding them in. Here's mine:

`#Inkscape page sizes
#NAME,                    WIDTH, HEIGHT, UNIT
Brother 5x7,	              5,      7, in
Brother 4x4,	             98,    102, mm
Janome 20x20,                20,     20, cm`

(and then it goes on with the ones Inkscape comes with)

Someday I should hunt down the exact size of the 5x7 hoop in mm, and confirm the 4x4 size. But in any case, that gives me this when I want to change my canvas size.

![image](https://user-images.githubusercontent.com/9473609/142772782-142b0b95-cf2c-48ce-9c21-84035d9f231a.png)

**Comment by tyrosinase** [comment]
Well, that preformatted text didn't work out at all. Let's try that again:

`Brother 5x7,	              5,      7, in`
`Brother 4x4,	             98,    102, mm`
`Janome 20x20,                20,     20, cm`
`A4,                         210,    297, mm`

But if this garbles too you can get the idea from looking at the file, the format isn't hard to figure out.
