### ISSUE TITLE
Malicious software?

### ISSUE THREAD

**Issue by pixelauthor** [inkstitch/inkstitch#1457]
Pretty concerning flags for the 2.0.0 version of this software (Windows, English, 64-bit): https://www.virustotal.com/gui/file/9e10febb5536b55af13ecdda4324b02c7644d7eb0bd3f7a5820819926857a122?nocache=1

**Comment by tyrosinase** [comment]
It's done that for some time; apparently a false positive, but virus checkers are extremely uncooperative about admitting to what has set them off so it's hard to fix.

It's open-source software, so you can always compile it from source yourself (I do, because I am on Linux and there are some oddities about my setup - it takes awhile but isn't particularly complicated).

**Comment by kaalleen** [comment]
https://github.com/hankhank10/false-positive-malware-reporting
