### ISSUE TITLE
Harmless error when closing Lettering too fast

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#1479]
This might be slightly outdated (I'm on Inkscape 1.0.2/Inkstitch 2.0.0 until the pre-holiday upgrade moratorium is lifted) but I occasionally get a complaint when I close Lettering.

The specific case is: TT Masters, opening an existing Lettering object, changing the text, and closing the dialog before the preview catches up. Often the preview gets a little hiccup:

![image](https://user-images.githubusercontent.com/9473609/145500822-a77bc9d4-31ef-4ebb-adb4-3db215e91905.png)

It goes ahead and stubbornly finishes drawing and won't return to Inkscape until I explicitly hit the Quit button, at which point it throws this:

Traceback (most recent call last):
  File "wx/core.py", line 2326, in Notify
  File "wx/core.py", line 3532, in Notify
RuntimeError: wrapped C/C++ object of type LetteringFrame has been deleted

After the error dialog is closed, the lettering in the design updates just fine and life goes on.

Also this is probably a separate issue, but according to my in-laws the dialog for "pet names" is limited to "literally what the animal is, or 'Max'" and that should be a freeform field. 😉
![image](https://user-images.githubusercontent.com/9473609/145501428-16110054-2051-4952-9356-0d435e1d52c6.png)

**Comment by kaalleen** [comment]
They look so nice, thanks for sharing.

Our wxpython windows don't really like to be closed before showing the simulation. This may be fixable, but I am not sure if it is worth the time, since we are moving away from it. But the displacement of the lettering is odd. Reminds me of an other issue which I am too lazy to search for right now. It was caused by an odd viewbox setting. But also showed up when the something was rendered in a certain area of the canvas. It displaced objects, when it wasn't supposed to change these objects so at all.

**Comment by tyrosinase** [comment]
Yeah, if that whole subsystem is going away it's not worth fixing.
