### ISSUE TITLE
Custom default param settings

### ISSUE THREAD

**Issue by Marif91** [inkstitch/inkstitch#1497]
Lettre au père Noël Inkstitch

J’aimerais pouvoir créer des paramètres par défaut qui seront utilisés automatiquement si je ne fais pas d’autre choix. 
Actuellement par exemple l’espace inter-lignes à 0,25 du remplissage me paraît bien trop dense, j’aimerais pouvoir revenir à une valeur de mon choix par défaut, même proposition pour la longueur des points droits et la densité du satin.

Merci !

**Comment by tyrosinase** [comment]
Me too, Santa!

I know we've talked about the default running-stitch length not always being ideal, but I can't find the specific issue. Because most of my designs are in-the-hoop things rather than embellishment, and when they *are* embellishment they're on vinyl, I almost always want running stitch to be 2.5mm instead of 1.5mm.

**Comment by Augusa** [comment]
Père Noël,
Moi aussi je voudrais bien une belle rubrique pour MES préférences par défaut. Tu sais, comme dans inkscape!

**Comment by kaalleen** [comment]
Closing. But don't be afraid, it is just a duplicate of #1069
So this is still a thing for future plans.
