### ISSUE TITLE
break apart error

### ISSUE THREAD

**Issue by buzzmandt** [inkstitch/inkstitch#1546]
`shapely.geos - ERROR - TopologyException: found non-noded intersection between LINESTRING (191.251 144.516, 201.354 143.633) and LINESTRING (185.996 140.283, 200.628 146.254) at 195.46664202139641 144.14772313391737

Ink/Stitch experienced an unexpected error.

If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below:

Ink/Stitch Version: v2.1.0 (linux)

Traceback (most recent call last):
  File "inkstitch.py", line 62, in <module>
  File "inkex/base.py", line 147, in run
  File "lib/extensions/break_apart.py", line 54, in effect
  File "lib/extensions/break_apart.py", line 68, in break_apart_paths
  File "shapely/ops.py", line 152, in unary_union
  File "shapely/geometry/base.py", line 76, in geom_factory
ValueError: No Shapely geometry can be created from null value

`
So far I have replicated the error 3 times in a row.
Steps for me to reproduce:

- On a blank new page, select the bezier tool (B)
- draw a circle with 8 points, the 8th point closing the circle
- Select the nodes tool and activate (highlight) all nodes.
- click the "Make selected nodes symmetric" button
- click on any node, grab one of the handles and spin around the node to make a small circle (intentional border crosses over itself)
- in fill and stroke, select a fill, no stroke.
- run Extensions > Inkstitch > Fill Tools > Break apart fill objects
- apply

Got errors whether doing simple or complex.

**Comment by kaalleen** [comment]
Wow, that's bad. This happens with all crossed border shapes and makes the break apart unusable. I wonder why it happens. It is exactly the error that I get in manual install when I use shapely 1.7.1, but not with shapely 1.7.0 and not with 1.8.0. Because we didn't update our code for 1.8.0 yet, I used shapely 1.7.0 for the linux build. So I am really surprised to see this now. I'll try to run a build with an other shapely version and send you a link for testing. Could take a while until I'll get to it though. Thank you for your error report!!!

**Comment by buzzmandt** [comment]
Thank you for the response. Is shapely in the inkstitch package or something I can upgrade/downgrade on my side (Manjaro Linux, testing repos).

I will try the 2.1.2 when I get home from work today and let you know

**Comment by buzzmandt** [comment]
tested 2.1.2, got the same error

**Comment by kaalleen** [comment]
Here you go: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-shapely

I am using 1.8.0 in this build. Couldn't get it to run with older shapely versions. But that should be ok, since we are suppressing deprecation warnings in the releases. I'd be curious to hear how it works with that version (not onyl break apart).

**Comment by buzzmandt** [comment]
Sorry about the delay, github didn't tell me you replied...

It works like a charm :)

**Comment by kaalleen** [comment]
Thanks for the feedback!
