### ISSUE TITLE
Lockdown stitches too short

### ISSUE THREAD

**Issue by MadTooler** [inkstitch/inkstitch#1605]
Hello!

I have been trying out inkstitch to drive a long arm quilting machine via gcode.  It has been fun with overall nice results!  I know the goal here is for embroidery, but the software toolsets are sooo similar I am hoping there is interest to make the bridge between the two.  I will be starting another open issue for feature work specifically for quilting machines.

Regarding Lockdown stitches, specifically with running stitches and Lockdown stitches at both ends, I have had inconsistent results in the length of the lockdown.  From what I can tell, it looks like the lockdown stitch length is designed to be 1/2 the length of the running stitch.  Where the resulting running stitch may not be a full stitch length at the end or start of a path, the resulting lockdown is half of that already short stitch.  

Beyond the unintended truncation of the stitch noted, for my application with a larger long arm machine, I would also prefer to have better control and specifically callout the lockdown length.  For example, regardless of running stitch length, I would like to set what distance to perform lockdown stitches (backstitching).  Even better if the length of those lockdown stitches was also declarable.  For example, if I use 2mm stitch length for the running stitch, total lockdown stitch length of 5mm with lockdown stitch length of 1.25mm (I made those numbers up).  I guess you could have it declarable for the total length of cumulative stitches and number of stitches over which or number of stitches and individual stitch length.  

I looked around and could not find anywhere to make changes to the Lockdown stitch variables.  Please point me in the right direction if they already exist and I overlooked them.

Thanks

**Comment by danielkschneider** [comment]
I also would appreciate some sort of parameter to make these longer. E.g. 'min_lockstitch_length'. This is crucial for working with thick w.t. 12 thread.

@MadTooler : As a workaround you can generate the stitch plan, move the nodes to make the lockes longer, then use the generated stitches instead. This is of course somewhat time consuming, but better than nothing. Once you modified the stitch plan, you can rename its layer and just that. If you just fix one object, then move the objet to the layer to be stitched. Basically you will use "manual stitches" from that point on.

**Comment by MadTooler** [comment]
@danielkschneider  Thanks for the tip.  I am fairly new to inkstitch and am not fully aware of some of the workflow.  I have not seen the method of generating stitch based paths.  I might try it, but my long term goal is to either find or help develop a software that has the features ready to go.  I am still piecing together exactly what all features are vital and which software to hardware approach is best suited.  Inkstitch is very promising in a lot of ways, but I would like to get a feel for the developers interest in broadening the features to include quilting machines before I get too carried away.

**Comment by lexelby** [comment]
Hi!  To your broader question, yes, I'd love it if Ink/Stitch supported long-arm quilting machines better.  I only have the slightest experience with long-arm machines.  I've driven a manual one and learned that I'm not very good at following a pattern. ;) I've never even seen one of the computerized ones.  I didn't realize they use g-code?  Please do open feature requests, your experience helps us since we don't know what is needed to support these machines.

For the specific question, yes, your understanding is exactly right.  Ink/Stitch tries to make a reasonable-length lock stitch inside the last stitch, but if that last stitch isn't long enough, it just sort of does its best with what's there.  When you have a running stitch with a length of, say, 1.5mm, if your line isn't an exact multiple of 1.5mm (which is almost always the case) then the last stitch is just the leftover length, and it can be quite short.  Ink/Stitch doesn't handle this well.

For a straight line, of course the reasonable thing to do here would be to go further back, whatever length is reasonable, perhaps even a customizable length.  The problem comes when the running stitch isn't a straight line, like this:

![image](https://user-images.githubusercontent.com/4446653/159131911-4c8e5f2e-a32a-433f-a883-48441363e82a.png)
![image](https://user-images.githubusercontent.com/4446653/159132018-d96c4e5c-a6ba-4e2b-b8dd-934b2528e012.png)

The red is where we might want to place the lock stitch.  But of course that's outside the shape of the curved running stitch, so it will stick out like a sore thumb.

Ink/Stitch previously handled this by trying to follow the path backward, but that turned out to be really computationally expensive to do for every lock stitch.  Theoretically we could just retrace over the last few stitches exactly, but in practice, for a precise enough machine, you really don't want to re-stitch in the same exact spot, because the needle can actually cut the thread clean through!  Then the thread pulls loose and you have a thread break.

So instead we should follow the contour backward but place stitches not in the exact same spots... at this point, I became frustrated and implemented the half-assed solution you see now. ;)  It's not great.  I'd love to hear any ideas you have.

All of this is stuff we'd love to work on, but our two main developers (me and @kaalleen) have had next to no time to work on Ink/Stitch lately.  Pull requests welcome.

**Comment by MadTooler** [comment]
Thank you for the detailed reply and interest in working quilting machines into the feature fold!  I am very new to longarm machines, but I have a couple decades of CNC experience.  This last year I started helping family with a longarm equipped with a "robotic controller" on it, and quickly found myself wishing I could drive the machine the same way I do my CNC equipment.  Thus, I am now running the longarm with an open source controller with a FluidNC based ESP32 board plus a few custom widgets of my own.  So no, most probably don't run g-code or have open source interfaces.  

Since I am coming from the outside, and I am not a quilter or make a living with a sewing machine of any kind, I am still digging into what will be needed.  When I have a better grip, I will throw some details your way.

Back to the lock stitches...  I understand your reasoning and realize the issues you noted.  I have not yet looked at your code to see if there is any real value I can provide in implementation.  I write a bit, but not great.  A lot of the CAM software I run have "lead in" and "lead out" features that are the same intent, less the variance in hole location you are aiming for, so maybe I will see if I can find some open code out there that possibly takes a different approach in solution.

With the possible thread cutting for same points, I really am not sure how much that matters.  Again, not actually a garment guy here.  My knowledge of proper sewing techniques is under development.  That said, the longarm machines have an "idle" mode where they will continue to stitch in place until you move the machine again.  One of the main purposes is to achieve sharp corners while free motion or machine controlled motion transitions at corners that fall not on the end of a stitch per the machines encoder stitch control system.  The result of the idle mode may be with numerous stitches in the same point.  From what I have seen, the thread does not seem to mind with several same hole stitches.  Surely it gets messy if you let it, but I have not seen breakage issues when using the size 16 and 18 needles and 40wt poly thread.

Thanks for all the work you and the other developers have poured into inkstitch!  It is very appreciated.

**Comment by lexelby** [comment]
Wow, replacing the controller with your own board, that's gutsy as heck!  Nice work :)

I might be overthinking things.  It's possible that the machine I observed the thread cutting on had its tension way too high, for example.  It's worth revisiting.

**Comment by MadTooler** [comment]
> Wow, replacing the controller with your own board, that's gutsy as heck! Nice work :)

Thanks.  Replacing the controller on one of these machines is not like gutting and replacing the controls of an embroidery machine.  I would say a lot less effort than creating your own embroidery software!



> I might be overthinking things. It's possible that the machine I observed the thread cutting on had its tension way too high, for example. It's worth revisiting.

I agree with the theory of needle cutting when repeat stitches in a single place.  I am simply unsure if it is a real issue in practice.  That could be well served by looking into some of the standard practices of sewing processes, assuming those exist somewhere.

**Comment by lexelby** [comment]
One thing I try to be careful about is not looking too closely at commercial embroidery software.  I don't want to rush a situation where they claim I reverse-engineered their stuff or whatever.  And there's not much written about machine embroidery software algorithms for some reason...

**Comment by MadTooler** [comment]
I agree with that approach.  My intent would be to look into the broader best practices of machine sewing (probably commercial or industrial), not at any software.  I bet NASA has a bit of data on parachute sewing if you want to get real technical ;)

**Comment by kaalleen** [comment]
Closing. Recent versions have more lock stitch options.
