### ISSUE TITLE
Extension to toggle command visibility

### ISSUE THREAD

**Issue by Marif91** [inkstitch/inkstitch#1609]
Il serait intéressant de pouvoir choisir une échelle pour afficher les commandes sur un motif sans accéder au fichier xml. Un membre du groupe français nous envoie cette photo d'écran !!!

Merci à tous les développeurs..

![Capture d’écran 2022-03-21 à 11 46 38](https://user-images.githubusercontent.com/65076100/159246423-81bcc678-d785-4742-a66c-9b7d85d182ba.png)

.

**Comment by kaalleen** [comment]
I am not sure if it is worth keeping those commands, since the fill start and end commands do not have any effect on satin columns.

But to answer the question. Your group member can do the following:
1. Select one of these command symbols
2. Select all symbols with Edit > Select same > Stroke
3. Open the transform dialog: Object > Transform... 
4. Go to the second tab (Scale)
5. Activate "Scale proportionally" and "Apply to each object separately"
6. Set desired size and hit enter

If the command symbols are disturbing the work at the design, it is also possible to set them invisible. They will still work as before.
Hope this helps?

**Comment by Marif91** [comment]
Merci Kaallen  
: -))

**Comment by kaalleen** [comment]
You are welcome :)

Maybe we can leave this open. I think it may be useful to have an extension to quickly toggle the command visibility on and off?
It's not a nice job to do it manually if ther are many commands in the document.

**Comment by Marif91** [comment]
C'est une très bonne idée ! Merci kaalleen !
Marif

**Comment by Marif91** [comment]
> Je vous en prie :)
> 
> On peut peut-être laisser ça ouvert. Je pense qu'il peut être utile d'avoir une extension pour activer et désactiver rapidement la visibilité des commandes ? Ce n'est pas un bon travail de le faire manuellement s'il y a beaucoup de commandes dans le document.

Il serait aussi très intéressant de pouvoir changer l'échelle de toutes les commandes en une seule fois !!!

**Comment by kaalleen** [comment]
Ok, here you go: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-scale-commands-etc

I would suggest to enable live preview while scaling, then you can see the result immediately.

**Comment by Marif91** [comment]
Merci Kall Een, je vais tester !

Envoyé de mon iPhone
