### ISSUE TITLE
ink/stitch installation fail

### ISSUE THREAD

**Issue by slobster7** [inkstitch/inkstitch#1613]
My ink/stitch keeps failing when I try to install the software to my mac

**Comment by tyrosinase** [comment]
Is it an M1? #1545 has some conversation about new Macs.

(One arrived in our house this week and it's very frustrating: company policy prevents me volunteering its use as a build platform. I run Ink/Stitch on my Linux desktop.)

**Comment by kaalleen** [comment]
@slobster7 I am not quite sure, which steps you have done before trying to install Ink/Stitch. This may be something you've done already, but I'd like to confirm...

Ink/Stitch needs Inkscape (current version 1.1.2 => https://inkscape.org/release/inkscape-1.1.2/) to be installed first. It is also a requirement, that Inkscape has been run at least once, before the Ink/Stitch installation.

**Comment by kaalleen** [comment]
@tyrosinase I had my husband write up a description how to build Ink/Stitch on an M1 processor -> https://inkstitch.org/developers/inkstitch/apple-silicon-manual-build/

Hope that helps. But I really believe, that it should work as is - that means, if Inkscape has been installed and run beforehand. Maybe you can try that too? I'd be curious if you run into any troubles...

**Comment by tyrosinase** [comment]
This is one of those laptops where they have spy software and can see anything you install, so alas, he's a bit hesitant. It's only the second week at the new company (acquired his old employer) so maybe when things settle down he'll be able to get it cleared.

If he does, though, it'll be a great test of the manual because I have *zero* Mac experience. Should be hilarious!

**Comment by kaalleen** [comment]
Wow, that's weired and scary. I totally understand that he is hesitant!

**Comment by tyrosinase** [comment]
I mean, it's kinda understandable: the laptop is exclusively for doing stuff in the HR software (he has a Linux laptop for technical work) and they're very security-conscious about it since it has access to all of his and at least some of his employees' personal data.

Feels like a *wildly* overpowered thing to use for that but whatever. I'm sure they would clear it but right now HR/internal IT/transition team is a li'l busy trying to integrate a couple hundred "new" employees so it isn't the right time to ask.

**Comment by tyrosinase** [comment]
Update: they decided the Mac laptops aren't appropriate so they are sending out another laptop... but not requiring the Mac *or* original Linux laptop to be sent back, so looks like we will have a test machine! 🎉

(at least until he gets burned out on the transition stress and joins the exodus and we have to return all THREE laptops)
