### ISSUE TITLE
Copying commands

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#1628]
What's the approved method for copying an object, commands and all, and pasting it into a new document without having the command balloons lose their magic and start trying to stitch out? I feel like I've successfully done it before, but it ain't happening for me at the moment.

**Comment by kaalleen** [comment]
In a quick test I couldn't reproduce copy errors. Can you post a broken copied file (or maybe before and after version)?

**Comment by tyrosinase** [comment]
If you open this file, it's fine (at least if Github doesn't mung it):
![TwoHearts](https://user-images.githubusercontent.com/9473609/163728724-e7de11b3-f344-41a0-aa1b-fbebf5f8cfae.svg)

Fill heart with a manually-set end fill, outline heart with a trim, and then another fill and outline set for the second heart. So far so good.

If I copy (Ctrl-C) and paste (Ctrl-V) in the same document, the command bubbles come along and behave correctly.

But if I want to get that into a new document, I run into trouble.

If I copy them out of this document and paste into the other, the command bubbles come along, but I end up with the scissor bubbles (but not the stop bubbles) stitching out. Not their stems, just the circle part. The fill stops seem to be fine, so maybe the first command ID is getting merged correctly, but the second isn't?

If I import this SVG into another doc, I get almost (but not quote) the opposite problem: the command bubbles come along fine, and don't stitch out, but only the trim commands actually do anything. I can drag the fill ends around but the fill calculation ignores them.

I feel like I've run into issues even when I only have one type of command involved, but maybe I'm wrong.

**Comment by tyrosinase** [comment]
Bless your heart, Github.
[TwoHearts.svg.txt](https://github.com/inkstitch/inkstitch/files/8502282/TwoHearts.svg.txt)

**Comment by tyrosinase** [comment]
Oh, and in the second document, there weren't currently any objects with commands but there have been and the ID's are still hanging around. In fact now that I think about it, those documents have a common ancestor, so the trim command has the same ID in both. It now has an inkstitch_fill_end, inkstitch_trim, and inkstitch_fill_end-7.

If I copy/paste it into a clean new document, both types of bubbles stitch out, and no defs have come over.

**Comment by tyrosinase** [comment]
One more thing: if I Duplicate instead of copy-paste within the same document, the stems stay in place no matter where I drag the duplicates to, so the trims work but the fill-ends don't.

**Comment by kaalleen** [comment]
Now I see what you mean. I believe though, that there is not much we can do about it - unless asking the Inkscape development team. Symbols are copied over to the new document as normal path objects and as symbols into the definition section of the svg.

When you duplicate objects the links of the connectors stay with the original elements, that's hard to change from our side, but we could write a special Ink/Stitch extension to duplicate objects with attached commands if that helps?

**Comment by tyrosinase** [comment]
As long as I remember to copy-paste instead of duplicate, I can work around that part. But I have a pretty regular need to copy or import multiple tiny designs into other, larger designs, and when they've got commands it can be a nightmare.

If there was a better way to handle commands than symbols I would learn Python to help implement them. I hate them so, so much - there is something about the connectors that pegs my CPU every time, so editing a "large" design (say, a [sheet of 22 snap tabs](https://silverseams.com/a-field-of-sunflowers/index.html)) means either clearing all the commands first, or waiting several minutes in between actions. Hide a layer, wait a few minutes. Drag a selection box, wait a few minutes. Move the selection, wait a few minutes to see where it actually moved to, etc.

It's not a terribly slow machine; I don't know if it's just not using a GPU for something or what. Poking around in Inkscape's bugs doesn't seem to show anybody else with the same problem though, which is somewhat surprising.

**Comment by kaalleen** [comment]
Yes I know. I have experienced it too. when I wrote the plugin to import existing embroidery fonts into the Ink/Stitch lettering tool, my computer barely could handle all the imported commands. Well, it is not especially fast anyway. So I add an option to not import the commands. These are all trim commands (of course, we talk about imported embroidery files). For a trim command we do not really need on canvas positioning. For me personally, I don't really need to see on the canvas which embroidery element has a trim command and which one not (I'll see it in the simulator or in the params). I thought often about to bring this topic up to attention. Commands are a nice to have to point on specific spots on the outline of objects (I wouldn't know a better way), but I believe, that we shouldn't use them, when a command doesn't need a specific spot to point on. @lexelby What do you think about it, should we move the trim command back to the params?

Instead of copying the object to an other one, could you drag and drop the entire svg into the new document or use File > Import ... instead? I believe if you do it like that, the commands will stay intact. I know, you may not want the whole document imported into the other one. So, an other option could be, to only import the object and add the commands afterwards. The decision between these two methods really depends on the amount of objects you want to copy over.

Inkscape version 1.2 may improve the speed quite a bit though. They have been working on speed issues lately. Also the connectors tool will have an update. I haven't tested it yet though.

**Comment by lexelby** [comment]
I'm on the fence.

On the one hand, you make a good argument for not having trim be a visual command.

On the other hand, I like the consistency of having everything be the same: a command symbol visible in the document.

I guess maybe we could do both?  Keep the visual command but also make a trim option in Params?

**Comment by kaalleen** [comment]
Not to myself: document, that it is recommended to copy-paste objects with commands and not duplicate them.

**Comment by kaalleen** [comment]
Duplicate vs copy/paste info added to documentation.
