### ISSUE TITLE
Ink/Stitch Version: v2.1.2 (windows)

### ISSUE THREAD

**Issue by kross3j** [inkstitch/inkstitch#1652]
Traceback (most recent call last):
  File "inkstitch.py", line 67, in <module>
  File "inkex\base.py", line 147, in run
  File "lib\extensions\object_commands.py", line 38, in effect
  File "lib\commands.py", line 384, in add_commands
  File "lib\commands.py", line 337, in get_command_pos
  File "lib\elements\element.py", line 267, in shape
NotImplementedError: ('INTERNAL ERROR: %s must implement shape()', <class 'lib.elements.empty_d_object.EmptyDObject'>)

**Comment by lexelby** [comment]
Oh interesting!  @kaalleen, I guess this happens if you try to add commands with an empty D object selected?

@kross3j This is a bug in Ink/Stitch, thanks for reporting it!  You may be able to avoid this bug by changing your SVG.  Somewhere in your SVG, there's a <path> that is corrupted: it has no coordinate point data (the "d" attribute).  You may be able to find it using Inkscape's XML editor.  If you delete it, this will stop happening.

**Comment by kross3j** [comment]
Is this meaning that the trace function from bitmap is not working and i need to do the path manually?

**Comment by kross3j** [comment]
Okay, I was able to fix this error by deleting the path and manually tracing the path and then adding the commands back.
