### ISSUE TITLE
Idea to import embroidery project into inkscape

### ISSUE THREAD

**Issue by the-emblazer** [inkstitch/inkstitch#1716]
I was wondering if you guys could implement a feature to import embroidery project to edit them in inkscape, sometimes I want to enlarge embroidery design I buy from Etsy, specifically .pes brother embroidery design file type.Iif there is already a way can you show me how to? Thank you very much for your time and product,.

**Comment by kaalleen** [comment]
You can open most embroidery file formats in Inkscape with the Ink/Stitch plugin installed. It will open the embroidery files as a stitch plan (manual stitch), each stitch as a node. You can edit them as you like.
Scaling changes the density of the output and should be used with care. We have no tools to adapt pull compensation, underlay, density, etc. of non-svg designs.

**Comment by tyrosinase** [comment]
Depending on the design, you can do *some* turning of a stitchfile back into an SVG. I have a couple of running-stitch designs that I've just turned off manual stitch on, enlarged/reduced, and let Ink/Stitch decide on new needle points. Sometimes you have to manually edit out lockdown stitches, but that's it.

And you can sometimes get good results turning fills back into solid objects using the same technique as knockdown/dieline creation: https://silverseams.com/2020/09/knockdown-stitching/ Depends on how precise the edges of the shape need to be, of course.

Beans and satins are slightly tougher; I've noodled around with bean-stitch detection/elimination in Perl. I should get back to that because it'd be nice to have that as a little utility in Ink/Stitch, once the algo is more reliable. I've also got the beginnings of one to turn satins into rail-and-rungs.
