### ISSUE TITLE
Feature request: stack reverse

### ISSUE THREAD

**Issue by atomic-bob** [inkstitch/inkstitch#1735]
I would like the option to "Re-stack objects in reverse order of selection" or "Match stitching order of objects to order of selection." When I use the current option "Re-stack in order of selection", it stacks my objects in "first-selected-on-top" order. But I need "first-selected-on-bottom" order.

![image](https://user-images.githubusercontent.com/5223811/179378386-87a7ceaf-e6e9-4898-a3cc-36e280c21f45.png)

**Comment by kaalleen** [comment]
I don't know if this would become confusing. Right now it will stitch first selected objects first and last selected last, which means last selected items will be on top of the first selected items.

Until now I thought it'd be sufficient, because if you want it the other way around, you simply go ahead and select the items in reverse order. Now I am curious what stops you from selecting the objects like that? Maybe I am overseeing something here.

**Comment by atomic-bob** [comment]
You're right. I tested the scenario again and it does work that way. Sorry for the confusion! When I use that feature it does indeed stack in stitching order. Thank you!
