### ISSUE TITLE
Install thread color palettes for Inskscape - hangs

### ISSUE THREAD

**Issue by Aelesas** [inkstitch/inkstitch#1741]
Inkscape 1.2 64-bit / InkStitch v2.2.0 / Windows 10 Pro v 10.0.19043 Build 19043

Process hangs inscape without completing. Have to end task in task manager to regain control of Inkscape.

**Comment by kaalleen** [comment]
Related issues: #1729 and #1728

#1729 is actually helpful because it delivers a traceback. It suggests permission problems are causing all electron extensions (install thread palette, print pdf and the simulator) to not work properly. I'm not sure how to handle the issue. Any suggestions from anybody else? ... or could you find a solution by yourself?

**Comment by Aelesas** [comment]
No, I have not been able to get it to work. I tried opening Inkscape as administrator as well to see if it would get around the problem, but that doesn't work. So, I'm still unable to use those features. The only thing I can use to even 'see' what it may look like is to run Params which seems to work fine.

**Comment by kaalleen** [comment]
Sorry that you never received a better response. I'm going to close the issue now, since we released a new version. It probably works now. If not, please feel free to open a new issue.
