### ISSUE TITLE
X stitch for a simple satin line on new macbook

### ISSUE THREAD

**Issue by CaptainNoAction** [inkstitch/inkstitch#1743]
I made a simple line, width made to 4mm, convert to satin, perform a simulator/realistic and I get a red x. I do the same thing on my pc and no issues. I made a line of triangles and it goes like a right view and all over the place. I compared the 2 computer inputs and dont see anything different. Any thoughts? Thanks

**Comment by kaalleen** [comment]
I'm not sure if I fully understand what is happening. Do you have images to show the bad effect?

**Comment by CaptainNoAction** [comment]
Yeah, no problem. Thank you.
<img width="1728" alt="Screen Shot 2022-07-20 at 7 54 30 PM" src="https://user-images.githubusercontent.com/24485278/180120293-8580ba77-c522-4d61-8ddc-d2d2671b49d3.png">
![drawing](https://user-images.githubusercontent.com/24485278/180120661-18a987c8-dfb6-4736-9247-c211bc5c20ee.svg)

**Comment by kaalleen** [comment]
Thank you. The two rails do not have the same path direction. To correct it select one node of let's say the top path and run Path > Reverse

Is this exactly how it comes out of convert line to satin?

**Comment by CaptainNoAction** [comment]
Welcome, thank you. Perfect. I selected just 1 node and Path>reverse and it satin stitched. NO IDEA why it decided to do that.

Yes, I didn't modify anything, just converted a simple line to satin and then simulator preview.

Any thoughts as to why? I just closed out Inkscape and opened back up and it still does it.

**Comment by kaalleen** [comment]
Looks like shapely is working a little bit different on a macbook than their documentation says:

`Right hand offsets are returned in the reverse direction of the original LineString or LineRing, while left side offsets flow in the same direction.`

In convert line to satin we compensate for that and reverse the right hand line to make it flow into the same direction as the left hand line. But on macbooks it doesn't seem to be true. At first I thought it could be an eror in the shapely version which we use for macOS (shapely 1.8.1 instead of 1.8.2). But on Linux it would still render correctly with shapely 1.8.1. Seems as if we actually need to check the path direction here.

**Comment by kaalleen** [comment]
If you like you can try this release here and see if it fixes your issue: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-thisandthat01
