### ISSUE TITLE
Disable Lock Stitches

### ISSUE THREAD

**Issue by ZekunCHANG** [inkstitch/inkstitch#1752]
Hi, I am using Brother PE800 embroidery machine. I'd like to precisely control the needlepoint of the running stitches. In Params, I checked manual stitch placement, and disabled lock stitches. In the Inkstitch simulation, everything looks fine. However, in the actual stitch pattern, the machine added the lock stitches to the start and the end of the paths. 

I was wondering if there's a solution to this issue.
Thanks!

**Comment by tyrosinase** [comment]
Short of a firmware upgrade (or rooting the machine and coding your own): not that I've been able to find.

When I needed to not have lock stitches (because I was using my machine to punch holes in paper; long story) I solved the problem by having the first and last stitch fall outside the paper. The PE800 is not trusting enough to honor no-lock-stitch, but it's trusting enough to not do lock stitches after ridiculously long jumps.

IIRC if the thread-out sensor tripped, it would then do its own lock stitch when it re-started, so it was not a *perfect* solution. But if you're running with thread in it, I *think* it doesn't do a lock if you pause it to manually cut the thread. That seems to only get triggered if it thinks the thread broke.

**Comment by ZekunCHANG** [comment]
Hi tyrosinase, thank you so much. It helps!

**Comment by ZekunCHANG** [comment]
Hi @tyrosinase, I was wondering if you have any suggestions on the other related issues. For the PE800, it will do no-lock-stitch after long jumps as you said. In the manual stitch placement setting, I do not have a clear idea (precise length) of when the machine will add the lock stitch automatically. When I need the lock stitch and draw the lock stitch manually, the machine also adds another lock stitch sometimes. The two lock stitches result in a big node on the back side of the fabric. If I do not draw the lock stitch manually and let the PE800 add it automatically, the machine will not do a lock stitch after a long jump. I was wondering if you have some ideas on this and if Tajima does a better job in this. Thanks!

**Comment by tyrosinase** [comment]
I haven't experimented enough to figure out what the machine deems an appropriate lock stitch; I am pretty sure whatever Ink/Stitch does is acceptable to it, so you could look at the length there and just duplicate it manually.

Manual stitch placement turns off Ink/Stitch's lock stitches regardless of the checkbox setting, IIRC.

I actually have never used a DST file on the Brother. I always forget it's compatible. I don't think it'll make a difference though, since it should end up with all the same stitch lengths in the machine.
