### ISSUE TITLE
Running stitch at sharp corner 

### ISSUE THREAD

**Issue by ZekunCHANG** [inkstitch/inkstitch#1754]
I was wondering if anyone knows how to create sharp corners with minimal needle points. Here is the pattern I wanted to create. Ideally, I want to add only **1 needlepoint at each corner**, and **the pattern on the back side needs to be as same as the front**. But this stitch plan causes so much trouble to the embroidery machine (breaking needles, fabric puckers, etc.) and wired patterns on the backside of the fabric. So I had to add more needle points ( 5 needle points) at each corner to achieve a reliable fabrication process. Does anyone have some suggestions? Thanks!
<img width="594" alt="Screen Shot 2022-07-28 at 12 12 48 PM" src="https://user-images.githubusercontent.com/105569911/181587411-d9776d79-3510-4a74-b713-fc60e967d94b.png">
<img width="345" alt="Screen Shot 2022-07-28 at 12 15 24 PM" src="https://user-images.githubusercontent.com/105569911/181587418-4193131b-6502-4d02-825d-13fc8dd861c0.png">
<img width="464" alt="Screen Shot 2022-07-28 at 11 48 27 AM" src="https://user-images.githubusercontent.com/105569911/181587420-47bda5e3-fae8-4156-9ac1-f027fdfa7c3c.png">

**Comment by lexelby** [comment]
Hi!  With a normal, correctly-adjusted embroidery machine, you will never see the same pattern on the back as the front, especially with sharp corners.  The reason has to do with tension.

With a normal sewing machine, you want to balance the top and bottom tension.  The top and bottom threads should cross exactly at the point the needle penetrates.

With embroidery, it's different: the bobbin thread should be much tighter than the top.  The top should actually be pulled down to the bottom partially.  This way, you ensure that the design looks the way it's supposed to on the top.  Plus there's an added benefit: you don't have to change the bobbin as often because you use less of it.

As you can see, that makes things look weird on the bottom, but that's expected and normal.

If you do actually want the bottom to look just like the top, you'll need to adjust the balance of tension between the top and bottom.  Either tighten the top tension or loosen the bottom, until they are balanced, like a normal sewing machine.

I think that might not work perfectly though, because all of the movement involved in embroidery may cause the tension to vary a bit.  Experiment!

By the way, you might find that that particular fabric (duck cloth?) also gives weird results due to its coarse weave.

But don't take what I've said as discouragement!  I like to do all sorts of weird things with embroidery machines.  I hope the above gives you the info you need to get the result you want.  I'd love to hear how it works out.
