### ISSUE TITLE
Spacing of generated lines not equal

### ISSUE THREAD

**Issue by kochy25** [inkstitch/inkstitch#1757]
![Inkstitch](https://user-images.githubusercontent.com/108870701/181907627-3a0212ff-65e2-4fb9-8e1a-f6269a74f4ef.png)
As you can see in this snippet, the lines generated by Inkstitch for embroidery are not all equally spaced. Is there anything else to set - or is that a program error?

**Comment by lexelby** [comment]
Hi!  What is your picture showing, exactly?  Is that the result of Stitch Plan Preview, or did you open up a DST (or other format) that you had previously exported?

I'm guessing that might be it.  Most embroidery file formats have a resolution of 0.1mm, because that's the resolution supported by almost every embroidery machine.  What you are seeing might be the result of rounding to the nearest 0.1mm.

**Comment by kaalleen** [comment]
No response. Closing.
