### ISSUE TITLE
Will not open on Inkscape

### ISSUE THREAD

**Issue by stapleremove** [inkstitch/inkstitch#1760]
I have the software downloaded and the extension comes up on inkstitch but it wont open. Every video that I have seen the software inside of inkscape is white and mine is black. Im not sure what I am doing wrong

**Comment by kaalleen** [comment]
To be able to help you with your issue, it'd be nice to have more information.

The headline suggests, that Ink/Stitch doesn't open at all. Is that generally the case or is it the case with only some of the Ink/Stitch options (which ones?).

In your text I get the impression, that at least something is happening when you open Ink/Stitch extensions, but it has a dark theme (macOS system?) or do you mean completely black? Are we talking about params?

**Comment by stapleremove** [comment]
I’m not sure if it just doesn’t work or what. Inkscape opens and I have the option to draw or add things but I have no side bar on the right hand side that shows layers ans then once I try to launch ink stitch the side bar also does not open for my layers. I have tried to do params and the application quits after it finishes no matter what and It doesn’t save the file.

**Comment by kaalleen** [comment]
You can open the Layers and objects dialog under `Object > Layer and objects ...`
Click on that and you'll see the sidebar.

Params won't save the file. You save a file through `File > Save a copy ...` and then choose your embroidery machines file format. Make sure to also save the svt file with `File > Save`, so you can edit yourdesign later on.

**Comment by MrTBPL** [comment]
Hello I am having the same problem with Inkscape/inkstitch so hopefully we can all assist one another.

Quick overview of the problem from my persepective:

The Ink/Stitch extension does not run with the exception of the Inkstitch "About" window. -- "MenuBar: Extensions>Inkstitch/about".

Inkscape itself seems to be running normally but after creating the drawing and trying to run the extension there is simply no response. Other extensions that came with Inkscape appear to be working normally though I don't much experience with Inkscape to compare it against.

I uninstalled and reinstalled Ink/Stitch and Inkscape several times trying to be careful to follow the directions on the Ink/Stitch website.  I have tried the 32 and 64 bit versions and the Manual installation as well.  I have also manually removed the Inkscape directory between installs.  The results are the same.  Ink/Stitch appears to call a browser or some external app so I reassigned the browser to the new version of Microsoft Edge to see if it would make a difference but that didn't have any effect.

I have been able to get Inkscape to run on my home computer so there may be some other considerations due to environment. ie. These computers are part of Windows Domains, and have some enterprise securitry, etc. to consider though I don't see why they would have any effect.

There are no error messages

Here are two of the systems I am having difficulty with.

--------------------------------------------------------<< System (1) >>
Processor	Intel(R) Core(TM) i7-10700T CPU @ 2.00GHz   1.99 GHz
Installed RAM	16.0 GB (15.7 GB usable)
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display
Dell Optiplex 5490 AiO
Edition	Windows 10 Pro
Version	21H2
Installed on	‎1/‎4/‎2022
OS build	19044.1826
Experience	Windows Feature Experience Pack 120.2212.4180.0

AntiVirus: Webroot

Inkscape Info:
Inkscape 1.2.1 (9c6d41e410, 2022-07-14) (32 Bit, but I also tried the 64bit version).
Ink/Stitch v2.2.0 (windows)
--------------------------------------------------------<< System (2) >>
Processor	11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz   2.50 GHz
Installed RAM	16.0 GB (15.7 GB usable)
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display
Dell Precision 3650
Windows 11 
Edition	Windows 11 Pro
Version	21H2
Installed on	‎6/‎16/‎2022
OS build	22000.795
Experience	Windows Feature Experience Pack 1000.22000.795.0

AntiVirus: Windows Defender

Inkscape Info:
Inkscape 1.2.1 (9c6d41e410, 2022-07-14)
Ink/Stitch v2.2.0 (windows)
--------------------------------------------------------<< System Info - End >>

[extension-errors.log](https://github.com/inkstitch/inkstitch/files/9270806/extension-errors.log)
[extension-errors (system 2).log](https://github.com/inkstitch/inkstitch/files/9270807/extension-errors.system.2.log)

**Comment by MrTBPL** [comment]
[extension-errors (system 1).txt](https://github.com/inkstitch/inkstitch/files/9270809/extension-errors.system.1.txt)

**Comment by MrTBPL** [comment]
Hope you can help me and I hope this helps you.

**Comment by tyrosinase** [comment]
The Ink/Stitch executable is missing, which usually means that Windows Defender has "helpfully" silently quarantined it. Last time this came up the devs were hoping the new version wouldn't trip the false alarm but it looks like, at least in that environment, it's still not the case.

It also looks like, based on that second batch of (non-Ink/Stitch) extension issues, that may not be the only thing Defender has removed.

**Comment by MrTBPL** [comment]
Thanks for the update!
Okay, so sounds like an older issue. Was there a specific fix or can I just disable Windows Defender temporarily and reinstall Ink/Stitch?

**Comment by tyrosinase** [comment]
I think there's a way to whitelist it in Windows Defender, but it's been a really long time since I've used a Windows machine (Linux weirdo all up in here) so I might be wrong. Hopefully one of the Windows experts will come along and give better info...

**Comment by kaalleen** [comment]
Closing. There is a new release out there. It still of course struggles with antivirus softwares.
Please open a new issue if installation is still a problem.
