### ISSUE TITLE
Color change from SVG to PES

### ISSUE THREAD

**Issue by JamesEXXII** [inkstitch/inkstitch#1761]
Hoping this is an easy fix, ran into people having similar issue a year ago (https://github.com/inkstitch/inkstitch/issues/1105 ) but couldnt find anything in inkscape forums.Been trying out Brother Embroidery machine and I noticed the colors were coming out wrong making a simple test file I see that some of the colors change when saving from an SVG to PES file. Image shows examples as well as the color does work when its alone, it acts up when there are other colors. The colors are correct when saving to PDF or PNG.Any ideas on solution?

![image](https://user-images.githubusercontent.com/68829691/182026926-c4ec9314-b5ab-4a42-81fc-ce8b2a084ff8.png)

also if i go into the newly created PES file, change the object in layers and objects from the wrong color to the right color and save it. If I reopen the file it reverts back to the wrong color.

**Comment by lexelby** [comment]
Hi!  The weird colors you're seeing are due to the nature of the PES file format.  There's no perfect fix but there is a fairly good workaround.

Here's what's going on.  The PES format does not let us store any color in RGB format.  PES has a specific palette of standard colors, and Ink/Stitch only gets to choose from among them.

When you save a file as PES, Ink/Stitch does its best to match up the colors in your SVG with the standard PES palette.  It starts with your first color, finds the nearest color in the PES palette, and then (and this is important) it marks that PES color as having been used.  From then on, no other color in your SVG can use that PES color.

When it gets to your 6th color (second row, right column), it does its best and picks that beige color.  Then when it gets to the 9th color, things get difficult.  Your 9th color probably matches best with that same beige from the PES palette.  But that beige has already been used, so now it has to find the next best color.  That's how it gets that pink.  Color matching is hard.

Now for the solution/workaround.  If you know you're going to be saving as PES, your best bet is to use PES colors in your SVG. Run the "install thread color palettes for inkscape" extension.  Then select the PES color palette and use only those colors in your SVG.  That way, you can be sure that Ink/Stitch will pick the right PES colors when saving as PES.

**Comment by JamesEXXII** [comment]
Thank you for the response @lexelby. That explanation makes sense and I think the solution will work, I have done something similar and I may have missed a step. when selecting the palettes using the three lined button at the bottom right I clicked on Ink/Stitch Brother Embroidery and use the respective colors. Looking at (https://edutechwiki.unige.ch/en/Embroidery_thread_color_and_chart) I can tell that the RGB values of the colors are correct. Is this menu at the bottom right where I select the correct PES color palette? 
Let me know if you need anymore information. 

![image](https://user-images.githubusercontent.com/68829691/182187192-9c993f75-f8a3-4550-9860-917bde111a51.png)

![image](https://user-images.githubusercontent.com/68829691/182187312-df9d6b7e-cf58-4b73-b3e8-1478eee7cb61.png)

**Comment by lexelby** [comment]
Yes, I believe so.  Are you saying you created the svg above using the brother thread palette?

I ask because bugs around this are quite possible.  Maybe the Brother palette is not the right one, or maybe the color-selection code is buggy -- it has been in the past.

**Comment by JamesEXXII** [comment]
Yes I used the brother thread palette shown in the image from my second comment to create the SVG. 

Also for consideration, I did notice going into my editor software and changing the RGB of one of the stitches to Linen (254,227,197), saving it as a PES and opening it in InkScape as a PES would give the correct color. This is the same RGB from the site and on the InkScape software for Linen. Also if I do just the Linen circle it does change to Baige, which supports your original statement. 

![image](https://user-images.githubusercontent.com/68829691/182193759-b1461aa4-3d2b-4d76-a7d3-0c120cf3d132.png)

**Comment by lexelby** [comment]
Hmm.  Sounds like we have a bug, then.

**Comment by lexelby** [comment]
Could you post an SVG of that test design?

**Comment by JamesEXXII** [comment]
![drawingTesting](https://user-images.githubusercontent.com/68829691/182512552-cf28a0a4-27d5-4c7d-9776-d65b37e88714.svg)

**Comment by JamesEXXII** [comment]
![drawingTesting](https://user-images.githubusercontent.com/68829691/182512643-df786663-e8ef-46e7-86f0-0ec3d8b69c1c.svg)

Let me know if this post is right, GitHub says it supports SVG

**Comment by kaalleen** [comment]
Closing in favor of #2668
