### ISSUE TITLE
[Feature Request] Ability to change simulator background color

### ISSUE THREAD

**Issue by atomic-bob** [inkstitch/inkstitch#1790]
I would like to be able to define the simulator background color. Or, it would be good to be able to check a box and have it auto match the document background color. I will be stitching on black fabric, and would like the realistic preview to reflect that fabric color. Right now it seems the simulator only has a white background.

**Comment by jooshkins** [comment]
I have been looking into adding this feature, because I want it as well. 
Actually, how I am thinking about implementing the change is slightly more complex. 
I want to have the simulator view replicate the inkscape view, including: page size, border, & color, and the desk color as well.
I'll create a pull request when I get fully working.

**Comment by lexelby** [comment]
Great idea!

**Comment by Slyerna** [comment]
You can already achieve this quite easily. File>document properties>desk color>change to preferred background color.

Place your embroidery outside the page, on the background.

It simulates on the background color you chose.

Here I simulated white thread on black.
![image](https://github.com/inkstitch/inkstitch/assets/157038977/03c026b3-f85c-45e6-a449-8ee9957c8ad0)
