### ISSUE TITLE
Contour Fill - TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by type8008** [inkstitch/inkstitch#1793]
Seems to look very similar to the issue i posted yesterday, i will send the devs this svg as well so they have 2 sessions to see whats causing it

**Comment by kaalleen** [comment]
For better readability I'll place the error message here down below instead of the title message:

`path1107: error: Error during autofill! This means that there is a problem with Ink/Stitch. If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new Ink/Stitch Version: v2.2.0 (windows) Traceback (most recent call last): File "lib\elements\fill_stitch.py", line 564, in to_stitch_groups File "lib\elements\fill_stitch.py", line 636, in do_contour_fill File "lib\stitches\contour_fill.py", line 397, in inner_to_outer File "lib\stitches\contour_fill.py", line 364, in _find_path_inner_to_outer File "lib\stitches\contour_fill.py", line 364, in _find_path_inner_to_outer File "lib\stitches\contour_fill.py", line 364, in _find_path_inner_to_outer [Previous line repeated 3 more times] File "lib\stitches\contour_fill.py", line 331, in _find_path_inner_to_outer File "lib\stitches\contour_fill.py", line 282, in _create_nearest_points_list TypeError: 'NoneType' object is not subscriptable`

**Comment by type8008** [comment]
Thank You Kaalleen That was stupid of me to put it is the issue
