### ISSUE TITLE
Fill: AttributeError: 'LineString' object has no attribute 'geoms'

### ISSUE THREAD

**Issue by AbsoluteRose** [inkstitch/inkstitch#1794]
Ink/Stitch Version: v2.2.0 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 231, in run
  File "lib/extensions/output.py", line 56, in effect
  File "lib/extensions/base.py", line 200, in elements_to_stitch_groups
  File "lib/elements/element.py", line 329, in embroider
  File "lib/elements/element.py", line 387, in validate
  File "lib/elements/fill_stitch.py", line 321, in validation_errors
  File "lib/elements/fill_stitch.py", line 274, in shape
AttributeError: 'LineString' object has no attribute 'geoms'
![David2](https://user-images.githubusercontent.com/111648675/185752961-0d35846b-a4cb-45ae-a8e7-76022b42dbb5.svg)

**Comment by tyrosinase** [comment]
Stealth-geoms strike again! There's a dev version mentioned in https://github.com/inkstitch/inkstitch/issues/1742 - see if that fixes it for you.

**Comment by AbsoluteRose** [comment]
@tyrosinase That didn't seem to help though I could have done it wrong. I tried deleting the whole app to get a fresh start and downloading it from there and same issue.

**Comment by tyrosinase** [comment]
If you look at the `Extensions > Ink/Stitch > About` screen it will tell you if you're running a dev version. If you are, and are still getting the error, the devs will take a look at your file.

That said though, the version won't fix the underlying problem, it'll just tell you your file has some problem paths (instead of crashing). It's definitely not ready for export yet: you have a lot of tiny bits that will either need eliminated or changed to satin, etc. For instance, all the tiny lines on top of the shirt - the lettering, the hood lines, etc. - will need to be converted to satin, and the shirt fill will go underneath them. Likewise, all the little texture on top of the braid will be too small to stitch. All the dev version is doing is catching those before the fill algorithm tries (and fails, messily) to fit stitches into those.

If you look over https://silverseams.com/tutorials/digitizing-with-ink-stitch/ you'll get a better idea of the cleanup that needs done to turn a screen image into something that will physically work in an embroidery machine.

**Comment by kaalleen** [comment]
Closing in favor of #1829

**Comment by kaalleen** [comment]
Closing in favor of #1742

If there are still issues with the mentioned fix, please post the version from the Ink/Stitch about screen as mentioned above
