### ISSUE TITLE
Zigzags in lettering revert to 0.265mm lines

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#1822]
So this alphabet has a ~1.5mm zigzag circle around it, which helps keep the monograms aligned, but when Lettering brings it in the line thickness reverts to the same as the bean stitches (probably reverting to a default rather than picking up the bean's thickness, but I dunno). Any ideas, or should I poke further in the XML myself and see what kind of weird intermediate transforms have happened?

https://silverseams.com/files/RoundMonograms.zip

**Comment by Augusa** [comment]
It looks like Inkstitch lettering does not accept zigzag. I try in another font and I get exactly the same small path 0.265mm instead of 2mm.
If I change your circle to column the result is correct but it does not explain why simple zigzag is not possible.
________________________________
De : Tyrosinase ***@***.***>
Envoyé : mardi 13 septembre 2022 19:07
À : inkstitch/inkstitch ***@***.***>
Cc : Subscribed ***@***.***>
Objet : [inkstitch/inkstitch] Weird transformations in Lettering (Issue #1822)


So this alphabet has a ~1.5mm zigzag circle around it, which helps keep the monograms aligned, but when Lettering brings it in the line thickness reverts to the same as the bean stitches (probably reverting to a default rather than picking up the bean's thickness, but I dunno). Any ideas, or should I poke further in the XML myself and see what kind of weird intermediate transforms have happened?

https://silverseams.com/files/RoundMonograms.zip

**Comment by Augusa** [comment]
Your Monogram font is a very interesting idea.

**Comment by tyrosinase** [comment]
> Your Monogram font is a very interesting idea.

It's not ideal, but I can't think of any other way to build a monogram for folks who are allergic to actually moving things around with a mouse. :laughing:

**Comment by tyrosinase** [comment]
Hmm. On giving it some thought: I bet every line reverts to 0.265, and that's because the scaling up and down in the Lettering dialog makes things visually inconsistent. So maybe I should just change that to a satin or running stitch (the circle is just there for aligning frames and whatnot to, but I thought I'd set it to zigzag in case someone wanted a simple frame).

So maybe it's not so much a bug as a limitation.

**Comment by claudinepeyrat06** [comment]
The lettering module is meant to set  all the running stitch to a single width and all the satin column to another one, for display purpose. However it  probably embark the zigzag with the running stitches. My guess is that as no one ever used zigzag in a lettering font yet, it never was a concern, but of course for zigzag the width of the stroke is part of the embroidery parameters. I'm sure that this can  be corrected.....but for now running stitch  or  satin column would work best.
I'm glad you made that  one, i was thinking of doing it but never had the time.... I would have  chose a slightly different way, not  putting the  frame in each glyph but using some special glyph to store a few frames and rely on the json to center the frame at the right place ( quite simple as here all your letters have the same width and height). I  did that  with the sortefax font, it was not a total success because letters don't have consistent size, but in the case of this alphabet it would work beautifuly....

**Comment by tyrosinase** [comment]
I thought that at first, but it turns out they *don't* all have the same width and height. Some don't complete the implied circle at the top, bottom, and/or sides. Which won't affect Lettering since it's using the JSON to set the width to 0, but was a concern for me since I built all the glyphs in a single page and then had to align them in a proper form.

When it's all done I should be able to remove the framing circles though. First I need to do the alternate first D, Q's, and a couple other letters I can't remember, and some actual frame options.

**Comment by claudinepeyrat06** [comment]
I looked into the lettering code, and my understanding is that lettering is supposed to set the width to 1px to anything with no fill and no stroke-dasharray ....so this is a mystery to me....but of course a lot of things are still mysteries to me....

**Comment by kaalleen** [comment]
That had to do with transformations resulting from imports of the letters from a file with an other unit - if I am correct. I'm sure this can be handled differently, but it seemed easy that way and we just did not expect the zig-zag to become important. In most cases it's not giving good results, that's why we are neglecting it a bit.

**Comment by tyrosinase** [comment]
Eh, maybe zigzag isn't important and we just document its unsuitability in the font-creation stuff and move on? It's not important to this font, it just happened to come up in development.
