### ISSUE TITLE
make auto-route running stitch work with manual stitch

### ISSUE THREAD

**Issue by gusvisser** [inkstitch/inkstitch#1856]
As i was doing a project with running stitch and manual stitch placement i found out that the auto route running stitch is not working on the manual stitch placement 

I think it would be nice that that could be implemented that the manual stitch place ment would work also with the auto route running stitch 

Thank you
Gus Visser
![dresden 4](https://user-images.githubusercontent.com/85417086/194775931-6edbf11b-e5d7-45cb-9d56-92f13e0a938c.png)

**Comment by kaalleen** [comment]
Nice design!

Adding manual stitch to auto-routing is definitely doable. There is a question though if we add nodes to manual stitch or not. Usually manual stitch should stay as, but in auto-routing we add nodes at intersection for nicer routing. I guess that's ok though, because we already have an option wether intersection-nodes should be created or not.

@claudinepeyrat06 since you are working on the auto-routing. Do you think this could be something you want to work on as well?

**Comment by claudinepeyrat06** [comment]
yes, i had not thought of it, but  why not....

**Comment by kaalleen** [comment]
I think this is pretty well possible with the new redwork extension. But you would have to reapply manual stitch afterwards.
