### ISSUE TITLE
Command Line or Automated batching?

### ISSUE THREAD

**Issue by marshallapparalautomation** [inkstitch/inkstitch#1913]
Awesome tool. First experiences have been great using your tool! Can you recommend best method to batch process consistently the same items with same settings? Ideally I would like to trigger processing file with command line, python or javascript method on Mac.

**Comment by lexelby** [comment]
It's possible you can skip Inkscape entirely.  Inkscape extensions are just programs that accept an SVG as input, make changes, and then output a new SVG.  So depending on what you're trying to do, you may be able to just call inkstitch directly a few times.

**Comment by marshallapparalautomation** [comment]
Directly via command line? Can you point me in the right direction?

**Comment by lexelby** [comment]
Try replacing the "inkstitch" binary (buried a couple directories deep) with a shell script that just does this:

```
echo "$@" >&2
```

Then run various Ink/Stitch commands in Inkscape and you'll see the arguments that Inkscape passed to Ink/Stitch.  I'm hoping that should give you an idea of how you can run it yourself to do batch processing.

**Comment by marshallapparalautomation** [comment]
Do you have time to discuss on quick zoom? I got very close to getting this and have some ideas how to resolve but need further assistance. I would be happy to contribute in return in any way or compensate you for your time.

**Comment by kaalleen** [comment]
Looks as if you need to pip install diskcache

**Comment by lexelby** [comment]
`pip install -r requirements.txt` might help too, it'd install diskcache and all the rest.

Sorry I led you on a wild goose chase!  Here's an example of running Stitch Plan Preview from the command line:

`./inkstitch --extension=stitch_plan_preview --move-to-side=true --needle-points=true < yourfile.svg > yourfile-with-stitch-plan-preview.svg`

The arguments correspond to what you'll find in `inkstitch_stitch_plan_preview.inx` which is included with Ink/Stitch.  The above should work with the installed version of Ink/Stitch, on Linux or Mac -- for Windows you'll need "inkstitch.exe" instead of "./inkstitch", I think.

If you want to emulate running an Ink/Stitch operation with objects selected in Inkscape, do it like this:

`./inkstitch --extension=object_commands --trim=true --id=id1 --id=id2 --id=id3 < yourfile.svg > yourfile-with-trims.svg`

This will run the Object Commands extension to add Trim commands to 3 objects that are specified by their IDs.  The ID is just the `id` attribute of a path from the SVG XML.

I hope that helps, let me know if you get stuck again.

**Comment by kaalleen** [comment]
Maybe we should explain this on the website ...

**Comment by marshallapparalautomation** [comment]
I would be willing to assist. I got 90% there but still, had troubles testing. I started to keep a list of steps. My goal was to automate the process without inkscape open. I thought if I got the developer setup in place I could test.

Also had some ideas how to implement a better satin stitch process.

**Comment by kaalleen** [comment]
> Also had some ideas how to implement a better satin stitch process.

How interesting. What do you have in mind?

**Comment by kaalleen** [comment]
Command line code has been documented on the website.
I think that's why we kept this open?
