### ISSUE TITLE
stop position command

### ISSUE THREAD

**Issue by kathinsk** [inkstitch/inkstitch#1921]
Hi everyone 

I got the following error message when trying to define a frame out position:

Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\layer_commands.py", line 23, in effect
  File "lib\commands.py", line 404, in add_layer_commands
  File "lib\svg\path.py", line 67, in get_correction_transform
  File "lib\svg\path.py", line 44, in get_node_transform
AttributeError: 'NoneType' object has no attribute 'getparent'

Thank you for your help.

![Stickdatei Fuchs](https://user-images.githubusercontent.com/119119679/204095476-a78f2949-02b0-4687-b675-1a0baf7c8c25.svg)

**Comment by kaalleen** [comment]
Thank you for reporting this error message along with an svg file. This is very helpful for us.

In your svg file there is no layer and Ink/Stitch is trying to find a layer to place the command in. Open the `Objects > Objects and Layers` dialog and add a layer. Place your shape into that layer and try to add the command again.

**Comment by tyrosinase** [comment]
FWIW this seems to be a really common thing in SVGs and maybe Ink/Stitch should handle it gracefully. For instance all the Twemoji are no-layer SVGs, and also have weird color info (that Inkscape itself drops in confusion when you Break Apart or otherwise poke it... though ISTR Ink/Stitch copes fine if you happen to leave the shape unmodified).
