### ISSUE TITLE
'LineString' object has no attribute 'geoms'

### ISSUE THREAD

**Issue by 19msullivan** [inkstitch/inkstitch#1931]
Hi! 

I made a file (both within Inkscape, and Illustrator) but when I try to use my Ink/Stitch extension, Params only shows part of the image stitched out. I've tried making it with text fonts, and making the text using a line tool, but in both cases, some of the objects will not stitch. When I try to run the Realistic Preview, gives me this error message:

"Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\print_pdf.py", line 312, in effect
  File "lib\extensions\base.py", line 200, in elements_to_stitch_groups
  File "lib\elements\element.py", line 329, in embroider
  File "lib\elements\element.py", line 387, in validate
  File "lib\elements\fill_stitch.py", line 321, in validation_errors
  File "lib\elements\fill_stitch.py", line 274, in shape
AttributeError: 'LineString' object has no attribute 'geoms' "

This is the file I am trying to convert to a PES file:
![CookLab](https://user-images.githubusercontent.com/119435799/204579500-b3153a2d-d61c-4fdd-bfd0-2f97cabd3c3e.svg)

Let me know if you have any solutions! Thank you:)

**Comment by tyrosinase** [comment]
That looks like the same as https://github.com/inkstitch/inkstitch/issues/1794, and the same situation as I explain in this comment: https://github.com/inkstitch/inkstitch/issues/1794#issuecomment-1221362680

**Comment by 19msullivan** [comment]
I've been reading through those! Is the solution to install the "development build of kall/test"?

**Comment by tyrosinase** [comment]
That's one solution... but really, if you find the broken path, you don't absolutely *have* to run the dev build (especially because I think there is about to be a new release). The dev build just fails more gracefully, as I understand it... it isn't going to make the path stitchable.

One way to track it down is by selecting subsections of the graphic and running Troubleshoot or Visualize on it (though the latter will seem to hang because you have to close the preview window for the error window to show). In this case it's the vertical coming out of the first "o" - it's got a fill on it, and Ink/Stitch can't fit any stitches into it. (Probably a good test situation, @kaalleen.) If you clear the fill (and any others, if that turns out not to fix it) it should be fine in the current release.

You will probably want to replace the lettering with a built-in font if you can rather than manually converting to satin, but if you want to do the latter there's a tutorial here: https://silverseams.com/tutorials/satin-joins-and-corners/

**Comment by 19msullivan** [comment]
Thank you so much! I am still learning the software, but I will use the built in fonts. I appreciate the speedy reply:)
