### ISSUE TITLE
'LineString' object has no attribute 'geoms'

### ISSUE THREAD

**Issue by dakki3** [inkstitch/inkstitch#1978]
Yes I have gone through previous threads of this and saw the comments leading to what the fix should be. I downloaded the files but am unsure how to implement them into the program in order to fix this bug. 

Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):

  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\output.py", line 56, in effect
  File "lib\extensions\base.py", line 200, in elements_to_stitch_groups
  File "lib\elements\element.py", line 329, in embroider
  File "lib\elements\element.py", line 387, in validate
  File "lib\elements\fill_stitch.py", line 321, in validation_errors
  File "lib\elements\fill_stitch.py", line 274, in shape
AttributeError: 'LineString' object has no attribute 'geoms'

![bmo](https://user-images.githubusercontent.com/121359666/209449758-c59bcf1b-9d1e-419c-bd98-046fa630472e.svg)

**Comment by tyrosinase** [comment]
I'm not a Windows user so that will have to be up to someone else to step you through, but if you drag the selection tool around to select various bits of the image and see which ones render (in preview, or as saved stitch file), you can eventually track down the problem object(s) even without loading the dev release. In this case:

![image](https://user-images.githubusercontent.com/9473609/209454979-cf188b6c-1494-45b5-bc9b-f82e55c06511.png)
![image](https://user-images.githubusercontent.com/9473609/209454987-4c42456b-03d8-4fa3-a08e-88d6d60038fe.png)

There's a one-node object floating in the body, and a two-node one in the + button, both in Layer 1. Delete those and the file will save successfully. The bad news is: it won't stitch out well. You'll definitely want to convert the black outline to satin first, because a fill won't give you a nice clean edge. https://silverseams.com/tutorials/digitizing-outlined-graphics/

**Comment by dakki3** [comment]
> I'm not a Windows user so that will have to be up to someone else to step you through, but if you drag the selection tool around to select various bits of the image and see which ones render (in preview, or as saved stitch file), you can eventually track down the problem object(s) even without loading the dev release. In this case:
> 
> ![image](https://user-images.githubusercontent.com/9473609/209454979-cf188b6c-1494-45b5-bc9b-f82e55c06511.png) ![image](https://user-images.githubusercontent.com/9473609/209454987-4c42456b-03d8-4fa3-a08e-88d6d60038fe.png)
> 
> There's a one-node object floating in the body, and a two-node one in the + button, both in Layer 1. Delete those and the file will save successfully. The bad news is: it won't stitch out well. You'll definitely want to convert the black outline to satin first, because a fill won't give you a nice clean edge. https://silverseams.com/tutorials/digitizing-outlined-graphics/

I ended up able to fix this by doing as you said, deleting the paths I did not see were there as well as redoing some of the smaller paths one by one and saving after each addition. I'm not sure which one did it or if I just redid paths unnecessarily but I appreciate your help! Thank you for the link for that I will be using that in the future- last minute xmas gift and didn't have time to play around too much :)
