### ISSUE TITLE
Double stiching some areas

### ISSUE THREAD

**Issue by chrisyelf** [inkstitch/inkstitch#1982]
When making a .pes from this svg
![bee](https://user-images.githubusercontent.com/121562270/209832685-8ec9ea8b-0160-4f76-b65e-1bc217cde524.svg)

The brown vertical areas are filled with yellow first (the entire body), and then brown is stiched over it. Could it fill brown areas only with brown?

**Comment by chrisyelf** [comment]
![Screenshot from 2022-12-28 17-14-15](https://user-images.githubusercontent.com/121562270/209833031-1fe8e86d-3263-4021-a13b-fcae156806f4.png)

**Comment by tyrosinase** [comment]
That is what the SVG looks like, so that's what Ink/Stitch stitches out. It's very literal.

![image](https://user-images.githubusercontent.com/9473609/209843842-2aab3d09-38ad-483c-b126-1446fc7c3d2b.png)

The graphic is designed for screen display, where only the last layer matters. To make it more suitable for stitching, you can duplicate the brown shapes and subtract them from the yellow with `Path > Difference` (and then `Break Apart`, clean up any remaining slivers using the node editor and `Troubleshooting`). The same is true for the stinger, and wing shapes in #1981.

You'll also want to turn off the outlines, and copy the shape so you have a single zigzag or satin line for each outline segment.

**Comment by chrisyelf** [comment]
Again, thank you. I'm new to these concepts. Appreciate your time, Tyrosinase!
