### ISSUE TITLE
Using "stroke to path" to create satin columns?

### ISSUE THREAD

**Issue by noddycode** [inkstitch/inkstitch#1991]
I'd like to contribute something like this eventually, but I have no experience coding inkscape plugins so I wanted to see if this was a viable idea or something that has been tried.

While struggling with editing satin columns, I read back on [this issue](https://github.com/inkstitch/inkstitch/pull/1751#issuecomment-1196144705) that mentions that main issue with keeping satin columns as simple lines is the unpredictable behavior of Shapely when converting a single stroke to two parallel lines. However, it seems that inkscapes built-in "stroke to path" does a pretty good job of this.

Taking the example shape:

![image](https://user-images.githubusercontent.com/23208696/210159964-12ac300b-a907-464c-bf2e-68c78f3c806e.png)

When using "stroke to path", it generates a single path from the outline that is parallel on both sides to the original stroke.

![image](https://user-images.githubusercontent.com/23208696/210159994-4f46491d-63c5-4bc8-835a-c0fd007337dc.png)
![image](https://user-images.githubusercontent.com/23208696/210160004-ca01d93e-d90b-4fcf-8dab-8174864001fe.png)

The challenge then is to 1) delete any squared off end nodes, 2) make sure both sides of the path are going the same direction  and 3) add rungs, but supposing users could still add rungs on perhaps another layer, would it work to use this method behind the scenes to automatically generate the parallel strokes needed for a satin column?

I've done the above steps manually for one of my patterns and it seems to be working well in the preview so far. I'll eventually finish this and actually embroider something to test it out.

**Comment by kaalleen** [comment]
Thank you for wanting to contribute. Here some thoughts about this problem.

These shapes are definitely not nice for satin columns. It doesn't really matter how we process them (as long as we use a single shape). These edges would look much nicer, if they were created like in this little satin edge tutorial on our website: https://inkstitch.org/tutorials/satin-edges/

Anyway, let's assume, we actually want these edges.

If we use stroke to path we get the merged outline. Which would be a problem if we have self crossings.

![stroketopath](https://user-images.githubusercontent.com/36401965/210258092-789acf74-807d-4418-a475-5f5d507802b5.png)

Next we cannot use Inkscape path operations in extensions, but that's not a big issue in this case, because an operation like stroke to path can as well be done with shapely.

**Comment by tyrosinase** [comment]
At the risk of sounding facetious: I didn't realize line-to-satin was even supposed to be working right now. I *always* use stroke-to-path and do it manually.

A quick test: 

3mm satin box
Converted direct from rectangle object: ope, got some weird corners.
Converted to generic path shape, bottom side split in the middle to control the starting point of the satin: almost fixed it, still have one bad corner.
Converted to generic path shape, all sides split in the middle, broken into four shapes. This time for sure, Rocky: haha oh no I'm gonna stop before shapely starts drawing swastikas or something.

![image](https://user-images.githubusercontent.com/9473609/210262530-18c875f9-1e6b-4c62-a63a-ee079967609c.png)

**Comment by tyrosinase** [comment]
(I'm on the 2.2.0 release fwiw; my plans to clean up those alphabets and stress-test the release candidate kinda got derailed over the holidays. Soon!)

**Comment by noddycode** [comment]
@kaalleen to be clear, my dream is to allow satin columns to be made in the background so that the original path may be freely edited without having to convert it to a satin column path and replace all the rails. Perhaps the simpler method would be to just allow rails to be defined as a separate path before conversion, but I'm hoping that a more foolproof method would allow some other additions down the line, like assistance with planning sharp corners.

> Next we cannot use Inkscape path operations in extensions, but that's not a big issue in this case, because an operation like stroke to path can as well be done with shapely.

My understanding was that Shapely's parallel path functionality was not completely reliable, which is the reason it potentially fractures the original path into many paths. This is the process I'm attempting to simplify. Are there improvements that can be made with Shapely to achieve a result similar to "stroke to path"?

As a last resort, it does seem that inkex's command module could be used to call "stroke to path" directly, specifically with the [inkscape_command](https://inkscape.gitlab.io/extensions/documentation/source/inkex.command.html#inkex.command.inkscape_command) function. "stroke to path" is listed as one of inkscape's edit verbs so that may work, 

> If we use stroke to path we get the merged outline. Which would be a problem if we have self crossings.

This is one thing I'm not sure how to handle, but I'm wondering if the benefits of using "stroke to path" (if you do see any) would be worth at least offering it as an option for those who do not have self-intersecting shapes (perhaps there's a way to detect these automatically?)

**Comment by kaalleen** [comment]
Yes I know, that would be nice.A lot of people are using fills and zig zags when they should use satins. But they avoid doing so, because satins cause them to spend more time to prepare their designs.

I'm not sure though if calling a second inkscape instance with the inkscape commands is our best option for this issue here and "stroke to path" will cause other problems.

This is what you get from shapely parallel_offset (right and left colored differently).

![offset](https://user-images.githubusercontent.com/36401965/210421120-411f765e-03ea-4843-90d2-16ab43d92537.png)

For shapely 2.0.0 parallel_offset will still exists, but they recommend to use offset_cruve instead. But we didn't update yet.

**Comment by noddycode** [comment]
Sorry for the gap in responses, would parallel curve do everything you expect for making a satin column? If so, I can try to work on updating that.

**Comment by lexelby** [comment]
> My understanding was that Shapely's parallel path functionality was not completely reliable, which is the reason it potentially fractures the original path into many paths. 

Nope!  It's plenty reliable: it does exactly what it's designed to do.  The problem is that what it's designed to do is not what we _want_ it to do.  `parallel_offset()` (and `offset_curve()`) are designed to "return a new shape with all points _n_ pixels from the original shape".  What we want is "return a new line that follows along _n_ pixels to the right (or left) of this line, even if this line crosses itself".

We coded Ink/Stitch to try to counteract the issues with the line crossing itself (or even just coming near itself).  It detects the case that the line comes near itself, backtracks, and tries splitting the line in half and processing the two halves separately.  It repeats this process until it finds pieces that don't cross themselves, such that it's able to produce sensible offset curves from each piece.  That's why you sometimes see a bunch of satins.  It's our code trying the best it can to work around the way that both shapely _and_ Inkscape do these offsetting operations.

**Comment by lexelby** [comment]
More explanation of why this is hard here: https://github.com/inkstitch/inkstitch/pull/1751#issuecomment-1196144705

**Comment by lexelby** [comment]
All that said, I would _love_ it if we could figure out a way to reliably convert lines to satins, along the lines of #255.  It just needs to work :)

**Comment by noddycode** [comment]
Ah, I misunderstood what the issue with parallel offset was, thank you for explaining!

A conundrum, indeed. I will go ahead and close this and track #1751 .
