### ISSUE TITLE
JEF format is broken

### ISSUE THREAD

**Issue by lexelby** [inkstitch/inkstitch#204]
When exporting as JEF, it's a complete mess.  There don't appear to be anywhere near enough stitches, and everything's all over the place.  What's amusing/surprising is that there are some vaguely recognizable elements, seemingly at low resolution or something.

![jef_broken](https://user-images.githubusercontent.com/4446653/41494661-5e03f3d4-70e4-11e8-8750-33ead3c1f360.png)

**Comment by tatarize** [comment]
If memory serves it's something along the lines of the written stitch count is overtly the stitch count regardless how many bytes are used to encode that stitch and the libembroidery code says take that count and and double it and that's the number of bytes expected, but that's in error because it's actually supposed to be stitchcount and some takes 2 and some takes 4, but both of those count as one. In load it says:

numberOfStitchBytes = binaryReadInt32(file) * 2;

and in save it says:

binaryWriteInt(file, embStitchList_count(pattern->stitchList) + jumpAndStopCount);

Which kind of works, but actually the stitchcount is the stitchcount regardless how many bytes are used to encode it. So I think at times the format will load and save their own files correctly, but if you have a 4 byte encode everything after that goes completely wonky or something.

And there was something else that caused it to read wrong and ended up swapping x, and y for parts of it beyond getting the count wrong and truncating early. 

I corrected this with the transcode in Java, but I regret that I didn't pay enough attention to what went wrong as I assumed it was an error in translation rather than in libembroidery itself.  I do recall it was just a couple tiny errors where a number was slightly off. And there was some error that became apparent after it was made totally compatible with its own loader and saver it got incompatible with known correct JEF files (I think save being stitches regardless whether 2 or 4 byte, and not assuming it was the half the number of bytes). And some robustness issues like anytime the X byte was 0x80 it was always control byte and needed to always skip those 2 bytes and the code in libembroidery would, on a failed catch use those bytes and toss them into the movement routine.

It might have been something else using 0x80 0x10 which caused the libembroidery routine to firstly throw that into moving the position, but also had the bizarre code:

```
            else if(b1 == 0x10)
            {
                embPattern_addStitchRel(pattern, 0.0, 0.0, END, 1);
				stitchBytes += 1;
                break;
            }
```

Which changed the parity of the stitchBytes number there and swapped x and y and screwed up the control codes, which then would be 0x80 in the y, which didn't trigger any control catches.

I'll check back into this for libembroidery and open an issue there.
