### ISSUE TITLE
Auto-routed Satin Column

### ISSUE THREAD

**Issue by lexelby** [inkstitch/inkstitch#214]
It would be cool if Ink/Stitch could automatically determine a stitch order for a group of satin column objects.  It would break satins if necessary and add running stitch between sections, always ensuring that the running stitch is hidden by later satin stitching whenever possible.  Start/end markers should also be possible as in #20.

Much like with AutoFill, the algorithm is going to be tricky.  Also as with AutoFill, I'm not sure how to have the user specify this in the SVG.

How would the user tell Ink/Stitch that a group of satins should be treated as a single unit for purposes of automatic routing?  I can think of two options, both with pros and cons:

1. Group the satins together (Object -> Group)
  * **Pros**:
    * easy to do in Inkscape UI
    * easy for Ink/Stitch to parse
  * **Cons**:
    * no visual indication of which satins are included in the group
2. Add a Command (symbol) for "auto-satin" and draw a connector line to each satin that should be part of the group.
  * **Pros**:
    * visually obvious that the satins are grouped together
    * (mostly) easy for Ink/Stitch to parse
  * **Cons**:
    * **nearly impossible** to do in Inkscape UI
      * The flow-chart Connector tool does not allow for drawing a connector line to an unclosed path like a Satin column.
      * Possible workaround: select the satins and run an extension, "Group Auto-Satin", that creates the auto-satin symbol and sets up the connector lines.
        * Once you set up the connector lines, Inkscape is happy to work with them as it does with any other connector.
3. Draw a dotted-line rectangle around the satins that should be treated as a unit
  * **Pros**:
    * (mostly) visually obvious
  * **Cons**:
    * harder for Ink/Stitch to parse
    * not as discoverable for the user
    * kinda... weird?
    * the dotted-line box may be visually distracting
4. Link all of the satins together as one single path
  * **Pros**:
    * perhaps the most sensible option of all for the user
  * **Cons**:
    * amplifies the problem in #195 about 100x
      * I'm really not sure how Ink/Stitch could reliably determine which things are rungs and which are rails if there are multiple sets of rails...

Anyone have any other brilliant ideas?

**Comment by lexelby** [comment]
This would be a pre-requisite for some of the more advanced features discussed in #142.

**Comment by wwderw** [comment]
I'm thinking number 2, especially if this is going to be the base for #142.  

Now, for full disclosure, this is the closest option that I would be used to using other software, where we have complete objects, so people with differing software experiences, it may not be the same.  I dunno.

I do believe which ever one that's a good base that helps with a smooth implementation of #142, because that's the crux of most any embroidery shop.  Even the hobbyist.  I think something making lettering easier and since lettering is best accomplished as a satin stitch, this base is going to be a biggy for that.  At least in my mind.

Thoughts?

**Comment by lexelby** [comment]
Interesting. So you think #2 would make sense to you as a user even though you'd have to use an extension to do the grouping?

**Comment by kaalleen** [comment]
I would vote for option 1.

It seems to be so natural to group connecting parts of the design. Most users would do this anyway. But here is also a problem, it could force the user to avoid grouping in case they don't want to use auto-routing. I think, we would need a checkbox within the satin column menu "use groups for auto-routing" or something like that. This way it would be super easy to turn it on and off, while users can keep their grouping as they like. In my opinion it would be a fast and easy way of doing it - both on the users side, but also easiest to implement.

**Comment by danielkschneider** [comment]
Hi, I'd prefer option 1 since it is "more SVG" (I do not know for sure but I see some potential for parametrization at the group level, see below).

This could also imply that users might be able to parametrize a group, with an inheritance mechanism that would preserve params in its member objects while allowing satin (and other params) at the group level. Routing children that are satin would be just one group parameter out of others. That proposition reflects the idea that SVG elements inherit stuff from its parents. https://developer.mozilla.org/en-US/docs/Web/SVG/Element/g

Implementing Kallen's button at the group level (as opposed to "use groups for auto-routing") might require some kind of reset button in the group popup: remove all  embroidery params from children in order to quickly deal with a dozen objects that are to be satin stitched.

**Comment by lexelby** [comment]
Awesome discussion here, thanks everyone!

While driving this morning, another option occurred to me:

5.  An extension that reorders and splits satins and adds running stitch objects as necessary.  The user would select a few satin columns and run this extension.  It would figure out an optimal stitch path and restack the satins as necessary to realize that path.  It would break satins and add running stitch paths (dotted line) as necessary.
  * **Pros**:
    * Feels natural and easy to understand.
    * Allows the user to see _and tweak_ the stitch ordering decisions that Ink/Stitch makes.
  * **Cons**:
    * ?

One could use start/end markers as with fills to guide the algorithm.

I could see possibilities for making a similar extension for autofill, too.

**Comment by kaalleen** [comment]
I like the new option, because of the idea to enable the user to tweak the results if needed.

**Comment by tatarize** [comment]
I'm more confused here. Why do you do a long winded breadth first search algorithm looking for a loop?

Do a depth first search algorithm you will by definition find a loop. If you never visit the same node twice, you can only ever get stuck back at the node you started from. You then have, or may have, these other nodes that weren't visited in our loop created by a random walk. We are Eulerian after all. 

All the unvisited nodes in those cases are attached to Eulerian graphs. You removed a loop. So you could not alter the Eulerian-ness of the connected nodes. You might have created orphan loops though, but you could not have created anything with an odd order. Everything had an even order and we removed an even order. We then do the same thing to any of these left over nodes and we get a loop from them too. We continue until we're out of nodes. Then we connect up all of our loops at the the first node we find they share (and they by definition will share at least one node with another loop) until we're out of loops. We have one big loop. That's a circuit. 

Also, why the hate on tiny loops? Gotta find one bigger than 2? If the loop is there it's a loop, add it to the pile. The thing that actually matters is that loops made entirely of scaffolding can be disregarded. That's really why you don't want those tiny loops. Just as we can find loops by walking (depth first search), and add those loops together. We can find pointless loops of scaffolding and just chuck those out the window. You removed an even number of links. Therefore you cannot have compromised the Eulerian nature of the graph. But, since the loop was made of entirely don't care stitches then we literally don't care, just chuck that loop out. It doesn't matter.

**Comment by tatarize** [comment]
> There are five heuristics used in autofill.py, and four of them are designed to try to ensure that the breadth-first search doesn't end up blowing up and searching way too far. Without them the algorithm wanders around forever and never finds a loop in any kind of reasonable time.

Okay, use a depth first search algorithm and you by definition will find a loop with a random walk starting from any node. 4 of them unneeded and that search will never blow up.

> The question in my mind is, if we start making more complex fill patterns (especially ones where rows intersect each other or intersect the outlines in weird ways), do my heuristics begin to fail?

The power of the algorithm is there's a solution. Your heuristics are based on a false premise. No amount of complexity will cause any issue ever. You can solve any graph. And solving the graph is very often done in order N where N is the number of nodes. Linking the loops together at the end if you have orphaned loops sometimes require you rewalk your loop, find another loop and doing a 2-opt crossover to link them.

There is some depth first utility with Dijkstra where you, want to look through every node to find a path (not a loop), because by definition you can discard exactly 1 non-loop path made entirely of scaffolding, from the graph at the end. You want to find that path to be the longest most serpentine bastard known to man. That's actually pretty easy to solve for using Dijkstra (order N where N is the number of nodes) . In fact when you, discard that, or call it the start of your loop, and you will end up back at where you started and you will have dropped the most scaffolding possible. In my version of this you might even end up dropping all non-essential scaffolding leaving the final path as the only possible path.

Given the complexity is not an issue, you can use the same thing to solve this. Just attach all the satins together with double links and solve for the entire thing. You'll end up with perfectly reasonable pathing. Obviously you'll want some heuristics if you can cut and it'll save X stitches then that matters, or if you have two nodes that are really close together, but don't actually connect, you can go ahead and nudge nudge wink wink give them a double link and when you solve one'll get dropped.

Things get a bit more complex when you use the same hammer to do underpathing. Obviously if you connect the rungs at the center with scaffolded underpathing the algorithm will throw out that underpath nearly all cases and use it in a small subset of those cases when it's actually correct to do so. However, underpathing actually only works given the order you go through the graph, and that throws a big ass wrench into the math gears. But, no when I noted this algorithm is brilliant, it really is. You can solve for a lot of stuff. Given my wonderful understandings of linear geometry and the fact that I've implemented similar things before explicitly for embroidery, I'm kind of sad I didn't think of it.

**Comment by tatarize** [comment]
In fact, I'd be shocked if you couldn't do all this work in constant time. I mean if you keep track of the essential bits and the scaffolding. You could just resolve the algorithm on the fly instantly when something changes even when it's wildly more complex. You then wouldn't even need this group and ungrouping nonsense. Every object would already be linked together using a linear time algorithm. If the user doesn't like the way that looks, have them nudge the path it found. It doesn't seem like it would take any extra time to add some veto powers to some particular links. If they delete some of the automatically generated scaffolding over the entire project (in ways that by definition do not violate the Eulerian constraint) it'll solve just as easily. 

Literally, man, you have a fucking winner here. While solving for the smallest amount of scaffolding is going to be order NP TSP problem, solving for any solution is linear time. You could even implement something like 2-opt and come remarkably close to the optimal solution. If you did that on a worker thread it might look pretty awesome too. Though that's a bit extreme. However if you've ever seen StippleGen, you'd be solving that but for required line segments.

**Comment by tatarize** [comment]
Likewise you could apply this to things like #195, using a better heuristic to determine that the two lines with the most intersections are non-essential scaffolding, would equally solve not just the that given geometry but a lot of other ones. Though this would be especially true if you could somehow just flag some element as scaffolding. Then you could generalize a lot of different things. Just draw two scaffolding lines through a bunch of lines and the solution would end up being a satin stitch basically by default. Unless there's some reason it can make a better solution because the lines are crossing or something.

**Comment by tatarize** [comment]
If you used my variant that doubles all links, even the rungs and just calls the second copy scaffolding, it would have the other interesting effect that #106 would be free. If you flagged a line as scaffolding and connected a bunch of rungs together with 1 rather than 2 rails it would, oddly enough, be forced to produce an E-stitch as the only valid solution to that graph.

**Comment by lexelby** [comment]
It's really hard for me to keep up with you when you say a bunch of things in one go like this.  Can you please try to consolidate a bit next time?

> Don't you think your every other node algorithm is too restrictive for creating a Eulerian graph? I mean there's some obvious topologies that cannot be rectified.

I think you mean every other edge?  That's the key insight from the paper I linked to in the comments: whatever the shape is, it's always possible to duplicate alternating edges on each outline (the outer outline and the hole outlines), and doing so will always result in an Eulerian graph.  Duplicating every outline edge doesn't.

I could add yet more edges on the outer outline, but I don't because I'd like to reduce the number of times the algorithm can sew over the same spot.  With underlay as the algorithm stands, it can sew each spot at most four times, which won't result in a thread or needle break.

> If you have a specified start position and a specified end position, why do you double those links? 

I could, but the way it is now is simpler to implement, and it's not a big deal adding extra edges along the path.  They usually just get turned into back-and-forth fill.

> Double every link and you have a Eulerian graph there. Just saying. Oh, and conceptually in this all doubled rungs would be flagged as scaffolding.

We don't want to double the rows, because we only want to stitch them once.  Even if we label the first pass through a double-stitched row as "scaffolding", it still has the potential to mess up the appearance.

> Why do you do a long winded breadth first search algorithm looking for a loop?

BFS has the distinct advantage that the first loop I find will be the shortest possible loop.

> Also, why the hate on tiny loops? Gotta find one bigger than 2?

I don't want to go down and then back one of the duplicated edges.  I can't remember the full details on this heuristic (and maybe it's obselete now?), but it was something like this: by consuming that tiny loop, it interfered with the ability to find the next loop easily.

The underlying issue here is this: it's easy enough to find an eulerian path.  It's difficult to find one that makes sense when stitched out.  It's no good if we stitch one row here, go down 10 rows, stitch a couple, come back up, stitch a few, etc.  The sewing order is really weird, and that kind of thing is going to matter to machine operators.  The heuristics are primarily designed with the goal of increasing the likelihood of long runs of boustrophedonic stitching.

If I didn't care about that, I'd just use this: https://networkx.github.io/documentation/networkx-1.10/reference/generated/networkx.algorithms.euler.eulerian_circuit.html

> You could just resolve the algorithm on the fly instantly when something changes [...]
> If the user doesn't like the way that looks, have them nudge the path it found. [...]
> If you did that on a worker thread [...]

I think you might be missing one of the key constraints of Ink/Stitch: it's an Inkscape extension.  When you invoke an Inkscape extension, Inkscape saves the document to SVG behind the scenes, runs your extension on the SVG, your extension prints out a new SVG, and Inkscape transparently replaces the document with the new SVG.  We can only do stuff when the user asks us to, and it's a blocking operation.  No UI interaction. :(  On the other hand, we get a _huge_ amount of vector UI power from Inkscape, so it's worth it.

**Comment by lexelby** [comment]
You've largely got the idea of the algorithm I have in mind for auto-satin.  Here are my notes:

auto-satin
  * use hierholzer again
  * build graph by duplicating each segment of each satin
  * once you find the final path through the graph:
    * the last traversal of each section is satin
    * all previous traversals are running stitch
  * do a simple path-finding algorithm from start to end to start it off
    * implicitly adding a third duplicate edge along the path
    * or maybe not?  we'll have to see how the pathing comes out
  * break up paths where they intersect with other paths
    * such as the crux of a K
    * perhaps instead, just break paths up into segments ~.5mm long?
      * this might achieve the same effect and be way simpler
  * add jump edges between nearby points such as the center of an X
  * also add doubled jump edges between "islands" to form a fully-connected graph
    * e.g. if they auto-satin an entire word at a time, add a jump between and double it to keep the graph eulerian

This one's much easier than fill stitch.  We don't really care about the pathing order -- it's going to come out looking fine.  The graph is much smaller and less connected, so the likelihood of a really weird path that goes back and forth all over the place is much lower (I think).  All we really need is a path that gets us from start to end and uses each satin edge at minimum one time.

Figuring out which edges should be running stitch (underpathing) versus which are satin is really cool: if my eulerian path consumes a given satin edge `x` times, where `x > 1`, then all but the last time through should be running stitch.  Last one's always satin.  Boom, automatic hiding of the underpathing.

**Comment by tatarize** [comment]
Note, due to the connected nature of the graph, 2-opt sounds like it doesn't apply, but keep in mind we are judging the path taken as a whole because we would assign actual values to the paths, we could then clearly judge whether a 2 opt improves the path or doesn't based on our heuristic values we assigned rather than something like distance that is typical in 2-opt. The swaps would happen at the nodes given that they are all order 4.

Keep in mind that the path would be the entire path including all the scaffolding and would likely need to add a prioritization to entirely scaffolded loops, since those can be omitted at a finalization stage.

We would end up with a damned near optimal path. And you could get away from your current weird breadth first hard coded stuff.

**Comment by tatarize** [comment]
> We can only do stuff when the user asks us to, and it's a blocking operation. No UI interaction. :( On the other hand, we get a huge amount of vector UI power from Inkscape, so it's worth it.

I guess. But, that's kind of shackling for something that ultimately isn't really a vector. As the code improves I'm guessing this will be even more shackling. But, I guess writing most of the vector stuff for my android app has taken a goodly clip of time.

**Comment by tatarize** [comment]
For the autosatins, it seems like it might be better to build a Eulerian graph, find a Eulerian circuit, solve for near optimal value heuristics by applying 2-opt on that path.  When you add some heuristic values to the problem that are non-uniform you get TSP and that's pretty easy to solve (in a truncated but fast manner, rather than the NP try everything approach). In general because you could seemingly adapt this solution to every problem.

**Comment by tatarize** [comment]
In the paper (Arken 2000) she's arguing that the problem is TSP and you can effectively solve it finding minimal addition edges that guarantee a solution, given some caveats to the problem. The reason for only doubling every other bit edge is that it the least you can do while guaranteeing a solution. Even though the problem is NP Complete, you can solve it in linear time in a solution that adds 1.5 * E additional segments. Don't get me wrong that's great.

There's no actual amazing power to how make that Eulerian graph, other than the very very few extra edges is requires. The power is in the guarantee that you have a solution regardless of what you used to fill the shape and regardless whether the shape is complex or not.  Her solution is about proving the lower bound for this solution.  But there's no reason to restrict yourself to her solution to the TSP problem. You could break out the big guns for solving TSP, and since adding a heuristic also makes it TSP again, you could just use amazing power in the fact that after you cut any fill with any shape you can just make that Eulerian and solve it.

**Comment by lexelby** [comment]
> This is slightly false. See the topology I posted. 

I was referring to the case of parallel grating lines intersecting a shape for pattern fill.  It extends to pretty much any set of _continuous lines_ intersecting the shape, but your proposed geometry (the "O" shape) involves rays.

> Such things seem like they might be better off with a depth first version that provide actual metrics for a path like value prioritizing going edge, rung, edge rung, edge, rung, [...]

These are interesting ideas.  If you think your idea will work better than the current algorithm, please by all means try it out and file a pull request.  I'd love to be able to switch to a DFS.

> The power is in the guarantee that you have a solution regardless of what you used to fill the shape and regardless whether the shape is complex or not. 

And yet, as I said, our users aren't going to put up with a weird fill algorithm that goes all over the place.  We have to do better than "a solution exists".  Filling a region in a haphazard order, a few rows here and a few rows there, can distort the fabric, resulting in thin lines of fabric showing through between fill lines.

In any case, why are we bothering to discuss this to death here?  If you're interested in all this, feel free to try your hand at implementing it. :)  At the moment, I don't have the time available to work on Auto-satin.

**Comment by lexelby** [comment]
Big news: https://youtu.be/tbghtqziB1g

That's a demo of an extension to do option 5: reorder satins and add under-pathing and jump stitches, cutting satins if necessary.  So far the algorithm seems really solid and I'm just putting on a few finishing touches before I create a PR :D

**Comment by wwderw** [comment]
Oh man, that's awesome.
