### ISSUE TITLE
Install Inkstitch on MacOS

### ISSUE THREAD

**Issue by jeremybolger** [inkstitch/inkstitch#2169]
I have MacOS Big Sur and Inkscape 1.1.2. The link "Download Inkscape v2.2.0" will not work because it says "developer cannot be verified".

I tried downloading. the .zip file but this self-extracting archive will not self-extract on my system.

The Tutorial video shows downloading a file ....osx-64.tar.gz but this is no longer available on the web page. I searched the .zip file and found at least most of the .inx data files. But I cannot find the inkstitch.py driver file which is present on the tutorial video (or the /inkstitch directory).

**Comment by kaalleen** [comment]
https://inkstitch.org/docs/install-macos/
There are two download links. Can you confirm, that you chose the first button for big sur/ monterey?

It is uncommon for this version to show the developer cannot be verified message. If you tried this version explicitly and still have the issue, you can allow the installer to run by following this instruction: https://inkstitch.org/docs/install-macos/#xxxx-cannot-be-opened-because-the-developer-cannot-be-verified

**Comment by jeremybolger** [comment]
Thanks, all, Ies

**Comment by jeremybolger** [comment]
Thanks all, I have resolved my issues. It looks like Inkscape was not fully installed when I was trying to add Inkstitch last time.
