### ISSUE TITLE
Auto Underlay Ignored for Changed Paths

### ISSUE THREAD

**Issue by mskressin** [inkstitch/inkstitch#217]
I discovered what I believe is a minor bug. I think the best way to describe it is to explain how I discovered it. 

I had a design with "Auto Underlay" enabled on the "Params" dialog. The design stitched as expected and it came out beautifully with all of the expected underlays.  I then changed one of the path objects by selecting two overlaying paths and doing an Inkscape  Path->Difference operation to subtract one path from the other. I then selected Embroidery->Params again. I verified that the "Auto Underlay" option was still selected and in the preview window I noticed that the path object that I had modified did not show the underlay for only the changed path.  All other paths had the underlay as expected. Just to verify, I sent the .pes file to the sewing machine and it did indeed not do the underlay under only the changed object.  I went back to the "Params" dialog and deselected "Auto Underlay" and then re-selected "Auto Underlay".  After doing this, the preview window showed the underlay under the changed path as well as all of the other paths.  Sending the new .pes file to the machine produced a design with underlay under all expected areas.  So it seems that if you change a path while "Auto Underlay" is enabled, the code will ignore auto underlay for the changed path when producing the stitch plan.

**Comment by lexelby** [comment]
Thanks for reporting this!  Definitely a bug, although one we may not be able to fully fix. :(

Ultimately the problem boils down to this:

**Certain path modifications in Inkscape discard the Ink/Stitch Params you've set on the paths.**

This is kind of understandable, since Ink/Stitch is just setting extra XML attributes and Inkscape has no clue about them, but I wish Inkscape would retain the extra attributes in all cases.  Ah well.

There's a compounding problem: when you select multiple objects, the Params window doesn't make it 100% clear if some objects don't have values for those parameters.  It _does_ show you if multiple objects have _values set that are different_ -- it shows a notice that values differ and each setting has a dropdown with the different values observed.

In your case though, the object in question doesn't have values at all.  I think checkboxes like "[x] Underlay" are especially poorly managed or at least poorly exposed to the user.

At the heart of it, if you modify a setting or checkbox, then Params will apply it to all the objects, irrespective of whether they had different values for that parameter or did or did not have it set originally.  If you don't touch a param, it will not touch that param on the objects.  So the workaround would be: uncheck and then check "Underlay" and futz with all the settings.

Does this description match with what you saw?  If not, there may be a subtle deeper bug I'm missing here.

All of the above is intended as an explanation for the buggy behavior you saw, rather than an excuse.  I still consider it a problem.  I would love to hear ideas you have for how to make this user experience more understandable and better.

**Comment by mskressin** [comment]
Hi Lex,

Your description sounds like it is an exact match to the behavior of what I
saw. I believe I understand the issue you describe. I don't claim to
understand the code, but for those parameters that apply to all paths in
the tree such as the "Auto Underlay", would it be difficult, to have the
code reapply them to every applicable path in the tree each time the code
is executed? That way, if the user changes a path (such as I did), and
Inkscape wipes out the XML attribute, the parameter such as the "Auto
Underlay" attribute setting will be reapplied or disabled as specified by
the last setting of the parameter.  Sort of automatically implementing the
workaround that you suggested. I only suggest this, as the user may not (as
it was in my case) be aware that manipulating a object may loose a
parameter that they previously set and it may result in a ruined print (for
lack of a better term).

Just a thought

Mark

**Comment by lexelby** [comment]
Thanks!  This is a tricky question, and I'll have to think on it.  I know we previously had a discussion about this kind of thing, and I believe @x3msnake pushed the case that Params should automatically apply what you see in the UI to all the selected objects, not just settings you actually "touch".
