### ISSUE TITLE
automatic satin generation - Dev version satin-selection

### ISSUE THREAD

**Issue by bianchifan** [inkstitch/inkstitch#2175]
1st. Zigzag line  to Satin
working patterns:
sqare, sawtooth

Problems: zigzag works only with "smoothing" enabled.
Else it sucks.

no smoothing, rungs only
![Bildschirmfoto vom 2023-03-26 16-05-18](https://user-images.githubusercontent.com/17491743/227974765-301dccc0-db27-4b75-9b67-568d99d72039.png)

neither smoothing nor rungs
![Bildschirmfoto vom 2023-03-27 11-16-47](https://user-images.githubusercontent.com/17491743/227964784-7af9f498-1741-4f7d-aeca-b90bab5b4429.png)

Test SVG: 
![drawing](https://user-images.githubusercontent.com/17491743/227965004-6745f411-f3aa-4ce2-8b4c-a98921d7cb9e.svg)

2nd. Stroke to LPE Satin
pro:
- works on all tested objects, bezier plus special objects like circles and squares
- works fine with beziers with changing curves, right to left and vice versa (the first versions sucked at that point)
- the width of the generated satin can be easily  adjusted afterwards (!!)
- seem to work even when a generated path crosses itself (??!!!!), various conditions tested, in extremo its mirrored
 
cons:
- sadly the preview is gone.. :((
- the inner path does not follow exavtly the original curve, the more the width, the more the deviation
  in extremo : a circle becomes a square

Excellent
![Bildschirmfoto vom 2023-03-26 16-23-11](https://user-images.githubusercontent.com/17491743/227971019-e82287fd-c2ae-4e6c-908c-acd8bb0abbe0.png)

Excellent, but slightly deviation on inner paths
![Bildschirmfoto vom 2023-03-27 11-39-46](https://user-images.githubusercontent.com/17491743/227971422-09db054d-9e35-4f27-b9f7-c5199450944c.png)

no more circle, theoretical crossed part mirrored
![Bildschirmfoto vom 2023-03-27 11-38-33](https://user-images.githubusercontent.com/17491743/227972918-45c98dc4-e69c-4ae4-8705-8a99cedd2a21.png)

not so extreme, but distinctly visible
![Bildschirmfoto vom 2023-03-27 11-44-07](https://user-images.githubusercontent.com/17491743/227973903-7a407c8b-8736-42b8-9c26-7ea141973c89.png)![Bildschirmfoto vom 2023-03-27 11-43-29](https://user-images.githubusercontent.com/17491743/227974000-444ed2fb-5c5c-4351-bdaa-4d9cee4efb14.png)

Test SVG: 
![Drawing-1](https://user-images.githubusercontent.com/17491743/227975119-0cffb545-5450-4218-b43d-9c135b3dfa41.svg)

For both functions
no "apply & quit", two separate actions needed: apply, them close

**Comment by kaalleen** [comment]
Thank you for your review. I updated the zigzags so that they should be working.

There is not much I can do about the remaining issues with lpe satins. I removed the preview, because it only causes trouble. I myself ran into a lot of issues with the preview and sometimes the path disappeared completely and I wasn't even able to recover the path. So I rather disable the preview option than creating a mess in user files. When we apply the lpe, we actually delete the path attribute in the svg file, which in turn triggers inkscape to update the path automatically. This also happens, when you run the preview function, which then creates some confusion for any undo method.

This is a pure Inkscape extension and uses their gui system. They don't have an apply & quit button for extensions. Also they don't have a button to restore the default values. This would be so great to have for several inkstitch extensions.
