### ISSUE TITLE
change stop handling?

### ISSUE THREAD

**Issue by lexelby** [inkstitch/inkstitch#228]
@wwderw, this one's for you :)

I'm wondering if we should reconsider how Ink/Stitch handles stops.

How it is now:

1. User creates an object and adds a stop command on it.
2. Ink/Stitch figures out the stitches that make up the object.  (Stop commands are handled in a post-processing phase).
3. For objects with a stop code, Ink/Stitch looks at their stitches and adds an artificial/fake "color change" 3 stitches from the end.
4. Ink/Stitch adds another artificial/fake "color change" at the end of the object.

The user is supposed to see this tiny little 3-stitch fake color block and assign as a stop block (C00 for Barudan, a red needle icon for Janome).  The stop block says "sew with the color you were already using and halt the machine when you finish this color block".

This gets us what we need to program a stop code, but it kind of makes a mess out of the code.  One example of how it can be confusing: what if the object you want to put a STOP after is only 2 stitches long?  Gotta handle that as a special case (can't go back 3 stitches...).

I also don't think the way it stands now is particularly intuitive for the user.  Say you have a color block with 3 STOPs in it.  All they see on the Print PDF page is "Nr stops: 3".  It doesn't tell them anything about what those stops look like or how to identify them on the screen on their embroidery machine.  The 2 artificial color changes might appear confusing if the user isn't familiar with why Ink/Stitch does that.

Here's what I propose:

1. User creates an object and adds a stop command on it.
2. Ink/Stitch ends that stitch block and marks it as being a "STOP" block.
3. If more stitches of the same color thread follow, they'll be in a new stitch block.
4. At the end, Ink/Stitch looks at each stitch block that was marked as a "STOP" block.  If the block _before_ this block is not the same color, then it splits this current block in half.
    * The first will be a normal block (with an extra COLOR_CHANGE at the end) and the second will be a "STOP" block.
5. Add some kind of tag on the color block in the Print PDF operator detail view saying "STOP code" for every "STOP" block..

Step 4 is necessary because we must have a normal stitch block of the correct color before a C00/STOP stitch block, so the machine knows what thread color to continue sewing.  We only have to split once though, even if we have a bunch of STOPs blocks in a row of the same color (right?).

The big advantage here is that we'll be able to make it much more obvious to the machine operator where in the design they should be setting STOP codes.  It also makes the code cleaner which I'm in favor of. :)  It will significantly simplify the work to transition to pyembroidery, too.

So, does this make sense?  As a professional digitizer and machine operator, does this make intuitive sense to you?  Do you think it would make sense to you even if no one explained it to you first?

**Comment by wwderw** [comment]
![example](https://user-images.githubusercontent.com/24878362/42545302-b244b946-847c-11e8-908b-a9be4128532b.png)

This is just a rudimentary layout, no way trying to change the type of layout that we have in our print PDF.

What I'm used to is that lets say that you have a one color design.  If you are inserting 1 stop, their will be two color blocks in the stitch list.  The first would be the name of the color used and then second one would identify itself as a stop.  It will have the same color swatch as the previous block, but won't say Xmas red, it says stop.

If there are more of the same color of stitches that go to another stop, then you have another block that is labeled stop.  If you have more stitches that are the same color but do not go to a user defined stop, it's labeled like the first one, the name of the color.

This also matches how it looks on the needle assignment menu at the machine.  I think from that perspective is why something like this would work, it matches what the operator is used to seeing on the machine.

Thoughts?

**Comment by lexelby** [comment]
I can't quite tell if you're agreeing with me or trying to show me why what I've said won't work :)

Question: in your example, with a design that has 3 rectangles... are you expecting the machine to stop _after_ the second block or before?

**Comment by wwderw** [comment]
After.

**Comment by lexelby** [comment]
Got it.  What would you do if you wanted a stop after the top block, too?

**Comment by tatarize** [comment]
The way I indicate this in Touch Embroidery is that I have objects that are themselves a stop. 

![device-2018-07-11-003358](https://user-images.githubusercontent.com/3302478/42557093-62b0856a-84a2-11e8-8123-11e9963d02b9.png)

In theory if you treated stops and trims as first order objects rather than flags on stitch objects you could indicate any order of them. Though I treat all objects as unbroken bunches of stitches, stopping in the middle of something isn't specifically a thing.

**Comment by wwderw** [comment]
> Got it. What would you do if you wanted a stop after the top block, too?

Technically all those blocks (or actually color swatches, they aren't the stitched objects themselves) are all apart of the same block.

This is how an InkStitch generated file with a stop shows up in a different operator sheet:

![inkstitch stop operator view](https://user-images.githubusercontent.com/24878362/42560960-97a4c8ce-84bd-11e8-911d-82a6a02bfa88.png)

These colors are supposed to be of the same color block.

Now here it is using the stop code from within a different program and their operator sheet, the top section is to show that they are indeed the same object:

![ideal stop 1](https://user-images.githubusercontent.com/24878362/42560998-b8413fb8-84bd-11e8-89b8-2319e398d6cf.png)

![ideal stop 2](https://user-images.githubusercontent.com/24878362/42561039-d23fd870-84bd-11e8-94c6-dcf0e2247bf6.png)

Bare in mind, this is their container format, not the exported DST version.  I think what is happening is in the stitch file itself, it's calling for a color change, but what that stop code does is for the printout it's calling for a 2nd color block using the same color as the previous one.  Because when you look at the exported DST from that second program and bring that exported DST in, it does exactly the same thing as ours.  So the differences has to be how that stop is handled within the container format (our case SVG).  It appears to be doing 2 different things.  Causing a color change and making the printout behave a certain way.

Make sense?

**Comment by lexelby** [comment]
@wwderw Where did your latest comment go? It was really helpful.

What does the column with "3511" and "50" signify in that program?

**Comment by lexelby** [comment]
I think I'll modify step 4 above: it should look back for a trim or jump and split there if it finds one.  That should make it split in a "natural" spot.  If it doesn't find one, it'll just split the block in half.

My thinking is that I want the stitch blocks to make sense to the operator at the machine, for machines that render a preview of the stitch block (nearly every machine?).  The current method would just show three unidentifiable stitches for the STOP block which I imagine would be pretty confusing.

> For color info on the second one that represents the stop, I would actually have it labeled stop versus the color name. Leave the color swatch as is, RGB info etc, just have it titled "Stop".

Yup, that's what I was thinking too.

**Comment by tatarize** [comment]
Some issues though is that different formats implement a stop differently. PEC for example will flag different layers with different colors and in theory if you say you do a color change to the same color in the color list, it should perform a stop. So the distinction between a stop and a color_change is that a color_change changes to a different color and a stop changes to the same color. In DST there's no distinction at all, though you will enter them on the embroidery machine by color changing to the same needle in the machine setting. There are no colors, and you cannot tell a stop from a color change. In .u01 a stop is command that changes the needle to the current needle again (I believe). JEF also includes a color log and a stop should be color change flagged to the same color. EXP has no distinction and it's just coded as a color change.

In theory some of these methods are distinct enough that it might just be correct to write a stop command to the backend and raise an issue on pyembroidery if it's dealt with incorrectly. Asking the user to do it manually kind of requires they know what format they are going to writing to. You can also flag these back to back. It would be possible in many of them to say STOP and then COLOR_CHANGE so if you were changing applique and moving on to another needle it would make sense in the encoding even without some fakey stitches. It would just color change to the same color, then color change to a different one. It doesn't seem like it would have any issues with that.

**Comment by lexelby** [comment]
Turns out this was predicated on an incorrect understanding on my part.  See https://github.com/inkstitch/inkstitch/pull/234#issuecomment-406684071
