### ISSUE TITLE
new inkstitch update doesn't work on Mac ?

### ISSUE THREAD

**Issue by takbm17** [inkstitch/inkstitch#2325]
nothing works, everything I press show this message ( Inkscape has received additional data from the script executed. the script did not return an error, but this may indicate the results will not be as expected.)

and Inkscape now doesn't open my PES files. it says ( failed to upload ) ???

**Comment by kaalleen** [comment]
Hm, thank you for reporting! It is just a guess into the blue, but could you try this build here https://github.com/inkstitch/inkstitch/releases/tag/dev-build-test-macos-build

Thhis build is not notarized, so you'll have to follow instructions for not signed packages: https://inkstitch.org/docs/install-macos/#xxxx-cannot-be-opened-because-the-developer-cannot-be-verified

**Comment by takbm17** [comment]
> Hm, thank you for reporting! It is just a guess into the blue, but could you try this build here https://github.com/inkstitch/inkstitch/releases/tag/dev-build-test-macos-build
> 
> Thhis build is not notarized, so you'll have to follow instructions for not signed packages: https://inkstitch.org/docs/install-macos/#xxxx-cannot-be-opened-because-the-developer-cannot-be-verified

it worked, thank you so much.
