### ISSUE TITLE
Would anyone know why when I try to load a .PES file to my Brother ULT2002 on a floppy drive, it does not show up on the screen?

### ISSUE THREAD

**Issue by BobCanuso** [inkstitch/inkstitch#2372]

**Comment by tyrosinase** [comment]
Sadly, no. I have the Baby Lock version of the ULT2001 and it loads files smaller than 5x7 from the floppy, but no larger - and it's a 6x10 machine.

Do you have the card writer? Mine was my late MIL's machine and she got a card writer *after* having the floppy, which seemed odd to me - FIL doesn't remember why she went that direction (since it seems like the cards are more of a hassle than the floppies) and the only thing I can think of is that the floppy can't handle larger designs. He hasn't located her writer for me to test the theory, though.

It should also read DST files (same format but no color info) but that didn't make a difference in my situation. If you can't load even small designs though, maybe give that a try.

**Comment by BobCanuso** [comment]
Thanks so much...I have an old laptop capable of saving to a 3.5 floppy
which is what the brother also uses...I found success with both formats as
I just rotated the artwork 90 degrees.
Thanks

**Comment by BobCanuso** [comment]
one weird thing though...when I trace to bitmap, the path shows two lines,
even though I created only one line.

**Comment by tyrosinase** [comment]
> Thanks so much...I have an old laptop capable of saving to a 3.5 floppy which is what the brother also uses...I found success with both formats as I just rotated the artwork 90 degrees. Thanks

Oh dang I'm gonna feel so dumb if I just needed to rotate my design.

(That machine is presently on the "low-priority" shelf behind a bunch of stuff to go in the garage we haven't built yet after a move, but I might have to shuffle everything around to get it out and try that. My PE800 auto-rotated stuff so it didn't even occur to me that would be an issue but of course the Ellageo is significantly older.)

**Comment by tyrosinase** [comment]
> one weird thing though...when I trace to bitmap, the path shows two lines, even though I created only one line.

Yep, trace to bitmap traces the outline of a line just like any other shape, by default. If you switch from `Brightness Outline` to `Centerline Trace` you'll get a single line (though it's about as good at getting it right as "AI" art is at drawing hands, so it'll take some polishing).

Of course, if you're doing satins you will eventually want two lines anyway. https://silverseams.com/tutorials/digitizing-outlined-graphics.html may be useful for figuring out what to do with them.
