### ISSUE TITLE
The Stitch Preview isn't working for me...

### ISSUE THREAD

**Issue by NekaB** [inkstitch/inkstitch#2419]
I have installed Inkstich in inkscape, but when I click 'stitch plan preview'  and select the 'live preview' option, it gives this error message:

**[133382] Error loading Python lib '/home/Goddess/.config/inkscape/extensions/opt/inkstitch/bin/libpython3.8.so.1.0': dlopen: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /home/Goddess/.config/inkscape/extensions/opt/inkstitch/bin/libpython3.8.so.1.0)**

Also when I select the stitch simulator/realistic review. Nothing happens.

I have a Centos 8 Linux Distro. Please let me know if you can help. Thank you

**Comment by bkmgit** [comment]
@NekaB  Thanks for reporting this.

- How did you install Ink/Stitch, using the rpm or using the linux.tar.xz file? 

- Can you type `ldd --version` on the command line to get the glibc version on your machine? May need to build distributed files on a machine with an old version of glibc.  

- Working on packaging Ink/Stitch for Fedora, can also add CentOS, but it may take some time. 

- If your environment allows, you might consider doing a [manual development install](https://inkstitch.org/developers/inkstitch/manual-setup/)

**Comment by NekaB** [comment]
Hello!

Thank you for responding. Let me answer your questions in order:

"How did you install Ink/Stitch, using the rpm or using the linux.tar.xz file?"

I installed it using the rpm.

"Can you type ldd --version on the command line to get the glibc version on your machine?"

ldd --version
ldd (GNU libc) 2.28
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

I am willing to set it up via the manual development install, but I'm not an expert. Do I have to be an expert to do that?

Thanks

**Comment by NekaB** [comment]
Hello? you still there?

**Comment by kaalleen** [comment]
Which Inkscape version are you running?
It should be at least 1.0.2, newest version is 1.2.2

We build with a higher version of glibc than the version you are using. So you'll not be able to run the packaged Ink/Stitch builds.

For manual install have a look over here: https://inkstitch.org/developers/inkstitch/manual-setup/

Please ask whatever you need to know.

**Comment by NekaB** [comment]
hello thanks,
Yes, I installed 1.2.2 as suggested. But for some reason, the manual install just wasn't working for me. That same error message is popping up. I have to confess that I know how to use terminal, but I'm not expert at navigating different files and adding things.

**Comment by NekaB** [comment]
Due to my distro, is this complicated to install?

**Comment by bkmgit** [comment]
It should be possible. Assume it is Cent OS Stream 8. What errors have
you obtained when following the manual installation notes?

Might you be able to use Cent OS Stream 9? It uses glibc-2.34

**Comment by bkmgit** [comment]
The current Linux tar.gz release builds are done on Ubuntu 20.04:
https://github.com/inkstitch/inkstitch/blob/main/Makefile
https://github.com/inkstitch/inkstitch/blob/main/.github/workflows/build.yml
So the glibc used needs to be the version used on Ubuntu 20.04 or newer
The rpm file is built using fpm
https://github.com/inkstitch/inkstitch/blob/main/bin/build-distribution-archives
https://rubygems.org/gems/fpm/versions/1.11.0
Which bundles all libraries,  so would also need a newer glibc.

CentOS 7 and Cent OS 8 Stream have another year of updates:
https://www.centos.org/download/
There are older versions of Ubuntu on extended security maintenance such
as 18.04.6:
https://www.releases.ubuntu.com/
Both of the above use older glibc and may be better to do release builds
on for portability, though the system python versions will be old, and
newer python versions should be used.

Easiest for developers is if you can upgrade to CentOS 9 stream, but can
examine providing releases that will work with older glibc versions,
though would take a few weeks due to other tasks that take precedence.

**Comment by NekaB** [comment]
I can upgrade to Centos 9. I hope that will make it work. I will message back shortly.

**Comment by kaalleen** [comment]
That's a while ago. So I assume things worked out. I'm therefore closing the issue. Please open a new issue if there are still problems.
