### ISSUE TITLE
Restack objects: reversed output when selecting with Alt key (opposed to Shift key)

### ISSUE THREAD

**Issue by gusvisser** [inkstitch/inkstitch#2425]
As i am selecting the objects in the main screen by holding down the alt key and make my selection and then go to inkstitch restack objects it puts all objects in reverse order of selection

was wondering if this is something what can be fixed

running windows 10 inkscape1.2.2 inkstitch 3.01

Gus Visser

**Comment by kaalleen** [comment]
It will stitch first selected elements first, I find that a logical workflow. I am a bit hesitant to add a reverse option, because people may accidentally chose the wrong option and will have to do it again. That's why I'd prefer a consistent order.
I may be overruled on this one though, if more people would love to have such an option, although I'd prefer not to.

**Comment by gusvisser** [comment]
By using the alt key and create the selection it is putting the first selected object in the top of the order it becomes the last sewn object when restack object is being used can this be fixed

**Comment by kaalleen** [comment]
Oh sorry, I missed that you said selecting with the alt key. You are totally right. Hm, this is annoying. I'm afraid we cannot do much about it, other than talking to the Inkscape team and wait until they fix the selection order which is send to the extension system.

Thank you for reporting this!!!

**Comment by kaalleen** [comment]
I opened an issue on GitLab. Hope they will fix it.

**Comment by kaalleen** [comment]
Closing this issue. They fixed it for the next Inkscape release (supposedly 1.3.1). Thanks again for the error report!
