### ISSUE TITLE
Print PDF Operator Notes Stick to their Index Position

### ISSUE THREAD

**Issue by kaalleen** [inkstitch/inkstitch#247]
The PDF Operator Notes are defined by their position within the loop:
inkstitch:operator-notes-block1
inkstitch:operator-notes-block2
inkstitch:operator-notes-block3
etc.

If the digitizer choses to change the order, the note will stay at its position and will apply to an other object.

Maybe it is not relevant, since people will enter notes at the end of the digitizing process. But perhaps we should prevent the notes from shifting by attaching an ID or the object name to the xml element rather than the loop index.

**Comment by lexelby** [comment]
Yup, that's true.  I knew that problem would exist when I wrote it, but I wasn't clear on what a good solution would be.

We can't really attach an ID to the object, because there's no one object to attach it to.  A color block is made up of a run of objects stitched one after the other, all of the same color.  If the user adds more objects or changes the stitch order, it becomes difficult to really say what things from before their changes are in the same color block as after their changes.

Here's my thinking about why I left it number-based: sure, if the user adds or removes a color, the notes will get put in the wrong place.  However, they'll pretty quickly see that in the print preview, and they can just move the notes.

**Comment by kaalleen** [comment]
I thought so. Well, it's good how it is.
I'll close this issue.
