### ISSUE TITLE
keyboard shortcuts don't work on Intel- or M1-based Macs

### ISSUE THREAD

**Issue by zourid** [inkstitch/inkstitch#2521]
I tried the last few development builds on an  Intel-based Mac Pro and on an M1-based MacBook Pro and unfortunately the delete keys (⌫ and ⌦) and all keyboard shortcuts (like  ⌘C,  ⌘V, etc.) do not work.

**Comment by kaalleen** [comment]
Ink/Stitch doesn't set any shortcut keys by itself. Check your shortcut keys in the Inkscape preferences.

**Comment by zourid** [comment]
Two **separate issues** with development builds: 
— Ink/Stitch development builds: the contour fill don't work 
— Inkscape development builds:  delete keys and keyboard shortcuts don't work

I've posted these issues a couple of times but I never got an answer

**Comment by kaalleen** [comment]
> * Ink/Stitch development builds: the contour fill doesn't work
>   I've posted these issues a couple of times but I never got an answer

#2478 ?!? You got a last answer last week, which in our time frames as a small group is not bad at all. Don't worry, the issue will be addressed whenever we find the time to do so. It may take a while though until we get to it.

> * Inkscape development builds: delete keys and keyboard shortcuts don't work

As I said above, this is not likely an Ink/Stitch issue (we do not automatically set or override any shortcut keys). It is either caused by your system or Inkscape.

Please check your system (if the problem also appears in other programs) if not, please address the issue to the Inkscape team.
