### ISSUE TITLE
cannot show settings windows

### ISSUE THREAD

**Issue by moolight-seashell** [inkstitch/inkstitch#2543]
even with reinstalls i still cannot open the settings windows .

even the realistic preview is broken idk why 

manjaro 
inkscape v 1.3
inkstitch v 3.0.1

xhen starting from terminal : 
$ inkscape
WARNING: unknown type: inkstitch:min_stitch_len_mm
WARNING: unknown type: inkstitch:collapse_len_mm
WARNING: unknown type: inkstitch:inkstitch_svg_version

**Comment by kaalleen** [comment]
This should be fixed for the next version, since the preferences have been rewritten.
Not sure why this is happening though. Our electron extensions don't seem to work for you out of the box on your system.
You could try to switch to a dev branch. But we aware that we are experimenting in some of them at the moment. But we'd like to hear your feedback :) Just don't try the versioning ones. They are not ready to go.
