### ISSUE TITLE
screwed up initial installation and can't get things working now

### ISSUE THREAD

**Issue by rlgafter** [inkstitch/inkstitch#2608]
Hi,
I installed both inkscape and inkscape, forgetting to run inkscape before the installation of inkscape. I realized my mistake when inkscape did could not generate a preview.

I then deleted the inkscape extention, deleted inkscape, ran the 'Delete Apps' application and emptied the garbage can . I reinstalled inkscape, opened it created a file and closed inkscape. I installed inkstitch, opened inkscape, created a square and tried to generate a preview, nothing happened.

I am doing this on a MacBook Pro, with an Apple M2 chip, running Sonoma 14.1.1. What do I need to do to make inkscape run?

Thanks in Advance for your assistance
Ricki Gafter
ricki@gafter.com

**Comment by kaalleen** [comment]
So this means you are seeing the Ink/Stitch menu in the Inkscape extensions? What happens if you run stitch plan preview (not the simulator) on a square? Does the options window show up, any error message when you apply?

(If you already have Inkscape 1.3.1 please convert the square to a path before doing so).

**Comment by rlgafter** [comment]
I resolved this issue by using a windows chip simulator.
