### ISSUE TITLE
Ripple stich + multi hoop for large designs on small machines

### ISSUE THREAD

**Issue by Asalle** [inkstitch/inkstitch#2613]
Hi all,

I have a 4x7" hoop on Brother Innovis 955. I want to do a huge ripple design aprox 12x12". Is it possible? So far, when I had designs larger than 4x4 (default design size supported by the machine), I just broke it down into 2 parts and aligned it to the best of my ability. This worked with text. However with ripples, it's an inkstitch effect that I cannot just divide with Path->Division. 

If it's impossible with the current code, do you think there's a way to achieve that by adding functionality? I would be interested in looking into the code if it's whatsoever feasible.

**Comment by bianchifan** [comment]
Just save your design in a format of your choice, once saved, open it with inkscape.
Now you should see a couple oh paths, one for each color. Now you can break these paths at any node you like and build a couple of sun-Designs to fit your hoop size.

**Comment by Asalle** [comment]
Just to be sure I understand you correctly: this is how the ripple design preview:
![Screenshot from 2023-11-23 17-12-40](https://github.com/inkstitch/inkstitch/assets/4975074/451dca43-8c20-4478-87d2-b0b37fe3b22b)
If I save it in .dst or .svg I will see this (the original curve I used to generate the ripple design):
![Screenshot from 2023-11-23 17-10-16](https://github.com/inkstitch/inkstitch/assets/4975074/e29161b3-43ab-4083-9923-aab226e69321)

Which format can I use to convert the ripple design into "normal" object I can split into subdesigns? Can I embroider it afterwards?

**Comment by bianchifan** [comment]
If you'll save it as "SVG" you will see your original design, if you'LL save it as DST or XXX or any other embroidery format you will see the stitch pathes as in preview/simulator.
Selecting the nodes tool you can brake this pathes at any node you like. You can break them manually or you can create seperate objects to cut them.

**Comment by bianchifan** [comment]
OK...
I just created an SVG from your pic above, rippled and break it apart.
I do not break them to 4x4 inches, only into three parts to fit a 4x7 inch hoop.
To do that I saved the the 40-lines ripple in XXX format and read that format into inkscape.
Then I created 2 break lines at roundabout 4" and 8" and put them above in path order (objects view right side)
Selecting the Ripple and one break path break the ripple by using "cut path" from the path menu.
Then I selected all paths right from the brake line and grouped them, afterwards I combined the rest.
Same procedure with the combined path and the second brake line.
Now I grouped all pathes left from the brake line and afterwards the rest.
The result are three groups of paths which can be stitched out individually.

![Bildschirmfoto vom 2023-11-24 09-23-13](https://github.com/inkstitch/inkstitch/assets/17491743/4a75444a-5188-42c4-9c10-cbf9b1e9a57e)
![Bildschirmfoto vom 2023-11-24 09-42-17](https://github.com/inkstitch/inkstitch/assets/17491743/a2f5b18d-0141-495d-ba17-780ff9ec1247)

One paths must be broken manually because of uneven crosses with the break line
![Bildschirmfoto vom 2023-11-24 09-32-29](https://github.com/inkstitch/inkstitch/assets/17491743/b6a1205e-58df-44c8-a785-ac3ff66e57c4)

[g417.zip](https://github.com/inkstitch/inkstitch/files/13457249/g417.zip)
[g541.zip](https://github.com/inkstitch/inkstitch/files/13457255/g541.zip)
[g542.zip](https://github.com/inkstitch/inkstitch/files/13457261/g542.zip)

**Comment by Asalle** [comment]
Oh wow! Thank you so much for the detailed explanation, somehow I had an impression that even saving with .dst won't work. I must have gotten confused with all the formats... :pray:
