### ISSUE TITLE
Sudden malfunction of the simulator preview and pdf export in a Linux system.

### ISSUE THREAD

**Issue by karnigen** [inkstitch/inkstitch#2625]
After system update Linux users of Inkstitch may encounter sudden disruption of the Simulator Preview functionality and PDF Export. This issue is elusive, as the program doesn't generate any error messages. Both functions are simply not doing anything at all.

Some information on why this is happening can be found here
https://bugs.launchpad.net/ubuntu/+source/linux-meta-nvidia-5.19/+bug/2017980
and here https://gitlab.com/apparmor/apparmor/-/wikis/unprivileged_userns_restriction#disabling-unprivileged-user-namespaces

Due to the use of Node.js, Electron and subsequently Chromium in the simulator and PDF export, the process immediately terminates with an exception upon invocation. However, neither Inkscape nor Inkstitch is displaying any errors.

As a quick solution, it is necessary to first verify the value in the file `/proc/sys/kernel/apparmor_restrict_unprivileged_userns` 
If the value is 1, it is possible that it is causing the malfunction. Note: This file is present only in new kernels.

A quick workaround is to set this value to 0 using the following command:

       `echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns`

until Chromium apparmor will be configured correctly in the system.

Other programs that use Chromium include, for example, Google Chrome and Microsoft Visual Studio Code. These programs also do not function properly if they are installed in the system.

**Comment by tyrosinase** [comment]
Huh. I get this on a regular basis (though Deb11 doesn't have user namespaces by default) and yeah, I end up rebooting my PC about once every other day to recover.

I assumed it was an LXDE issue, so hadn't said anything.

**Comment by kaalleen** [comment]
Interesting. Thank you for the info.

**Comment by tyrosinase** [comment]
More details: I can't guarantee it's not an LXDE thing (or a weird function of my weird keyboard driver), but sometimes when I overwork my machine I will get a weird lockup: the keyboard will still work, the mouse cursor will move, but the mouse buttons and alt keys will stop working. So I can, say, ctrl-tab around in Firefox tabs if I happen to be there when it locks (if I've popped over to check something while the simulator builds or whatever) or type commands in a terminal window if I'm there, but I can't close any windows or jump from one window to another. SSHing in works, but `kill`ing the Inkscape etc. tasks doesn't return things to functioning... gotta kill the whole login or (because I am more likely to remember the command) just restart the whole computer. I've left it overnight to see if it returns from a very slow process and that's not it.

The thing that has made me assume it's that particular PC and *not* an Ink/stitch issue is that I also have a toy laptop (a little Evolve Maestro III) that also runs Deb11 and LXDE, and while I can overwork it even more easily, that doesn't cause the weird lockups the same way... just the occasional oomkiller attack.

So I'm not 100% sure it's a real Ink/Stitch issue, other than it does seem to only happen when one of the simulator-type windows is active.

**Comment by kaalleen** [comment]
Closing as electron will not be part of the next release anymore.
