### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by rlgafter** [inkstitch/inkstitch#2669]
I received the following error from the attached file
![crash](https://github.com/inkstitch/inkstitch/assets/135143711/a82278db-62e1-46ff-8ea0-f7c6c34456fb)
when I do the following Extensions / Ink/Stitch / Tools:Stroke / Fill to Stroke ...

Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v3.0.1 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 250, in run
  File "lib/extensions/fill_to_stroke.py", line 70, in effect
  File "lib/extensions/fill_to_stroke.py", line 128, in _get_centerline
  File "lib/extensions/fill_to_stroke.py", line 148, in _get_voronoi_centerline
  File "shapely/ops.py", line 236, in voronoi_diagram
AttributeError: 'NoneType' object has no attribute '_geom'

**Comment by tyrosinase** [comment]
While it shouldn't be giving you the raw error (and future releases won't), what it's trying to tell you is that your graphic is not stitchable as it is: there is an object (or in this case, a lot) that is too small to fit a stitch into.

The problem is, you're trying to use a line-art graphic as a fill - you'll need to tell Ink/Stitch where and how to convert each line into satin stitching. You can ignore the parts about the colored fill areas, but otherwise this tutorial will get you on the right road: https://silverseams.com/tutorials/digitizing-outlined-graphics.html
