### ISSUE TITLE
Timeline and Stitch Counter

### ISSUE THREAD

**Issue by wwderw** [inkstitch/inkstitch#267]
I was wondering if it would be doable to add a timeline and a simple stitch counter (something like current stitch / total stitch) to the Simulate module?

Something that I can pause the animation, scrub through manually and find the exact stitch count that I'm on in a pattern.

One possible use case would be to find the exact stitch count to add specialty functions to individual stitches in an exported CSV file format and then convert that CSV file back into a raw stitch file that would accept said commands.

Thoughts?

**Comment by tatarize** [comment]
Come now, isn't what you really want a little app that you can launch on an embroidery file iterate through the stitches until you find the right spot, interject the commands you want in there, and then save it out. Seems like if you had that you wouldn't need the inkstitch bit at all. It would just be a little modification script with a GUI. Little of that seems like it would require being an extension of inkscape at all.

Simply turn the file into a EmbPattern object then modify that directly. Then save it out again, for this, usecase at least. At least then you're not editing a text file when you don't really need to.

You'd could be able to pare off the fine-tune and draw-simulator parts of the program and do them outside of inkstitch anyway. It's basically a stand alone little app at that point. I daresay if I had any idea how wx guis worked it wouldn't be too hard to make a little bit of a UI there, I'd have no trouble writing this stuff for android.

In any case, a stitch counter is quite doable and kind of needed. 

Even if the backend might turn it into more stitches or subdivide some things as needed by the format. A point count could give you a solid idea of where the relevant section would be, even if it couldn't point to the exact stitch number, it would be really close.

**Comment by wwderw** [comment]
> Come now, isn't what you really want a little app that you can launch on an embroidery file iterate through the stitches until you find the right spot, interject the commands you want in there, and then save it out. Seems like if you had that you wouldn't need the inkstitch bit at all. It would just be a little modification script with a GUI. Little of that seems like it would require being an extension of inkscape at all.

I don't know.  It would depend on how it's implemented.  I would for sure want to have portability in such a small utility like that.  Maybe something in it's own zip/tar file with each release of Ink/Stitch?  Just not bundled in the main archive files, so that way we can extract it somewhere else and use it.  

I believe outside that one example that I gave, a lot of people might be looking for a stitch counter and a timeline to scrub through on their own.  Maybe not, but I know they are in most commercial software (and even some free conversion/resizer software as well) they are there.  I'm thinking a stitch counter at the very least though.

As far as editing CSV files.  I'm used to doing that, even in commercial software using their "stitch list" module.  In order to apply some commands, you have to do it through such a module as they don't have another method of applying them (at least not very discoverable to me) and it looks just like what I would see in Kate editing a CSV file.  It's also what I'm used to doing when trying to modernize stitch files generated from Thred.  There was just a way to see the exact stitch count of where I wanted to add commands (mainly 3 JUMP commands together for a trim).  Only thing I couldn't do away with was the 65k stitch count max for a file.

**Comment by wwderw** [comment]
I thought that was for the Mac build.  I'll try to see about that this afternoon.

**Comment by kaalleen** [comment]
It was... but the counter does changes to the same file, so I included it to the same pull request to avoid merging difficulties. If you test it on a windows computer I also would be very interested if all the buttons and shortcut keys work for you :) The counter has a little error though ... compared to the print output and the stitch plan nodes ... one stitch got lost somewhere. I only don't want to add it manually. Maybe @lexelby knows better where it went.

**Comment by wwderw** [comment]
That stitch counter will do the trick nicely.

Left a review on it using it in Windows in a VM in the main PR thread.  In Linux, it appears to be good to go.

**Comment by lexelby** [comment]
A couple of things:

1. I do think there's a clear need for both a stitch count and the ability to move back and forth more precisely in the timeline.  The way the simulator is implemented right now, going backward is... not so easy.  I think we can do this perhaps by having it take snapshots every X stitches so that it can go back to a previous state, but it may be awhile before we get a chance to implement it.

2. I'm glad we have the stitch counter in the simulator now, but I don't think it's quite going to do what you want.  The reason is that it's not counting things like jumps, trims, etc.  So if you see stitch 1084 in the simulator, for example, that will not be commadn 1084 in the CSV file.

3. I'd really like to be able to scratch your itch in a way that doesn't involve you having to edit the CSV file.  I know you're a power user and all, and you'll probably always have at least _some_ use-case for hand-editing, but ideally I'd like to learn what commands you want to be inserting manually and add them as command symbols in the "attach commands" extension.  If you want it, chances are others will, and they may not be savvy enough to edit a CSV and convert to DST.

Plus, hand-editing is just that: a manual operation.  What if you then need to tweak your design in Inkscape a bit?  You'll have to remember the hand-tweaks you did to the CSV and re-implement them.  I'd love to save you that time/aggravation.

**Comment by wwderw** [comment]
> I'm glad we have the stitch counter in the simulator now, but I don't think it's quite going to do what you want. The reason is that it's not counting things like jumps, trims, etc. So if you see stitch 1084 in the simulator, for example, that will not be commadn 1084 in the CSV file.

Oh yea, it would have to account for those.  I didn't think of that.  For one set of commands, I would need to know the exact number.  That would be imperative, the other set, I can get within a general range and be OK, but not the other.  It would require precision.

>If you want it, chances are others will, and they may not be savvy enough to edit a CSV and convert to DST.

Unfortunately, not in this use case for what I'm wanting.  This is for Slow/Fast commands and for sequins.  Slow/Fast, to my knowledge, is only available in the U?? format of Barudan (which isn't supported as an output file directly in the extension), so that's limited to a very specific brand and sequins is actually far more limited then that as not many people have those. And there is no reason to take up programming time for something that has such a small use case, until Ink/Stitch is far more mature.  At least with this functionality (time line and stitch counter), it should give me a much more precise work around and I think most people would like this functionality, versus being able to insert codes that won't apply to them.

As of now, I can do a color block work around for the sequins (as they would more often then not be at at a color change and sequins are the only reason why I use C01 as the pressure foot is different then a regular embroidery pressure foot (accommodate the size of the sequin)).  Slow and fast commands, I can afford to be a little less precise.

>Plus, hand-editing is just that: a manual operation. What if you then need to tweak your design in Inkscape a bit? You'll have to remember the hand-tweaks you did to the CSV and re-implement them. I'd love to save you that time/aggravation.

I would either add in a "special instruction" layer with live text, so it won't go through the extension as embroidery objects or I can setup another text file with the info.

I don't mind more manual work arounds just so long as I'm aware of them and I'm comfortable doing them and like I said, no point in taking up programming time for something that I doubt would even apply to 5% of the people out there.

This will give you a little idea of what I'm trying to do.  The last picture was within a commercial free conversion/resizing program.  I used it to make sure that everything worked correctly.  The one above that was how I digitized it in Ink/Stitch, but I had to remove the objects that I used for illustrative purposes for the sequins, otherwise they would have stitched out as fills.  This is the one that requires the most precision (and the digitized run stitch is a manual run).

![csv original](https://user-images.githubusercontent.com/24878362/43874958-3b5ec684-9b54-11e8-8ced-711a3a956be7.png)
![csv sequins](https://user-images.githubusercontent.com/24878362/43874963-4432466e-9b54-11e8-954b-4a09d7e2e794.png)
![sequin inkscape](https://user-images.githubusercontent.com/24878362/43874964-46ef7bd8-9b54-11e8-80cd-7d46bb3739ce.PNG)
![sequin view](https://user-images.githubusercontent.com/24878362/43874967-49250f3a-9b54-11e8-9f06-c95a22dcbf44.PNG)

**Comment by tatarize** [comment]
@lexelby 
1) I don't believe that the code is correct if it cannot instantly display the rendering. I'm guessing you're rendering the stuff to a display image or something weird. That is, if you're thinking about snapshots or whatnot. It must be broken in a very slow way. -- I'll add my 'ever-so-helpful-2-cents'... you're doing it wrong. I implemented a timeline stitch simulator for android which is way less powerful than most desktop info and it works seemlessly forward and backwards. From the times I've looked at the stitch simulator, it's pretty clear that flickers a lot between frames and I gotta suggest that the slowness there is not a requirement.

As for the processing I coded up a jfiddle to do this to demonstrate the manner. 

https://jsfiddle.net/Tatarize/0bdpuonL/

Drop on an exported CSV and it'll process the generated SVG to add and remove the stitches (note, no attempt is made to make this not suck, it literally regenerates the entire SVG each tick). For ww's sake the info button will give the exact stitch it is currently at, and I made it go forwards and backwards for show. The seek bar is also generally for show, but I couldn't really get it to hook up right.

**Comment by tatarize** [comment]
[vvhead.v6.pes.csv.zip](https://github.com/inkstitch/inkstitch/files/2273281/vvhead.v6.pes.csv.zip)

pyembroidery-convert will convert the files to .csv by default so you can just drag them on there to quickly make your own. Here's a zipped huge example csv, in case you don't want to make your own to see it work. Though, the seekbar might be sketchy for some reason. Slight bug there.

**Comment by tatarize** [comment]
> In this case what you aren't taking into account is that the simulator is not a web browser and it can't just render SVG.

It could be. I mean the print preview is an a web browser rendering an SVG. I hacked up a simulator that will also give @wwderw the exact actual stitch number in a couple hours. 

But, it's also clear that there's something wrong at the core with how you're doing this if you cannot do this instantly and in real time. There's no software package today that couldn't render that stuff in real time. The flicker, for example, is because the canvas is erasing the background and redrawing it. You catch that and stop it from wasting that time (self.Bind(wx.EVT_ERASE_BACKGROUND, self.OnErase)) in that giant flicker and you're telling me that passing the paint routine a subset of points cannot be real time? 

I swear I've messed with various canvases from rendering my own by implementing Bresenham's line drawing and Wu's algorithms directly on bitmaps and android and little javascript canvases both Canvas and SVG. They can all draw a large set of lines quite rapidly when you hand them the lines. There is nothing that should be faster about running it by inefficiently implementing svg changes (by deleting the entire svg and recreating it each tick) in javascript in a web browser that should be faster than a pretty raw rendered windows.  

My comment there is honest, this cannot be correctly done. There's some rather easy and fundamental flaw that, when identified and rectified will make everything significantly better. If you can't do this thing, you must be doing it wrong. Find that bug and you suppose things like snapshots going backwards or something. wx cannot possibly be that slow, it has double buffering and GL.

**Comment by lexelby** [comment]
I'm going to tell you again: the way you're going about talking about this is offensive and I need you to stop.  This is not a competition and you don't need to prove that I'm doing it wrong.  I need you to assume good intent and skill on my part and assume that if I haven't done it the way you're saying, there is probably a good reason for that.  Approach the conversation on that footing.  I've already given suggestions about how to get across what you're saying without being offensive.

If you say "you're doing it wrong" or similar again, I will temporarily suspended your commenting privileges.  This is your last warning.  Please understand that I appreciate the contributions that you've made to our project but I can't allow behavior like this to continue.

**Comment by tatarize** [comment]
You are not your code.  I am not at all making any personal comments about you. I categorically do not mean "doing it wrong" to be a pejorative. I do stuff wrong all the time. I mean to say that what you are saying should not actually be the case.  I would never speak ill of you or anybody here, I do not make personal comments about people. My comment should not be construed as doing that. It was not my intent to be offensive. It's not intended as a pejorative. I'm not trying to one-up you are make  some kind of dig at you or your code. I'm telling you that, with considerable expertise in a lot of canvas technologies, it categorically must be the case that it can do that. There's no canvas technology today that could should be unable to do this.

Here I'll prove it.

* [EMBulate.zip](https://github.com/inkstitch/inkstitch/files/2276277/EMBulate.zip)

Attached you'll find a standalone python script (requires pyembroidery, wx), a nice little PES file, and in a directory go ahead and run the script with that file. You'll get the same a wx window that will (with some flickering), run the simulation backwards and unstitch everything and do so in real time without any caching (adapted from https://wiki.wxpython.org/DoubleBufferedDrawing ). It must be doable if I can do it. So when you say it can't be done that way you *******************.

**Comment by tatarize** [comment]
Here, takes the example stitch as the default stitch. Gets rid of the flicker. Adds menu items to set Forwards and Backwards so you can switch them on the fly.

[EMBulate2.zip](https://github.com/inkstitch/inkstitch/files/2276365/EMBulate2.zip)

**Comment by lexelby** [comment]
@tatarize, I'm suspending your access to the Ink/Stitch organization for 1 week.

I warned you that saying "you're doing it wrong" _or similar_ again would result in a suspension.  Asterisks won't help you here; your intent was clear.

Our code of conduct contains the following items relevant to this discussion:

> * Being respectful of differing viewpoints and experiences
> * Gracefully accepting constructive criticism
> * Focusing on what is best for the community
> * Showing empathy towards other community members


I'll add some responses to what you've said, but none of the following should be construed as an opportunity to appeal the decision to suspend you:


> It was not my intent to be offensive.

**Intent is irrelevant.**  I expressed the fact that I found your comments offensive and at that point empathy would suggest that _you should stop_ whether you agree it is offensive or not.  There was plenty of opportunity at that point to discuss better ways to communicate to avoid offense.

> Here I'll prove it.

**Being right is no excuse for rude behavior.**  I'll also remind you that our similar conversation regarding the fill algorithm (with similar offensive behavior) resulted in your discovery that your assumptions were incorrect.

> So when you say it can't be done

I never said that it could not be done in my [comment](https://github.com/inkstitch/inkstitch/issues/267#issuecomment-411611062).

-----------------

One final note: again, I appreciate your contributions to this community.  However, I want it to be known that being a valued contributor does not excuse one from abiding by the code of conduct.


Please take the next week to consider what's happened here, as I will.  If you decide to resume interaction in this community, I truly hope that we can converse in a way that avoids offense on either side.  Let's try to work together to make that happen.


As a reminder, as per the code of conduct, if anyone would like to discuss this situation, please feel free to reach out to me at inkstitch-coc@lex.gd.

**Comment by lexelby** [comment]
In the interest of full transparency:

I've extended the suspension to 30 days after receiving an email from tatarize containing another occurrence of "doing it wrong".

If anyone in the community objects to the way I've handled this situation, I'd really appreciate hearing your thoughts.  You can reach out above or post here, whichever you prefer.

**Comment by lexelby** [comment]
Just in case anyone was tempted to use it, I've removed the code link from tatarize's post above.  It has no open source license attached and is therefore  a copyrighted work that we have no permission to use.

**Comment by lexelby** [comment]
@wwderw Sorry, looks like I forgot to respond to your comment!

> As of now, I can do a color block work around for the sequins (as they would more often then not be at at a color change and sequins are the only reason why I use C01 as the pressure foot is different then a regular embroidery pressure foot (accommodate the size of the sequin)). Slow and fast commands, I can afford to be a little less precise.

Awesome, I'm glad you have a viable workaround.  I do hope to support even machine-specific things like slow/fast codes in U01 eventually, but you're right, it may be awhile before we can prioritize that.

**Comment by wwderw** [comment]
> Sorry, looks like I forgot to respond to your comment!

No worries, I think you had other things going on the past couple of days on here.

Yea, the work around seems to be viable.  Hopefully, I can figure out how to add my own symbol for sequins, as I don't think symbol paths will be converted as embroidery fill objects in Ink/Stitch.

I think if we can do the simulation timeline and be able to have true stitch counter that takes into account empty stitches as well as regular stitches, that will make my workaround even easier to handle.  Especially if an edit has to be done to the original SVG and the commands re-applied.

**Comment by Metallicow** [comment]
@tatarize @wwderw @lexelby If you are looking for the wxPython version of Embroidermodder, It draws everything using the python bindings and a custom written wxPy widget, so it isnt slow as molasses. ...As far as why people keep porting the libEmbroidery to different languages against Jon's reasoning as to why not too..., leads me to one conclusion. You are doing it wrong. Well maybe not. But I would probably modify a few lines and see just how much faster it will run with the official lib. otherwise I would have released it myself lol.

Written as an educational piece for kids. So it is easy to understand.
```
    def DrawSnakeyMemoryDC(self, bmpScale=0):
        bmp = wx.Bitmap(16, 16)
        dc = wx.MemoryDC(bmp)
        dc.SetBrush(wx.TRANSPARENT_BRUSH)
        dc.SetPen(wx.TRANSPARENT_PEN)
        dc.Clear()
        dc.DrawRectangle(wx.Rect(0, 0, 16, 16))

        # Draw the Skin.
        dc.GradientFillLinear(wx.Rect(2, 2, 13, 13), '#15FF19', '#DBFFDB')
        # Draw Outline.
        dc.SetPen(wx.BLACK_PEN)
        dc.DrawLineList(lines=((1, 1, 15, 1), (11, 2, 13, 2), (14, 2, 15, 2),
            (3, 4, 15, 4), (1, 6, 13, 6), (3, 8, 15, 8), (1, 10, 13, 10),
            (3, 12, 15, 12), (1, 1, 1, 14), (1, 14, 15, 14), (1, 1, 14, 1),
            (14, 4, 14, 14)), pens=None)
        # Draw the Tongue :)~
        dc.SetPen(wx.RED_PEN)
        dc.DrawPointList(points=((14, 3), (15, 3), (15, 4)), pens=None)

        if bmpScale:
            img = dc.GetAsBitmap().ConvertToImage()
            img = img.Rescale(16 * bmpScale, 16 * bmpScale,
                              wx.IMAGE_QUALITY_NEAREST)
            img.SetMaskColour(255, 255, 255)
            bmp = img.ConvertToBitmap()
            return bmp

        return dc.GetAsBitmap()
```

Written by a self funded team.
https://github.com/Embroidermodder/Embroidermodder/graphs/contributors

Written by a couple of guys who argued a lot... with help and advice from a lot of volunteer hardware experts and refurbishers.
https://hackaday.com/2014/02/15/generating-embroidery-with-an-arduino/

Written on the shoulders of giants we stand. Thats the biggest embroidery/cnc machine most folks ever seen. 
![bridge](https://user-images.githubusercontent.com/4668356/44502011-2d76ee00-a655-11e8-956f-5c7c86540399.png)

Moral of the story. Build bridges, don't burn them. Keep arguing and please don't waste any more of my or anyone elses time attaching/referencing wxPython code that leads down a river. I don't see any wxPython developers or code written by anyone here. Only a bunch of deleted information and wasted time. Now get back to work (ALL of you!).

Ref: https://github.com/Embroidermodder/Embroidermodder/issues/94 https://gist.github.com/lexelby/1075376375182702780a941d90587d3e

If you take the C Embroidermodder gui undo/redo framework code and port it and understand how the GUI code is working... glue all that into this and blend then draw all that in reverse and you might have a start. But yes, the end product will all draw as a single frame if you want it to.
https://github.com/wxWidgets/Phoenix/tree/master/samples/roses
