### ISSUE TITLE
Ink/Stitch on El Capitan (macOS)

### ISSUE THREAD

**Issue by EkaMino** [inkstitch/inkstitch#2701]
Hello, 
I have a very old mac book pro (2009) and the latest upgrade I can install is El Capitan. 
The Inkstitch extension appears in the inkscape menu but whenever I try to do anything it tells me "803 error loading python lib" etc (see picture). What should I do?
thanks for your help

![Bildschirmfoto 2024-01-27 um 03 40 57](https://github.com/inkstitch/inkstitch/assets/157862601/a3579acc-1783-4ee8-8ecd-a778aaf278e0)

**Comment by kaalleen** [comment]
We do not support El Capitan anymore. Try out an older version: https://github.com/inkstitch/inkstitch/releases/tag/v2.2.0
Download  inkstitch-v2.2.0-capitan-catalina-osx.pkg 
And follow the instructions to install unsigned packages: https://inkstitch.org/docs/install-macos/#xxxx-cannot-be-opened-because-the-developer-cannot-be-verified
