### ISSUE TITLE
ImportWarning: pandas not found, skipping conversion test. 

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#2705]
Installed add-instrument-and-reenie and it's throwing a little warning on command-line.

`networkx/convert.py:136: ImportWarning: pandas not found, skipping conversion test.`

**Comment by kaalleen** [comment]
Ah sorry, I forgot about that. It's a pyinstaller issue. @rejbasket is going to create a pull request for that one soon.

**Comment by kaalleen** [comment]
For the FloatingPointError... do you have a test file for it?

**Comment by kaalleen** [comment]
The `FloatingPointError` will be also fixed with geos 3.12 versions. I just hope shapely won't make us wait too long for the update. It's a pitty that it is so hard to have people test releases at the moment.

I'll close the issue though. And reference to #2660

Thank you anyway for the error report!
