### ISSUE TITLE
ignore

### ISSUE THREAD

**Issue by Pyembroidery** [inkstitch/inkstitch#271]

**Comment by lexelby** [comment]
Of course the ban is permanent.  Somewhere around your third or fourth increasingly harassing email, I gave up on trying to work this out in a reasonable fashion.

I'm not stealing your code.  It's MIT licensed, and I left your copyright notice and your name on it.  My goal was to allow Ink/Stitch to continue without my having to continue to interact with you.  **I get to choose when to draw the line and stop receiving abuse from you.**

That said, since the current solution is upsetting to you I'll try to come up with something different.

As you can see, I've edited your comment to paraphrase it, as you've given up your right to an audience in this community.  **The full comment is available in edit history should anyone like to see it.**

Goodbye, and I'm sorry you chose to end our collaboration in this way.
