### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by iris-lodnik** [inkstitch/inkstitch#2721]
Hi, I want to create my own translation of Ink/Stich into Czech. I downloaded the file messages_cs_CZ.po with Crowdin, compiled it into an inkstitch.mo file with Poedit, put it in C:/Users/........LC_MESSAGES and nothing :-( Can you please advise me how to insert the translation into Ink/Stich .
Thank you, Vitek

**Comment by bkmgit** [comment]
Thanks for contributing to Ink/Stitch. Please see the localization
instructions at:
https://github.com/inkstitch/inkstitch/blob/main/LOCALIZATION.md
Not sure how active the Czech team is, but you can also ask to become an
approved contributor so that changes you make on Crowdin get synced to
the GitHub repository.  If not in a rush to have the translations, once
they have been approved and are in the GitHub repository, the
pre-releases available at https://github.com/inkstitch/inkstitch/releases
will contain the translations.  The localization instructions need an
update since Travis CI has been replaced by GitHub actions.

If getting the translated version is very urgent you could also build
Ink/Stitch on your own machine, or make a fork of the repository and use
GitHub actions to build it, but getting your translations through
Crowdin would likely take a few days.

**Comment by bkmgit** [comment]
Please also see https://inkstitch.org/developers/localize/

**Comment by iris-lodnik** [comment]
Hi, I don't understand what's on this page. Can you explain this to me
please? Vitek

https://github.com/inkstitch/inkstitch/releases/tag/dev-build-bkmgit-localization-instructions-update

út 13. 2. 2024 v 4:59 odesílatel Benson Muite ***@***.***>
napsal:

**Comment by iris-lodnik** [comment]
Hi, I'm not a developer and working with Crowding is incomprehensible to me
even for the language barrier. My translation is very amateurish and only
covers the parts that interest me. I would like to create my own
translation and install it on my PC. I have the inkstitch.mo file
translated, am I on the right track? Please advise.
Thank you Vitek

út 13. 2. 2024 v 4:59 odesílatel Benson Muite ***@***.***>
napsal:

**Comment by iris-lodnik** [comment]
Hi, this statement no longer applies...

https://edutechwiki.unige.ch/en/InkStitch_-_installation

   - Backup file inkscape/extensions/inkstitch/bin/locales/fr_FR
   directory/inkstitch.mo to inkstitch.mo.old
   - Copy the file to the inkscape/extensions/inkstitch/bin/locales/fr_FR
   directory


út 13. 2. 2024 v 5:30 odesílatel Benson Muite ***@***.***>
napsal:

**Comment by kaalleen** [comment]
Are you running a release or manual install?

> `C:/Users/........LC_MESSAGES`

Can you paste just a littler more of the path so we can verify if it is the correct location?
It should go into locales...

Here is the official installation guide: https://inkstitch.org/docs/install-windows/

---

@danielkschneider this may be interesting for you though...

> Hi, this statement no longer applies...
> 
> https://edutechwiki.unige.ch/en/InkStitch_-_installation
> 
>    - Backup file inkscape/extensions/inkstitch/bin/locales/fr_FR
>    directory/inkstitch.mo to inkstitch.mo.old
>    - Copy the file to the inkscape/extensions/inkstitch/bin/locales/fr_FR
>    directory

**Comment by iris-lodnik** [comment]
I am running the release, the path given at
https://inkstitch.org/docs/install-windows/ is correct.
Here is the error - https://inkstitch.org/docs/install-windows/

Vitek

út 13. 2. 2024 v 19:09 odesílatel Kaalleen ***@***.***>
napsal:

**Comment by iris-lodnik** [comment]
Repair
Here is the error - https://edutechwiki.unige.ch/en/InkStitch_-_installation

út 13. 2. 2024 v 19:09 odesílatel Kaalleen ***@***.***>
napsal:
