### ISSUE TITLE
Tartan fill — feature request

### ISSUE THREAD

**Issue by zourid** [inkstitch/inkstitch#2726]
I love the new Tartan Fill — thank you Kaalleen.

Is it possible to add settings to control the pattern direction — select an angle basically — and other parameters like spacing between columns and rows?

thanks

**Comment by kaalleen** [comment]
Thank you for your feature request on my unfinished branch :)
I originally didn't plan to allow different directions, since the tartan style seems to speak 45 degree ... But yes, why not. Seems possible. Although angles near to 90 degrees will need some extra treatment in the code since the distances between the line end points are much bigger.

**Comment by tyrosinase** [comment]
On a slightly different but related note: I just upgraded to Debian 12 (bookworm) and have a shiny new Inkscape install (from source - whyyyyyy does Inkscape only offer AppImages for Linux now?!) and am ready to break whatever branches/features you or any other devs want me to stress-test. 😜

**Comment by kaalleen** [comment]
Uh nice :) I will come back on this offer soon. Right now we still have the shapely/geos issue to manage. First I thought we are just going to wait until they update shapely. Well, they updated shapely... but they still not use an updated geos version (it is still 3.11.x not 3.12.x). Therefore I'd not recomment current dev builds.

@rejbasket wants to update our build process, so that we can build on geos 3.12.x ourseleves as long as pip shapely isn't delivered with the geos version we need. When this is done, it'd be great to have test reports for the dev versions.

**Comment by zourid** [comment]
I tried the new tartan release — it is great. The herringbone pattern is fantastic. Now all parameters can be customized under tools:fill. Just wanted to say thank you Kaaleen.

**Comment by kaalleen** [comment]
That is really nice to hear. Thank you for your feedback :)
