### ISSUE TITLE
Existing fonts in inkstitch

### ISSUE THREAD

**Issue by gusvisser** [inkstitch/inkstitch#2729]
I hardly ever use the inkstitch fonts but i did some testing and checking on a few fonts and noticed there are a lot of improvements possible there are letters where within the letter the travelstitches become exposed outside the satin and there are fonts where there are letters what still have jumps within the letter

So i would like to ask the font developers to revisit their created font and if possible improve their font
This would be nice if this could be done before the next release since the program is expanding all the time and more and more improvements are being made Here is just an example of where there only should be one jump stitch showing but within the letter there are two

Thank you for your contributions to the software
And it would be nice if we can keep up the quality and make improvements

Gus Visser
![image](https://github.com/inkstitch/inkstitch/assets/85417086/848f77bc-4f9b-4650-8e13-ade942734604)

**Comment by Augusa** [comment]
Can you say which fonts you tested?

**Comment by tyrosinase** [comment]
Emilio has some problems, as I mentioned in #2712 (not technically a font problem, but a problem with any satin that has just two rungs nowadays).

(I was hoping to have gotten to it by this week but that hasn't happened yet)

**Comment by gusvisser** [comment]
Just to mention a few
Ags
Amitado
Apex
Auberge
Aventurina
Baumans
Dejavu 
Cherry for kalleen
and so on
Most of these fonts are having jumpstitches within one letter 
I would reccommend that all fonts would be revisted

Gus Visser

**Comment by Marif91** [comment]
Il est vrai que inkstitch a évolué... les fontes ont été réalisées avec des versions antérieures et testées en grandeur nature sur tissu... à l'époque ces problèmes n'étaient pas apparus. S'il y en a maintenant, il vaut mieux signaler précisément où se situe le problème comme cela a été fait avec le H d'Emilio.

**Comment by Marif91** [comment]
Concernant Emilio, la police fonctionne parfaitement dès qu'on modifie sa taille avec l'échelle, par contre aucune police ne fonctionnera avec les effets de chemins (comme cela est montré avec le H de Emilio). Si on veut écrire en courbe, on utilise la fonction "lettrage le long d'un chemin". 


> Emilio a quelques problèmes, comme je l'ai mentionné dans [le #2712](https://github.com/inkstitch/inkstitch/issues/2712) (pas techniquement un problème de police, mais un problème avec tout satin qui n'a que deux échelons de nos jours).
> 
> (J'espérais y arriver cette semaine mais ce n'est pas encore arrivé)

Emilio n'a de problème que parce que un effet de chemin a été appliqué sur une police.

**Comment by gusvisser** [comment]
I overlooked one thing when i created the post a lot of the fonts have jumpstitches within each letter based on default settings in the preference window  so there is an option that the preference window has a different setting as default since most people use the software in default settings  and that creates a lot of jump within the letters and this would create slowing down of the embroidery and unneeded tie ins and tie outs 
but if the fonts are properly digitized there should be no reason for having jumps within a letter no matter what the preference setting should be 

If i am wrong on this then please explain it to me

Gus Visser

**Comment by Augusa** [comment]
J'aimerais bien comprendre comment les préférences par défaut peuvent créer des points d'arrêt à l'intérieur d'un caractère. Il me semble que si la préférence par défaut est à 3mm cela signifie qu'un saut de fil de 3mm ou moins est brodé comme un point simple.
Quel serait la solution proposée s'il y a un saut de fil à l'intérieur d'un caractère ? Le convertir en chemin ? Est-ce que la création d'un chemin avec deux points est pertinente ? Ne risque-t-on pas d'alourdir singulièrement les fichiers de glyphes ? Le module de lettrage est déjà bien long pour l'affichage. Certains sauts de fil sont inévitables comme les sauts entre les lettres et leur accent ou le point du i. Il est indispensable de mettre des points d'arrêt si on veut pouvoir couper les fils ce qui donne un résultat bien plus beau.
J'ai beaucoup utilisé les polices d'Inkstitch et je n'ai pas trouvé qu'elles fonctionnaient moins bien que les polices de Stitch Era Liberty que j'ai aussi. Certaines sont là depuis 4 ans et ce problème n'a jamais été évoqué. Il peut se faire qu'il reste des points d'arrêt à l'intérieur des caractères sur des chemins de dessous où l'on ne pouvait pas les supprimer dans les versions très anciennes d'Inkstitch.
Avant de penser à des modifications sur des polices dont chaque glyphe a été testé en broderie je veux être sûre de bien comprendre s'il s'agit vraiment d'une amélioration. J'ai donc vraiment besoin d'explications.

________________________________
De : gusvisser ***@***.***>
Envoyé : dimanche 18 février 2024 23:39
À : inkstitch/inkstitch ***@***.***>
Cc : Augusa ***@***.***>; Comment ***@***.***>
Objet : Re: [inkstitch/inkstitch] Existing fonts in inkstitch (Issue #2729)


I overlooked one thing when i created the post a lot of the fonts have jumpstitches within each letter based on default settings in the preference window so there is an option that the preference window has a different setting as default since most people use the software in default settings and that creates a lot of jump within the letters and this would create slowing down of the embroidery and unneeded tie ins and tie outs
but if the fonts are properly digitized there should be no reason for having jumps within a letter no matter what the preference setting should be

If i am wrong on this then please explain it to me

Gus Visser

**Comment by claudinepeyrat06** [comment]
@gusvisser  you are right i think that it is really related to the preferences and more precisely to the "Minimum jump stitch length". Once upon a time this was set to 3mm, meaning that any jump less than 3mm  was just like a stitch and only larger  jumps would create trims. If you set your preferences to 3mm you will see almost no trim inside  ink/stitch letters. If  you set it to a smaller value, then you will get trims. I think that this occurs because autosatin  creates running stiches  starting from the centerline, and not the rails, so if a satin is somewhat large you get the issue. Yes it would be possible  to modify the existing font so that even with a very small  "Minimum jump stitch length" no trim happens, but it would be tedious and boring work.

**Comment by tyrosinase** [comment]
> Concernant Emilio, la police fonctionne parfaitement dès qu'on modifie sa taille avec l'échelle, par contre aucune police ne fonctionnera avec les effets de chemins (comme cela est montré avec le H de Emilio). Si on veut écrire en courbe, on utilise la fonction "lettrage le long d'un chemin".

The problem isn't specific to Emilio (Dino Mouse is doing the same thing), or even specific to fonts. It's caused by changes in the satin algorithm. Path Effects is just exposing it, and it's going to come up in other cases. Any satin with two rails is now incredibly fragile, and any alteration is likely to break it.

Arching letters is very different than lettering on a curve, and it's extremely popular right now. If I can go into the Brother Embroidery Group with tens of thousands of members and say "hey, you can do that thing with this free tool," that is a *huge* win for Ink/Stitch.

**Comment by claudinepeyrat06** [comment]
two rails and exactly two rungs should be avoid as in that case inkstitch consider that the two longest of the 4 paths are the rails, anything that deform the satin column may confuse inkstitch

**Comment by tyrosinase** [comment]
> two rails and exactly two rungs should be avoid as in that case inkstitch consider that the two longest of the 4 paths are the rails, anything that deform the satin column may confuse inkstitch

Yep, but that didn't used to be the case, which means there are a lot of older-than-that bits of lettering that are broken now (sometimes even *before* any deformation; I really gotta fix DinoMouse before the next release, and maybe Emilio though that one isn't mine).

**Comment by claudinepeyrat06** [comment]
@tyrosinase  @kaalleen i tried to arch emilio to see the problem (using the enveloppe deforming extension) , and i'm afraid it is not just a question of just two rungs but also a question of rungs being not long enough. They are long enough to cross both rails, but barely and therefore any distortion can prevent that. So i'm afraid that in addition to hunting the two rungs satin, there will be many rungs to lengthen, maybe i need a little helpful extension to lengthen all rungs of selected satins. Also there are 5 Emilio fonts, which one is your favorite candidate  @tyrosinase for arching (i would like to start with that one so that you can check that it does what you want)

**Comment by claudinepeyrat06** [comment]
@gusvisser i have started the process of hunting for unwanted jumps stitches Kaalleen made  some additional  extensions to help the process, but it is still going to take time to review all the fonts.

**Comment by tyrosinase** [comment]
> which one is your favorite candidate @tyrosinase for arching (i would like to start with that one so that you can check that it does what you want)

The applique one, which unfortunately is probably the most complicated.

Also in font goofs: the 3 is duplicated in Ink/Stitch Small (glyph is duplicated then they're grouped). I will fix it if no one else does but I figured I should write it down here just in case.

**Comment by claudinepeyrat06** [comment]
<img width="937" alt="image" src="https://github.com/inkstitch/inkstitch/assets/88194877/44d32015-30f7-471a-83b8-4e119b77c325">
@tyrosinase After heavy modification of  emilio applique  i can somewhat successfully apply path effects. Strangely i often need to flatten to avoid strange stuff with running stitches. No Satin with exactly two rungs, and almost all rungs were lengthen.  Hope it will help you achieve your goal.
The image use grid deformation path effect. 

[You can find the file here ](https://github.com/inkstitch/inkstitch/tree/claudine/make_emilio_applique_more_robust)

**Comment by kaalleen** [comment]
Closing. Fonts are in the process of being heavily reworked. Thanks to @claudinepeyrat06 

No rungs warning has been added to troubleshoot.
