### ISSUE TITLE
pes files don't work

### ISSUE THREAD

**Issue by pivi66** [inkstitch/inkstitch#273]
I have created several stich files using the Mac version. The dst files works on the Brother innovis v3. The pst files are not visible on the machine. Other pes files not generated by inkstitch  are displayed.
I use an USB stick to transfer the files to the machine.

Thanks for the mac version!

**Comment by wwderw** [comment]
I was originally thinking that this might be a Mac only concern since this was the first release of the Mac, but this also applies to the Linux version of the new release as well.

@lexelby , this applies (on Linux anyway) to exporting both through embroider and through the "save as copy" function.

I was able to view it in another software (and bring it back into Inkscape as a PES file as well), however.  One thing that I did notice that in the commercial software, it took out 198 stitches compared to the CSV version of the same file.

My testing was on a PR-1000.

**Comment by pivi66** [comment]
Thanks for the quick answer. If there is any thing to test let me know.

**Comment by wwderw** [comment]
Both Version 1s appeared on my PR1000.  Ver 6 did not.

**Comment by tatarize** [comment]
Do any V6 files work for the machine?

[alternative-6.zip](https://github.com/inkstitch/inkstitch/files/2289231/alternative-6.zip)

**Comment by tatarize** [comment]
The test files there had three files. Is it accurate that only 2 showed up? And are these the files that end with 1?

It seems like V6 of the files have a critical error. But version 1 works.

However, the lack of the preview is not comforting on the version 1 of the file.

The alternative v6 are a selection of other company outputs, sewing them is unneeded, sewing the V1 files might be useful to know if that goes off without a hitch. Especially the 6k version 1 file, rather than the 18-19k one (they have truncated headers which is an idea, originating with the early file mapping).

---

If this stuff is wrong maybe a major assumption about how the machines loads the files is wrong.

What preview image does this display?

[A-or-flower.zip](https://github.com/inkstitch/inkstitch/files/2290413/A-or-flower.zip)

Is it a flower or is it the A image from before (if you have Brother software and something like Wilcom opening this will show the interesting nature of this test file).

**Comment by pivi66** [comment]
Sorry you are right, one file is missing. The  filename of pes files are not displayed by the V3 only the preview.
So i retested the files one after each other.
convert6-A.pes is not displayed and A-or-flowers.pes is also not displayed.

**Comment by tatarize** [comment]
How about these one?

[couple-other-tests.zip](https://github.com/inkstitch/inkstitch/files/2290639/couple-other-tests.zip)

* Should be standard Brother V1, check if V1 just doesn't get image displayed or if it's actually broken.
* Brother V1 empty header, with pec body.

**Comment by pivi66** [comment]
Both files are displayed as preview.

**Comment by tatarize** [comment]
Really? Interesting.
How about this, Brother blank header, but with the typical PEC body as pyembroidery produces it.

[BH-PyB.zip](https://github.com/inkstitch/inkstitch/files/2290736/BH-PyB.zip)

**Comment by pivi66** [comment]
This file is not displayed.
Next testing has to wait until tomorrow.

**Comment by tatarize** [comment]
Yeah, I'll figure out something, but it means the PEC block is wrong in some way. Since the other pec block worked for doing that trick. I'd guess it's something to do with the colors. But, since both of those were displayed. It narrows things down pretty nicely.

**Comment by danielkschneider** [comment]
Hello everybody :)
I can confirm that PES is broken for version 1.17 of Ink/Stitch
I tried BH-PyB.pes and the machine (a Brother PRX1050) just says that it cannot be stitched. It won't display a thumbnail in the control panel either.

Workaround (for people who are not aware of this). Most Brother machines should be able to stitch DST format.

**Comment by lexelby** [comment]
Thanks for the report.  This is interesting, because I've never had a problem on my brother SE400.  I'll take a look at this when I have a chance.

**Comment by pivi66** [comment]
We did some more testing see
https://github.com/EmbroidePy/pyembroidery/issues/2

@wwderw @lexelby is pyembroidery only a forge in your project and how are the results of tatarize are reflected in inkstitch?

**Comment by lexelby** [comment]
@pivi66 It's unfortunately a tad complicated at this point.  However, I can tell you that once @tatarize fixes the bug(s) in his repo, I'll merge the changes into ours.
