### ISSUE TITLE
How to make goes stitches from top to bot

### ISSUE THREAD

**Issue by LeagueOfShards** [inkstitch/inkstitch#2757]
Hi guys,

i have same issues with inkstitch. I would like to know if its possible to set stitichin direction from top to bot or bot to top. Now i have something like this and its pretty cool but when i embroid the graphic on t-shirt i have some empty lines. Thanks in advance 

![418410896_952723183106856_5725907126737374287_n](https://github.com/inkstitch/inkstitch/assets/160267267/acdfb2c1-2189-46c3-b6b2-be6cb85205bf)

![dadas](https://github.com/inkstitch/inkstitch/assets/160267267/16ea77ca-2444-499e-95d0-d52a3ade6f96)

**Comment by gusvisser** [comment]
You can set your start and stop point on a fill by adding the fill start and stop command to an object and drag them to where you want to start and stop
 But also for your "missing line" a reason for that can also be not using enough stabilizer 
Another option you have is breaking up your object into multiple fills because it is trying to find the best path possible and since you have some pointed areas it is hard to find the right path
And one more option is if it is possible to fill your holes in and sew those parts overtop that makes it easier to fill from one end to the other also
And it is also possible when you fill the whole area that your stitch count could be less also due to the many shortstitches what are being created by going around your holes

Gus Visser
