### ISSUE TITLE
Adjusting density of pre digitised font PES file. 

### ISSUE THREAD

**Issue by Macey2000** [inkstitch/inkstitch#2820]
Currently saved as an object, not a path - the PES file does not seem to allow density to be increased. Unfortunately, the person I purchased the pre-digitised font from is unable to provide an SVG file, only a PES file which I find bizarre as typically, wouldn't you save your original digitised file as an editable SVG file in case you later required edits?

Thank you in advance - Google says it is possible to adjust the density within a PES file, just unsure how / if Inkscape can do this.

**Comment by kaalleen** [comment]
The digitizer most possibly didn't use Ink/Stitch to create the embroidery file and therefore they wouldn't be able to provide the svg file. Other embroidery programs have their own editable formats.

Ink/Stitch at the current time can't do density adjustments to rezise pre-digitized embroidery. Depending on the design you could try to use a few tricks through. - Or you try an other program that is able to do the resizing adjustments necessary. I never tried any other program, so I don't know which one you could use for your purpose.

**Comment by tyrosinase** [comment]
Also even if the designer does have the vector version (SVG or Embrilliance-source or whatever), they may not want to share that. Some sell different sizes as separate products (Urban Threads/Embroidery Library, [in]famously), others just don't want it to be easily edited.

_(And some of us do include the SVG because being "open source" is kind of our whole shtick. Sadly, it means you can acquire slightly-altered versions of my designs on skeevy sites but, what can you do.)_

There's some notes down in the bottom of https://silverseams.com/2021/03/the-embroidery-resizing-problem.html on converting a stitch file into an Ink/Stitch SVG, which may or may not be of use, especially in font conversion.

**Comment by kaalleen** [comment]
I'll close this one. You can still post further questions in here.
