### ISSUE TITLE
Menu déroulant dans les colonnes satin....

### ISSUE THREAD

**Issue by Marif91** [inkstitch/inkstitch#2836]
Si je sélectionne 2 ou plusieurs colonnes satin dont le paramétrage est différent au niveau de la longueur maximale de point, inkstitch considère que ces colonnes sont paramétrées de la même façon. Un menu déroulant indiquant la valeur 8 pour une colonne et la valeur vide pour l'autre serait utile...

Il faut donc modifier colonne par colonne cette valeur./

Merci !!!
<img width="512" alt="Capture d’écran 2024-04-11 à 11 15 02" src="https://github.com/inkstitch/inkstitch/assets/65076100/de41b837-ba4a-4157-83b2-b37bbcd7719d">

**Comment by claudinepeyrat06** [comment]
I think that  this is  due to maximum stitch length having no default value. Therefore inkstich has nothing to show in the drop down menu showing all the values of this parameter for all the selected satin columns. 
This means that when you want to check that all selected satin columns have say a maximum stitch length of 8 mm, params shows if some have a different value, but does not show if some have no value at all. A turnaround is to set maximum stitch length to 9 (anything not equal to 8) apply, call params again and set it  to 8.

**Comment by Marif91** [comment]
Oh yes ! Thanks !!Envoyé de mon iPhoneLe 15 avr. 2024 à 20:32, Claudine Peyrat ***@***.***> a écrit :﻿
I think that  this is  due to maximum stitch length having no default value. Therefore inkstich has nothing to show in the drop down menu showing all the values of this parameter for all the selected satin columns.
This means that when you want to check that all selected satin columns have say a maximum stitch length of 8 mm, params shows if some have a different value, but does not show if some have no value at all. A turnaround is to set maximum stitch length to 9 (anything not equal to 8) apply, call params again and set it  to 8.

**Comment by Marif91** [comment]
Merci pour la solution de bons sens en attendant les modidifications à venir !
