### ISSUE TITLE
Error message when running demo

### ISSUE THREAD

**Issue by Sparky6548** [inkstitch/inkstitch#289]
Hi,
I just installed inkstitch.  When I try to run the suggested demo, I get the following error as soon as I click on params:

Traceback (most recent call last):
  File "F:/Program Files/Inkscape/lib/python2.7/site.py", line 64, in <module>
    import traceback
ImportError: Bad magic number in F:\Program Files\Inkscape\python\Lib/traceback.pyc

Inkscape is fresh .92.3, running on Windows 7, installed on drive F:

**Comment by lexelby** [comment]
Hi, welcome to the project, and thanks for installing!  That sure is a weird error message.  It seems to indicate that something is wrong with the Python bundled with inkscape.  

You might be able to fix this by deleting that `traceback.pyc` file.  It might then start complaining about another pyc file -- you can safely delete all of them. 

I would suggest reinstalling inkscape except that this is a fresh install.  I wonder if maybe anti-virus caused the problem.

**Comment by Sparky6548** [comment]
I went through 4 more traceback.pyc errors after deleting the first one.
After deleting the last one, inkstitch started drawing the stitches for the
test object.  Do I need to do anything else to fix this problem?  Is it
safe to run without these .pyc files?  Here are the rest of the error
messages I encountered:

Traceback (most recent call last):
  File "inkstitch.py", line 5, in <module>
    import subprocess
ImportError: Bad magic number in F:\Program
Files\Inkscape\python\Lib/subprocess.pyc


Traceback (most recent call last):
  File "inkstitch.py", line 5, in <module>
    import subprocess
  File "F:\Program Files\Inkscape\lib\python2.7/subprocess.py", line 61, in
<module>
    import threading
ImportError: Bad magic number in F:\Program
Files\Inkscape\python\Lib/threading.pyc

Traceback (most recent call last):
  File "inkstitch.py", line 5, in <module>
    import subprocess
  File "F:\Program Files\Inkscape\lib\python2.7/subprocess.py", line 61, in
<module>
    import threading
  File "F:\Program Files\Inkscape\lib\python2.7/threading.py", line 13, in
<module>
    from collections import deque as _deque
ImportError: Bad magic number in F:\Program
Files\Inkscape\python\Lib/collections.pyc


Traceback (most recent call last):
  File "inkstitch.py", line 5, in <module>
    import subprocess
  File "F:\Program Files\Inkscape\lib\python2.7/subprocess.py", line 61, in
<module>
    import threading
  File "F:\Program Files\Inkscape\lib\python2.7/threading.py", line 13, in
<module>
    from collections import deque as _deque
  File "F:\Program Files\Inkscape\lib\python2.7/collections.py", line 22,
in <module>
    from keyword import iskeyword as _iskeyword
ImportError: Bad magic number in F:\Program
Files\Inkscape\python\Lib/keyword.pyc

**Comment by lexelby** [comment]
> Do you think it could have anything to do with my having an installation of Python already on my computer?

It's possible.  Inkscape bundles its own copy of Python, so it _should_ be isolated from your system Python.  However, if the Inkscape installer did something weird, it might have tried to compile the Inkscape .py files with your system Python.  I'd be especially suspicious if your system Python is version 3 or greater.

 > Do I need to do anything else to fix this problem? Is it safe to run without these .pyc files?

I would recommend you delete all .pyc files from Inkscape's folder.  Otherwise you may continue to have this kind of error with other inkscape extensions.

It is safe to delete these .pyc files.  When Python goes to run a .py file, it first compiles it.  It stores the compiled version as a .pyc file so that it can skip the compilation phase next time.  Deleting the .pyc file just means it will rebuild it next time and store a new one.  It's possible that it may not be able to store the new .pyc file due to Windows permissions, but that's not a big deal and it shouldn't affect performance noticeably. 

I hope that helps, and please let us know if you run into any more problems!

**Comment by Sparky6548** [comment]
Ok, I'll delete the .pyc files.  Thanks for your fast response.

Now I just have to learn to use the extension!

**Comment by lexelby** [comment]
Yay! Lots of tutorials on https://inkstitch.org to help us get started. Please do let us know if anything is unclear so that we can improve the docs.  Have fun! :)
