### ISSUE TITLE
Version v 3.1.0 schedule

### ISSUE THREAD

**Issue by kaalleen** [inkstitch/inkstitch#2978]
With a lot of bug fixes, new extensions and new fonts Ink/Stitch is almost ready for a next official release (https://inkstitch.org/upcoming/).

Here is what we still need to do beforehand ...

- [x] Fix and add proportional pull compensation
- [x] Fix windows builds (there has been a cloud update which broke them)
- [x] Revisit randomization options
- [x] Test if signing (Windows, macOS) notarization (macOS) is still working
- [x] Run tests with the upcoming Inkscape version (especially: select embroidery elements and realistic stitch plan preview)
- [x] Release a beta release version (sort of)
- [x] Fix reported bugs
- [x] Release beta2
- [x] Fix bugs
- [x] Proofread website
- [x] Ensure translations are ready
- [x] Release v 3.1.0
- [x] Announce release on website and remove "upcoming version" hints

Please add what is missing in the TODO list.

@capellancitizen are you on to improvements for the realistic stitch plan preview that we should consider important for the next release? Usually new feature like this would be so well received by users. Since we removed realistic preview from the simulator, this is a though one to accept for everybody ... ... Just in case you wonder about the amount of complaints ;)

**Comment by tyrosinase** [comment]
I keep meaning to dig through the code and figure out how to submit a patch (I have installed Gitea on my local network and have been using it to synchronize my design work between the laptop and desktop in hopes of familiarizing myself with multi-user git repos enough to contribute, and instead I have learned a wide variety of ways to create irreconcilable differences).

So it if it's not too difficult before 3.1.0 comes out, could someone please look at the `inkstitch:label` for Target Position commands versus other commands, and make it the same as other commands (unless there's a reason for the distinction, in which case never mind).

**Comment by tyrosinase** [comment]
Also, I think if there was an option in the simulator to adjust the line width, no one would complain if the fully-realistic view went somewhere else. 99.9% of what I use the current realistic for is a quick visualization of what the coverage density will look like, and dropping shading out of it would be perfectly fine (probably even a quality-of-life improvement when I'm on the slow laptop).

**Comment by kaalleen** [comment]
> So it if it's not too difficult before 3.1.0 comes out, could someone please look at the inkstitch:label for Target Position commands versus other commands, and make it the same as other commands (unless there's a reason for the distinction, in which case never mind).

Sounds like an easy fix if I just knew what is wrong with the target position label?

**Comment by kaalleen** [comment]
> I keep meaning to dig through the code and figure out how to submit a patch (I have installed Gitea on my local network and have been using it to synchronize my design work between the laptop and desktop in hopes of familiarizing myself with multi-user git repos enough to contribute, and instead I have learned a wide variety of ways to create irreconcilable differences).

Any specific questions about this? Can we help out to get you started?

**Comment by kaalleen** [comment]
> Also, I think if there was an option in the simulator to adjust the line width, no one would complain if the fully-realistic view went somewhere else. 99.9% of what I use the current realistic for is a quick visualization of what the coverage density will look like, and dropping shading out of it would be perfectly fine (probably even a quality-of-life improvement when I'm on the slow laptop).

Uff, an other option. I think we have to rethink the simulator ui too. I am already not happy with the background change button (that I included myself). It's just too many buttons. Maybe we should add a button for settings and open an other panel with ... settings...

**Comment by tyrosinase** [comment]
> Any specific questions about this? Can we help out to get you started?

"How does git even work" is probably not very specific. :laughing: 

>  Maybe we should add a button for settings and open an other panel with ... settings...

This might work. Though I would be perfectly happy with "the default width of the line in the simulator is ~40wt". But if that's tied to the params preview, maybe not (I'm sure we'd sometimes want to see thinner lines for clarity... right?)

**Comment by capellancitizen** [comment]
I was tooling around with trying to improve the shading of the realistic preview but wasn't able to make any significant leaps. If the core problem here is that the stitch is too wide, it'd be possible to reduce the stitch width back down. That was a change Lexelby added to the branch initially, given some of the feedback was that it was "too fat" I reduced the width back down in a local branch I haven't pushed yet.

If you have a particular set of things that need to change I'd be happy to hear them. This weekend I took a break from hacking on realistic preview to hack on multihread support but that was just because I wanted to tinker on something else for a bit.

**Comment by gusvisser** [comment]
In my opinion the shading can be of importance to get the right visual of the stitches  on where there are improvements needed in the design
I had last week where i added an inkstitch lettering in a design and by running it through the simulator and viewing it in the realistic mode i noticed that there were issues with that lettering and went back and forth from the design to the player to make sure all issues were solved
Also the player plays a big role because when we apply the params to the object we see it in the param window but we cannot visulize it in the vector object so we rely on the realistic simulator 
And i really like the one in the current version

Please Please give us a good one
Gus Visser
Thanks for the awesome work

**Comment by capellancitizen** [comment]
I guess is the takeaway that we need to have realistic preview back in the simulator? That could probably be arranged.

**Comment by buzzmandt** [comment]
> I guess is the takeaway that we need to have realistic preview back in the simulator? That could probably be arranged.

I would prefer that myself. I'm sure there will be plenty of people saying they no longer have a realistic preview, just because they don't know it has been moved. Gus and I and others will do all we can to spread the word.
I would prefer it back in the simulator just because it's a quick one button toggle click. However, having said that, I also like that the realistic preview now offers options of realism and once I get used to the new location I think it'll be fine over time.

**Comment by kaalleen** [comment]
> That could probably be arranged.

@capellancitizen  We dropped this feature for now because we felt, that we didn't have enough time resources to implement it into the wxpython simulator just now. Do you want to tackle it down? If so ... how much time do you think you'd need?

**Comment by bianchifan** [comment]
Just my 2 cents..

> That could probably be arranged.

That would be great!!

Nevertheless the current version has a great advantage, you can toggle between your construction and the realistic view and can fade over, an awesome feature, so please keep it!

The new simulator seems to be the same within param's dialog and embroidery simulation.
A realistic preview within the params would be another great feature.


> given some of the feedback was that it was "too fat"
> Please Please give us a good one
If it could be tweaked a little more..outstanding!!!
old one
![Bildschirmfoto vom 2024-06-12 10-46-57](https://github.com/inkstitch/inkstitch/assets/17491743/a21becee-77eb-4142-a9bb-2f198e23c5d0)

new one
![Bildschirmfoto vom 2024-06-12 11-26-06](https://github.com/inkstitch/inkstitch/assets/17491743/dc7f18e7-8795-4ffb-929e-819541438512)

> This weekend I took a break from hacking on realistic preview to hack on multihread support
phantastic!

> Thanks for the awesome work

**!!!!!**

**Comment by bianchifan** [comment]
> because we felt, that we didn't have enough time resources to implement it into the wxpython simulator just now

Please, please don't hurry!
Take all the time you need.....!!

**Comment by buzzmandt** [comment]
just out of curiosity could we have both? A realistic preview button in the simulator like v3.0.1 for simple realistic and the other realistic menu option you've made for v3.1.0 as it is now keeping the more detailed preview and realistic settings options. I also don't want to begin 'feature creep' either. Just a thought.

**Comment by kaalleen** [comment]
> Please, please don't hurry!
> Take all the time you need.....!!

Well, that's why we decided to release without it in the first place. We all agree though, that this is something a lot of users will actually miss. So if there is the chance we can still figure it out before the release, then it might be worth to wait just a little bit longer with the release. That's why I wrote up this issue in the first place, just to figure out what is possible for the next release.

@bianchifan Your realistic preview doesn't look at all as expected (it has no visible filters?!?).
Is that the svg preview or the png preview? Or do they look alike?

**Comment by buzzmandt** [comment]
> If you mean if we can have realistic stitch plan preview and simulator realistic preview? ... The realistic stitch plan preview will not be removed. It is there to stay.

Yes, that's what I mean, thank you for the info

**Comment by bianchifan** [comment]
> Is that the svg preview or the png preview? Or do they look alike?

Its the vector one and all views look similar. 
Pics in your new thread.

**Comment by capellancitizen** [comment]
> > That could probably be arranged.
> 
> @capellancitizen We dropped this feature for now because we felt, that we didn't have enough time resources to implement it into the wxpython simulator just now. Do you want to tackle it down? If so ... how much time do you think you'd need?

I wouldn't set it for this release if we want to release so soon. Unfortunately we'd be implementing it basically from scratch given the wx renderer, and the performance in doing a pixel effect like the lighting might suffer in Python, but maybe there's something we can do to cheat... Still, I'll try to take a look at it this weekend and see how far I can get. 

As for the realistic stitches appearing without filters, I'll follow up in that thread.

**Comment by kaalleen** [comment]
> I wouldn't set it for this release if we want to release so soon

@capellancitizen  Ok, yes, that is reasonable.

> Also, I think if there was an option in the simulator to adjust the line width, no one would complain if the fully-realistic view went somewhere else. 99.9%

@tyrosinase Ok, here is an approach to do that. View buttons are moved to the side to gain some extra space. Especially when we want to add more buttons, such as the button for realistic preview.

The release can be found here: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-simulator-line-width-option
If something isn't working or if anyone has complaints about the ui decisions made in there, please add a comment here #2992

**Comment by tyrosinase** [comment]
Just finished the big project for the month so I'm finally getting around to updating today... if there's a newer release you want me to poke at, let me know.

**Comment by kaalleen** [comment]
Inkscape 1.4 will neglect the about and the embroider extension as they do nothing (windows and linux).
Guess we will have to rewrite them with wxpython.

**Comment by kaalleen** [comment]
@tyrosinase any of the latest releases will be fine. They all include only minor fixes.
We need test reports for the pull compensation though. It will be in all of the next releases - just not yet (merged a minute ago).

**Comment by tyrosinase** [comment]
I may not be the greatest tester for those, since I don't do garment embroidery. Pull is considerably less of an issue for marine vinyl. 😆

**Comment by capellancitizen** [comment]
I am busy this weekend but Monday I can probably put up a PR with some changes to the realistic preview. Thinner stitches and a shading tweak will be doable and can address the main complaints about them being too "fat".

**Comment by claudinepeyrat06** [comment]
@capellancitizen  just to let you know that sometimes when  i try the realistic preview (png  not vector) on a huge embroidery file i end up after a long time with a png being a black rectangle.
I have  saved an example, but can't put the result here as it is more than 200M large.  
In case you want to try it (but it takes ages....) this is a file where it happens if one try to get a realistic preview of the whole  thing.
Using  main, but it also happened  to me with previous versions, when  the file is huge and full of fills.
![cooper](https://github.com/inkstitch/inkstitch/assets/88194877/0f7fc10f-3fee-4452-857c-5f94d8877bec)

**Comment by capellancitizen** [comment]
I've been getting `FloatingPointError: invalid value encountered in line_locate_point` trying to embroider Claudine's file here: I know it's related to #2660 and #2705, but I wasn't able to get it working with any shapely version 2.0.0 to 2.0.4. Is there something I can do to get it working? (I guess, is that something that's going to impact the release?)

**Comment by kaalleen** [comment]
The releases are good. It depends on the GEOS version on which shapely is build. pip install shapely with --no-binary

**Comment by capellancitizen** [comment]
Re: Claudine's image: I think a good question to ask before release is what we want to do with the raster modes for the realistic preview. I originally implemented them because it was suggested as a possible nice-to-have and to be honest I thought it would be fun to implement (and it was, more or less).

Maybe it's not worth it in the first place: I can easily render a realistic vector stitch preview for Claudine's file (Hitting the cache: ~60s to run the extension, ~30s to load the result) and performance in Inkscape isn't unusably bad after it loads in - ~5s per re-render isn't exactly snappy, but it might be okay enough. On the other hand the rasterized version is so big it takes minutes to render and crashes Inkscape after loading.

We could change the raster method  to take the resolution multiplier as a suggestion rather than a rule, and instead go with a lower multiplier if the end result is going to be too big. But then there's a bit of complexity to that with the current implementation, because it actually uses inkscape to calculate the bounding box, because otherwise it does that in Python incredibly slowly, so we'd either have to go back to getting the bounding box in Python, or communicate with the opened inkscape process, and the latter sounds more complex than it's probably worth.

I'm leaning towards suggesting getting rid of rasterization for the realistic preview (for now at least), unless we think it's a big enough benefit to leave in. If we do leave it in maybe the issue is around making sure users know when to use raster vs vector? Or at least have a guardrail or two in place from letting users destabilize inkscape by asking for huge realistic stitch plans of either kind?

**Comment by kaalleen** [comment]
I understand your concern. However I would definitely prefer to keep the png feature. I know you improved the filters and they are much faster now than they used to be, but my computer still freezes when I move the canvas with a complex design in realistic vector preview in it (even when I reduce effect quality in the inkscape settings). While the png takes longer to render in the first place, but doesn't slow down Inkscape afterwards.
The bug claudine is seeing is annoying, but I think most people (if they do not run tests for new fonts) won't try to render a huge file like this and as a workaround you could render it part by part. When I find the time I may try to investigate the issue and inform the inkscape team about it. It's probably a bug on their side (and can be reproduced with just one long, long line). I think though, that in most cases the png output works out fine.

**Comment by claudinepeyrat06** [comment]
if it stays in there  would it be possible simply to warn the user when the design is too big and hint at doing several smaller previews ? 
It is not a common case as normally the size of the hoop is the limit, but it's nice when one  make a font to have a global view. If it requires several steps it is not really a problem, what was annoying was to have to wait for a very very long time for a black rectangle. I'd rather be warned.

**Comment by kaalleen** [comment]
@claudinepeyrat06 Do you think it would be enough to warn people in the documentation?
If you have a lot of stitches use png, if you want to render huge designs use svg.
If you have both together, do not use realistic stitch plan preview at all.

@capellancitizen I think the complaint about the realistic preview being too fat resulted from the missing filter.
I mean no pressure, just ask if you are still planning an realistic filter update?

**Comment by kaalleen** [comment]
> If we do leave it in maybe the issue is around making sure users know when to use raster vs vector? Or at least have a guardrail or two in place from letting users destabilize inkscape by asking for huge realistic stitch plans of either kind?

If that can be implemented easily it would be best. I'm just not sure though, what the best parameters would be and there sure will be differences depending on computer speed and also the inkscape settings for rendering quality will matter.

**Comment by capellancitizen** [comment]
I tinkered with changing the rendering of the preview, but I wasn't able to get anything that's a significant improvement. I did note that the realistic stitch width is supposed to be .32mm, but in practice it's generally significantly thicker because it doesn't use functions like `unittouu`. But if we make the stitches actually .32mm thick they're too small to see the shading and they leave gaps in satins and fills that don't really seem to match how they actually look. I think maybe we should just leave it for now. Can push the branch if people want to tool with it further.

**Comment by claudinepeyrat06** [comment]
@kaalleen  could  we in addition  also add a warning in the help  tab ?

**Comment by kaalleen** [comment]
> @kaalleen could we in addition also add a warning in the help tab ?

Sure, done.

**Comment by kaalleen** [comment]
@capellancitizen I really do think that you did a good job with the rendering filter and I had a lot of very positive feedback already. I think we are almost set for a "beta version" and push more fixes later on when we had feedback and bug reports from that one.
