### ISSUE TITLE
auto route verses red work

### ISSUE THREAD

**Issue by gusvisser** [inkstitch/inkstitch#3058]
![auto red](https://github.com/inkstitch/inkstitch/assets/85417086/848e696d-8a8c-4e18-bbc9-2b1ba1ea4d57)
as i was asked to check a few things concerning auto route running and red work with solid and dashed lines 
i have attached the svg what gave different results in different scenarios
also when we use auto route running stitch we need to apply params first in order to set a stitch lenght 
while in the red work we can set the stich lenght right in the redwork popup window
if more info is needed let me know and i wil see what i can do

Gus Visser

**Comment by kaalleen** [comment]
I guess we just didn't care since it doesn't matter anymore. Stroke style should be fixed for the release. Thank you for pointing it out. The other differences stay. At this point I don't want to make any big moves until the next release, only bug fixing.
If you think it'd be helpful to have the stitch length setting in auto-route as well. I'm not sure though, if I'd want to change it, because the way it is, it allows to keep various stitch settings for the strokes, while redwork unifies the stitch settings (which makes sense for redwork), but maybe not so much for auto-run.
