### ISSUE TITLE
Corrupt File Singer SE300

### ISSUE THREAD

**Issue by BTaylor22** [inkstitch/inkstitch#3130]
This is my first time using inkstitch. I download my file as both a .xxx file and a .dst file and neither one are able to be read by my machine.

**Comment by kaalleen** [comment]
5. What are the dimensions of your design? And what are your available hoop sizes?

**Comment by BTaylor22** [comment]
1. I am using inkscape 1.3.2 and inkstitch v3.0.1 high sierra catalina. My laptop is a macOS Big Sur version 11.7.9

2.  I am using a .png image, downloaded as a single file.

3. I am using a USB Singer Memory Stick that came with the machine.

4. Yes, I able to transfer non inkstitch files to the machine and it operates normally. I did try taking a simple 1 layer object, a star, and tried transferring it to the machine and it transferred with no problem. 

5. The dimensions of the design is 4.461" x 4.791"

**Comment by tyrosinase** [comment]
If you're not doing anything with the PNG besides importing it, there's nothing to stitch yet. You have to go through a lot of steps to actually get a stitch file: https://silverseams.com/tutorials/digitizing-with-ink-stitch.html 

If you go into `Extensions > Ink/Stitch > Visualize and Export > Simulator` it should show you what it's going to export. (I just tried it on a blank file and got no response, though I'm still on beta2.)

`Troubleshoot` tells me an empty file is valid as well, which - yeah, it should probably throw a warning if any of those things comes up with zero stitches to display/export.

(If you do have stitches, then that's not the issue here, but it's still *an* issue.)

**Comment by BTaylor22** [comment]
I have done my fill and satin stitches for every layer before I exported the file.

**Comment by kaalleen** [comment]
It's hard to tell what is going wrong without seeing the file. Is it possible to share it?
If you can't for license reasons, you can also upload it to https://lexneva.name/owncloud/index.php/s/NCcJbJqnKmL7nES

**Comment by bianchifan** [comment]
> I download my file as both a .xxx file and a .dst file and neither one are able to be read by my machine.

My W6 machine is technically  nearby identiacla, the firmware is different. But I guess the core shoud be very similar..
The are many designs out there which couldn't be read by W6. Also (much too) many designs saved by InkStitch are not readable for whatever reason.

1. Try to flip /rotate your design if possible.
2. Try tof lip/rotate a couple of times before saving.
3. Read your saved embroidery file into Inkscape, select the paths within the various color groups, open the params view and change the stitch method to "Manual Stitch".

Additionally make shure that your USB Stick is correctly unmounted before removing it.

**Comment by kaalleen** [comment]
No further response. I'll close the issue. If you are still having problems, please continue to comment here.
