### ISSUE TITLE
Enhancement Request -- Closed Path Satin Colums

### ISSUE THREAD

**Issue by owendelong** [inkstitch/inkstitch#3175]
When trying to create a satin column either using line->satin or rails, the software doesn't seem to like closed paths (e.g. circles, etc.). This appears to be an artifact of the fact that closed paths lack a defined start and end point since they are essentially continuous and the error message reflects this fact.

The current most prevalent workaround is to cut the path and then create two satin columns for the resulting pieces.

I think there are better ways to handle this situation. Two that come to mind: Just pick a point (line) or pair of points abeam one another related by an (imaginary) line perpendicular to either or both rails and use that. Since that path is closed, it shouldn't really matter where the satin column starts or ends.

Alternatively, allow the user to select a second (line) or third (rails) object and use the intersection of that third object with the prior objects as the start/end point of the satin column.

**Comment by kaalleen** [comment]
Can you go a little bit more into detail of how it doesn't seem to like closed paths and which error message you are seeing?

**Comment by kaalleen** [comment]
I'm not really sure what the request means and we didn't get any further explanation by now. I'm going to close the issue. We can still reopen it, when more information is available.

**Comment by tyrosinase** [comment]
I think it means sometimes the choices that it makes about where to break the rails when you have a loop are not quite right.

That is, if you make a Circle object and then convert line to satin, you still get two unbroken circle subpaths for rails. If something happens to cause the points to be reordered within a rail, like a break and re-join, you get string art because the starting point is arbitrary without an explicit break.

OP is suggesting using one rung-creation point to instead make an explicit break.
