### ISSUE TITLE
Can't set inkstitch: namespace properties using custom extension

### ISSUE THREAD

**Issue by ToonChopper** [inkstitch/inkstitch#3206]
Hi, this may not be an InkStitch issue, but when I try to set an inkstitch: namespace property like inkstitch:trim_after, the namespace is reset to 'ns0'. Setting an inkscape: namespace property works fine (e.g. label). It looks like it happens after the python code has been completed because when I try to read the property using the inkstitch: namespace, I get the correct value. After closing the execution dialog, however, the property key is altered. Is there a way to override this behavior? Thanks.
PS: Ubuntu 20.04

**Comment by ToonChopper** [comment]
Btw, one workaround is using the namespace URL (http://inkstitch.org/namespace).

**Comment by kaalleen** [comment]
Which Inkscape version are you using?

When I try to set an inkstitch param it just works fine - as long as the file has already run an Ink/Stitch extension once.
If I try to set one before I ran any Ink/Stitch extension it will warn about an unkown namespace.

**Comment by kaalleen** [comment]
I should read titles more carefully. I just noticed that you are talking about custom extensions. I thought you were manually setting the attributes. If you set namespaces within an extension, you'll need to register the namespace previously.

https://inkscape.gitlab.io/-/extensions/-/jobs/7899463212/artifacts/build/html/tutorial/document-namespaces.html

I hope this document will lead you to your answers. I'm going to close the issue. Since this is not really an Ink/Stitch issue as you said. But you can still comment here.
