### ISSUE TITLE
Start/End Command not staying in place; why is this happening? Is this a bug?

### ISSUE THREAD

**Issue by ewalus** [inkstitch/inkstitch#3209]
Hi hi! Just started learning Ink/Stitch about a week ago, so I'm fairly new! Thanks so much ahead of time for helping me out!

I'm running inkstitch v3.1.0 osx, on inkscape 1.3.2

I have an embroidery piece I'm working on, which includes 2 areas of fill stitches. To avoid huge, inefficient thread jumps between colors, I set a start and end command on the objects. When I run the simulator, everything works great! However, when I do one of three things:

    1. Close out of the before mentioned simulator window

    2. Move the objects on the canvas in any way

    3. Run the Stitch Plan Preview

...the start and end commands shift from where I set them to, to seemingly arbitrary places on the fill area. The shift is always to the same locations for each time; it's like it's locked to these specific areas on the canvas. I can shift them back without issue, but the moment I do one of the 3 things above again, the problem repeats itself.

When everything is in the correct position, I save the embroidery as a .pes, and actually run the stitches on the embroidery machine, everything works just fine! The start and end commands work as they should.

A video of the issue (demonstrating 2., moving the object in anyway) can be found here: https://youtu.be/vJR8H8a6Plc

Is there something happening behind the scenes that I'm missing? Is this a bug?

**Comment by kaalleen** [comment]
Thank you for the report. But no, it is not a bug, just common inkscape behavior.

Commands are attached to the center of the object and they will correct their position every time something is wrong (as long as the action of moving the connector itself doesn't disconnect the command entirely). Instead of moving the connectors endpoints, you should rather select the command symbol and position it in that way, that the connector points to the correct position.

See also second info box for object commands on the website: https://inkstitch.org/docs/commands/#attach-commands-to-selected-objects-

**Comment by ewalus** [comment]
Hi Kaalleen,

Appreciate you taking the time to explain things to a newbie! Thank you!

**Comment by kaalleen** [comment]
You are welcome. Don't hesitate to ask questions here, others may learn from it too and we really don't want to miss out on possible bugs.
