### ISSUE TITLE
Selecting embroidery elements

### ISSUE THREAD

**Issue by gusvisser** [inkstitch/inkstitch#3227]
![person](https://github.com/user-attachments/assets/309fcb13-add6-4a9e-a8c3-2abbe7a159f9)
I am unable to select embroidery elements in a red work design it does not give errors when the python window runs the elements flash for a moment and dissappear

Running windows 10
inkstitch 3.1.0
inkscape 1.3.2

Gus Visser

**Comment by kaalleen** [comment]
The redwork top stitching paths somehow received a zig-zag stitch param.
Can you try to check the zig-zag stitch option?

**Comment by gusvisser** [comment]
![automatic-save-0-2024_10_07_19_21_05-15336-1](https://github.com/user-attachments/assets/be2a2196-d18f-4031-bebe-06614c3c221d)
the previous svg i had done a copy and paste in place into a new document 
so the file does not keep the embroidery setting with it
this is an autosave from the original and does not give me option to select the redwork embroidery elements either

Gus Visser

**Comment by gusvisser** [comment]
![person 2](https://github.com/user-attachments/assets/c2505993-2ca4-404d-81ea-e8b5843f3249)
on this one i did reworked the params and i was able to select the red work understitching but totally nothing of the redwork topstitching

on my first svg i was able to select the zigzag

Gus Visser

**Comment by kaalleen** [comment]
Here is the thing. To keep backwards compatibility we introduced an automatic conversion from running stitch to zig-zag stitch  when we think, that the file is old (created before the introduction of ink/stitch svg versioning). Zigzag was the previous default for non-dashed lines (as you may remember well).
I'm a bit annoyed about the way I did it back then. As it is now causing your issues. When you copy a design into a new file without running any Ink/Stitch extension on the empty file before pasting the elements. It will definitely match the "this is an old file" case and converts your running stitches into zigzags.
I believe we shouldn't be doing this, because this will creates much more confusion and unwanted behavior than that it helps to keep old designs intact. We always discouraged the usage of zigzags. So I just hope that there aren't many zigzag files out there that need this type of repair. But I can't think of an other way to recognize old files neither.

Nevertheless I would lean towards to dismiss the old file conversion from running stitch to zigzags. This is the only conversion in there that actually changes the stitch type. But there are also changes for the stitch length that might matter. In fact it would be best if we could pop up a window asking if the file should be updated or not. But that might be difficult for non-wxpython extensions.

For now I would give one advice... When you want to copy elements with Ink/Stitch attributes over into a new file, run the simulator on the empty file once before doing so. It won't open, but it will add the Ink/Stitch metadata which is necessary to avoid the issues you are seeing.

**Comment by gusvisser** [comment]
But even if i create a brand new svg i still am not able to select embroidery elements top stitching for redwork

Gus Visser

**Comment by kaalleen** [comment]
Copying elements with inkstitch attributes into a brand new svg file is exactly what is breaking it (automatic conversion into zigzags). If you need to copy things over, run the simulator first (on the empty file) and only paste the elements afterwards.

**Comment by kaalleen** [comment]
Uhm, sorry, you are so right. It's not selecting redwork top stitchting. I prepared a fix. Thank you.
