### ISSUE TITLE
Lettering, No Route Stitches shown in Params

### ISSUE THREAD

**Issue by Blechkanne** [inkstitch/inkstitch#3269]
When creating Lettering and using Param on the whole group it, it does not show the routes that should be used instead of jump stitches:
![image](https://github.com/user-attachments/assets/ade1d419-72b1-40e3-a6e3-be66c5fbb0e3)

It does show Correctly on the Simulator though:
![image](https://github.com/user-attachments/assets/359234be-be75-4bbf-94a5-24145ff32b05)

Is this intended behaviour?

**Comment by tyrosinase** [comment]
Yes, Params is only set up to handle one param-type of things at a time. I *think* that it goes with the types that match the first type of object it finds, but I might be wrong on that (haven't looked at the code).

(I'm sure there's a good reason why selecting Params couldn't just open Lettering when it realizes it has a Lettering object, but that'd sure be nice for those of us whose muscle memory goes to Params every. single. time. :laughing: )

**Comment by kaalleen** [comment]
>  I think that it goes with the types that match the first type of object it finds, but I might be wrong on that (haven't looked at the code).

When running stitches and satins both are selected it will always show the elements with multiple subpaths and render them as satin. Elements with a single subpath will be ignored, because they can't be rendered as satins. The Params was build to define a specific stitch type for all selected elements. So it doesn't make a lot of sense to have multiple target stitch types selected and run params. But this is a recurring question, so this might not be very intuitive.

> I'm sure there's a good reason why selecting Params couldn't just open Lettering when it realizes it has a Lettering object

You may want to change the params for elements in the lettering group. I think it would be very annoying when that's not an option anymore, because the lettering dialog pops up when it was not requested. Maybe I just misunderstood what you were saying...

**Comment by tyrosinase** [comment]
> You may want to change the params for elements in the lettering group. I think it would be very annoying when that's not an option anymore, because the lettering dialog pops up when it was not requested. Maybe I just misunderstood what you were saying...

I can't speak for anybody else (I think we all know my usage of Ink/Stitch is pretty iconoclastic :laughing:  ) but I don't ever choose the whole lettering object when I'm changing the params... they're always mixed object types. Even NickAinley mixes bean and regular running stitches, though it doesn't have satins. I always always select a single object  and then `Select Same Stroke Style` (I should use Ink/Stitch's version but old habits die hard) so I have all the satins selected as individual objects.

But I finally, after all this time, did break down and assign F4 and F5 to Lettering and Params respectively, and that's made it much easier to select the right thing, so don't change the behavior if nobody else would benefit.

**Comment by kaalleen** [comment]
> I can't speak for anybody else (I think we all know my usage of Ink/Stitch is pretty iconoclastic 😆 ) but I don't ever choose the whole lettering object when I'm changing the params... they're always mixed object types.

That would be great advice for everyone :)
