### ISSUE TITLE
Inkstitch not working Xubuntu 18.04 error in sub-process.py

### ISSUE THREAD

**Issue by piscvau** [inkstitch/inkstitch#327]
Hello I just installed inkstitch on a xubuntu 18.04 machine and Inkscape 0.92.3 
The extension does show but when I click on embroder param I get the following error message:
Traceback (most recent call last):
  File "inkstitch.py", line 33, in <module>
    extension = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Any help would be most welcomed.

**Comment by lexelby** [comment]
Hi! Welcome, and thanks for trying out Ink/Stitch.

This error happens when Ink/Stitch can't find the main executable for the extension.  It expects to find a binary named "inkstitch", located at `inkstitch/bin/inkstitch` relative to your extensions directory (where inkstitch.py and the inx files are).  Maybe there was an issue untarring the extension?

**Comment by piscvau** [comment]
Thanks re-installation solved the problem

**Comment by lexelby** [comment]
Great, glad to hear that!
