### ISSUE TITLE
pes file is not displayed on brother Innov-is 1500

### ISSUE THREAD

**Issue by durgaBahadur** [inkstitch/inkstitch#3324]
Hi there

I am on Inkstich 3.1.0 and created a pes file with it. However, after having transferred it to the machine, nothing is displayed where normally the uploaded files would be shown.
I also uploaded a dst version of the same drawing. This one is displayed but (as expected) throws a format error when chosen.

What could be the problem?

Thank you!

**Comment by tyrosinase** [comment]
Most of the time, that's an indication that your design is too large for your machine. I can't remember what the true size of a 1500 is, but I thiiiiiink it's one that is called a 6x10 but is actually 150x250mm. If you're maxing out a hoop, try making the design a little smaller and see if that fixes it.

(I *wish* machines would throw a "too large for the hoop" error instead of just ignoring them, but Brother is not the only manufacturer to have decided that's the way it should work.)

If that's not it, some machines also object to things like spaces in the filenames and whatnot, or there's some other possibilities that escape me right now.

**Comment by durgaBahadur** [comment]
Oh, thanks a lot for your prompt response!

Indeed, my document size is 210x210mm. I don't have access to the machine before next Wednesday. I will try then and report back!

**Comment by tyrosinase** [comment]
6x10 machines are generally either 150x250 or 160x260, so you might try both of those so you know for sure. (I spent a long time assuming my "5x7" machine was limited to that when I had a whole 2-3mm more to work with!)

The document size doesn't actually matter, for what it's worth: I always set my page size to the hoop size just as a visual reminder, but the only thing that matters is the actual punches. Likewise, it doesn't really matter where the design falls on the Inkscape page, it'll be "centered" in the design file (and on most embroidery machines, though you can use a basting box to force the actual design to be placed off-center).

**Comment by durgaBahadur** [comment]
Thanks a lot for your hints!
I reduced the size of the image to 100x100mm and it actually worked :)
