### ISSUE TITLE
.pes file not recognised by Brother innov-is v3

### ISSUE THREAD

**Issue by tobiastykvart** [inkstitch/inkstitch#342]
I am having trouble with the second .pes I've created (the first one was stitching perfectly).

My Brother innov-is v3 can't load the .pes with an error "The data of the selected pattern was not recognised. Possibly the date is faulty. Switch the machine off and on again"
However I can't find anything wrong with the file, I've started it from scratch designing it a second time, and it doesn't seem to be a problem with the machine either, because my first design I did with inkstitch worked fine on it.

Any pointers to what could be wrong? I would really like to use inkstitch for further designs.

I've zipped the .svg and .pes file:
[Frankenrechen.zip](https://github.com/inkstitch/inkstitch/files/2506076/Frankenrechen.zip)

I am on macos 10.14

**Comment by lexelby** [comment]
Hi @tobiastykvart, thanks for using Ink/Stitch!  I'll be honest, file formats aren't my strong suit.  That said, I'll take a look and see what I can do.

If you can think of what might be different between the one that worked and the one that didn't, that'd be a huge help.  Maybe it's the size or number of stitches?

**Comment by tobiastykvart** [comment]
Hi @lexelby, seems like the problem was not the file format, but the positioning of the design within the Inkscape canvas.
![screen shot 2018-11-13 at 12 53 52](https://user-images.githubusercontent.com/44401648/48412453-fccebe00-e744-11e8-855b-cefe13befddd.png)
I didn't think the position of the design would matter and get cropped to its size. But I guess the center of the canvas is also the center for the hoop, so if the design is outside that hoop area the machine thinks there is a big jump out of the bounds of the hoop.
Now I know that I just have to center the design, but others might run into the same problem.
@tatarize mentioned "Calling pattern.move_center_to_origin()", maybe it would make sense to always do that during export

**Comment by lexelby** [comment]
Ah!  That makes sense.  My Brother machine completely ignores a file if the design is even a tenth of a millimeter bigger than its maximum size.

I don't call `pattern.move_center_to_origin()` because I want the user to have explicit control over the origin point of embroidery files.  The default origin is the center of your inkscape canvas (not the center of the design itself).

If you'd like, you can set the origin wherever you like.  Click Extensions -> Ink/Stitch -> language -> Commands -> Add Commands and add the origin command.  place it wherever you like, and that point will be (0, 0) in your exported PES files.  Hope that helps :)

I'm going to close this now, but feel free to reopen if the above didn't help.
