### ISSUE TITLE
Closed Path Satin Stitch

### ISSUE THREAD

**Issue by harryiliffe** [inkstitch/inkstitch#354]
I've been using Ink/Stitch for a while now and on thing that keeps bothering me is the inability to create a closed path satin stitch.
If I create a closed path and run the "Convert line to Satin" Tool it works well. But then, In params it fails to create the satin column correctly.

Hopefully these images show what I'm struggling with.
<img width="700" alt="screen shot 2018-11-20 at 12 27 01 pm" src="https://user-images.githubusercontent.com/23181431/48742494-023b8380-ecc4-11e8-919e-2256e806c342.png">
<img width="700" alt="screen shot 2018-11-20 at 12 27 29 pm" src="https://user-images.githubusercontent.com/23181431/48742495-023b8380-ecc4-11e8-8d46-2bffa1e2c440.png">
<img width="700" alt="screen shot 2018-11-20 at 12 27 47 pm" src="https://user-images.githubusercontent.com/23181431/48742493-023b8380-ecc4-11e8-9f03-7f1706bafe1f.png">

My current work around is added a node and deleting the section of the path but this is annoying and tacky. 

My question is, Is this a bug or just a thing that hasn't been looked at yet.

**Comment by lexelby** [comment]
Ugh, I know, isn't that annoying?  There are actually two issues going on here.

One is, as you guessed, a bug: Convert To Satin Column doesn't handle closed paths very well.  It gets confused and starts one rail in a different spot from where it starts the other.  #253 covers this bug and a couple of related scenarios.  I hope to fix it soon but it's unfortunately kind of complicated.

There's a general issue with closed paths and satins, though.  Technically speaking, in an SVG, a closed path _does_ have a start and end, it's just that the path ends where it starts.  However, Inkscape doesn't give us any way to tell it where this starting point is, and it also seems to like to shift it around at random.  The result is that you can't really control a closed-path satin column very well.

Fortunately, as far as embroidery goes, having a non-closed path that starts and ends in the same place gives the same result.  That means you can just force the starting position by selecting a node in the node editor and clicking "break path".

Cleaning up after Convert Stroke To Satin can be a bit of a pain, as you're seeing with your circle.  You can select a spot and break both paths there.  You'd also need to find the spot where Ink/Stitch mistakenly broke the paths and mend them bak together.

You can prevent Convert Stroke To Satin from screwing up like this if you artificially break the path before running the extension.  Just make it into two half-circles, and the extension will do the right thing.  It'll sew just the same as two satins instead of one.
