### ISSUE TITLE
error message when digitizing 

### ISSUE THREAD

**Issue by ARKopp** [inkstitch/inkstitch#355]
I get this error message when I hit stich. Before I did in parameters a botton stich.

File "lib/elements/element.py", line 279, in fatal
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 40: ordinal not in range(128)

**Comment by kaalleen** [comment]
Du hast einen Bug entdeckt, danke für die Rückmeldung!
Ich habe eine Version angelegt, die das Problem (hoffentlich) behebt. ABER, das ist eine Fehlermeldung für eine Fehlermeldung, die einfach nur falsch dekodiert wurde. Das heißt, dein eigentliches Problem wird hierdurch nicht behoben und du erhälst mit der neuen Version einfach nur eine andere Fehlermeldung. Aber mit der richtigen Fehlermeldung, kommst du der Lösung vielleicht schon ein kleines bisschen näher.

Wahrscheinlich überkreuzen sich Pfade in deinem digitalisierten Text, die sich nicht überkreuzen sollten.

Die neue (temporäre) Version von Ink/Stitch kannst du hier herunterladen: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-fix-encoding

=====

You just discovered an encoding bug. This means, you raised an error message, which couldn't be displayed properly due to wrong encoding. This doesn't solve your issue though, but a properly displayed error message might already help to find the right path to solve the actual problem.

Probably you created paths that are crossing each other but shouldn't.

Release to fix the encoding bug (temporary):
https://github.com/inkstitch/inkstitch/releases/tag/dev-build-fix-encoding

**Comment by ARKopp** [comment]
@kaalleen vielen Dank! Thank you. Will try it out tomorrow.
