### ISSUE TITLE
Extension: Break Apart and Retain Holes

### ISSUE THREAD

**Issue by jnweiger** [inkstitch/inkstitch#360]
inkstitch asks me to convert text glyphs to paths. that is fine.
But after doing so, some characters need special processing.

A `j` consist of two separate entities (dot and stem) and produces the error

path3891: Fehler: shapely.geos - INFO - Hole lies outside shell at or near point 67.071956989867715 -15.55192694853509

Workaround: This can easily fixed by applying 'Path' -> 'Break apart'
That is also necessary for `:` `;` `"` `i` `j` and several other characters.

But for `%` `Ä` `ä` `ö` the 'break apart' operations also breaks away the holes and we get additional stitches instead of no stitces where the hole should be. The workaround that is necessary for some characters must thus not be applied for other characters. We need to resort to tedious manal decomposition and re-assembly on a character by character basis. 

This is espacially bad as a user needs to know and locate the affected characters first.

Is there a way to enhance institch so that it recognizes a closed subpath that lies completely outside another closed subpath as two distinct objects, and not a hole?

**Comment by lexelby** [comment]
Oh hi, @jnweiger!  I've seen you over at inkscape-silhouette.  Welcome to Ink/Stitch!

You raise a really good question, one I've given some thought to.  It would be feasible to have Ink/Stitch break a path up into its separate polygons, so that your `Ä` becomes three separate fill shapes: two dots and an `A` (with its triangular hole intact).

The question is, what order should Ink/Stitch stitch those fill shapes in?  The obvious answer would be to do them in the order that the subpaths are defined in the SVG.  The problem is that order is not exposed to Inkscape users at all and it's hard or impossible to manipulate it in the UI.

When I'm breaking this kind of shape apart, I first do "break apart" (ctrl-shift-k) as you mentioned.  Then I drag-select each sub-part (getting the shape plus any holes) and combine them (ctrl-k).  A bit of a pain but I've gotten used to it.

For text, though, I'm working on a solution you may find much more palatable: a lettering extension.  A basic version of it is already available [here](https://github.com/inkstitch/inkstitch/releases/tag/dev-build-lexelby-lettering).  I'm working on a GUI in #351.  As a bonus, it already supports German characters :)

That may not be helpful for you though, since you're talking about fill stitch.  For letters, fill stitch is only going to make sense for really big letters (1-2 inches wide or more).  I'm planning to create a font for big fill-stitched letters, but that's probably a ways off yet.

Again, thanks for joining us over here, and thank you for all of your work on inkscape-silhouette!  I use it all the time.

**Comment by lexelby** [comment]
It's all about ordering with embroidery. :)  With a Silhouette it's just a matter of efficiency.  With embroidery, ordering is about efficiency, plus routing the sewing, and even managing distortion of the fabric.  One of the first things I did when I took over inkscape-embroidery was to do away with its old method of automatically choosing ordering, and put that control entirely in the hands of the user.

Hershey can be helpful for embroidery, especially with Ink/Stitch's (relatively new) "Convert stroke to satin column" extension, but there's really no substitute for a carefully hand-crafted font.

**Comment by wwderw** [comment]
> I haven't given the exact order too much thought, my Idea was, that it should not make much of a difference in the first place, and would add to the robustness of the code.

In embroidery, order is very much important.  Some substrates require a very specific sequence of stitching otherwise it can compromise quality.  Specialty embroidery like applique and puff foam also have their own quirks with ordering and how things are digitized that really only apply to their own needs and won't work with "regular" embroidery.

Plotter work, sequencing isn't so much important until you get to where your needing to use role substrate and tracking becomes a concern.  How things are nested in a design becomes the concern.

But with embroidery, order of how things stitch out is always important as @lexelby mentioned.

**Comment by lexelby** [comment]
> Hey @lexelby now I know where you were hiding all the time :-) Inkstitch is defintily a project that is worth to invest in! Thanks for starting and developing it so well!

@jnweiger Oh, I forgot to mention, when I wrote that Silhouette Multiple Actions extension, I borrowed a fair bit of GUI code from Ink/Stitch's Params dialog. :)

And come to think of it, I also borrowed a bit of inkscape-silhouette's viewbox handling logic in Ink/Stitch (with credit).  I also ported over some of the transform composing logic into inkscape-silhouette.  There's a surprising amount of common ground between the two extensions!
