### ISSUE TITLE
inkstitch index out of range

### ISSUE THREAD

**Issue by piscvau** [inkstitch/inkstitch#366]
Hello I am new to inkstitch and almost new to embroidery machine.I just tried the basic usage tutorial. I draw a circle with a stroke and fill. I transform it to a path then I do inkstitch parameters. It shows an embroidery. Then I try to do embroi and I get the following error:
Error writing to home/odile/Documents/travaux manuels/broderies/embroidery.pes:
and I get no stitch plan I can inspect.
Any help would be welcomed.

**Comment by lexelby** [comment]
Hi there, welcome to Ink/Stitch!  I'm sorry you're having trouble.  Hopefully we can get you up and running quickly.

It's a little hard to tell what's going on from the message you pasted.  Could you paste the entire text that Ink/Stitch shows?  That would give me more context to help me understand what's going on, so that I can hopefully find and fix the bug.

As a work around, it may work to do `File -> Save a Copy`.  Choose an Ink/Stitch file format from the dropdown and a place to save the file.  That uses a different method to save the file and may avoid whatever is causing the crash for you.

**Comment by piscvau** [comment]
I already posted the complete error message :
Error writing to home/odile/Documents/travaux manuels/essai inkstitch.pes:
this message is displayed in a box whose title is: 
Inkscape has received additional data from the script executed.  The script did not return an error, but this may indicate the results will not be as expected.
OK doing save a copy and choosing the file format.pes solves the problem.

**Comment by piscvau** [comment]
However I see no layer inkstitch to look into

**Comment by lexelby** [comment]
Hmm, in that case, I think I'm missing something.  Where does "index out of range" appear?

> However I see no layer inkstitch to look into

Yes, that's what I meant when I said that Save A Copy is a workaround, rather than an actual solution to your problem.

I did find a bug in the error message code that's hiding the actual error message.  It should be giving you more of a hint of what's going wrong after the `:` in the message.  I've created a development version that should show the error message correctly, available [here](https://github.com/inkstitch/inkstitch/releases/tag/dev-build-lexelby-bugs).  Could you try installing that one and running Embroider, to see whether it properly prints the error message?

**Comment by DreadKnight** [comment]
I used to get the "index out of range" a lot when using those special objects to define where to start/end stitching.

**Comment by lexelby** [comment]
@DreadKnight Yikes, that's not good.  If you have come across one of those "Index out of range" errors, I definitely want to know about it.  If you can post an SVG that causes it, that's even better.  That error _always_ indicates a bug in Ink/Stitch -- it's never something you should just have to put up with as a user, and it's never "user error".

**Comment by jameskolme** [comment]
Seems to be same problem, started suddenly, no extra commands or anything. Error message comes if try to run embroider, simulate or export. Simulating one shape at a time will work. 

Trying to do:
![offi1](https://user-images.githubusercontent.com/44113605/53693784-b5c90f00-3dad-11e9-9f83-5583914a89fd.png)

Doing params, it will simulate, but not all.
![offi2](https://user-images.githubusercontent.com/44113605/53693788-bbbef000-3dad-11e9-93ba-28f823d867a6.png)

```
Traceback (most recent call last):

  File "inkstitch.py", line 62, in <module>

  File "inkscape\share\extensions\inkex.py", line 283, in affect

  File "lib\extensions\simulate.py", line 17, in effect

  File "lib\extensions\base.py", line 180, in elements_to_patches

  File "lib\elements\element.py", line 268, in embroider

  File "lib\elements\satin_column.py", line 769, in to_patches

  File "lib\elements\satin_column.py", line 328, in validate_satin_column

IndexError: list index out of range
```
File: [offipalsta flat.zip](https://github.com/inkstitch/inkstitch/files/2922992/offipalsta.flat.zip)

**Comment by kaalleen** [comment]
You have some elements with only two nodes at the same spot. Delete them and it will work. I pushed them into an extra group.

[offipalsta.flat.zip](https://github.com/inkstitch/inkstitch/files/2923044/offipalsta.flat.zip)

Other than this... should we establish a proper message for this problem?

**Comment by jameskolme** [comment]
OK, thanks. Is there anyway to make these to show? Now that I know what I´m looking for, I can scroll object list and found these.

**Comment by kaalleen** [comment]
Well, that is a good question ;)
You can run the simulator on smaller selections of the not working area to see where exactly the problem lies. Best way I know (in this particular case) is to actually move through the object panel list. You could also select all objects that you actually want to sew and invert the selection with `Shift + 1`, then you have everything selected what doesn't belong to your design. Then delete everything in the selection.
... Hope this helps a bit.

**Comment by jameskolme** [comment]
Invert selection sounds clever idea in this case, this helps a lot, thanks again. 
Accidentally similar problem on other file, but that´s no problem anymore.

**Comment by lexelby** [comment]
> Other than this... should we establish a proper message for this problem?

**Comment by lexelby** [comment]
Finding and removing little "shrapnel" pieces in a fill shape like this can be hard, especially if they're too small to see.  When the fill shape itself is big but has these extra bits of shrapnel, it's almost always the case that the user doesn't actually intend for the shrapnel to be there. Usually shrapnel comes from using Inkscape's Trace Bitmap command.

Question: what if ink/stitch simply ignored the tiny little bits?  This would be much like enabling "despeckle" when tracing a bitmap.
