### ISSUE TITLE
path effect causes scaling error in auto-route satin

### ISSUE THREAD

**Issue by lexelby** [inkstitch/inkstitch#376]
Discovered by @jameskolme in #374. 

If the document units are anything but pixels, auto-route satin improperly scales some (but not all) of the objects.  It's likely getting the document transform wrong.

To reproduce, load up `3 satin autoroute.svg`.  Hide everything but the "trying to do" layer.  Select the 3 satins and run auto-route.

https://github.com/inkstitch/inkstitch/issues/374#issuecomment-452304562

**Comment by tyrosinase** [comment]
Getting the same thing on this file even if I change doc units to pixels.

The red satin stitch was copy-pasted from an older file (pre-dating the 90-96dpi change) and I don't remember what I clicked to get past the conversion since I was resizing it anyway. The blue satin stitches are all new to this file (and work fine).

File extension changed to txt because Github is a butt.

[WichiFlag_MC.txt](https://github.com/inkstitch/inkstitch/files/3468685/WichiFlag_MC.txt)

**Comment by lexelby** [comment]
Thanks for the reminder about this bug!

**Comment by tyrosinase** [comment]
Ran into this again, yelled at Inkscape for awhile because Combine or other things didn't clear all the transforms on an object, poked around a little and discovered this: https://github.com/Klowner/inkscape-applytransforms

It seems to clear attributes like stroke weight/style, which is slightly annoying, but after I restored the stroke weights the satin stitches were fine. So that's a workaround for now, since it seems to be transform matrices that are confusing things.

**Comment by lexelby** [comment]
I love that extension!  Use it all the time.

**Comment by tyrosinase** [comment]
On 12/6/19 2:47 PM, Lex Neva wrote:
>
> I love that extension! Use it all the time.
>

I will too now that I have it. Can't believe it isn't a built in
feature. "Yes, please DO clean up all the weird transforms on this
object so it doesn't keep glitching all over the screen, why is this
even a question?"

**Comment by lexelby** [comment]
Ideally, transforms should be completely transparent to the user (unless she wants to pay attention to them).  In practice, the math can be a bit mind-bending to get right.

One thing is certain: if you have to run Apply Transforms to get Ink/Stitch to work properly, that's a bug in Ink/Stitch.

**Comment by tyrosinase** [comment]
On 12/6/19 3:17 PM, Lex Neva wrote:
>
> Ideally, transforms should be completely transparent to the user
> (unless she wants to pay attention to them). In practice, the math can
> be a bit mind-bending to get right.
>
Ideally. But in practice very often when I go to copy or rotate one, it
glitches back to its untransformed self briefly. Or not so briefly.


> One thing is certain: if you have to run Apply Transforms to get
> Ink/Stitch to work properly, that's a bug in Ink/Stitch.
>

Yep. But it's not *just* Ink/Stitch.

**Comment by lexelby** [comment]
Oh, I see what you're saying.

**Comment by kaalleen** [comment]
Looking at the 3 satin auto route file...
It doesn't seem to be a unit issue. It has a lot of path effects in it.
When you run 'Shift + Ctrl +C' on them, they render in correct size.
So this would make it a path effect issue. Do you think Inkscape 1.0 and new ways to catch the paths might solve it?!?
