### ISSUE TITLE
Satin spacing auto correction

### ISSUE THREAD

**Issue by jameskolme** [inkstitch/inkstitch#379]
Feature request.

I think it would make better end results, if cornering with satin was assisted with short stitching on inside. There is limit how tight bend can be done, until thread blob or hole is made.  Maybe selected feature? Manually adding rungs helps sometimes, but then it usually runs on this second problematic thing. 

This second thing is sort of related to first one. Image is little over the top, but shows exactly how stitching is made. Distance from previous stitch is calculated probably using line, but line goes on angle, so actual distance thread to thread is only half what it should be. This is the way to make big blobs of thread and ends uneven results.  

![y_shape](https://user-images.githubusercontent.com/44113605/51084573-e5a45080-1734-11e9-9bf8-f23fc52ee4b8.png)

Somehow it is quite common to me, start or stop satin using some sort of V shape. How ever, if V shape is widening too fast, it will make 3D blob shape. Converting fancy letters to satin, this will happen really easily and most likely somewhere middle of letter.  

This can be avoided if shape is split many different parts, manually adjusting spacing, but then it gets complicated to work, even worse if shape is already long.

**Comment by jameskolme** [comment]
Yes #308, did not find that. 

Second thing, tried to draw, but it ended up so complicated even I lost track. 
This is what I'm thinking: 
V shape, going down from top. There are zig-zag lines going left and right. Let's assume 2 lines are already made and starting from right side.
  
Third line comes (end left side) and end point is calculated using shape line, actual gap between threads are calculated from line one end diagonally. 

Fourth line comes (end right side) and end point is calculated using shape line, actual gap between threads are calculated from line two end diagonally. Etc....

Spacing will change depending where previous same direction zig-zag went. So it will be correct at all times. There is just huge problem, this will not follow bends, unless some degree of freedom and extreme situations short stitching is allowed to happen. Both ideas are needed to make this work, I think.  

I have no idea is this good idea at all, might be huge can of worms.

**Comment by monotonee** [comment]
I, too, have been negatively affected by this phenomenon. I have significant coding experience and hope to acclimate myself to the current satin column algorithm soon.

In the mean time, I'd welcome the opportunity to be a part of this discussion. Are there any recommended workarounds other than manual node placement or trying to eyeball additional peak-to-peak spacing compensation? Is this an issue that you consider worth addressing?

![satin_spacing_03](https://user-images.githubusercontent.com/1015266/52148725-93ba6080-2638-11e9-86db-73f745fcbe4a.png)

**Comment by lexelby** [comment]
Hi @monotonee, welcome to the project!  I'm really excited to hear that you're interested in digging into the codebase.  I've tried to make it as approachable and understandable as possible. If anything is unclear, please let me know and I'll step in and improve the comments ASAP.  The relevant code is in `lib/elements/satin_column.py`.

This is definitely an issue I consider worth addressing.  I ran into it myself recently while digitizing a font with slanted serifs (https://www.dafont.com/triforce.font).  The density of the serifs increases significantly and the result is really not optimal.

The best workaround I can suggest is to break up the satin in the troublesome area and tweak the zig-zag spacing in each section.  Definitely not a great user experience.  The "split satin column" extension can help.

**Comment by lexelby** [comment]
I've been thinking about this, and it's really quite a hard problem.  I'd love to hear if anyone has any ideas.

As far as I can figure, we need to "penalize" each bit of a rail where it's not parallel to the other rail, treating it as less long than it is.  It's going to look something like the cosine of the angle between the rails.

The problem is, how do we know a section of the rails isn't parallel?  In order to figure out two corresponding points on the two rails, we would need to run the algorithm that's in Ink/Stitch... but then we won't have properly penalized non-parallel sections.  It's a chicken and egg problem, and it's bending my brain.

Maybe I'm making this too hard?

**Comment by jameskolme** [comment]
I have been thinking this also, it´s hard and seems to go wrong really easily. I was thinking would it be possible to make presolver, this would split shapes to known geometry with known solution and place rungs as needed with some sort of marker to use correct solution for every place, ignore manual rungs and other points when doing.  Splitting problem to more manageable pieces sometimes helps. There is still left huge amount of thinking, but possibly need to build chicken inside ready made egg can be avoided.

**Comment by kaalleen** [comment]
Hm, maybe spreading the distance points from a centerline to the rails could help to solve a part of the problem. But it wouldn't be perfect neither. At least for symmetrical shapes it would do the trick. For asymmetric shapes it can only solve half of the shifting. What do you think, is this possible or doesn't it make sense at all?

**Comment by lexelby** [comment]
Both of your ideas are good, and they got me thinking a bit more.  Now I have another idea of my own to try out, too.

I was thinking that the current algorithm works great for rails that are roughly "parallel".  But when they start being non-parallel, that's when we get into trouble.  Either contracting toward each other or spreading away from each other causes the density to artificially increase.

If you look at each "zig" in the satin's "zig-zag", you have this:
![zigs](https://user-images.githubusercontent.com/4446653/53381034-7037bc80-393d-11e9-8ab0-d6c2bf32cf28.png)

Let's look at two of the zigs in the section that's expanding out on the right:

![two_zigs](https://user-images.githubusercontent.com/4446653/53381149-cc024580-393d-11e9-9382-61ed0d3a1bbe.png)

If we connect them with two lines we get a trapezoid:

![zigs_trapezoid](https://user-images.githubusercontent.com/4446653/53381203-0370f200-393e-11e9-88cf-ab2946a8b3a6.png)

The closer the rails are to being parallel, the closer this trapezoid will be to a rectangle.  If they're far away from being parallel, then the stitches get too dense.  In this example, with a 0.4mm zig-zag spacing, we have this:

![zigs_angles](https://user-images.githubusercontent.com/4446653/53381572-3071d480-393f-11e9-9898-feed8d797b15.png)

The hypotenuse is 0.4mm because that's the zig-zag spacing, and the zigs are 0.24mm apart due to the angle this section of the rail is at.  So far I'm just stating what we all know.

My idea: every "zig", Ink/Stitch will figure out that angle and see if it's greater than, say, 10 degrees.  If so, it will compensate by travelling further along the hypotenuse before making the actual stitch, so the zigs stay 0.4mm apart:

![zigs_compensation](https://user-images.githubusercontent.com/4446653/53381822-0e2c8680-3940-11e9-85bf-11d4d8143a89.png)

If the hypotenuse is 0.67mm in this case, then the zig-spacing will be 0.4mm, which is what we want.  So if we travel an additional 0.27 before making the stitch, we'll compensate for the 53.8 degree angle.

```
0.67 = 0.4 / cos(53.8)
```

(okay actually it should be 0.677, but you get the idea)

So!  Every stitch, look at the angle, if it's greater than 10 degrees, walk an additional amount equal to `zigzag_spacing / cos(angle) - zig_zag spacing`.

This is easy enough to code, with the slight concern that all this trig may impact performance.  I think I should be able to optimize it, though.  I'll try to put together a proof-of-concept soon if no one gets to it before me. :)  Feel free to take a shot at it if you're interested, because my free time has been quite limited lately.

**Comment by lexelby** [comment]
One more thing: I realized that there's no good way for ink/stitch to figure out this compensation factor in advance just by looking at the rails, to avoid doing that trig on each zig.  That's because you have to figure out where the corresponding points are on the two rails, and the only way to do that is the existing algorithm we have already.  That's why my idea above involves running things as they are now and compensating, rather than calculating somehow in advance.

**Comment by jameskolme** [comment]
I think, this will solve so many shape related issues.

**Comment by lexelby** [comment]
It works!!! Really well! I'll polish my proof of concept a bit and get a version up for you folks to test.

**Comment by jameskolme** [comment]
Thanks, that was fast :)

**Comment by jameskolme** [comment]
There are so many possibilities now \o/
![queen](https://user-images.githubusercontent.com/44113605/53659949-768fa680-3c65-11e9-90ff-c4632352d938.png)

**Comment by lexelby** [comment]
Fixed!
