### ISSUE TITLE
NetworkXPointlessConcept: ('Connectivity is undefined ', 'for the null graph.')

### ISSUE THREAD

**Issue by Failly93** [inkstitch/inkstitch#386]
Hi! 
I'm trying to make a patch and made it in small steps, but after inserting bitmap (and tracing it into a path), I get the following message:
NetworkXPointlessConcept: ('Connectivity is undefined ', 'for the null graph.')
What do I have to change to make this work?
Sunny

**Comment by lexelby** [comment]
Hi @Failly93, welcome to the project!  I'm sorry you're having trouble -- it looks like you've found a bug!

I think I might know what's going on here.  When you trace a bitmap, Inkscape will often leave little speckles along with the main shape.  Those small extra shapes are confusing Ink/Stitch, and they may be small enough that you can't even see them!

Try this as a workaround: select the shape with the pointer tool (not the node editor).  Do *Path -> Break Apart* to break it into multiple objects.  While holding shift, click the main shape to deselect it.  By now, you should have only the tiny extra bits selected.  Press Delete to get rid of them.

You may also want to Simplify the shape to make it easier for Ink/Stitch to understand it.

I definitely don't want Ink/Stitch to be giving a weird error like it's doing for you.  Do you think you might be willing to post your SVG?  If I could try it out on my end it would make it much easier for me to fix this problem or at least make it give a much more helpful error message.  If you don't want to post it here, feel free to email me at `inkstitch at lex.gd` instead.

**Comment by Failly93** [comment]
Hi @lexelby!
Thank you for that quick answer! I tried breaking it apart and simplyfying it, but I'll try the rest as well (that might help me with another problem I got. ^^)
attached is the svg. 
[LGVE.zip](https://github.com/inkstitch/inkstitch/files/2840416/LGVE.zip)

**Comment by jameskolme** [comment]
Check tail end, there is one small dot, but I can't get any errors from it.

**Comment by lexelby** [comment]
Thank you, @Failly93! That really helped a ton.  I was able to see the error message on my side, so I've put in a fix.

Okay, well, I sort of fixed it.  What I've actually done is put in a much more helpful error message:

```
path939: error: Unable to autofill: This shape is so small that it cannot be filled with rows of stitches.  It would probably look best as a satin column or running stitch.
```

In this case, path939 is that super-tiny speck that @jameskolme noticed just right of the tail.  Once you get rid of that, though, you'll also get that error message for some parts of the unicorn horn.

The underlying problem here is that these shapes are too small to use fill stitch.  Fill stitch is back-and-forth lines of stitches to fill a shape, and with such a tiny shape it would only be one or two stitches.  Definitely not going to look right.

You'll get a much better result using satin columns for the unicorn horn.  Same goes for the letters, too.


While I was working on the code, I also put in better error handling in the case that Ink/Stitch crashes while trying to generate fill stitch, like it did for you.  Now you'd see something like this:

```
path939: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "/home/lex/repos/inkstitch/lib/elements/auto_fill.py", line 183, in to_patches
    ending_point))
  File "/home/lex/repos/inkstitch/lib/stitches/auto_fill.py", line 63, in auto_fill
    graph = build_graph(shape, segments, angle, row_spacing, max_stitch_length)
  File "/home/lex/repos/inkstitch/lib/stitches/auto_fill.py", line 181, in build_graph
    if not networkx.is_eulerian(graph):
  File "/home/lex/.pyenv/versions/2.7.14/lib/python2.7/site-packages/networkx/algorithms/euler.py", line 59, in is_eulerian
    return all(d % 2 == 0 for v, d in G.degree()) and nx.is_connected(G)
  File "<decorator-gen-174>", line 2, in is_connected
  File "/home/lex/.pyenv/versions/2.7.14/lib/python2.7/site-packages/networkx/utils/decorators.py", line 82, in _not_implemented_for
    return not_implement_for_func(*args, **kwargs)
  File "/home/lex/.pyenv/versions/2.7.14/lib/python2.7/site-packages/networkx/algorithms/components/connected.py", line 161, in is_connected
    'for the null graph.')
NetworkXPointlessConcept: ('Connectivity is undefined ', 'for the null graph.')
```

Then I'd be able to either fix the bug or, as in this case, make a better error message.

Thanks again for the bug report!
