### ISSUE TITLE
Ink/Stitch won't run; AttributeError

### ISSUE THREAD

**Issue by liambrownweb** [inkstitch/inkstitch#397]
OpenSuSE 42.3, x86_64. Executing 'inkstitch' binary from the command line results in the following:
```
sh: /home/lima/Desktop/inkstitch/inkstitch/bin/libreadline.so.6: no version information available (required by sh)
sh: /home/lima/Desktop/inkstitch/inkstitch/bin/libreadline.so.6: no version information available (required by sh)
sh: /home/lima/Desktop/inkstitch/inkstitch/bin/libreadline.so.6: no version information available (required by sh)
Traceback (most recent call last):
  File "inkstitch.py", line 51, in <module>
AttributeError: 'NoneType' object has no attribute 'title'
[3506] Failed to execute script inkstitch
```

**Comment by kaalleen** [comment]
@liambrownweb Welcome to the project.

Ink/Stitch is an [Inkscape](https://inkscape.org) extension.

Which means, that you have to run it through Inkscape. When you have Inkscape installed, place the Ink/Stitch files as described on [our website](https://inkstitch.org/docs/install) into the Inkscape extensions folder (`~/.config/inkscape/extensions`) and open Inkscape.

You will then find Ink/Stitch under `Extensions > Ink/Stitch`.

Hope this will help you to get Ink/Stitch running.
If you run into more trouble, don't hesitate to contact us.

**Comment by candice3000** [comment]
Well I've followed directions several times and although it's in the right area for inkscape extension, it' not appearing under the extensions in Inkscape. Not understanding why?

**Comment by lexelby** [comment]
Did you end up with a directory `inkstitch` in your Inkscape extensions directory?  Or did you end up with a bunch of other directories like `inx`, `bin`, `images`, etc?

Another possibility: did you restart Inkscape after installing Ink/Stitch?

**Comment by candice3000** [comment]
It took a while but finally figured out the extra step in Mint which is to
go to extensions and then onto app manager and then into inkscape and
finally installed. Yes I followed the steps in several tutorials and run
Inkstitch in Windows but wanted in my Linux because it's all faster and
cleaner. It's up and running now and am happy. Now to coordinate all the
info into one pdf for myself and I'll be so happy. Thanks for asking and
your helpful nature. It's a great extension. Candice
