### ISSUE TITLE
Print feature minor tweaks? 

### ISSUE THREAD

**Issue by jameskolme** [inkstitch/inkstitch#415]
I have started to use Inkstitch print feature now more and it is excellent. But Like so many times before, using something long enough, some nice to have features will pop up. This is something to do with my current double sided embroidery thingies. 

![pussukka](https://user-images.githubusercontent.com/44113605/54621661-c4cbe480-4a70-11e9-9ae7-3f7ae930138b.png)

Operator Detailed View, can we have text field before program starts, mainly for information and fabric sizes etc. If end result is something else than embroidery, some extra information is needed. It would be handy if everything can be found on same place. (Tried to make layer for information on Inkscape, but insanely difficult to print, if page size is hoop size) 

Operator Detailed View, would it be possible to have file name visible? I have bad habit of naming files using non existing filing system and my memory stick holds little bit more programs than recommend 20 :) (This is not that important but nice to have) 

Printing issue, I have A4 printer and no matter what I try from printer settings, every page fills something like 3/4 from full sheet. A4 size is selected from menu. I´m assuming here every page should cover full paper sheet? 

Printing to pdf results same problem, everything is shown so nicely on browser.

**Comment by kaalleen** [comment]
> Printing issue, I have A4 printer and no matter what I try from printer settings, every page fills something like 3/4 from full sheet. A4 size is selected from menu. I´m assuming here every page should cover full paper sheet?

Could you give an example file?

**Comment by jameskolme** [comment]
Yes
[Ink_Stitch Print Preview.pdf](https://github.com/inkstitch/inkstitch/files/2992841/Ink_Stitch.Print.Preview.pdf)

**Comment by kaalleen** [comment]
Thanks for the example file. I just cannot reproduce the print size issue. Which browser are you using?
Size is calculated in milimeters already, I don't know what would cause such a big difference.

I know you said it above, but could you confirm the A4-setting was set twice - in the printer settings and in the Ink/Stitch settings dialogue?!? (Just hoping something went wrong there :D)

Referring to your request for a field with extra information. The calculation of the operator detailedview page is somewhat complicated (amount of color blocks per page). That's why I came up with an other proposal instead and added an extra page for additional custom information. Would it help to fulfill your projects needs? You can add the custom page through the settings dialogue, just like the other layout pages.

**Comment by tyrosinase** [comment]
### As an old person, I would like to see a larger font used, and a larger version of the little stitch preview for each step.

**Comment by kaalleen** [comment]
@tyrosinase Thank you for your advice.

There is a possibility to enlarge the thumbnails in operator detailedview:
In the print settings you will find a slider to enlarge the thumbnail size. The new branch will now increase the font-size for large thumbnails a little.

You could also consider to use the the client detailedview. This will produce one page for each color-block.

**Comment by jameskolme** [comment]
> I don't know what would cause such a big difference.

Ermh, I have idea, maybe user? Yes, sorry. I found that Firefox page setup can set size as well as print properties, I know that now.  So something went wrong between keyboard and monitor as usual :)

Extra page will do perfectly, custom information can be found same place as everything else.

**Comment by tyrosinase** [comment]
@kaalleen Okay, different suggestion: make the "settings" button really large and flashing so I notice it's there. :woman_facepalming: 

That does most of what I want, thanks.
