### ISSUE TITLE
feature request: lettering bought alphabets

### ISSUE THREAD

**Issue by SchmetterlingK** [inkstitch/inkstitch#416]
I have a feature request. When I by alphabets online I get an extra file for each letter. I would like to have the possibility to, for example copy those files to a folder structure and then be able to just write my text to inkstitch and inkstitch copies the right letters together.

**Comment by wwderw** [comment]
Are you talking about alphabets or fonts?  Fonts are typically software specific, alphabets are embroidery files that happen to look like letters.

**Comment by SchmetterlingK** [comment]
Oh, than I mean alphabets. Sorry for the misunderstanding.

**Comment by lexelby** [comment]
I'd love that feature!  Unfortunately, it's not as easy as it sounds.  The biggest problem is: how will Ink/Stitch figure out where the baseline of each letter is?  You want to have the bottoms of the letters line up, but a "g" for example should be lined up by the bottom of its main body, not its tail.  There's no good way to do this automatically.

It would be fairly easy (if tedious) to build an Ink/Stitch font from an alphabet that you purchase.  I haven't written instructions on how to create Ink/Stitch fonts yet because the Lettering capability is still quite new.  The short of it is that you use Inkscape's built-in Typography extensions as their instructions indicate, except you skip the part at the end about converting to an SVG font.  For each letter, you'd use File -> Import to import the design file from the alphabet (DST, PES, or whatever format it's in).  Import can read those files directly using Ink/Stitch.

Not easy to do, but hopefully in the future we'll make a video tutorial to make the process more clear.

Thanks for using Ink/Stitch!

**Comment by wwderw** [comment]
Alphabet's also have the size consideration (typically why one gets a couple of different sizes) since they are still raw stitch files.

I don't know of any commercial program that does this well at all.  None of them (to my knowledge) make it to where alphabets could be used as a keyboard font.

It's all manual kerning/sequencing with an alphabet.

When a file is exported as a DST (or other stitch format) a lot of things are set in stone (sequencing and size especially).  Very similar to a raster file compared to a vector file.

**Comment by lexelby** [comment]
Yup, exactly.  The process I suggested above would effectively be adding back in all the stuff to make an alphabet into a true font -- alignment, kerning, etc. 

 It wouldn't really work though, now that I think about it, because as you pointed out, the sequencing would still be set in stone.  It wouldn't be possible for auto-satin to do its thing.

**Comment by jameskolme** [comment]
So there is tool for making these complicated files, but why there are four files?
![font](https://user-images.githubusercontent.com/44113605/54834909-c9d7a080-4cc9-11e9-9117-8107bb2bae62.png)

Will it work, if I just overwrite those files with my own similarly made files? No, I get possible longest error ever starting with thread -1....

**Comment by lexelby** [comment]
@jameskolme The four files are used for lettering in different directions.  The arrow points in the direction of stitching, so for example `→.svg` is used for left-to-right text.  The idea with naming the files this way is that they're more likely to be recognized than "left_to_right.svg" by folks that don't speak English.

Why do we need different files for different directions?  The Lettering extension uses Auto-Satin with "preserve order" enabled.  That's so that a font designer can make sure that the crossbar of an "H" stitches last, for example.  It's not ideal to have four files, but I couldn't come up with a better way to do it.

Yes, you can just overwrite those files with your own, although it might be better to create your own directory.  I'm hoping to add font selection support in soon.

I'd love to see that long error you get... Perhaps upload it as a txt file?

**Comment by jameskolme** [comment]
That makes sense and I just made last effort to find what was wrong. Problem was, letter shape was on sub layer, that is not allowed. I can now fluently type any letter that is  A :) Have to be careful when copying more. 

I need second opinion on this, but it should be ok to digitize and share OFL licensed font? The Open Font License is a free software license, and as such permits the fonts to be used, modified, and distributed freely (so long as the resulting fonts remain under the Open Font License).
https://en.wikipedia.org/wiki/SIL_Open_Font_License
Not sure what other licenses allow to do this, many cases tracing or modifying is not allowed at all. 

I´m thinking small Inkstitch font library some day.

**Comment by lexelby** [comment]
Oh yes, using an OFL font as a starting point should be just fine.  I released the built-in font under the OFL, in fact.

I'm thinking about making a font based on Hershey text if its license allows.

**Comment by jameskolme** [comment]
Nearly done, this is slightly booring... 
www.free-fonts-download.com/Script/tt-masters-font
![TT_MASTERS](https://user-images.githubusercontent.com/44113605/54948289-f21f0380-4f44-11e9-8814-42d2dc3d8e1d.png)

Center line underlay is only on first half of T, accidentally put contour on every letter.

**Comment by lexelby** [comment]
Cool!  Yeah, it can definitely be a bit tedious.  I'm pretty sure designing normal computer fonts is, too. :)

> Center line underlay is only on first half of T,

You sure?  It could just be travel stitch from the Auto-Route Satin that Lettering does behind the scenes.

**Comment by lexelby** [comment]
@jameskolme It would actually be useful to me to have a second font to work with as I work on font selection for #399.  Could you push a branch with your font in it?  I'll go ahead and grant you push access now.

**Comment by jameskolme** [comment]
>  Could you push a branch with your font in it?

Yes, but not sure what to do?

**Comment by jameskolme** [comment]
Something interesting happened (S), first image is preview from lettering tool
![asd1](https://user-images.githubusercontent.com/44113605/55071788-3b309e00-5092-11e9-98a0-eb1efc581f71.png)

After apply and preview again
![asd2](https://user-images.githubusercontent.com/44113605/55071794-3ec42500-5092-11e9-8960-b716497dbf49.png)

But no errors.

**Comment by jameskolme** [comment]
What about another font type?
![TT_DIRECTORS](https://user-images.githubusercontent.com/44113605/55151669-6e893080-5157-11e9-80f9-f94e48a8fc21.png)

**Comment by jameskolme** [comment]
Just one letter more...
![rounded](https://user-images.githubusercontent.com/44113605/55277609-f4011200-530a-11e9-83af-2aa37c9a64e1.png)

**Comment by lexelby** [comment]
> Yes, but not sure what to do?

Oh right, I forget that not everyone here knows Git. :)

You can do everything from the web interface:

1. Go to the main Ink/Stitch repository: https://github.com/inkstitch/inkstitch
2. Click the Branch dropdown.
3. Enter a new branch name, `jameskolme/fonts`, to create a new branch.
4. Your new branch should now be selected.
5. Click "Upload Files".
6. Select or drag-and-drop the files.
7. Enter a short commit name ("add James's cool font")
8. Select "commit directly to jameskolme/fonts"

Once you do that, I'll merge your branch into my branch for #399 and we'll be good to go :)

**Comment by lexelby** [comment]
> Something interesting happened (S),

Wow, I have no idea what happened there.  Did you ever see that again?

**Comment by jameskolme** [comment]
Yes, that interesting thing should pop up every time SD is written. Now I did some Git upload thingy, hope it is where it should be.

There are few things wrong that I know:
Directional files are currently same file, reason being minor tweaks are needed. Sometimes auto satin rungs cross three lines and that's no good. This happens mainly when shape gets close and rung end cross third line. 

Font.json can´t be changed at all, so currently I have to use small font .json file.

> 
> Exception in thread Thread-1:
> 
> Traceback (most recent call last):
> 
>   File "threading.py", line 801, in __bootstrap_inner
> 
>   File "lib\gui\simulator.py", line 699, in run
> 
>   File "lib\gui\simulator.py", line 702, in update_patches
> 
>   File "lib\extensions\lettering.py", line 93, in generate_patches
> 
>   File "lib\lettering\font.py", line 46, in __init__
> 
>   File "lib\lettering\font.py", line 53, in _load_metadata
> 
>   File "json\__init__.py", line 291, in load
> 
>   File "json\__init__.py", line 339, in loads
> 
>   File "json\decoder.py", line 364, in decode
> 
>   File "json\decoder.py", line 382, in raw_decode
> 
> ValueError: No JSON object could be decoded
> 
> 
> 
> Traceback (most recent call last):
> 
>   File "lib\extensions\lettering.py", line 48, in <lambda>
> 
>   File "lib\extensions\lettering.py", line 87, in on_change
> 
>   File "lib\gui\simulator.py", line 691, in update
> 
>   File "threading.py", line 730, in start
> 
> RuntimeError: threads can only be started once
> 
> Traceback (most recent call last):
> 
>   File "lib\extensions\lettering.py", line 48, in <lambda>
> 
>   File "lib\extensions\lettering.py", line 87, in on_change
> 
>   File "lib\gui\simulator.py", line 691, in update
> 
>   File "threading.py", line 730, in start
> 
> RuntimeError: threads can only be started once
> 
> Traceback (most recent call last):
> 
>   File "lib\extensions\lettering.py", line 134, in apply
> 
>   File "lib\extensions\lettering.py", line 93, in generate_patches
> 
>   File "lib\lettering\font.py", line 46, in __init__
> 
>   File "lib\lettering\font.py", line 53, in _load_metadata
> 
>   File "json\__init__.py", line 291, in load
> 
>   File "json\__init__.py", line 339, in loads
> 
>   File "json\decoder.py", line 364, in decode
> 
>   File "json\decoder.py", line 382, in raw_decode
> 
> ValueError: No JSON object could be decoded

There are 2 other fonts nearly done.

**Comment by jameskolme** [comment]
Something goes wrong when I do upload, tried to upload masters and directors font, but it seems files get overwritten. Really can´t figure out how to do folder for separate files.

And then I write on wrong place... DOH!

**Comment by lexelby** [comment]
I see them!  Here are your commits: https://github.com/inkstitch/inkstitch/commits/jameskolme/fonts

It looks like the files went in the main directory rather than the fonts directory, but that's okay, I can work with that.  I'll add them to #399 when I get a chance.

Thank you!!  It will be really great to have more than just my little font :)

**Comment by lexelby** [comment]
I don't really know how you're supposed to make a directory using the GitHub web UI.  I guess maybe when you upload a file, you set the name as "fonts/tt-director/README_en.md" or something?  No idea.  Anyway, I can pull the files out of the commit history, so it's fine as it is.

**Comment by lexelby** [comment]
Oh no, I didn't realize that TT Masters and TT Directors weren't free fonts. :( I don't think we can include your versions of them in the project.

**Comment by jameskolme** [comment]
Directors and Masters fonts are under Public domain / GPL / OFL I decided to go with these, because 
https://en.wikipedia.org/wiki/SIL_Open_Font_License says:

> 
> Terms
> The Open Font License is a free software license, and as such permits the fonts to be used, modified, and distributed freely (so long as the resulting fonts remain under the Open Font License). However, the copyright holder may declare the font's name as being a "Reserved Font Name", which modified versions then cannot bear (this includes subsetting for web fonts). The License permits covered fonts to be freely embedded in documents under any terms, but it requires that fonts be packaged with software if they are sold. Open-source fonts are a popular choice among designers. Most open-source fonts utilize the Open Font License (or OFL) by SIL international. The only stipulation is that anyone cannot charge others to use them.
> 
> Intention
> The intent is to keep people from making money by simply redistributing the fonts. The only people who ought to profit directly from the fonts should be the original authors, and those authors have kindly given up potential direct income to distribute their fonts under the OFL. 

I understand if this is still no go, with licenses, things get complicated and need to approach delicately to avoid possible back fire effect.

Third font what is under making, need extensive test sewing, it is "100% free". http://www.free-fonts-download.com/basic/rounded-elegance-font I´m thinking should this be used, because 100% free is not license at all. 

What we need is some sort of simple rules, what is ok with font licenses.

**Comment by lexelby** [comment]
Oh!  OFL is perfect, it's exactly what we need.  I was confused because they do also sell a version of those fonts, and I missed that there were OFL versions.  Yay!

As for rules, OFL is perfect.  Any other free license that allows modification and distribution should be fine.

**Comment by kaalleen** [comment]
Closing in favor of #586
Font making editor is planed, but may take a long while until realized.
