### ISSUE TITLE
Use Inkscape language

### ISSUE THREAD

**Issue by Katee** [inkstitch/inkstitch#433]
Currently I need to select a language every time I want to use an Ink/Stitch command:
<img width="296" alt="Selecting a language in the InkStitch Extension menu" src="https://user-images.githubusercontent.com/80069/56082803-376b7e00-5deb-11e9-9eb1-e076353f706a.PNG">

Inkscape has a language setting in the perferences. Can Ink/Stitch use that language selected for Inkscape instead of making the user select it for every command?

**Comment by tyrosinase** [comment]
I keep wondering about this too.

At minimum it would be nice if all the languages had the same menu order. Right now Sticken, for instance is at the end of Deutsch but Embroider is second in English and Broder is first in Français, so if I get the wrong flyout I either have to back up, or I have to take a moment to mentally translate. It's not awful, but it's a little burr in the otherwise-habitual process.

Not having that little menu selection at all would be even smoother though.

**Comment by jameskolme** [comment]
I would recommend to place keyboard shortcuts, at least for params. I did build quick access buttons for key features and Inkstitch is working now reasonable fast and smooth.  New idea using electron for GUI can help with languages too.

**Comment by lexelby** [comment]
Thanks for sharing your user experience, @Katee, and welcome to our community!  I would love to make the menus more sensible.  It's definitely not ideal the way it is now.

As you folks may have guessed, there are some constraints at play here.  Inkscape does have the ability for extensions to be translated into the user's language, but only for extensions bundled with Inkscape itself (which Ink/Stitch is not).  Instead, we had to settle for bundling all translations of the extensions, separated out into menus by language.  Definitely not great.

James's suggestion of using keyboard shortcuts is a good one and it's what I do.  Another option is to delete the `*.inx` files for the languages you're not interested in and restart Inkscape.  That does mean you'd still have an extra level of menus.  You'd also have to delete them every time you upgrade Ink/Stitch.

I'm hoping at some point that we can put together a proper installer.  Perhaps it could look at your system's local language and tailor the `*.inx` files accordingly.

> At minimum it would be nice if all the languages had the same menu order. 

Unfortunately, Inkscape sorts menus lexicographically, and we don't get to change that :(

**Comment by Katee** [comment]
Thanks @lexelby. How about a different packaged version of Ink/Stitch for each supported language? The `*.inx` generation, and packaging step in the Makefile appear straight-forward. I'm happy to contribute this change if it would be accepted.

I didn't see a repository for the website. However, that would also need some updated instructions for installation and the manual setup / developer documentation.

**Comment by kaalleen** [comment]
> I didn't see a repository for the website. However, that would also need some updated instructions for installation and the manual setup / developer documentation.

You can find the website in the [gh-pages-branch](https://github.com/inkstitch/inkstitch/tree/gh-pages) of the Ink/Stitch repository. You are most welcome to contribute here. If you have any questions, don't hesitate asking.

**Comment by lexelby** [comment]
> Thanks @lexelby. How about a different packaged version of Ink/Stitch for each supported language? The *.inx generation, and packaging step in the Makefile appear straight-forward. I'm happy to contribute this change if it would be accepted.

That would work!  I think the idea has been floated before but I kind of wondered about uploading 12+ release files for each version of Ink/Stitch.  But GitHub hasn't complained at us yet for the size of our releases, so I see no reason not to do this.  You're right that it would be a huge improvement.

A PR would most definitely be welcome!  I've granted you write access to this repo so that you can push a branch.  Every time you push to a branch, Travis CI automatically builds a development version [here](https://travis-ci.org/inkstitch/inkstitch) and posts it as a pre-release on GitHub, so you can test out your changes before we merge them.  Let us know if you run into any trouble.

**Comment by Katee** [comment]
Thanks for the pointer @kaalleen. I've opened a PR with some website changes.

**Comment by Katee** [comment]
I merged #438, which updated the website. This was premature, as a version with the locale changes has not yet been tagged as a non development release.

**Comment by lexelby** [comment]
Oops, that's my mistake!  I forgot to cut a release.  The way I've been doing it is to create an empty commit on master and git-tag it with v1.##.##.  When you push the tag, .travis.yml notices and tags an official release as opposed to a pre-release.  I'll do that right now.

I should note, I have no particular qualms with folks other than me tagging releases like that, after all we can always correct things after the fact. :)

**Comment by lexelby** [comment]
I went ahead and called this v1.24.0 to make it easier to reference it in the documentation if we need to (along the lines of "since 1.24.0, you'll need to download the ZIP corresponding to your language" or somesuch).
