### ISSUE TITLE
support duplicated objects

### ISSUE THREAD

**Issue by DreadKnight** [inkstitch/inkstitch#436]
Sometimes when my embroidery design can be fitted several times on my hoop, I tend to create a production file, where I duplicate around my design. The problem is that the (linked) duplicates don't show up in Inkstitch's preview, nor they work, which makes having to edit the original design and duplicate / move / unlink for each a total nightmare. Inkstitch should be able to stitch duplicates as well!

**Comment by jameskolme** [comment]
Not fully understand this linked part, but trims most likely "fly away" if duplicate is made. Noticed I have accidentally avoided this problem. Usually I made just one for test/tweak and when it sews out nicely, then I duplicate design inside machine and save.   

I think this would be something that should be on Inkstitch export function (someday). When exporting, first selecting hoop size, how many splits x and y direction and then Inkstitch centers design on every square. Only one actual design is needed, so making tweaks is easy and no need for linking.

**Comment by wwderw** [comment]
I've always done this at the machine itself (of course, this would depend on the abilities of the machine in question), if there is a need to use a single design for multiple copies once in a blue moon.  That way there is no chance of any loss of functions (trims, stops, slow/fast etc)

If the need of having a highly production worthy multi-design file (for instance for patches), it's actually best to do a section (before any functions are coded), copy that section and place that section in the desired new location(s).  This would cut down on color changes (which take up about as much of as a trim, which varies depending on machine) when doing one design in full at a time.

I don't know of any software that would make a multi design up really set up for true production as an auto configuration.  There are some things that would still have to have user input.

**Comment by lexelby** [comment]
Ah yes, this is the thing I was talking about in #378 when I mentioned the `<svg:use>` tag. For the sake of completeness, it would probably be a good idea for Ink/Stitch to support linked duplicates.

**Comment by tyrosinase** [comment]
Are we talking about cloned objects here? Because I've finally busted out the 5x12 multi-attachment-point hoop and being able to embroider cloned objects would be extremely useful. (I'm drawing out a big design, then breaking it into 5x7 chunks. The hoop has attachment points 6cm apart, so I duplicate the righthand half, move it to another layer, and shift it left. Then I hide that layer, create an embroidery file, then swap the hiding and create a second file. Embroider the first, shift the hoop, embroider the second, and boom, I can put off buying that MC1500e (😍 but  💸) a little while longer.

Being able to leave the duplicate as a clone so I can edit the original would be pretty useful. Even better if they can have separate stitching parameters (so the one off in the distance can have stitch-repeat-zero), but that's not strictly necessary (they can always live on a layer that I hide).

Alternately, fixing the issue that a 5x7 design that's not literally in 0-5x by 0-7y creates a weird PES file would mean I could hide the lefthand side and generate the righthand half in place without duplicating/cloning anything.

**Comment by kaalleen** [comment]
Ok, I originally wanted to do something else today, but since I had contact with those clones in the troubleshoot branch (#525), I had a look into it. Clones should be part of the stitchplan soon. You can test it [here](https://github.com/inkstitch/inkstitch/releases/tag/dev-build-troubleshoot-inkscape-objects). They can have their individual params too.

The build failed for linux though, windows worked out and macOS is not done yet.
Aw, travis is having some issues latey.
