### ISSUE TITLE
Wonky Results

### ISSUE THREAD

**Issue by HoneyPhantomhive** [inkstitch/inkstitch#453]
I have consistently had issues with the finished product of multi-colored projects. The file attached was stopped halfway through because it really wasn’t looking so hot. You can still see the black/brown through the stitches, meaning i’m doing something in the settings wrong. The running stitch is almost always out of alignment with the original shape, and the shapes shift slightly so they aren’t in the right place relative to the other shapes. What can I do to fix this?

**Comment by HoneyPhantomhive** [comment]
![IMG_5006](https://user-images.githubusercontent.com/45114379/57181720-d4568f80-6e5c-11e9-8848-bcdb9cb0c3b5.JPG)

**Comment by tyrosinase** [comment]
If you're doing a lighter color over a darker (stitching or ground), you almost always need to turn on understitching. If the ground is shifting, try a heavier stabilizer (adding a top stabilizer will help keep the stitching smoother, which helps with coverage too). And using the newest Inkstitch (which will path through the shape instead of an outer running stitch) will also help conceal any shifting that does happen.

Depending on your thread, you might want to increase stitch density, but I have yet to run into a case where understitching didn't do the trick.

You can see the difference in this design where the understitching on the upper body got dropped somehow. You can see the difference between those colors and the fins, which are the same stitch density, same brand of thread, same stabilizer: (
![IMG_1738](https://user-images.githubusercontent.com/9473609/57182283-5948a580-6e6b-11e9-9e42-405a365aaef0.JPG)

**Comment by lexelby** [comment]
@tyrosinase is right on.  Here's a great article about underlay: https://www.mrxstitch.com/underlay/

I only disable fill underlay on the rarest of circumstances.

You're probably also experiencing distortion: https://www.mrxstitch.com/pull-distortion/

Distortion is not something you're ever going to get away from, although stabilizer will help.  Having two fills right against each other can make distortion especially obvious.  I sometimes hide it by doing a satin between them.

I hope that helps, and thanks for using Ink/Stitch!

**Comment by tyrosinase** [comment]
On that note... why isn't fill underlay the default?

**Comment by lexelby** [comment]
Good question!

**Comment by lexelby** [comment]
Feel free to create a PR, or I'll do it next time I'm near a computer.

**Comment by wwderw** [comment]
Bare in mind as well, stitch angle of the fill on certain substrates can also create push/pull issues.  "Spooning" is perhaps the most common issue when one has the stitch angle of a fill that coincides with the angle of the weave of the substrate.

There are times, even when doing multi-color designs that you don't want to have an underlay (either with fills or with satin stitching) and more often then not, it's the size of the individual objects being digitized.  Other situation could be when doing blends, having an underlay (other then trapunto) can kill the effect of the blend.

As far as underlays being default, what I tend to make heavy use of presets for my more common setting needs.

**Comment by lexelby** [comment]
I'm going to close this now and add a feature request, "enable fill underlay by default".
