### ISSUE TITLE
Custom Satin Columns-Stopped working

### ISSUE THREAD

**Issue by tangerinepiggy** [inkstitch/inkstitch#459]
Hi I was working on digitizing a font for use when I stopped being able to make satin columns.  Even with two lines side by side I get the following error.  I tried uninstalling and reinstalling Inkscape and Inkstitch and the problem persists.
Traceback (most recent call last):

  File "inkstitch.py", line 44, in <module>

    print >> sys.stderr, traceback.format_exc()

  File "inkscape\share\extensions\inkex.py", line 283, in affect

  File "lib\extensions\simulate.py", line 17, in effect

  File "lib\extensions\base.py", line 181, in elements_to_patches

  File "lib\elements\element.py", line 268, in embroider

  File "lib\elements\satin_column.py", line 772, in to_patches

  File "lib\elements\satin_column.py", line 328, in validate_satin_column

IndexError: list index out of range

**Comment by lexelby** [comment]
Hi there, welcome to the project, and thanks for using Ink/Stitch!  I'm afraid you've run into a bug we know about and have yet to fix.  It's the same issue as in #366.  The situation is that your lines aren't quite set up correctly to do satin, but Ink/Stitch is crashing instead of showing you a helpful explanatory message.

Here's how to fix your satin columns.  Having two lines side by side like you've done is the first step.  Importantly, you also need to select both lines and link them together so they're part of the same shape.  Do that with Path -> Combine (usually ctrl+k).  Once you do that, then you can use the Params extension to enable "custom satin column" and you should be good to go.

I hope that helps, and if you're still stuck, please reply back and we'll get you unstuck!

**Comment by tangerinepiggy** [comment]
Thanks that was it.  I feel silly now.  I had been working along fine for hours and then forgot to combine the lines.  I appreciate your friendly and patient response.

**Comment by lexelby** [comment]
No problem.  If Ink/Stitch makes you feel silly, then I want to fix it!

**Comment by lexelby** [comment]
I'm going to close this issue in favor of #366, but please don't hesitate to reopen this or open a new issue if you think I might have missed something.
