### ISSUE TITLE
This extension is not working properly 

### ISSUE THREAD

**Issue by fnavas00** [inkstitch/inkstitch#461]
Id really like to be able to use this program and I have watched the ALL the youtube tutorials on this but Im still lost. I created artwork on GIMP seperated the colors for the artwork, created paths from the shape outline... exported paths and imported them into Inkscape.. put paths on top of each other and aligned them to make the art. Then I changed colors to embroidex colors filled path/shape with color I want for the artwork. Since the shape of the artwork is complex I seperated them into smaller objects. I them clicked params for each object and put all default settings for Autofill with autofill underlay by default there is a satin stitch or stroke outline of path. I tried to find a way to remove this since I only want to do fill for shapes but I keep getting error messages telling me "satin column: object %s has a fill (but should not)" I DONT WANT SATIN COLUMN! I only want fill for the shapes but I keep getting error messages, error messages, error messages, what am i doing wrong

I posted a question like this with a person telling me to remove the fill.. then im left with only the outline of the shapes and this error message:

Traceback (most recent call last):
  File "inkstitch.py", line 54, in <module>
    stderr = stderr.strip()
  File "inkscape/share/extensions/inkex.py", line 283, in affect
  File "lib/extensions/simulate.py", line 17, in effect
  File "lib/extensions/base.py", line 181, in elements_to_patches
  File "lib/elements/element.py", line 268, in embroider
  File "lib/elements/satin_column.py", line 772, in to_patches
  File "lib/elements/satin_column.py", line 328, in validate_satin_column
IndexError: list index out of range 

This is literally the most difficult program to learn to use... even making CGI is easier than using this extension

**Comment by lexelby** [comment]
I'm sorry you're having trouble!  I place a high value on the user experience, and I know Ink/Stitch is still lacking in a lot of areas.  The learning curve is big, and I want to improve that.  Thank you for asking for help here rather than moving on to another program, we really appreciate hearing from you.

What you're describing above is actually two bugs we're tracking that I hope to fix soon.  If you _ever_ see a traceback, that's a bug, not a mistake on your part!  It should never happen and we want to fix it if it does.
