### ISSUE TITLE
Command connectors move only to center of object

### ISSUE THREAD

**Issue by fnavas00** [inkstitch/inkstitch#462]
I am not sure what I am doing wrong whenever I try to add command attachments to my object the command connectors keep moving towards the center of artwork even when I try moving it to a node it will just make the connector larger and go right back to the center of the object.

**Comment by lexelby** [comment]
Yes, I'm afraid this is just how command connectors work. :(  This is because of how we're "repurposing" Inkscape's flow-chart tools for the "attach commands" functionality.  It's not ideal, and I'd love to hear if you have any ideas for how to make the user experience better.  One thing to note is that we have to work with Inkscape as it is, rather than modifying it.
