### ISSUE TITLE
fill shape parser ignores first point

### ISSUE THREAD

**Issue by pneumaticdeath** [inkstitch/inkstitch#469]
When I ttry to simulate a large complex SVG, one subcomponent doesn't render properly in the simulation.  

This is a PNG of the original SVG
![Logo_draw4](https://user-images.githubusercontent.com/569440/58498274-93d3f400-8132-11e9-9a6b-6658832b6caa.png)
Take note of the red phone in the lower right corner... that's what doesn't render correctly.  When I simulate that subcomponent it looks like:
![Screenshot from 2019-05-28 10-11-42](https://user-images.githubusercontent.com/569440/58498380-cc73cd80-8132-11e9-8536-2631501cc174.png)
The rest of it seems to come out correctly:
![Screenshot at 2019-05-28 10-03-50](https://user-images.githubusercontent.com/569440/58498552-207eb200-8133-11e9-96ff-975c840fdc66.png)

**Comment by jameskolme** [comment]
Hello, can you upload file?  So I can give it try to fix it.

**Comment by pneumaticdeath** [comment]
I can't seem to get github to accept svg files for upload.
I uploaded it to the website:  https://dial-a-grue.com/Logo_draw5.svg

**Comment by jameskolme** [comment]
Phone is definitely broken,  exploding phone graphic and add stroke to it: 
![phone1](https://user-images.githubusercontent.com/44113605/58594073-5b88fe80-8275-11e9-9fd0-18662717b82f.png)

Few important segments between nodes are missing and end result is: 
 ![phone2](https://user-images.githubusercontent.com/44113605/58594121-7ce9ea80-8275-11e9-90c3-01b57dfe116f.png)

Some node tools and few segments later:
![phone3](https://user-images.githubusercontent.com/44113605/58594317-e669f900-8275-11e9-9747-a3b063786b09.png)
Fill shape must be closed to perform correctly

Remove stroke and simulation works fine:
![phone4](https://user-images.githubusercontent.com/44113605/58594417-3c3ea100-8276-11e9-9be1-38f91dd0a22c.png)

**Comment by pneumaticdeath** [comment]
Hmm... I thought the SVG spec included something that said any filled shape is implicitly closed, rather than requiring that it be explicitly closed.  Still I can fix that.  Thanks!

**Comment by lexelby** [comment]
> Hmm... I thought the SVG spec included something that said any filled shape is implicitly closed, rather than requiring that it be explicitly closed. Still I can fix that. Thanks!

This is a case of me not knowing the SVG spec rather than you being in error. ;)  I'm reopening this and marking it as a bug so we can fix it.  Ink/Stitch should definitely treat unclosed fill shapes correctly as per the SVG spec.

**Comment by lexelby** [comment]
I was wrong!  Ink/Stitch was already properly handling unclosed fill shapes.

This turns out to be an extremely old bug that's been in Ink/Stitch since the very beginning.  The code involved is one of the very few lines that I have not rewritten since the original inkscape-embroidery code.  And sure enough, that old code has a bug that causes it to ignore the very first point in every fill shape.

Usually we don't notice this.  The points in question are after Ink/Stitch has already internally converted bezier curves to a series of tiny line-segments.  Missing one usually isn't noticeable.  When the first part of your shape is a straight (or mostly-straight) line, it's very noticeable, like with your phone.

Now that I know what's wrong, I'll get a fix out asap.
