### ISSUE TITLE
additional jump stitches in imported files

### ISSUE THREAD

**Issue by kaalleen** [inkstitch/inkstitch#486]
A german discussion board brought an issue to my attention, which I am very curious about. I am not aware if this was a topic before, so I wanted to bring this discussion to GitHub.

The user would expect two identical files after the following operation:
* open an existing (bought) embroidery file with Ink/Stitch
* without any modifications save the embroidery file

But in fact the result isn't identical. Ink/Stitch adds jump stitches between the color blocks (which weren't there before). A user of the before mentioned discussion board had actually to struggle with this behaviour. Some of these jump stitches where long and they caused bird nests during the embroidery process. (The first stitch wouldn't stay in place and the long loose ends caused all the struggle). I tested it too, without bird nests, but the additional jump stitches felt unnecessary and the orginal file didn't have them at all.

I had a look at stitch_plan.py (function: patches_to_stitch_plan) and it reads: "adds jump-stitches between patches if necessary".

From the code I assume, that these jump stitches between the color blocks have a purpose or am I looking at the wrong bit of code - because the jump stitches do not disappear if I comment it out?!

I also tested the issue with the "embroider" function:
* export two little paths (e.g. squares) with a different color
  - the stitch plan doesn't show the jump stitches
* open the so created file:
  - jump stitches are present
  - they can also be found in an exported csv debug file
  - but they are missing in the svg debug file

There is an other issue which I couldn't test myself. The user reported, that Ink/Stitch also wouldn't respect the trim commands from the original file. If this information is of any help the file format mentioned was jef. But maybe she will test this issue again, when the jump stitch issue has a solution.

**Comment by lexelby** [comment]
Thank you for documenting this in detail!  I've seen this too, and I kept meaning to dig deeper and never got around to it.

I think the problem is in `lib/extensions/input.py`.  The algorithm there is really rather rudimentary, and it's probably to blame for the extra jump stitches.

The fact is, when I wrote that, I was really just trying to get a proof-of-concept implemented as quickly as possible.  I didn't really expect it to be used as a way to fully round-trip a design (￼export as JEF then import).  I mostly wanted the input functionality so that I could bring in a design I'd purchased and modify it, so I didn't mind deleting the extraneous jumps.  The same logic led me not to bother importing trims.

I think with a little work, we should be able to fix up both of these issues.  We can just add trim commands where they should be.  I'm not sure if we'll ever get to perfect round-tripping (read JEF -> export JEF results in the exact same file) but I bet we can get close enough.
