### ISSUE TITLE
Extension to point out where stitches are too close or too many

### ISSUE THREAD

**Issue by MatsIBengtsson** [inkstitch/inkstitch#498]
When buying patterns, you seem to get predefined paths. Some of these may stitch very close. Sometimes too close. For some others, when you shrink them to fit where you want them, they stitch too close.

It would be good to get to know this before your embroidery has gone bad. It does not need to be fixed, it is a good help just to get to know where the risk is high.

Preferably, some predefined setting of minimum stitch length, and of maximum number of "re-entries" within such length. Since it depends on the thread and the fabric, the setting should be adjustable.

If this already exist, I have not been able to find it in the documentation. If it does, please point me to it. I believe I can measure stitch distance in inkscape, but it is too cumbersome.

--- Mats ---

**Comment by wwderw** [comment]
Alot of this comes from experience more then anything else.  As far as identifying trouble areas.

As far as editing bought files, in general, that's always going to be tedious and stitch by stitch.  With resizing raw stitch files (DST, PES etc), it's best not to scale more then 5% of the original size, either up or down.  While some can handle more, some can handle less (depends on the design).  Depending on which way you scale, you can either get stitch lengths really wide or stitches that jack hammer in a single place being too small.

**Comment by tyrosinase** [comment]
On 7/24/19 1:49 PM, wwderw wrote:
> As far as editing bought files, in general, that's always going to be
> tedious and stitch by stitch. With resizing raw stitch files (DST, PES
> etc), it's best not to scale more then 5% of the original size, either
> up or down. While some can handle more, some can handle less (depends
> on the design). Depending on which way you scale, you can either get
> stitch lengths really wide or stitches that jack hammer in a single
> place being too small.


I've had wonderful results on linear designs importing the PES shape,
resizing it, and letting Ink/Stitch stitch it out as though it was a
(very node-y!) line I had drawn from scratch in Inkscape. Doesn't work
for fills, obviously (although setting the stroke settings to a nice
thread-like width and then doing a stroke-to-path and then some
judicious combines can go a long way toward converting those).

**Comment by MatsIBengtsson** [comment]
> Alot of this comes from experience more then anything else. As far as identifying trouble areas.
> 
> .
> .
> .
Thank you for reply. Yes, I am sure it does. But that is where good functions in programs can help to make the learning easier, even guided, by pointing out some specific issues, like needle points being to close, instead of forcing you to experience the issue in practice.

I notice for example that the free Wilcom truesizer gives you a view of all needle points, tells you of the shortest distance between them, and by default, when converting, removes all which are below a threshold (the last is not part of my suggestion, but may be part of machine specifications).

In the file I already sent up in the separate issue on trims in vp3 files, you can notice that happening. In the file created through Ink/Stitch, there are needle points as close as 0.1 mm. In the file converted by truesizer, the closest point is 0.2 mm. 

Without the added function I am suggesting, it is hard finding those points using Ink/Stitch unless you already know where to look. As a beginner, you will likely not even look for them. Thus the idea of an improved functionality having a warning.

--- Mats ---

**Comment by wwderw** [comment]
>I notice for example that the free Wilcom truesizer gives you a view of all needle points, tells you of the shortest distance between them, and by default, when converting, removes all which are below a threshold (the last is not part of my suggestion, but may be part of machine specifications).

That middle section (tells you the distance) and the removal of the offending stitches is apart of the same functionality, "small stitch filter".

Which the distance is user configurable (in the digitizing versions, not in TruSizer, at least I don't know of the option in the freebie), if one set's that too high, it can actually remove tie in and tie off stitches.

> Without the added function I am suggesting, it is hard finding those points using Ink/Stitch unless you already know where to look. As a beginner, you will likely not even look for them

There would be another issue that could benefit from this and that's when digitizing for puff, in certain areas (that wouldn't be picked up in the Wilcom functionality unless that stitch removal was set very, very high and that would cause other issues) will have regular and shortened stitches (rounding corners especially, but not all corners, depends on size and angle of the stitch width) which are desirable in regular embroidery, but not so much in puff embroidery.

I don't know since stitches aren't technically generated while digitizing in Ink/Stitch.  One would have to bring in the stitch file back into Inkscape and run another extension to highly those areas (unless maybe Inkscape has a node selection (which would be needle penetrations in embroidery files brought into Inkscape) by distance functionality?)  Maybe able to have different options in that extension to highly different areas that could be of concern depending on the application of the file.

**Comment by MatsIBengtsson** [comment]
> That middle section (tells you the distance) and the removal of the offending stitches is apart of the same functionality, "small stitch filter".
> 
> Which the distance is user configurable (in the digitizing versions, not in TruSizer, at least I don't know of the option in the freebie), if one set's that too high, it can actually remove tie in and tie off stitches.
> 
> > Without the added function I am suggesting, it is hard finding those points using Ink/Stitch unless you already know where to look. As a beginner, you will likely not even look for them
> 
> There would be another issue that could benefit from this and that's when digitizing for puff, in certain areas (that wouldn't be picked up in the Wilcom functionality unless that stitch removal was set very, very high and that would cause other issues) will have regular and shortened stitches (rounding corners especially, but not all corners, depends on size and angle of the stitch width) which are desirable in regular embroidery, but not so much in puff embroidery.
> 
> I don't know since stitches aren't technically generated while digitizing in Ink/Stitch. One would have to bring in the stitch file back into Inkscape and run another extension to highly those areas (unless maybe Inkscape has a node selection (which would be needle penetrations in embroidery files brought into Inkscape) by distance functionality?) Maybe able to have different options in that extension to highly different areas that could be of concern depending on the application of the file.

Interesting thoughts and info, thanks again. You seem to know a lot, even of the big programs. I did find something about a stitch list in Wilcom on-line help. I do not know how Ink/Stitch divide work with inkscape, nor what is doable or easy. But when generating the machine file, the file must be filled with the stitch placements? Is that not a chance to create the stitch list and see how close stitches are?

If this is considered, and you seem to consider it, then a thought regarding how and where to do it: If it is hard to do in inkscape, could it not be a selectable addition of pages in the print output? That output does anyway already have access to the stitch placements?

--- Mats ---

**Comment by wwderw** [comment]
> You seem to know a lot, even of the big programs.

I'm a freelance digitizer by trade and Wilcom EmbroideryStudio for the longest time was my go-to program, having switched to the Linux platform, it was time to seek alternatives that worked natively on what I had installed on bare metal.

> I did find something about a stitch list in Wilcom on-line help.

This is a great tool, I've used it for inserting in slow/fast commands for my Barudan machine to tell the machine to slow down or resume normal speed (fast) hard coded into the design, so I didn't have to babysit the design while it stitched out.

There is something similar in Ink/Stitch, but it's workflow is different.

After you do the digitizing, you would export a CSV version of the file (using the embroider module).  This does present the information in the same way as the Wilcom software, but slightly more verbose compared to Wilcom's Stitch List module.

Now, the main difference between how the 2 programs use this info in that the CSV file is separate of your SVG file, so any changes you make to the CSV file is separate to the SVG.  Likewise, if you were to make any changes to the SVG after having already exported it to the CSV, you would have to re-export to the the newer info.  Changes in the Stitch List in Wilcom are implemented into the file and saved, so your not working in a separate file.

If you make changes to the CSV and you want to use that as your embroidery file, you'll have to use pyeembroidery (back-end engine of Ink/Stitch) to make the conversion directly (I use CLI to do this) and have it convert the CSV file to an embroidery file.

This is a little more "poweruser"-ish compared to how Wilcom has it.  I do use this workflow on occasion as this is the only way for me to insert slow/fast commands and to add in sequins into my designs (some Barudan machine also has a sequin dispenser attached to it).

It really does a good job, but it isn't for the beginner as "you" would have to know what the explicit commands are (simple for slow/fast, now as obvious for sequins).

I would love to see a more interactive stitch list that can be done on the fly.  It's probably not going to be the easiest thing to implement now and I think the next big project on the roadmap (could be wrong) is converting everything to Electon (which means I'm going to have to take some refresher courses on HTML, CSS and JaveScript, about the only stuff I somewhat know and it's been a long time since I've messed with them in a big involved way (to give an idea, it was the early stage of transitioning from CSS1 to CSS2 and it's CSS3 now)).

**Comment by MatsIBengtsson** [comment]
> I'm a freelance digitizer by trade and Wilcom EmbroideryStudio for the longest time was my go-to program, having switched to the Linux platform, it was time to seek alternatives that worked natively on what I had installed on bare metal.

Ok, then it is clear how you know not only the area, but also the tools. Wilcom to me seem to be the best one, yet Ink/Stitch seem to fulfill my needs, although I would really like the stitch warning to be there. It is a good newbie aid.
> This is a great tool, I've used it for inserting in slow/fast commands for my Barudan machine to tell the machine to slow down or resume normal speed (fast) hard coded into the design, so I didn't have to babysit the design while it stitched out.

I see. It can be used for other purposes and automation as well.

> There is something similar in Ink/Stitch, but it's workflow is different.

I tried that out. It produces a file which is readable. The X and Y values are there. So doing the stitch warnings should be doable. Even removing a stitch if the faulty ones come in a row should be doable (but that was not part of my aim). Doing the needle point view to point to dangerous stitches if doing the output in print preview likely is similar to code which already exist for the preview?

Doing the workflow you are after would be much harder, I can see that. But that could be seen as a later phase, where adding the "slow" "fast" could be an easy thing, thus providing the stitch list functionality. Getting them back into workflow could be a later and much bigger task.
>... 
> I think the next big project on the roadmap (could be wrong) is converting everything to Electon 

Would there be a user benefit of using Electron? There must be a reason to wanting to go that path, but at same time you have to remain part of inkscape as well? I struggle to understand what is to be moved and what it will mean for using it. Is there a description somewhere of the plan?

**Comment by wwderw** [comment]
> Wilcom to me seem to be the best one, yet Ink/Stitch seem to fulfill my needs....

Ink/Stitch does allow for users to do all of the semi-manual, manual techniques that Wilcom allows for as well.  It really is a very robust plugin even for those that need/want more advanced features as well.

> Would there be a user benefit of using Electron? There must be a reason to wanting to go that path, but at same time you have to remain part of inkscape as well?

Reasons for moving to Electron:  Handling of the UI, which would lead to a better UX as well.  

Also interoperability among the different platforms (Linux, Windows, Mac etc).  

To give an idea, I don't know how long you've been using Ink/Stitch, but the Print PDF module is already over to Electron.  It used to be in older versions, it would open up in the user's default webbrowser as a new tab.  Which could lead to different output renderings depending on what browser the user had set as default.  On Linux, I use Firefox, in my Windows VMs, I use Vivaldi (which is based off Chromium/Chrome), so they render different, have different options/ability.

Now, since the Print PDF is an Electron, it opens up it's own viewport and everyone is using Chromium to display everything, so there is more consistency for users and the extension itself.

As to staying with Inkscape, don't have to worry about building everything else from the ground up, use what's already there and add on top of that.

**Comment by MatsIBengtsson** [comment]
> Ink/Stitch does allow for users to do all of the semi-manual, manual techniques that Wilcom allows for as well. It really is a very robust plugin even for those that need/want more advanced features as well.

Agree, really glad it exists. It seem a little more suitable for the advanced than the newbies, Wilcom is easier to understand, and has moved some experience into the warnings, like too short stitches and so.
>...  
> Now, since the Print PDF is an Electron, it opens up it's own viewport and everyone is using Chromium to display everything, so there is more consistency for users and the extension itself.
> 
> As to staying with Inkscape, don't have to worry about building everything else from the ground up, use what's already there and add on top of that.

Ok, thanks, then I understand Electron reasons. In meantime, I thought further on the "too close stitches" expansion, current thoughts:

- An additional ink/Stitch command, below Simulate, working in same way, except instead of lines it shows needle points. 
-- Needle points in pink=>below min limit
-- Needle points in red=> in a high density area (like in a CAD program for tension)
-- Needle points in yellow=> somewhat high density, not suitable for all materials

Doing like that allows for a prompt allowing to define min limit, and remain in the interactive part of workflow. Same output can later be used in the print on a new page

On the above new mapping, could later be added a command to show and alter stitches, which is then saved as part of the SVG file, and used to alter final output to embroidery files.

I think it would be usable for those not yet too experienced (me for example). I would learn what to look for...

--- Mats ---

**Comment by lexelby** [comment]
Lots of great discussion here!

This feature is definitely feasible to implement, and it probably wouldn't even be too hard.  It's just down to a question of priorities and available time.

Until then, there are at least a couple of options to get you close.  In the Simulator, you can turn on needle penetration point visualization.  There's a (somewhat poorly-marked) button at the bottom to show dots at each stitch point.  Does that help?

You can also see the needle penetrations in inkscape.  Run the Embroider extension and you'll get a preview of the rendered embroidery design.  Use the Node Editor tool to select a path.  Every node in the path is a needle penetration point.

I believe there's an extension that comes with inkscape that helps visualize path nodes.  You might be able to use that to see dense spots better.  Maybe if you rendered the dots using a semitransparent fill color, the most opaque spots would be the densest.

As to electron, check out this issue for our reasoning: #426

**Comment by MatsIBengtsson** [comment]
> Lots of great discussion here!

Agree, I learned a lot just from the discussion, and got more insight into what I wanted.
> This feature is definitely feasible to implement, and it probably wouldn't even be too hard. It's just down to a question of priorities and available time.

Yes, this is very close to something which already exist in simulator and print. Basically dots instead of lines, and colors depending on an algorithm.
> Until then, there are at least a couple of options to get you close. In the Simulator, you can turn on needle penetration point visualization. There's a (somewhat poorly-marked) button at the bottom to show dots at each stitch point. Does that help?
> 
> You can also see the needle penetrations in inkscape. Run the Embroider extension and you'll get a preview of the rendered embroidery design. Use the Node Editor tool to select a path. Every node in the path is a needle penetration point.

Already tried both of above. The issues:

1. In the simulator, I can see them, but it is not that easy to measure them, thus not that easy to understand which are too close individually, nor which are overloading the fabric or stabilizer by being too many in a certain area.
2. In inkscape I can also see them, I can even measure them. But I have to turn on the nodes to do that. Then I am looking at the details when trying to find out if there is an area I should worry about at all (or I turn on all nodes and then I am too zoomed out and cannot measure with precision). Also, I get x and y values, but am really after distance in total.
3. Both attempts above was done after I had embroidered, and destroyed the fabric I used. I had tried it on a thicker fabric, and there it worked. The pattern was purchased. I then tried a better stabilizer, and finally got it working. Then switched to a nicer thread (shiny) and it broke the thread.

All of this lead me to think I would want to know it in advance, not know it afterwards. When doing the vp3-file, detailing the issue of trim commands, I found out that Wilcom truesizer actually told me when it loaded the file. And I thought that minimum a beginner would benefit if Ink/Stitch provided that information up front. 

As an added side note, I have later seen that when using only defaults, Ink/Stitch does create satin columns where the issue exist, which I as beginner did not expect. So again, a warning system would help a beginner.
> 
> I believe there's an extension that comes with inkscape that helps visualize path nodes. You might be able to use that to see dense spots better. Maybe if you rendered the dots using a semitransparent fill color, the most opaque spots would be the densest.

Possibly. But I would have to know what density I was looking for, that is first knowing what distance I was looking for, and how to scale the size of the circles to provide such coloring. Again, it would help me only if I already know what I would like help of knowing :)

I can find the information in Ink/Stitch. And I can fix it in Ink/Stitch. Already have, for two designs. But I would prefer the warning before the embroidery machines tell me where to look for it .:)

**Comment by wwderw** [comment]
This right here:

> Both attempts above was done after I had embroidered, and destroyed the fabric I used. I had tried it on a thicker fabric, and there it worked. The pattern was purchased. I then tried a better stabilizer, and finally got it working. Then switched to a nicer thread (shiny) and it broke the thread.

Some of it is going to come in from experience, because what would affect some thread or affect some stabilizer, fabric substrates isn't going to be across the board.  Even using the same design just changing up the other variables (stabilizer, substrate type, thread type, speed of machine and even needle used) can affect quality of output and if the thread breaks/bird's nest, breaks a needle etc.  

Despite common practice (even I have a lot of customers that want to do this and I do it with the caveats) of trying to get one file to do it all, it is just going to depend.  Some work, some don't.  One has a better chance if the digitizer knows up front (like wanting a design for hats and for shirts), but stock designs, not so much.  They may work across many substrates, but that isn't a sure thing.

I'm thinking for something like this to truly be effective (especially for beginners) it's going to have to compensate for a lot more variables.  Drop down, select a few items and have it generate (on average) where issues of concern would be using whatever variables that are being used.

Otherwise, a beginner could try to take out density/needle points, but they are using a 60# thread and actually need to put more in.  But that it also depends on the shape of the object(s) to be embroidered.

You said "shiny", I don't know if you just mean polyneon (as that thread has more sheen then rayon, spun cotton etc) or metallic.  If meaning metallic, may have to pull more density out and even change the shape of the smaller points to make it work.  Especially if using a needle with a regular eyelet versus a needle with an eyelet specific for working with metallic thread.

There are quite a few variables that could go into it and sometimes it's even a combination of variables.  I'm sure I'm missing some stuff that could also affect breakages of thread.

I'm thinking though for it to be truly helpful for beginners, it's going to have to compensate for a lot more variables that would otherwise have to be conquered through digitizing, stitching out and correcting accordingly afterwards.

**Comment by MatsIBengtsson** [comment]
> .
> .
> . 
> I'm thinking for something like this to truly be effective (especially for beginners) it's going to have to compensate for a lot more variables. Drop down, select a few items and have it generate (on average) where issues of concern would be using whatever variables that are being used.
> 
> Otherwise, a beginner could try to take out density/needle points, but they are using a 60# thread and actually need to put more in. But that it also depends on the shape of the object(s) to be embroidered.

Good points. I agree. It should be expanded to more points to try to help with the things you otherwise need to spend time to check for, know to check for, or will find out the hard way, and which is easy to do as a function. I do not know those other points. I know too close, and too many. So does other programs. 

You mention thread. As with so much else, I think it is better to start somewhere and get feedback, than not to have anything at all because there could be more to think of. The two ones I suggest are easy to implement, and common. 

If thread size is something well handled by Ink/Stitch already, commonly used by beginners, and easy to do a function for, then there should be a warning for it as well. If not, wait until thread size is a clear part of the workflow or the need is expressed.

> You said "shiny", I don't know if you just mean polyneon (as that thread has more sheen then rayon, spun cotton etc) or metallic. If meaning metallic, may have to pull more density out and even change the shape of the smaller points to make it work. Especially if using a needle with a regular eyelet versus a needle with an eyelet specific for working with metallic thread.

polyneon, not metallic.

**Comment by MatsIBengtsson** [comment]
> ...In meantime, I thought further on the "too close stitches" expansion. Current thoughts:
>
>An additional ink/Stitch command, below Simulate, working in same way, except instead of lines it shows needle points.
>   -- Needle points in pink=>below min limit
>   -- Needle points in red=> in a high density area (like in a CAD program for tension)
>   -- Needle points in yellow=> somewhat high density, not suitable for all materials
> 
> Doing like that allows for a prompt allowing to define min limit, and remain in the interactive part of workflow. Same output can later be used in the print on a new page

Kept thinking about above. Current thoughts, ignoring density plot for now:
- Purple:       <0.15 mm to next needle point
- Light blue: <0.3   mm to next needle point
- Black:         anything else.

Example as per enclosed picture. It is easy to spot areas with too many purple points (the density issue). The stars in left side do have issues when embroidering, so does the eyes. To me it indicates this could be a way to see it before trying.

![Capture needle density](https://user-images.githubusercontent.com/15014932/62012206-7c8da300-b183-11e9-8b6a-50ae0dc492c9.PNG)

**Comment by lexelby** [comment]
Ooh, neat idea!  Did you make that by modifying the Ink/Stitch code?  If you wanted to continue working on this, we'd welcome a PR.  It'd be especially neat if we can make this a gradient of color, rather than just 3 colors (purple, blue, and black).

Why I like this: it's less about "these stitches are too close together" and more like just a density map.  It's still up to the digitizer to understand whether the density will be a problem for their specific situation, but this will still provide useful hints for inexperienced digitizers too.

**Comment by MatsIBengtsson** [comment]
> Ooh, neat idea! Did you make that by modifying the Ink/Stitch code? If you wanted to continue working on this, we'd welcome a PR. It'd be especially neat if we can make this a gradient of color, rather than just 3 colors (purple, blue, and black).

Yes, it is the Ink/Stitch code. I split the simulator.py into three files, a common set of classes, the embroidery simulator (basically now an almost empty file just calling 4 classes) and the needle density simulator. Calling same four classes, but doing override of the load and OnPaint in the DrawingClass.

What is a PR?
> Why I like this: it's less about "these stitches are too close together" and more like just a density map. It's still up to the digitizer to understand whether the density will be a problem for their specific situation, but this will still provide useful hints for inexperienced digitizers too.

Yes, I am aiming for the density. But I have tons of problem with the wx drawing functionality. The existing embroider function redraws the whole picture from scratch to crosshair for each step. I have not managed to find a wx function which allows me to do that fast enough based on what I want to output (using other functions than the original code, I get strange error messages). But that you likely have those that know how to fix anyway. 

I was aiming for gradients, but the risk is it becoming slow and bulky besides the drawing part, due to the need to check many distances between needles and translate to how to show that (if you show it per "square mm" it becomes bulky, if you show it per stitch, you risk many "good stitches" to hide bad stitches). So right now, just experimenting. I thought I would get sort of a gradient if using overlapping opacity circles mixing their colours, but have not managed to make wx draw those (I am not a programmer). 

Anyway, switching the blue from yesterday to sky blue made it stand out better, and I think the density is reachable without having to go to too many steps. In fact, seen from my point, it already gives me what I was aiming for. I clearly see the terrible areas, and I also see the areas where I have some issues. Also I see areas which have one or two or few warnings, but not enough to bother doing anything about it.

As per below, you can now clearly see the eyes starting to stand out, and three other points in the hair which I also know has an issue when embroidering, but not as severe as the starts to the left.

![Capture needle density 2](https://user-images.githubusercontent.com/15014932/62023039-5392ff80-b1cf-11e9-95fa-5858299363f2.PNG)

**Comment by MatsIBengtsson** [comment]
> > Why I like this: it's less about "these stitches are too close together" and more like just a density map. It's still up to the digitizer to understand whether the density will be a problem for their specific situation, but this will still provide useful hints for inexperienced digitizers too.

It is possible to do a full gradient density map view as well. I did experiment a bit. My biggest issue is that I for example cannot get canvas.DrawLineList or dc.DrawLineList to work, so I am stuck with a very slow DrawLines. Also with those working, there will be some work not to hide important needle density points which have a close less important point displayed later (z order or layers needed).

Here is for a radius of 0.5 mm (so diameter 1 mm):
- Purple = 12 or more stitches within circle, self uncounted (I will reduce all limits one or two steps down)
- Red = 10 or more
- Orange = 8 or more
- Sky blue = 6 or more  

It shows similar, but not same points as the distance one, since they now target the load on the fabric in a bigger area, not just the closest.

![Capture needle density as density 3](https://user-images.githubusercontent.com/15014932/62101340-5d7f3600-b295-11e9-8aa0-d464fd37beca.PNG)

**Comment by lexelby** [comment]
A PR is a Pull Request, the method of collaborating in code here on GitHub.  I've granted you write access to this repository, which means you can `git push` your branch here.  Once you've done that, then come back to https://github.com/inkstitch/inkstitch, go to Pull Requests, and create a pull request for your branch.  That lets us see your code and we can talk it through and even suggest modifications.

I will say that we're all still learning when it comes to wx.  We're hoping to move away from wx and toward Electron, which will allow us to make use of Chrome's built-in SVG renderer.  For now, hopefully we can come up with something that at least gives us marginal improvement.

It looks like you're already pretty close.  I can't wait to see the code :)

**Comment by MatsIBengtsson** [comment]
> A PR is a Pull Request, the method of collaborating in code here on GitHub. I've granted you write access to this repository, which means you can `git push` your branch here. Once you've done that, then come back to https://github.com/inkstitch/inkstitch, go to Pull Requests, and create a pull request for your branch. That lets us see your code and we can talk it through and even suggest modifications.

Ok, I understand. I have never worked with github or git push or its branches, so I have to learn how to do that, I will try. It would be a good thing to be able to share and discuss, I do need help.

> I will say that we're all still learning when it comes to wx. We're hoping to move away from wx and toward Electron, which will allow us to make use of Chrome's built-in SVG renderer. For now, hopefully we can come up with something that at least gives us marginal improvement.

Ok pitty. If I could just get something like DrawLineList working (anything allowing me to "batch draw" like the original code) I believe I can speed it to "usable". As it is now, without that part, speed does not matter anywhere else.
 
> It looks like you're already pretty close. I can't wait to see the code :)

There is a lot left to do. I started with:
- the needle distance (the base warning system), gives a very good start picture when shown as a density map of such points
- then added the needle density (the fabric warning). Also a quick and good warning but now for fabric and stabilizer (how many penetrations are done within an area of the fabric).
- I am now combining it to "thread density", which is based on the thought of density of "other threads" pushed into the fabric within a "thread core distance" (needle pushing it close to the thread) plus a "thread to thread" distance (other thread close to thread). Where the first one is more severe, yet the second one adds to the issue when combined (packing threads, preventing them from moving)

Trying to use the last one to tune the warning levels for the other ones (number of threads that perfectly fit within the area examined, Pi * r *r divided by Pi * rt * rt, where r is radius examined and rt is thread radius). Maybe it is easier doing that manually.

**Comment by MatsIBengtsson** [comment]
> Ok, I understand. I have never worked with github or git push or its branches, so I have to learn how to do that, I will try. It would be a good thing to be able to share and discuss, I do need help.

Uploaded the files I have. They run correctly locally on my PC (although slow, 1200 points per second. Slowness is both due to calculations and to lack of DrawLineList, if the last could be solved, I think speed may be acceptable).  

I failed updating Ink/Stitch menu. I tried to add them all, but by some reason, the menu system only shows one of them (although 4 times). 

Definitely need help to understand how to update the menu system to show them as I intended.

**Comment by MatsIBengtsson** [comment]
> I failed updating Ink/Stitch menu. I tried to add them all, but by some reason, the menu system only shows one of them (although 4 times).

Slightly better, menus work. However, the views do not die as expected, they give a weak warning from Ink/Stitch after being closed.

**Comment by kaalleen** [comment]
Realized as an on canvas density map extension in #1687
Maybe it'd be still interesting to be included into the simulator at some point.
