### ISSUE TITLE
Extra lines, how to eliminate them or improve?

### ISSUE THREAD

**Issue by igenyar** [inkstitch/inkstitch#502]
I use an embroidery lettering software to generate pes file. When I open it in inkstitch for re-editing, I see extra lines across. Is there way to eliminate or reduce them? Below is the screenshot. The top one is the output from the software and the bottom is when I open it in inkstitch.

My apology in advance if this issue was raised before.  Thanks a lot for the help!

![image](https://user-images.githubusercontent.com/13770542/62011301-7c61b900-b12b-11e9-9738-b418748c130a.png)

**Comment by kaalleen** [comment]
Hello @igenyar and welcome to the project. Thank you for reporting your issue. It is always helpful to know, if Ink/Stitch isn't behaving as expected. This issue is actually one of the latest things we have been working on. With the next Ink/Stitch release you shouldn't get the extra lines anymore. Instead you will see trim commands attached to the letters.
