### ISSUE TITLE
Maybe not an issue, but builds seem to work differently

### ISSUE THREAD

**Issue by MatsIBengtsson** [inkstitch/inkstitch#510]
Before, I got the impression that a style error detected would stop the build. Today, I had a style error, but the build continued anyway. Which I did not notice, so I uploaded, and the build started, but collided for some destination deployments with the previous build, and errorred due to that.

Should builds continue even with style errors found?

**Comment by lexelby** [comment]
It should fail -- or at least, part of the build should fail.  Each time you push, four builds are triggered:

1. style check
2. linux build
3. windows build
4. mac build

2-4 won't fail if your code doesn't pass the style check, because they don't run `make style`.  1 only runs `make style` and will fail, and that should cause your pull request to get the little red X.

> but collided for some destination deployments with the previous build, and errorred due to that.

I'm not sure I understand what you mean by that.  Can you share a link to the failed Travis CI build?  It's the "Details" link next to the "Travis CI build failed" on your pull request.  You may have to click "show all checks" to expand it.  You can also find the failed build directly here: https://travis-ci.org/inkstitch/inkstitch/builds

**Comment by MatsIBengtsson** [comment]
> It should fail -- or at least, part of the build should fail. Each time you push, four builds are triggered:
> 
> 1. style check
> 2. linux build
> 3. windows build
> 4. mac build
> 
> 2-4 won't fail if your code doesn't pass the style check, because they don't run `make style`. 1 only runs `make style` and will fail, and that should cause your pull request to get the little red X.

And it did. I just thought 2-4 were depending on 1 to start.

> > but collided for some destination deployments with the previous build, and errorred due to that.
> 
> I'm not sure I understand what you mean by that. Can you share a link to the failed Travis CI build? It's the "Details" link next to the "Travis CI build failed" on your pull request. You may have to click "show all checks" to expand it. You can also find the failed build directly here: https://travis-ci.org/inkstitch/inkstitch/builds

Link: https://travis-ci.org/inkstitch/inkstitch/builds/567948650 .On this one, linux and windows build failed. I believe they did that only because I had another build ongoing at same time. (Since I beleived 2-4 did not start if 1 failed, I fixed 1, uploaded, and then had two parallel running builds.

**Comment by MatsIBengtsson** [comment]
> It should fail -- or at least, part of the build should fail. Each time you push, four builds are triggered:

Those are working beautifully. Really good. I missed renaming an "inx" file. which fails the builds. Maybe the test of inx file names should be on the struct one? The checks done sort of works as a teaching guide for how to develop for Ink/Stitch...
