### ISSUE TITLE
Export to JEF file not working

### ISSUE THREAD

**Issue by rayendumeldust** [inkstitch/inkstitch#511]
OS: WIndows 10
Inkscape: 0.92.4 
Inkstitch: v1.25.0

Hey,

first of all, a huge thanks to all of you for working on such a great program. Since I bought my embroidery machine four months ago, I worked with Ink/Stitch and never had any problems. Til; now. 
Two days ago, without changing or updating anything, I suddenly got error messages when wanting to embroider simple satin columns. As mysterious as this appeared it also vanished yesterday without having found or done anything. But now the jef file is corrupted when doing satin columns. In Inkscape the satin column looks like it's supposed to. But when I take a look at the jef file with the Embroidery Editor or on my machine I only see a view of the lines that should be there. I also tried stitching it, to be sure that it's not just a failure of display but it seems that the machine is making little dots randomly where there's supposed to be a satin column.
I'm thinking, this could be a total user fail on behalf of me but after two days of trying, I just give up and hope you can help me.
Thanks in advance! 

![1](https://user-images.githubusercontent.com/7116219/62485745-d878ad00-b7bd-11e9-9641-54a689156a49.JPG)
![2](https://user-images.githubusercontent.com/7116219/62485765-e9c1b980-b7bd-11e9-89aa-776aa06f1f2b.JPG)
![3](https://user-images.githubusercontent.com/7116219/62485767-ecbcaa00-b7bd-11e9-8c9e-1a391b4ec7ea.JPG)

[files.zip](https://github.com/inkstitch/inkstitch/files/3468822/files.zip)

**Comment by lexelby** [comment]
Hi, @rayendumeldust!  I'm so glad you've been enjoying Ink/Stitch, and thanks for joining us here.

I've got some good news and bad news for you.  The good news is, I'm pretty sure I know what's wrong.  The bad news is that I may not have a complete solution for you.

The problem here has to do with the way the .JEF format works, at least as far as I understand it. The maximum length a stitch in a .JEF file can be is 12.7mm (half an inch).  Anything bigger than that, and it has to be encoded as one or more jump instructions followed by a stitch.  Check out what happens if I convert your `Satin.jef` to a CSV file so you can see the instructions:

[Satin.zip](https://github.com/inkstitch/inkstitch/files/3470075/Satin.zip)

This has a couple of nasty consequences, espeically for Janome machines.  First of all, the .JEF file format has no TRIM instruction for trimming the thread.  You encode a TRIM by putting three JUMPs in a row.  There's no way for the machine to tell the difference between a long stitch (three JUMPs plus a STITCH) versus a TRIM.  The result is that your super-wide satin is going to look like it has TRIMs for the longer stitches.

Second, at least on my Janome machine (memorycraft 400e), if you put a JUMP instruction in the file, it switches into "jump" mode.  It pauses, unclamps the thread, jumps, and reclamps.  It takes forever.  I tried this recently for some fringe embroidery and eventually gave up.

If your machine supports another format, try it.  But if that format is DST, well, I'm afraid you're no better off.  DST has exactly the same limitations: 12.7mm maximum stitch length and three-jumps-equals-trim.  I think JEF format was modeled on DST.  Other formats like brother PES can support much longer stitches.

You may be able to convince your machine to at least try to stitch this thing by turning off trimming in the settings (if it even supports trims?).  Otherwise, you may have to convert this to a fill stitch instead.

Sorry I couldn't help more.  I'm guessing this is the first time you've tried a really wide satin like this?

**Comment by wwderw** [comment]
12.7 mm to my knowledge is the biggest stitch length before a forced trim, even on my Brother PR machines and Barudan.

You could see if there is a function to turn off trims, but to my knowledge all machines have a forced trim and some are actually 12.1mm and not 12.7.

What Brother machines will do is force a jump if there start and end point of 1 objects full within a certain length, regardless if there is a trim in the file or not.  Which annoys me, and I've had to artificially force start/end points in PES files for customers that didn't want that.  Which at times goes against production.

**Comment by lexelby** [comment]
Interesting!  PES format allows for much longer stitches, up to around 200mm I believe.  My little SE400 is perfectly happy to sew 30-50mm stitches without  pausing or trying to trim.  Maybe that's because it doesn't have TRIM command support?  The result is that it is way better at long fringe than my janome mc400e!

**Comment by wwderw** [comment]
>  Maybe that's because it doesn't have TRIM command support?

That's why.  

Machines that support trims, will automatically trim at 12.7 (or 12.1 depending on the machine) and Wilcom actually has it hardcoded to force trims at either one of those lengths depending on the machine file used.  I've tried various methods to circumvent that (manual stitches, removing trim functions in stitch list etc) and it will always do the trims.  Even if you were to circumvent it in the software, you would would have to tell the machine to ignore trims anyway.

Even if using the old open source software Thred that doesn't support trims in it.  The machine will perform the trim if it's at or greater then the max jump stitch width.

Unless you turn it off at the machine, which is a global setting.  Meaning not only will it affect all trims (except those at color changes or end of pattern), but all future patterns that you run until it's changed back to accepting trims.

**Comment by rayendumeldust** [comment]
Hi @lexelby and @wwderw, thanks for the quick answers and useful tips. That's it; did not know about the maximum stitch length. I have an Elna 830/Janome MC500e and was aiming for a fringe design. I looked at some and they seemed a lot wider than 12 mm but I can totally live with that limitation. As long as I can use Ink/Stitch and know what I have to do to get it working, I'm happy.

**Comment by wwderw** [comment]
Look to see if there is a way to turn off trims on your machine.  That will enable you to do longer fringe.

It may or may not be there, but that would help increase that length if that option is on the machine.

**Comment by lexelby** [comment]
I'm going to go ahead and close this issue now, but if you find any other weird behavior, please do let us know.
