### ISSUE TITLE
No Linux Build

### ISSUE THREAD

**Issue by kaalleen** [inkstitch/inkstitch#526]
Since v1.26.1 the Linux build fails and is not published.

I don't think the changes from the release themselves are the issue.

**Comment by lexelby** [comment]
Uh oh!  I saw the build failure and tried rerunning it the other day.  Guess that didn't work.

Now that GitHub has released a competitor to Travis, it might be a good idea to switch over.  Since their company was acquired (and for awhile before), Travis has been having a lot of stability issues.

That's a lot of work though, so for now I've just been crossing my fingers and hoping Travis keeps working....

**Comment by lexelby** [comment]
I fixed it.  No idea why it broke, but installing `libsdl1.2-dev` seems to have fixed the problem.  Version 1.26.2 is building now with the fix.
