### ISSUE TITLE
(PRINT SCREEN WORKAROUND!) SUPER HELPFUL FOR MAC USERS!

### ISSUE THREAD

**Issue by ALPHAMOTIF** [inkstitch/inkstitch#528]
(Deleted)

**Comment by ALPHAMOTIF** [comment]
***Im using this app more now so I'm learning new things as I go,
This app also has a beautiful simulator built in that will show you in real time how long it will take to stitch out!  I think this app paired with Inkstitch is a F***** power combo for Mac Users who want to use this program!

**Comment by lexelby** [comment]
Thanks!  I'm really glad you found a workaround.  I don't see a reason for you not to post about that here, no need to delete this :)

I really wish we could figure out what's wrong with Print PDF on Mac.  Maybe you'd be willing to help out?  It would be really helpful if a Mac user could go into the "inkstitch/electron/inkstitch-gui.app" directory and see what happens if you run it.  If there's any kind of error message, that might help us figure out what's going wrong.

**Comment by lexelby** [comment]
Thanks!  I'm really glad you found a workaround.  I don't see a reason for you not to post about that here, no need to delete this :)

I really wish we could figure out what's wrong with Print PDF on Mac.  Maybe you'd be willing to help out?  It would be really helpful if a Mac user could go into the "inkstitch/electron/inkstitch-gui.app" directory and see what happens if you run it.  If there's any kind of error message, that might help us figure out what's going wrong.

**Comment by ALPHAMOTIF** [comment]
I ditched the workaround because upon using it I found it was not totally free and after i paid I discovered an export but that does not allow saving if PES over 5 inches, huge downer for me so I didn’t wanna mess anyone’s day up 💀 

TAYLOR B.
ALPHAMOTIF
info@alphamotif.net

**Comment by lexelby** [comment]
Ugh!!! That's terrible.  We'll get Ink/Stitch working.  Actually free is way better.
