### ISSUE TITLE
Installation incomplete

### ISSUE THREAD

**Issue by Augusa** [inkstitch/inkstitch#538]
First of all thanks for Inkstitch. I already use it for several patterns. I enjoy it.

But I have installed Inkstitch with the method given on the site of Inkstitch. I can use it but a part of it is in french and other parts stay in english for example parameters, commands... I don't have the step with choice between languages  which I see on videos. The use of commands for start and end seems not be completely normal. Often black windows appears which I don't see on videos of other users

I use inkstitch-v1.26.2-win32-fr_FR I unzip it in C:\Users\famille\AppData\Roaming\inkscape\extensions
Windows 7 64 bits

I don't know what to do. I have exactly the same problem on another computer where I try to use it. I probably forget something somewhere.

Thanks for help. Sorry for my "frenchenglish"

**Comment by kaalleen** [comment]
Hi Augusa!

The language choice within the Ink/Stitch extension was removed from the Ink/Stitch installation in favor of separate download versions for available languages.

The incomplete translation is not due to an error in the installation. There is simply not everything translated into french. Any string without translation will be displayed in English. If you want to change this behavior and have some spare time you could help us by translating Ink/Stitch into french. The website for translations can be found here: https://crowdin.com/project/inkstitch
You can also use your GitHub  account if you like.

As for the black windows I have no idea what is going on. Could you post a screenshot of it?

**Comment by lexelby** [comment]
The black window appears on Windows every time an extension is run.  I tried to get rid of it but I never could figure out how.  It doesn't hurt anything and you can ignore it.

**Comment by Augusa** [comment]
Thank for your answers. I try to help to the translation as much as possible.
