### ISSUE TITLE
Need help learning how to get better designs

### ISSUE THREAD

**Issue by fnavas00** [inkstitch/inkstitch#542]
my designs always look sloppy,  either there is a bunch of gaps between the stitches , or the underlay is visible...  the autofill will completely break my machine lol. I have yet to create a design that is worth selling or even worth taking a picture of to post on social media. I have tried multiple combinations  of different params for the satin stitch, underlay, fill, etc. Even going as far as to writing them down to see which combos worked and which didn't. Nothing seems to really work and my designs always look terrible

**Comment by lexelby** [comment]
Hi, and welcome to our community!   I'm sorry you're having a hard time.  You're up against steep learning curves for two separate skills: learning machine embroidery digitizing and learning how Ink/Stitch works.  I know both can be very frustrating!

I also found that my designs didn't look great at first.  There's a ton of trial and error involved in learning to digitize.  The fabric shifts and puckers as you add stitches to it, and as you've found, what you create on the screen is often not what you get when the embroidery machine executes your instructions.  

There is a lot of skill and art involved in learning to compensate for the way the fabric behaves.  Folks like @wwderw spend their entire careers learning how to do this well.  I can't tell you how many pieces of fabric I've thrown away, sometimes after carefully untangling them from my poor machine with scissors!

You're on the right track with writing down your settings as you experiment.  In time you may start to get a feel for what settings will look good for a given project.  Even still, I never get a sellable result the first time I stitch out a given design.  There's _always_ trial and error involved.  Every design behaves differently.

I found that Mr X Stitch's articles on machine embroidery distortion were especially helpful when I was starting out.  He helped me get into the right mindset for embroidery digitizing.  I learned to think of digitizing as writing instructions for the machine, rather than just drawing the shapes I wanted to see it sew.  Often what I draw in Ink/Stitch differs from the end result on the fabric.  For example, to get the baseline of text to line up nicely, it's usually necessary to shift some of the letters up or down in the SVG.

We're all learning here together.  Feel free to post your designs if you're interested in feedback.  I, for one, would be happy to take a look.

I'm sorry that auto-fill is trying to break your machine!  What settings are you using?

**Comment by wwderw** [comment]
This is apart of the learning curve.  It'll take time.

What I tend to suggest when starting out is getting (purchasing) designs that are known to be good.  Study how they use stitch types, pathing.  Density settings will still be trial and error, but at least you'll have someplace to start.  I would suggest trying to digitize your versions of those patterns and then compare them.

Keep in mind that what type of fabric you stitch it on is going to play a part.  I would suggest *not* stitching it out on just stabilizer only.  Stitch it out on fabric, that's going to be the only to "put it through it's paces".

Writing down what works is an excellent way to keep track of what settings work and on what fabric type.  Once you got settings that you know are good and under what fabric conditions, start putting them in the "presets" part of Params with a name that you'll know exactly what those settings are for.  This way you can easily backup the JSON file and transfer to other installs as well.

Don't get frustrated it will take time.  There are a lot of variables that people don't think about and there are quite a lot of myths out there.  Needle/eyelet size, speed of the machine, size of pattern and individual objects within the pattern (helps determine stitch type), fabric type, amount and type of stabilizer, speed of the machine, even brand of machine (not all brands of machines are able to do everything the same way, some stitch better doing certain things then others and at certain sizes).

It's a lot to take in and some of these machine vendors obfuscate that fact by showing off their machines/software with designs that can easily look good with a press of a few buttons and running it on the typical fabric/stabilizer/speed/needle combinations that 95% of the embroiderers will be dealing with.

**Comment by fnavas00** [comment]
@lexelby What stitch settings do you use for satin columns on t-shirts? I can show you some of my work with ink/stitch its all terrible  though
![fail](https://user-images.githubusercontent.com/50570593/66020762-d07f7580-e4ad-11e9-8103-9ca2841030df.jpg)
![IMG_0869 fail](https://user-images.githubusercontent.com/50570593/66020775-db3a0a80-e4ad-11e9-93e9-d61d20629c27.JPG)

**Comment by fnavas00** [comment]
@lexelby  Here is an updated version of the VHS design I did just now on a t-shirt, medium weight cutaway stabilizer, 90/14 ball point needle, 40wt thread, level 3.5 tension

### Params 
**BORDER** 
- Satin Column -Pull comp: 0mm 
- Zig-Zag Spacing (peak 2 peak) : 0.35mm  
- Center Walk Underlay : 1.5mm

 
**VHS LETTERS :** 
- Satin Column -Pull comp: 0mm 
- Zig-Zag Spacing (peak 2 peak) : 0.3mm  
- Contour Walk Underlay : inset 1.2mm, stitch length 1.5mm

**Comment by wwderw** [comment]
You always want to have some pull comp, either it's you digitizing extra width on your own if you want to have 0 in the pull comp settings or applying a value in the pull comp settings.  Density settings are going to be dependent on fabric type.

Fills, while they are easier to do, I wouldn't suggest doing them on anything less then 10mm wide.  For me (some people wait until it's 12.7mm wide, stitch width that is), this is where I start thinking about do I want this object as a fill or satin.  

As far as this goes:

>How long do i have to use ink/stitch before I get good at it?

Got two different things going on.  Finding out the right combination of settings and path sequencing, needle size, machine speed, thread type/size etc on one hand and then software usage.  

The former takes a lot longer then the latter.  Even at that, how long that takes is dependent on each individual circumstance.  But thing that I can suggest is to keep at it.  I'm been doing this since '94 professionally and I'm still learning new techniques.

**Comment by fnavas00** [comment]
@wwderw what settings do you recommend I use for the VHS design on a t-shirt then? Can you send me a inkk/stitch digitized file of yours to see how do it correctly?

**Comment by wwderw** [comment]
Quite a few of the samples that are included within Ink/Stitch are mine.  Go into the examples folder where you have the Ink/Stitch bin folder installed at.

Depending on a few variables would determine what I would recommend for the VHS design.

**Comment by lexelby** [comment]
@fnavas00 Hang in there, learning embroidery design is a long road and requires a ton of experimentation.

 Is it a knit t-shirt?  Knits are the most challenging fabric I've worked with so far. Perhaps only silk would be more difficult.  Before doing anything else, make sure you're using a very sturdy stabilizer.  I've had the most luck with iron-on tear-away.  Try two layers of Sulky Totally Stable.

 Before I can make a recommendation on satin settings, I'd need to know: how wide are they?  I use quite different settings for 1mm-wide satins than for 4mm-wide.  It's all about how many threads you're trying to cram together in a small space.

 For the VHS, sew the border second.  When you sew the letters VHS, the thread will pull and push and distort the fabric.  If you sew the rectangle after, it'll be more likely to _stay_ a rectangle when you unhoop the fabric.

I'm sorry that you're having trouble finding other Ink/Stitch users.  I'm hoping that some of the features we have planned will attract more folks. :)  On the plus side, the difficulty you're having us the kind of thing people will encounter when designing embroidery on any program.  You'll find analogs for most, if not all, of the settings like contour underlay, etc, in Hatch and the rest.

For the fill stitch that's tangling your machine and tearing your fabric, yikes!  What settings are you using?  My "go-to" settings for auto-fill are: .25mm row spacing, 2.5-3mm max stitch length.

**Comment by lexelby** [comment]
Oh, and .8mm row spacing on the underlay, 90 degrees offset from the main fill.

**Comment by lexelby** [comment]
One more thing: if I'm doing a knit shirt, I always buy two. ;)  It's a challenging fabric, and there's a distinct possibility I'll mess one up.

Get a yard or two of knit fabric and experiment.  Write down what you try and the results you get.  Change only one thing each time and try again, so that you'll know what helped if you get a better result.  That goes for stitch settings and also the type of stabilizer you use.  

Practice, practice, practice. I know it's tedious but you _can_ do this!  :)

**Comment by wwderw** [comment]
What I'll do to help with the knits is do a lattice motif fill underneath everything, slightly offset around the entire design extending outward  and that helps structure and stiffen up the knit.

Works well with beanies as well.

When you stitch this object, you want to stitch it as close to the color of the substrate as you can.  Helps it "disappear".

**Comment by fnavas00** [comment]
Im not sure if they are knit t-shits. Im just using old shirts i found around the house to practice. Unfortunately, I dont think im anywhere close to start embroidering products for sale. How do you figure out the pull compensation?  I don't know how to measure the mm for satin columns im looking on the inkscape rulers but it just shows 14, 16 , 20 etc..

**Comment by fnavas00** [comment]
@lexelby can ink/stitch do designs as good as professional programs? Does it just take a lot of practice? Like im considering buying software but at the same time I feel like I would just face the same issues like you said since im a newbie im going to face the same issues wether the program is $1,000 or completely free like ink/stitch.

**Comment by wwderw** [comment]
>  can ink/stitch do designs as good as professional programs?

Yes, but it takes knowledge and it takes time.  Not just practice, but knowledge as well.  One can be practicing the wrong techniques, but still know how to use the software well.

Purchased software does have better text tools (as in you can use pre done digitized fonts), but you can still achieve the same results, just takes a little longer.  Text tool that's in Ink/Stitch is still in early stages.  I will say this, with a budget of around $1k, your still in the consumer range, probably looking at $1900 for at least having manual tools.  Sub $1k, your going to be dealing with more auto converting then truly digitizing, there will be some digitizing tools, but they will be heavily dependent on auto converting.  Pro software, which is where I would have to be due to have a sequin dispenser and wanting all of the manual digitizing tools, well put you in the range of $3k to $15k.

Auto converting will get you results closer, but they won't efficiently stitch out, to get the best results with auto converting, you would have to have a design ready to go specifically to go with embroidery auto converting.  Auto converting will never give you great results for hat embroidery, I have yet to see the ability to tell it to do the proper sequencing.  That's not going to be what people will give you most of the time for digitizing for embroidery.  I've been doing this professionally since 1994, very very few times have I received files that were supposedly done by professional graphic designers were ready for embroidery as is.  Most designers from them were setup for web or print, different animal (and the down side, when ever I come up with a concept, it's setup for embroidery first, so it does keep the limitations in embroidery in mind, which can be just as limiting).

Keep in mind, the biggest thing that design that we get for digitizing for embroidery do not have traveling stitches in them (it would be impossible to have them if those graphic files were to be used for plotters especially).  Those help immensely with making a design go faster and make us more money (remember we aren't making money unless the needle is touching the fabric). 

Now, I will say this, Ink/Stitch does require you to know how to manually/semi-manually digitize (which is great, I'm glad that there aren't any auto converting tool, to me this is a plus, but for newbies it's a steep learning curve, I'm one of those that doesn't auto converting should be available to those that are just getting into it).  If one knows how to do that, you can do any design.  You can get designs to stitch out even smaller then normal (still have limits, but you can stretch those limits).  I learned when we were doing it all manually, truly stitch by stitch.  8k stitch count design meant 8k mouse clicks.  If you want to really be able to do all that can be done with say blends, you need to know how to place manual stitches for the more realistic designs (like with realistic animals).  No way around it, no matter how much you spent on software.  That knowledge will be required.  There are times with corporate work that level of knowledge will be required.  That knowledge is separate of software.

I'm going really long, because one thing that has disturbed me with current trends is for people to go with auto converting tools, while that does help initially, it won't get you the knowledge any quicker as you won't know why it's trying to do what it's trying to do.  And most importantly, you won't be able to fix it (or sometimes can't because of how limited the software is).  Text, for instance, there are alot of good text tools in commercial products, we can still achieve the same results in Ink/Stitch just have to manually/semi manually digitize (which I was still doing even in the commercial software, because the custom fonts in the designs I was getting wasn't in the font library and I was quicker with doing that).

Learning to do digitizing manually/semi manually does have a steeper learning curve, but it gives you a more robust skill set and that's regardless of the software used.  It sucks, but I've been doing this for a lot of years and that skillset is what sets me apart from others (that and being able to create my own designs from scratch).  Sorry for such a long post, I do have my own definitive ideas on the subject matter.

**Comment by lexelby** [comment]
To be honest, I don't actually know if Ink/Stitch can make designs as well as professional programs.   That's my goal, but I've never used professional digitizing software.  I'm entirely self-taught, and I've learned digitizing as I've developed Ink/Stitch.

I do know this:  I'm able to create designs that look good enough to sell when seem out.  When I run into limitations that hey in the way of making nice designs, I try to add features to Ink/Stitch.  There's still a ton left to do, but what we have now generally doesn't hold me back.

**Comment by lexelby** [comment]
To measure your satin in mm, select the ruler tool, and change the unit to mm in the tool options panel just under the menu bar.  That should let you measure how wide the satin is in mm.  You could also post the SVG here if you'd like.

**Comment by wwderw** [comment]
Pro digitizing software (which is in the range of $3k to $15k), makes certain things more efficient and it has auto conversion (which for a newbie may get your further quicker, but it doesn't necessarily make better designs, although since it's what people have started with, they don't know better).  

Your sub $1k programs rely more heavily on auto conversion (may have a few manual/semi manual tools, but most is auto) and in a lot of instances, generate a bad file.

I've been doing this professionally since '94 (summer of), back then it was nothing but manual (one mouse click equals one stitch).  The thing is, if one has the knowledge, due to the fact that Ink/Stitch is manual/semi manual digitizing, you can do a lot with it.

The biggest thing is knowledge and the quicky auto conversion "stuff" that most software vendors highlight may get you a smidge further quicker, it does more damage then good.  If you can digitize manually/semi manually, you can use just about any pro commercial software ($3k on up) and create great designs.

It's up to you, but I would suggest sticking with it and learning the harder tools, that's a big part of what is going to separate you from the multitude of other digitizers out there (if you can create your own designs from scratch even better) and there are a lot of them, but they only know the auto tools.

**Comment by fnavas00** [comment]
Thanks for you response @wwderw you say you have been digitizing since 94'? did you ever try the digitizing program called "thred"? I tried it out the other day its exactly like you said stitch by stitch I was going to use it but it was taking too long to make 1 letter. Id rather stick to ink/stitch. Do you use ink/stitch exclusively? or do you use any other programs? Also how long did you practice before you got good designs? I wish there was more videos online of ink/stitch tutorials besides the beginner series. I feel like ink/stitch could really become a big thing. I appreciate the people who but the program together

**Comment by wwderw** [comment]
> did you ever try the digitizing program called "thred"?

I have.  It's a nice little program.  Low distract UI, but it is somewhat dated.  I don't think it has been modified in any way since 2006 and it's geared to home machines.  So between the dates of when it was made and what machines it's geared for, it is dated.  But for teaching people how to digitize, it works well because of the low distract UI (at least I think it's low distract).

>exactly like you said stitch by stitch I was going to use it but it was taking too long to make 1 letter.

It actually does have object based embroidery.  I would use the line tool and then convert it to "satin ribbon" to in order to get a more robust use for satin manipulation.

It is very key board centric (a lot like Blender was before 2.8)

> Do you use ink/stitch exclusively? or do you use any other programs? Also how long did you practice before you got good designs?

I do use Ink/Stitch exclusively.  I have used Wings, Pulse, Wilcom (my personal favorite), PE Designs (not bad for the price point, but really only geared to Brother machines and Creative InDrawings (really wasn't bad for what it is, also done by the same people that do Wings).

Since I'm now on the Linux platform, I needed something for that platform.  Although before this program had become robust enough for my ability to exclusively use it, I did VM Win 7 with Wilcom as a crutch.

Ink/Stitch has really gotten good.  Now, I'm also an old school digitizer, I like the manual/semi manual method.  I think that gives the user more power, more control, better quality, but it is also dependent on their knowledge base.  It does take a long time to get comfortable with production and manually digitizing.  I wouldn't give up on it.

**Comment by fnavas00** [comment]
Are comments getting deleted or something?

**Comment by lexelby** [comment]
I'm not deleting anything...

**Comment by wwderw** [comment]
Everything appears good to go on my end.

**Comment by fnavas00** [comment]
Idk whats going on... im not seeing some of your guys responses or my comments.. Im seeing the previous error I mentioned before my comments got deleted. This time the error is showing for the sample SVG "InkStitch Logo QR Code Path" 

"outer square (rect10257): error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "lib/elements/auto_fill.py", line 218, in to_patches
  File "lib/debug.py", line 125, in decorated
  File "lib/stitches/auto_fill.py", line 64, in auto_fill
  File "lib/debug.py", line 125, in decorated
  File "lib/stitches/auto_fill.py", line 568, in path_to_stitches
  File "lib/stitches/auto_fill.py", line 533, in travel
  File "site-packages/networkx/algorithms/shortest_paths/generic.py", line 172, in shortest_path
  File "site-packages/networkx/algorithms/shortest_paths/weighted.py", line 163, in dijkstra_path
  File "site-packages/networkx/algorithms/shortest_paths/weighted.py", line 472, in single_source_dijkstra
  File "site-packages/networkx/algorithms/shortest_paths/weighted.py", line 738, in multi_source_dijkstra
NetworkXNoPath: No path to (146.9891261679123, 164.78734521248998)."

I ran the troubleshoot objects  and got message 

"All selected shapes are valid!

Tip: If you are still having an issue with an object not being rendered, you might need to convert it it to a path (Path -> Object to Path) or check if it is possibly in an ignored layer."

**Comment by lexelby** [comment]
Oh, is it that we are talking in two different issues?  You posted that error in #179.  I'll take a look at the QR code sample svg and see if I get the same error.

**Comment by lexelby** [comment]
Wow, sure enough, the QR sample fails for me too.  I'll take a look at that when I get a chance and see if I can fix the bug.
