### ISSUE TITLE
Creating embroidered font

### ISSUE THREAD

**Issue by jrsprad** [inkstitch/inkstitch#548]
I'm new to Ink Stitch and I'm trying to do something that I feel should be easy but is a struggle. I have a word that I want to embroider which I create in Inkscape or Affinity Designer. I'm then trying to run that vector image through Ink Stitch but I am getting an error that the shape is not valid. I know why it is happening as the word is made up of separate fills (letters) but I need to know if there is a way to work around this issue. I basically need to get a multiple group vector to be treated like the Ink Stitch logo example. I'll attach an image of the font I'm trying to embroider.

![United](https://user-images.githubusercontent.com/56012157/65932917-8e86fe80-e3dd-11e9-8e0e-06da1f4ba034.png)

**Comment by danielkschneider** [comment]
InkStitch can only deal with simple fills, lines or "rails". Transforming your design into fills would be easy. Menu Path -> Object to Path. Then remove Stroke and define the Fill. However, unless you plan to make the letters really big, the result would be ugly. The only way to go is to transform each path into "rails" with "rungs", then configure a satin stitch. A good idea is to look at the build-in fonts, you can find these in some sub directory. Alternatively, I once wrote a piece on how to create fonts: https://edutechwiki.unige.ch/en/InkStitch_-_design_letters#Stitch_with_satin_stitches and https://edutechwiki.unige.ch/en/InkStitch_-_Geneva-simple_typefaces

**Comment by jrsprad** [comment]
Thanks for the reply. I finally got it to do the DST file by breaking apart all the paths. That was the main problem I was trying to solve. However, now that you brought up the issue of what the fill would look like, I'm wondering if you could answer me two other questions.

First, I'm attaching a sample of what the embroidery looks like when opened in TrueSizer. It does not look bad, but the thread connecting the different fills worries me. Is this one of the things you were saying wouldn't look right? Are these threads a permanent part of the design, hidden, or removable? The design will be on the front of a ball cap. Sorry if that is a dumb question.

My other issue is the color. I saved two versions of the DST - one black and one blue. As you can see however, the TrueSizer software displays them both as green. Is this likely just a quirk in TrueSizer, or are the DSTs not saving the color profile right? I can see a difference in the color as I'm exporting the DSTs in Inkscape.

Thanks.

![UnitedSample](https://user-images.githubusercontent.com/56012157/65947286-efc2c800-e405-11e9-9346-0cc3495aa738.PNG)

**Comment by danielkschneider** [comment]
Hi. In your design you use a fill (as opposed to a satin stitch). Test "print" to see if that is OK with you. 
The stitches you see are so-called jump stitches and you can remove them using scissors. 
Alternatively, Ink/Stitch allows inserting commands. You probably want to insert a TRIM. Select the object(s), then Commands Menu -> Attach Commands to the Selected Object 

Colors don't really matter (and I never understood these), since you will have to insert a thread into your embroidery machine anyhow. Each thread vendor uses different numbers for each thread and each software formats uses different default numbers. I cannot help with this.

**Comment by wwderw** [comment]
DSTs do not retain color information, that's why it appears to be random when you open them up.  Open them up in different software and get those would be different in what colors are displayed.  Most software, even if they use different default palettes (unless the usr has changed the defaults) will still do a close color match (of if they have the thread palette in the software, it will pull from that) as long as the file retains color info.  Like I said, DST does not, this is why you want to make sure to use the print pdf, so you know when to use what colors.

Depending on how long those jump stitches are, you may not want to have them in there in the first place.  Some newer, even single needle machines, will automatically do a trim even if there isn't one, if a stitch is greater then 12.7mm wide (unless the usr turns that off within the machine).  Not all single needle machines do that, typically your mid range and higher, but even there might be some that don't.

Since there isn't anything for me to judge scale, I don't know how tall the letters are or how wide the stitching would be.  If this is a normal LC size lettering, I would highly suggest digitizing this as satin stitching.  If "you" try to pack in fills in such a small area, there is a possibility of doing some damage to the garment.  Likelihood increases depending on fabric type of said substrate.

I hope this helps.

**Comment by kaalleen** [comment]
Closing the issue now.Please reopen if needed.
