### ISSUE TITLE
Is-it possible to enable or disable lockstitches

### ISSUE THREAD

**Issue by Augusa** [inkstitch/inkstitch#549]
I would start and finish small objects of my design without lockstitches because it is sometimes nearly impossible to stitch them. The machine has to slows every 10 stitches and lockstitches are not necessary if my objects are adjacent. I create something like candelwick with some little stars along a path. It work if I join stars together in a single path but it is awfully long to do.

**Comment by lexelby** [comment]
We don't have a command or option to disable lock stitches -- yet.  But you do have a couple of options:

* Use Manual Stitch Placement. Objects with Manual Stitch Placement enabled do not have tie stitches before or after them.  If you run the Embroider extension, the resulting objects in the Stitch Plan layer are manual stitch versions of the objects you started with.  You can copy/paste them into your design.

(More ideas coming but I have to go AFK)

**Comment by Augusa** [comment]
Thanks for your help.

**Comment by lexelby** [comment]
Here's the rest:

* Instead of converting your objects to manual stitches using Embroider, you can add your own manual jump stitches.  Use Inkscape's Pencil tool to draw a line from one object to the next, right about where Ink/Stitch is inserting a jump stitch.  In Params, set that line to Manual Stitch Placement.  Make sure that the line is stacked in between the two objects in the stacking order (use the Objects panel to set the order).  Now Ink/Stitch will think that it doesn't have to add a jump stitch between the two objects, and so it won't add lock stitches either.

* Are your stars made as Satin Columns?  If so, you have another option: the Auto Route Satin extension.  It will set your stars in order so that the jump stitches between them are minimized.  If they're close enough together, Ink/Stitch won't decide to add jump stitches between them so you won't get the lock stitches.

I've had in mind the idea of making it possible to configure the jump stitch distance.  The idea is that you'd tell Ink/Stitch that anything below, say, 10mm, does not require a jump stitch and therefore also does not require lock stitches.  Sounds like that feature would be useful for you -- I could envision you setting it to 1000mm to disable lock stitches entirely :)

**Comment by lexelby** [comment]
Oh, I forgot, that setting actually _is_ available in the Embroider extension, although I think it may have a maximum of 10mm.  If you're feeling especially sneaky, you could edit the `inkstitch_embroider.inx` file and raise the maximum :)

**Comment by Augusa** [comment]
Thanks for your help. It works fine for my "candelwick". I study the other possibilities

**Comment by kaalleen** [comment]
Closing this issue, a checkbox for lockstitches is available within the next release.
