### ISSUE TITLE
Ink/stitch (MacOS) cant open print preview

### ISSUE THREAD

**Issue by fnavas00** [inkstitch/inkstitch#555]
Anytime I try the print preview I get a message "inkstitch-gui" can't be opened because it is from an unidentified developer. Ive tried overriding the security settings by:

"To override your security settings and open the app anyway:

In the Finder  on your Mac, locate the app you want to open.

Don’t use Launchpad to do this. Launchpad doesn’t allow you to access the shortcut menu.

Control-click the app icon, then choose Open from the shortcut menu.

Click Open.

The app is saved as an exception to your security settings, and you can open it in the future by double-clicking it just as you can any registered app."

This didnt work either. I dont know what to do. Ive opened it in the past but out of nowhere its not working.

<img width="421" alt="Screen Shot 2019-10-19 at 5 12 31 AM" src="https://user-images.githubusercontent.com/50570593/67143287-947b3d00-f22f-11e9-993d-18410ce8af4d.png">

**Comment by wwderw** [comment]
If you've updated to Catalina, could it be something to do with how they (Apple) handle apps like this in Catalina?

**Comment by kaalleen** [comment]
@fnavas00 While the problem you've got could be easily solved (https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac), you will not see anything but a white page when you finally succeed to run the print preview. Somehow we still have a problem with it when it comes to macOS, sorry for that.

**Comment by fnavas00** [comment]
Im still using Mojave

**Comment by classicmac** [comment]
One way to solve the problem is to right click on the "inkstitch-gui.app"application then select open. It will prompt you to confirm that you would like to open it. Once you do that it will not prompt you again.

Here are the steps to accomplish this:
1. In the Finder click the "Go" menu then select "Go to Folder"
2. Type or copy/paste this path in. ~/.config/inkscape/extensions/inkstitch/electron/ then click "Go"
3. Right click on the inkstitch-gui.app application and select "open"
4. A windows comes up asking if you are sure you want to open it. Select "Open"
5. When the application opens click the "inkstich-gui" menu and select "Quit"

That fixed it for me.

**Comment by kaalleen** [comment]
Closing the issue. The print preview wasn't working in this older release. It's working now (sadly not for Mojave).
