### ISSUE TITLE
extensions folder(s) don't actually exist

### ISSUE THREAD

**Issue by sewnawayfromhome** [inkstitch/inkstitch#562]
I'm having trouble installing InkStitch on my Mac (Catalina); InkScape is installed and as far as I can tell operating properly, but the folders it wants extensions installed into don't actually exist on the computer. I am usually a Windows user and having trouble understanding my hubby's Mac! Help!

**Comment by leafyrabbet** [comment]
Hiya! I haven't gotten things working but I ran into something similar just now. The folders exist for me, but I can say that the Inkscape v1.x beta version in macOS Catalina (`10.15`) is configured for the extensions to be in:

`~/Library/Application\ Support/Inkscape/config/inkscape/extensions/`

So you'd need to use that path instead of the one suggested in the "Manual Install" instructions for InkStitch:

`~/.config/inkscape/extensions/`

I've been trying the manual build from source and install into the top path, since that's where Inkscape is looking, but then I ran into this error:

```
Extension "Win32 Vector Print" failed to load because the extension is designed for Windows only.  This is caused by an improper .inx file for this extension.  An improper .inx file could have been caused by a faulty installation of Inkscape.
Extension "PostScript Input" failed to load because a dependency was not met.
Dependency:
  type: executable
  location: path
  string: ps2pdf
```

... which I'm currently still troubleshooting. I'll post a pull-request if I can fix it.

_Note_: In case you weren't aware, you should be able to Open "Finder" and use `CMD+SHIFT+G` to get the "Go To Folder..." drop-down and then you can copy the path above to get to that directory. Also you can double-check what Inkscape is expecting by looking in the `Edit > Preferences... > System` menu; there should be an entry called `User Extensions` that tells you where to install custom extensions like InkStitch. 

Hope that helps!

**Comment by DavidPhillipOster** [comment]
The comment from leafyrabbet commented on Oct 28, 2019 is obsolete:

1.) https://inkstitch.org/docs/install/ has bug the in the macOS link at the top, in the Video guide section: the macOS link goes to a youtube video https://www.youtube.com/watch?v=gmOVLNh9cu8&list=PLvlbfDmZyXG1ORmeqHdp4aP7J71e7icJP&index=3 that says it is obsolete.

2.) macOS Section 2, install, on that page, says for use Inkscapes Preferences dialog to see where it says to put them, and Inkscape 1.0 says to puts them in /Applications/3rd Party Apps/2D/Inkscape.app/Contents/Resources/share/inkscape/extensions This is terrible: everything inside the Inkscape.app directory should be treated as readonly, since the directory will be wiped out when Inkscape is updated, but it is what it is: (I'll file an Inkscape bug about that.)

2.) Section 2 continues with: "for Inkscape 1.0 the cd $directory is different, please check and confirm the directory in your preferences" but that prose will not be understood by most Mac users who never use Terminal.

3) Section 2 continues with a code fragment that describes cd'ing to a directory that Inkscape on mac ignores, further confusing Mac users.

# what I want you to do:

add a getting started video for installation video for Mac users that actually works for macOS 10.15 (Catalina) and, ideally, test it with macOS 11 (Big Sur)

Fix the main installation page:

macOS - Inkscape 0.99 : or earlier do this1
macOS - Inkscape 1.0 : do this2
etc, where each "do thisN" leads to a clean, simple, straightforward page with no branching so a novice can follow it without getting lost.
