### ISSUE TITLE
Inkscape 1.0 Extensions API

### ISSUE THREAD

**Issue by doctormo** [inkstitch/inkstitch#564]
I've just done a quick review of your extension for the Inkscape 1.0 release.

Your extension isn't ready for Inkscape 1.0, so you're going to get many deprecation warnings (I hope it's just warnings, I haven't run any tests).

The inkex module has been completely refactored and some modules you're using no longer exist. (such as cubicsuperpath, etc)

Some of your code may be redundant since inkex can do a lot more and a lot better than the collection of tools we had before. But what you upgrade is up to you.

I'm making myself available on chat.inkscape.org `#inkscape_extensions` to help extension authors with the upgrade for 1.0. Any questions can go here or there as you need.

**Comment by doctormo** [comment]
(addendum; I found where Moini had pointed you guys towards the new code last year. So you're all very much aware of the changes)

**Comment by lexelby** [comment]
Hi!  Thanks for reaching out.  We're in a fortunate position for the 1.0 release because we use PyInstaller to package our releases.  Since we bring our own inkex.py and friends with us, we won't be subject to deprecation warnings and other issues.  As far as I understand, the actual extension interface with Inkscape won't change, right?

Our plan has been to wait while the Inkscape Python libraries stabilize.  Once 1.0 is released, we'll start forming a plan to transition to the new libraries.  And assuming the Inkscape extension interface hasn't changed, we should be able to make a smooth transition and even retain compatibility with earlier versions of Inkscape.

**Comment by doctormo** [comment]
While I've not been involved in Inkscape's command line interface, it has changed. At least some of the extensions had to be changed when they called back into Inkscape. This happened I believe because of refactoring in Inkscape itself to use Gtk's own command line handling.

So it's worth checking to make sure. I believe the effected parts are verbs, but don't quote me on it

**Comment by lexelby** [comment]
Oh yes, I knew that verbs changed.  Fortunately we don't call back into Inkscape -- primarily because it's too hard to find the Inkscape binary.

I'm referring to the tiny where Inkscape writes the SVG to a temp file and passes it in as an argument, then expected the script to write a new SVG on stdout.

**Comment by doctormo** [comment]
Yes that's the same.

There's a new option that suppresses the "waiting for extension" popup for extensions that have their own user interface. This might be useful to you.

**Comment by lexelby** [comment]
Hmm, it might.  Inkscape still does actually wait though, right?

**Comment by lexelby** [comment]
Love this item from the release notes:

> Inkscape now adds itself to search path on startup, so you should always be able to call it from your extension by simply calling inkscape, without the need to add it to search path manually, or worrying about other potentially incompatible versions of Inkscape being available on search path.

That's going to be huge for us.

**Comment by doctormo** [comment]
Yes it still waits.

You should look at `inkex/commands.py` for the full API, we're trying to make it easier to self-call inkscape and that includes making it easier to call verbs etc.
