### ISSUE TITLE
lex @36c3

### ISSUE THREAD

**Issue by ARKopp** [inkstitch/inkstitch#596]
@lexelby are you at the caos communication congress?

**Comment by lexelby** [comment]
Nope, sorry :)

**Comment by kaalleen** [comment]
Wouldn't that be a thing for some other year?

This is really a very interesting place to go (I have bad luck though, because usually I have to be at work when it takes place:/ - between Christmas and new year). There is a lot creative and technical stuff to see, to learn. An Ink/Stitch workshop on the communication congress would be a really nice thing to have :D

**Comment by lexelby** [comment]
Maybe someday :)
