### ISSUE TITLE
Linux-en v.1.26.2 - Params Bug

### ISSUE THREAD

**Issue by TyHanks** [inkstitch/inkstitch#604]
Extensions Error Log:
`Extension "Win32 Vector Print" failed to load because the extension is designed for Windows only.  This is caused by an improper .inx file for this extension.`

When you click Params you get this error in the extensions log I deleted v1.26.2 and went back to version 1.24 and problem doesn't exist

**Comment by lexelby** [comment]
Wow, that's so weird, because Ink/Stitch doesn't contain anything called "Win32 Vector Print"...

**Comment by mudlight48** [comment]
Couldn't tell ya I haven't looked through the code enough yet to figure it out if I do I will submit a commit

**Comment by tyrosinase** [comment]
I just installed 1.27.2 and am getting the same thing. I thought I was on 1.26.2 before that, but I could be wrong.

Interestingly, it's smushed together with something else, doesn't have any other info:

`Extension "GIMP XCF" failed to load because a dependency was not met.
Dependency:
  type: executable
  location: path
  string: gimp

Extension "Win32 Vector Print" failed to load because the extension is designed for Windows only.  This is caused by an improper .inx file for this extension.  An improper .inx file could have been caused by a faulty installation of Inkscape.
Extension "Sketch Input" failed to load because a dependency was not met.
Dependency:
  type: executable
  location: path
  string: skconvert`

Now, maybe there's nothing else to say about it, but probably it should at least get a blank line to separate it from the next error.

**Comment by tyrosinase** [comment]
Backed down to 1.26.2 and things work again (print/realistic on 1.27.2 went off to la-la land) although it's still throwing that error in the log (and, as far as I know, has been indefinitely; I only check the log when things fail).

**Comment by kaalleen** [comment]
The messages in the error log really doesn't seem to be Ink/Stitch related. I get the same error log messages, even when I completely remove Ink/Stitch.

The other issue mentioned here is, that Ink/Stitch isn't working correctly?
What exactly happens when an Ink/Stitch script (every script or just specific ones) is called?
No error messages within the program itself?
