### ISSUE TITLE
Cannot get satin column via rungs to work. Are my paths too complex?

### ISSUE THREAD

**Issue by amordesoul** [inkstitch/inkstitch#615]
I've added the rungs (not in the screenshot) and made sure the inside and outside paths are lines (broken apart). Params indicates "path989: error: Satin column: Object has too few subpaths.  A satin column should have at least two subpaths (the rails)." Am I adding the rungs incorrectly or are my paths just too complex? 
![image](https://user-images.githubusercontent.com/7471258/74793582-bf81a600-528e-11ea-87b0-3d63369330b8.png)

I also tried taking just the outside path and using "Convert 
line to Satin." This is the result:

![image](https://user-images.githubusercontent.com/7471258/74793785-5fd7ca80-528f-11ea-86d0-5b70fd3beca2.png)

**Comment by tyrosinase** [comment]
When you get a string-art image like that, it usually means your paths go in opposite directions. Never seen convert-to-satin do that, but I don't use that tool much.

But what you'll want to do is break the line up further, because as it is the satin stitches aren't going to end up in quite the right places. Split it into four pieces - the upper and lower parts of the circle, and the two protrusions, and the stitching will come out more natural.

Then leave the ends of the stitching open (so each part is two separate paths, reversing one of the paths so you don't get string-art, and adding rungs as needed) and Bob's yer uncle.

**Comment by tyrosinase** [comment]
Basically, if you let Ink/Stitch try to figure out how to satin-stitch those intersections, you end up with something like this: ![bitmap](https://user-images.githubusercontent.com/9473609/74841488-c3491300-52f6-11ea-8ef3-d61521703b39.png)

You can fix some of the string-art of the upper version with rungs, but what you really want is two separate satin runs, as in the lower version.

(If you want rounded ends, the ends of the rail paths can curve toward each other and even meet; this was just a quick-and-dirty demo)

**Comment by amordesoul** [comment]
SUCCESS! You were right about the paths. The directions did not match (in reference to the bottom one created with "Convert line to Satin." ). In the top one, a bunch of nodes were broken up, so I had a bunch of different line segments instead of one continuous path. Obvious rookie mistake but so much for clarifying. :-)

**Comment by lexelby** [comment]
It's so weird that Convert to Satin produced a satin with rails going in opposite directions.  I'm working on an enhanced version of Convert to Satin that should work better on more complicated paths like this.

Anyway, I'm glad you got unstuck :)
