### ISSUE TITLE
Translation of video. 

### ISSUE THREAD

**Issue by Augusa** [inkstitch/inkstitch#620]
I have translated the video 2 on installation to french. It doesn't appear on video. I have something else to do?

**Comment by kaalleen** [comment]
Wow, great work.

I have uploaded a folder for the french subtitles and edited your translation into the three installation videos. I've also uploaded them to the YouTube channel.

If you want to translate more videos, tell us if you want to become a member of the Ink/Stitch YouTube channel, this way you'd be able insert the translated subtitles directly?
Otherwise you can inform us here, if you finished a file, so we can add it to the video.

Subtitle files can be found here (ready to be translated):
https://github.com/inkstitch/inkstitch/tree/gh-pages/assets/files/beginner-tutorial-series-subtitles/fr

**Comment by Augusa** [comment]
Thanks for your help. I think I will try to translate more videos. I wish to become a member of  the Ink/Stitch YouTube channel. Tell me please wath I have to do.
May be you can help me in another way if you have a look in issue #586. I am not able to finish my file for kerning just because I don't know how to separate my pairs in json file. It would be great if you know! Sorry if I ask to much.

**Comment by kaalleen** [comment]
I have send you a message over at #586 
Ask as much as you need to know. We really appreciate your work on Ink/Stitch!

To make you a member of the YouTube channel, we need your e-mail address. Then we can send you an invitation to the group.

**Comment by kaalleen** [comment]
@Augusa This time I want to ask you for a favor.
I've updated the installation page and didn't want the french part to fall behind. So I tried to recover my rusty french language skills, but I am not sure, if it came out ok... (french lessons from school are almost forgotten as time passes by).
Could you have a look at it?

**Comment by Augusa** [comment]
I will do it. It'not a problem.
I will also go on with videos translation. I give you my adress 
lyogau(at)hotmail.fr
Explain me how to do it when you have time.

**Comment by kaalleen** [comment]
I am not very confident at using YouTube and these videos are the only thing I've ever done on the platform. But I managed to invited you to the Ink/Stitch YouTube channel :D

After accepting the invitation, switch to the Ink/Stitch account.

For some reason the language always defaults to be Portugiese, even when you changed it to English on last login. I usually leave it as is, because I can manage to navigate through it (speaking Spanish and a tiny bit French makes it understandable to me). If you rather have it in french, click on the ink/stitch symbol in the top right corner and watch out for the term "idioma: ...".

On the left side go to the beginner tutorial playlist and open it. There you get a full list of all the tutorials. Open the one you've prepared subtitles for and click on "Edit Video".
On the right side click on "Subtitles".
From there you can open the "Add Language" dialogue, where you have to choose the language. This will add a new language to the list. Click on "Add" underneath "Subtitles". Now you can select the method. Choose "Upload a file" and select the srt file on your computer, which you translated before on the website (https://github.com/inkstitch/inkstitch/tree/gh-pages/assets/files/beginner-tutorial-series-subtitles/fr) 

Hope it helps?!? Don't mind to ask questions!

**Comment by Augusa** [comment]
Thanks for this message. Everything is allright (even french in the language of youtube!)except the very last step where my file srt is unknown when I want to add it. I copy it on github and don't understand where is the problem. 
Something more, The issue Inkstitch 1.27.2 with Sierra #634 has no answer. It is somebody of our french group and nobody can help. Have you an idea. She is very sad not have any answer.

**Comment by kaalleen** [comment]
> Thanks for this message. Everything is allright (even french in the language of youtube!)except the very last step where my file srt is unknown when I want to add it. I copy it on github and don't understand where is the problem.

YouTube doesn't know about our GitHub files. You have to add the file manually to YouTube.
After translating it on GitHub, you are able to download the srt file here: https://inkstitch.org/fr/tutorials/resources/beginner-video-tutorials/#03-customize
Use the "subtitles" link underneath the time tables. Hope this answers  your question?

**Comment by Augusa** [comment]
I have to copy sentences by sentences on the left side of the video?
________________________________
De : Kaalleen <notifications@github.com>
Envoyé : mercredi 11 mars 2020 17:18
À : inkstitch/inkstitch <inkstitch@noreply.github.com>
Cc : Augusa <lyogau@hotmail.fr>; Mention <mention@noreply.github.com>
Objet : Re: [inkstitch/inkstitch] Translation of video. (#620)


Thanks for this message. Everything is allright (even french in the language of youtube!)except the very last step where my file srt is unknown when I want to add it. I copy it on github and don't understand where is the problem.

YouTube doesn't know about our GitHub files. You have to add the file manually to YouTube.
After translating it on GitHub, you are able to download the srt file here: https://inkstitch.org/fr/tutorials/resources/beginner-video-tutorials/#03-customize
Use the "subtitles" link underneath the time tables. Hope this answers your question?

**Comment by kaalleen** [comment]
No no, you can upload the srt file to YouTube.

**Comment by Augusa** [comment]
I succeed to upload my file. But i had several errors. I have the new correct file but I am unable to get the good subtitles. The old one is always displayed. I don't know what must be done.

**Comment by kaalleen** [comment]
If these are only small corrections, you can edit the text on the left side in the editor.
If it's more than that, delete the translation and upload the file again.
If you need me to do it, just ask for it and I will ;)

**Comment by Augusa** [comment]
Everything is ok! Thanks
