### ISSUE TITLE
Random threads and stitches in designs

### ISSUE THREAD

**Issue by y123rena** [inkstitch/inkstitch#622]
I’m new to InkStitch- I keep getting random threads and stitches in my designs - even simple circles. Do you know if there is a setting that I missed?
![image](https://user-images.githubusercontent.com/61449477/75223294-be0f1c80-576b-11ea-9f23-fb98f8b7cb9a.jpg)

**Comment by tyrosinase** [comment]
That's underpathing. You can turn it off (there's a checkbox for both the fill and underfill), and Ink/Stitch will instead route its repositioning-stitching around the edge of the shape.

Depending on how the fabric pulls, the repositioning may not end up around the shape properly which is why underpathing is generally the default - but if you're doing a looser fill (for lace or whatever) the underpathing will show, so you can turn it off.

**Comment by lexelby** [comment]
Hi there!  Thanks for trying out Ink/Stitch, and welcome to our community!

The stitches you're seeing are called "underpathing".  When Ink/Stitch is planning a route to fill your shape with stitches, it often needs to travel from one section to another.  It has two options: travel around the border or travel in the middle of the shape (underpath).  

With underpath, it ensures that those travel stitches come before the rows of stitches in that area, so they're always covered up. It also avoids traveling in the same direction as the rows of stitches so as not to disrupt the visual pattern of the rows.  That's why you see zig-zags in some places.

You can disable underpathing with the checkbox in the Params extension.  You can see how the underpathing comes before the rows of stitches by using the Simulator extension.

I hope that helps :)

**Comment by y123rena** [comment]
Thanks so much l! I appreciate that.


Sent from Yahoo Mail for iPhone


On Tuesday, February 25, 2020, 7:25 AM, Lex Neva <notifications@github.com> wrote:


Hi there! Thanks for trying out Ink/Stitch, and welcome to our community!

The stitches you're seeing are called "underpathing". When Ink/Stitch is planning a route to fill your shape with stitches, it often needs to travel from one section to another. It has two options: travel around the border or travel in the middle of the shape (underpath).

With underpath, it ensures that those travel stitches come before the rows of stitches in that area, so they're always covered up. It also avoids traveling in the same direction as the rows of stitches so as not to disrupt the visual pattern of the rows. That's why you see zig-zags in some places.

You can disable underpathing with the checkbox in the Params extension. You can see how the underpathing comes before the rows of stitches by using the Simulator extension.

I hope that helps :)

**Comment by y123rena** [comment]
> That's underpathing. You can turn it off (there's a checkbox for both the fill and underfill), and Ink/Stitch will instead route its repositioning-stitching around the edge of the shape.
> 
> Depending on how the fabric pulls, the repositioning may not end up around the shape properly which is why underpathing is generally the default - but if you're doing a looser fill (for lace or whatever) the underpathing will show, so you can turn it off.

Thanks a million!
