### ISSUE TITLE
Sizing issue between Inkscape and machine

### ISSUE THREAD

**Issue by Robotorium** [inkstitch/inkstitch#625]
Hello,

We're using ink/stitch with a Brother Innovis 800E, and at first were able to determine the size of the embroidery by the sizing in Inkscape (using millimetres). Now the file gets resized, sometimes a lot and sometimes a little - sometimes made bigger, sometimes made smaller - and often we'll get it to the machine to find it's too big to load onto our biggest frame, even though in inkscape, the embroidery looks to be several centimetres below the maximum size.

Is this a known issue? What can we do to prevent it?

**Comment by lexelby** [comment]
Huh, I haven't heard of this happening at all.  The code takes great pains to ensure that dimensions in Inkscape match up with the dimensions of the sewn result.  It's really important!

What file format are you using, PES or DST?  What happens if you try the other format?

@tyrosinase You've done a lot of work on a Brother home machine, have you seen this problem?

**Comment by Robotorium** [comment]
We've been using PES, will give DST a go, see how we get on, and update
here. Thanks!

Op do 5 mrt. 2020 03:11 schreef Lex Neva <notifications@github.com>:

**Comment by kaalleen** [comment]
Would you mind trying how it behaves with this version, if it makes any difference?
https://github.com/inkstitch/inkstitch/releases/tag/dev-build-preserve-aspect-ratio

**Comment by kaalleen** [comment]
Is this issue still present in Ink/Stitch v1.28.0?

**Comment by Robotorium** [comment]
I'm not currently able to access the machine, let me update, then send a
file across to the person who is. Will let you know!

Op za 16 mei 2020 11:34 schreef Kaalleen <notifications@github.com>:

**Comment by kaalleen** [comment]
Wow, thank you! No rush. I was just curious to know on my way to clean up older bugs.
Hoping this has been fixed somehow ;)

**Comment by kalledi** [comment]
Having the same issue but I realised when I check the stitch plan - it's making my image 5 times larger without fail
Document is 10cm square, but when I do params and check stitch plan/outcome it's 50cm square. Can't make it stop doing this, so machine refuses to even load it

**Comment by kalledi** [comment]
Zipped inkscape file that shows the sheer disparity of my image vs what inkstitch thinks I want embroidered :(
[satinsat2.zip](https://github.com/inkstitch/inkstitch/files/4727071/satinsat2.zip)

**Comment by kaalleen** [comment]
In the objects panel (ctrl+shift+o) could you select the "group" a832 in Layer 1 and hit shift + ctrl + g. This will remove the group. You can regroup with ctrl + g if you like. After this operation your size should be fine. We do not check for link-groups when calculating the size, because we weren't aware of them to be existent.

**Comment by kalledi** [comment]
That's done it thank you. I mainly put them in as I'm not sure how else to organise the stitch routes and I was getting a lot of back and forth. Still learning - thanks!
