### ISSUE TITLE
Version 1.27.2 not at all in french

### ISSUE THREAD

**Issue by Augusa** [inkstitch/inkstitch#626]
Just desappointed to see that the v1.27.2 is allways in english.

**Comment by lexelby** [comment]
I'm disappointed too!! I thought I'd fixed that.  What OS?

**Comment by Augusa** [comment]
Windows. I tried to uninstall Inkscape without keeping my preferences. I killed everything from Inkscape or Inkstitch. I install again. Nothing better.

**Comment by danielkschneider** [comment]
This happens to others (actually most other people it seems) and it's a really weird bug since it is not systematic, i.e. I don't have this problem on windows 10 Professional installations. I don't know if this can help: It's absolutely impossible to switch InkScape to French or any other language without changing the Windows settings. E.g. if my display language is English then Inkscape won't change to French despite a correct preference.xml file that says french. Furthermore, if I switch both the system and Inkscape to English, then the french Ink/Stitch strings still appear (that is maybe wanted by you).

**Comment by lexelby** [comment]
Wow, that's not the experience I had when I tested this prior to release.  I found that if I changed Inkscape's setting to French, I got French in Inkscape and Ink/Stitch.

**Comment by lexelby** [comment]
It's especially weird that when you set the system and Inkscape settings to English, you still get French Ink/Stitch.  Do you mean all of the dialog text in Params is French?  Or just the Ink/Stitch entries in the Inkscape Extensions menu?

**Comment by danielkschneider** [comment]
I get this on this on a Win10 Pro machine:
1. Win = en_CH, Inkscape = English (en) : Inkscape in English, Menu in french, Panels in English
2. Win = en_CH, Inkscape = French (fr): Inkscape in English, Menu in french, Panels in French (weird)
3. Win= fr_CH, Inkscape = French (fr): Inkscape in french, Menu in french, Panels in French (good, but Augusa and lots of others don't manage to get that)

I changed Win using the normal "language settings" panel in Windows. Also fr_FR or plain fr seems to have the same effect as fr_CH (I tried yesterday). I changed the language in Inkscape using the preferences menu. Inkscape 1.0Beta2 seems to behave in the same way.

An idea: I wonder if some folks have unset windows and inkscape preferences (i.e. use system defaults that you code does not deal with).
- daniel

**Comment by lexelby** [comment]
Okay, my experience mirrors yours so far.  I tested your scenario 2 and got the same result.

If they unset both windows and inkscape language preferences, then Ink/Stitch will show its panels in English, _even if you choose the fr_FR ZIP file_.  The Ink/Stitch menus in Inkscape will be French.

That probably doesn't make much sense, does it?  Here's why it happens.  The translation system Ink/Stitch uses (Gettext) will default to the language that the strings in the code were written in (English in our case) if a language is not selected by the user.

The language of the Ink/Stitch menus in Inkscape's Extensions menu is dictated by which ZIP file you download.  That's because Inkscape doesn't offer a good way for extensions to get their menus translated[1].  That's the _only_ effect that the selection of the ZIP file causes.  It's totally possible to download the `fr_FR` ZIP file and set your system language to `de_DE`, so you'd have French Ink/Stitch menus in Inkscape and German Ink/Stitch UI panels.  Weird, but possible. :)

Does that help explain what's going on?  Ultimately I hope we can add a way to override Ink/Stitch's language in case all of this doesn't work properly.

**Comment by danielkschneider** [comment]
OK, so if I understand right I have to tell the french users to explicitly set the language in their Windows and in the InkScape preferences to fr. Since I got a multilingual Windows Professional my PCs may behave differently than theirs.

So for starters, I will ask them to check again both settings.

To recall the problem: A majority of users in the France cannot get Ink/Stitch in French despite trying to install/reinstall etc. for hours.

**Comment by lexelby** [comment]
It should be enough to just set the language in Inkscape.  That worked in my testing.

**Comment by Augusa** [comment]
![pref-langue-fr](https://user-images.githubusercontent.com/54963659/76142786-21088980-6071-11ea-9122-185464714097.JPG)
An image for those who need help. I was looking for it a long time!

**Comment by kaalleen** [comment]
@Augusa thanks for the image. I've updated the F.A.Q. pages to include a description. When you find the time, could you translate the french part of it?

I've inserted it in english into the french translation: https://github.com/inkstitch/inkstitch/blob/gh-pages/collections/_docs/fr/005-001-faq.md

**Comment by Augusa** [comment]
The translation is online. Thanks
