### ISSUE TITLE
Menu Disabled

### ISSUE THREAD

**Issue by MBarrie53** [inkstitch/inkstitch#655]
I am running macOS Catalina 10.15.2 and Inkscape 1.0. I downloaded v1.27.2 and successfully added it to the extensions folder for Inkscape. The extension shows up in the menu. But all of the options are always disabled. I was following the instillation tutorial so I converted a shape to a path and selected it but still all of the menu items for Ink/Stitch are disabled. Am I doing something wrong? Thank you. Very excited to start using it.

**Comment by MBarrie53** [comment]
I also tried the 1.1 Development build of Inkscape and that has the same issue for me. The extension shows up but even when a path is selected all of the options are disabled.

**Comment by kaalleen** [comment]
Hm, we have seen issues like that before, but we didn't fully understand why it happened.

Mostly it was due to a wrong package for an other operating system or something like that. So I am just making a guess into the blue.

Could you double check, if you have downloaded the correct zip-file for macOS?
The packages are also linked on our website: https://inkstitch.org/docs/install/#1-download

Installation for macOS Catalina also likes to cause issues because of verification issues. In this case, you need to perform a special way of downloading the file as described on our website as well: https://inkstitch.org/docs/install/#macos

Hope this helps a little?!?

**Comment by palladionIT** [comment]
I just had the same issue and I am not sure what happened exactly. I noticed that with my installation I was also missing all the default extensions so I guess my install was messed up. I downgraded from "bleeding edge" (inkscape-git provided by the arch user repositories) to the provided *.appimage of the Inkscape project and now it works. I guess it might be more of an Inkscape issue and not an inkstitch issue.

Maybe your issue is related and maybe this helps you.

**Comment by MBarrie53** [comment]
@kaalleen Thank you so much. I guess the issue was the version of the extension I had because I downloaded it from the link you send and it worked great. I really appreciate the help!

**Comment by kaalleen** [comment]
Great, thank you for your report.

@Augusa I've updated the F.A.Q. to include this issue. I know, you are still busy with the subtitles, but when you find the time, could you translate it to french? Also have a look at the sentence above the "The system cannot find the file specified" error message. I tried myself to translate it to french, but it might not be a good translation :D It is about the antivirus thing, which is really disturbing for a lot of users. So I included the error message for a better recognition of the issue.
