### ISSUE TITLE
Ink/Stitch ignores layer style settings

### ISSUE THREAD

**Issue by davepoulsen** [inkstitch/inkstitch#661]
I have a Python script that generates cool drawings (see original.svg attached).  This imports into Inkscape just fine, but Inkstitch says that it's not path elements so can't process it.

The saved.svg is the result of importing original.svg then saving it in Inkscape format.

Just installed the latest Inkstitch today (MacOS) and using Inkscape 0.92.

I'm wondering if simple changes to the SVG in original.svg would provide a work-around, since perhaps I did something your extension didn't expect.

[Archive.zip](https://github.com/inkstitch/inkstitch/files/4489670/Archive.zip)

**Comment by davepoulsen** [comment]
Experimenting a bit, the immediate problem is due to the <def> <use> pattern.  I need to be able to do this for other types of drawings I want to generate.   Is there any way to support this use of paths?

**Comment by davepoulsen** [comment]
Specifically I installed Inkscape v1.26 for OSX Mojave.  BTW, I don't see the Stroke tab and manual-stitch mode which is what I wanted to use for these paths.  How come these don't appear?

**Comment by lexelby** [comment]
@kaalleen is in the process of writing code to support use tags.

Until then, you can use Edit -> unlink clones to convert to a regular path, would that work for you?

**Comment by davepoulsen** [comment]
Thanks...I'll try the workaround, and keep me posted on the feature above!

**Comment by kaalleen** [comment]
Wow, this is a very interesting file, thank you for posting it!!

The above mentioned pull request will solve the problem of the clone objects... but it shows an other interesting issue: the style attributes are set to the group only, which will be understood by Inkscape. Ink/Stitch instead will try to set the standard black fill, which fails because of border crossing in a fill object. Means, we will have to check on the layer groups for styles as well if no style is set.

**Comment by davepoulsen** [comment]
Yeah, I subsequently reworked my SVG to put the style next to the path to get Inkstitch to work.  But it would also be nice if I didn't have to do that so I could have a global style instead of replicating it per path.  Or having the style in the defs.  This isn't nearly as important as the issue I originally reported tho.

**Comment by kaalleen** [comment]
Well, the rest (clones) is already being worked on. You can try it out if you like and report back?
https://github.com/inkstitch/inkstitch/releases/tag/dev-build-svg-objects
(It will only work if you adapt your styles.)

One additional note: Clones of deeper levels are not supported yet. We decided to wait for Inkscape 1.0 to do so, because it brings in new features, which will make it a lot easier to implement them.
