### ISSUE TITLE
inkstitch not showing up under extensions 

### ISSUE THREAD

**Issue by hobo87** [inkstitch/inkstitch#669]
Hi, i'm new to inkstitch but very familiar with inkscape. I extracted the latest inkstitch (inkstitch 1.27.2) into the user extensions file (i watched the video) in inkscape (version Inkscape 0.92.40), but when i restart inkscape, inkstitch does not show up in extensions. What can I do?

**Comment by kaalleen** [comment]
Hm, could you double check if the Ink/Stitch files are directly in the Inkscape extensions folder?
It should look something similar to this: https://inkstitch.org/docs/install/#2-install

**Comment by hobo87** [comment]
Yes it is there.

**Comment by kaalleen** [comment]
Hm, no additional subfolder present?

**Comment by hobo87** [comment]
What do you mean by subfolder? It’s in the user extensions folder that I located through the preferences part of Inkscape. I can see it there in the correct folder but I cannot see it when I open Inkscape. I extracted it directly into that folder like the instructions said.

**Comment by kaalleen** [comment]
Usually we have seen this issue, when a subfolder was present. That's why I am so insistent on this question. A subfolder would mean, that inside the extension folder you would have an other folder named 'inkstitch' or so. And only in this folder you've got all the .inx-files, a inkstitch.py file and an other folder named inkstitch.

I could be wrong, because it looks like, that you've taken care for it being directly in the extension folder. I wouldn't know what the issue would be in this case. Which operating system are you using?

**Comment by hobo87** [comment]
using windows 10. when i look at the extensions errors it says "dependency
was not met" and then it lists the dependencies for different fails:

Extension "Dia Input" failed to load because a dependency was not met.
Dependency:
  type: executable
  location: path
  string: dia
  description: In order to import Dia files, Dia itself must be installed.
You can get Dia at http://live.gnome.org/Dia

Extension "DXF Output" failed to load because a dependency was not met.
Dependency:
  type: executable
  location: path
  string: pstoedit
  description: pstoedit must be installed to run; see
http://www.pstoedit.net/pstoedit

Extension "EPS Input" failed to load because a dependency was not met.
Dependency:
  type: executable
  location: path
  string: ps2pdf

Extension "LaTeX" failed to load because a dependency was not met.
Dependency:
  type: executable
  location: path
  string: latex

Extension "LaTeX" failed to load because a dependency was not met.
Dependency:
  type: executable
  location: path
  string: dvips

Extension "LaTeX" failed to load because a dependency was not met.
Dependency:
  type: executable
  location: path
  string: pstoedit

Extension "XFIG Input" failed to load because a dependency was not met.
Dependency:
  type: executable
  location: path
  string: fig2dev

Extension "GIMP XCF" failed to load because a dependency was not met.
Dependency:
  type: executable
  location: path
  string: gimp

Extension "PostScript Input" failed to load because a dependency was not
met.
Dependency:
  type: executable
  location: path
  string: ps2pdf

Extension "Sketch Input" failed to load because a dependency was not met.
Dependency:
  type: executable
  location: path
  string: skconvert

**Comment by kaalleen** [comment]
Thank you for having a look into it. These messages are all about other extensions though. On each block you can see the extension name in the first line. So this sadly doesn't give us any clue what is going wrong with your installation.

Ink/Stitch should show up in the extensions menu as soon Inkscape spots the '.inx' files. In your case it looks like it doesn't seem to find those files for whatever reason.

There is only one workaround I could think of by now. Instead of copying the files into the `User extensions` folder, try to put them into the `Inkscape extensions` folder. You can look it up as follows:
Edit > Preferences > System > Inscape extensions

Hope this will help?!?

**Comment by crouserj** [comment]
I've been having a similar issue.  I'm running inkscape 0.92, as when I try in 1.0 the inkstitch menu is completely grayed out. The first time I launch inkscape 0.92 after adding the extensions to the extensions folder (with no subfolders), it shows up, but when trying to run "params" or "install add-ons" an empty box pops up then disappears ("instantaneously"), and nothing happens. If I close inkscape and reopen a second time, the inkstitch extensions menu is empty. With that, I get a long list of extensions errors in the log. I'll try putting in the Inkscape extensions and comment back on how that goes.

Extension "Auto-Route Satin Columns" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "Break Apart and Retain Holes" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "Convert Line to Satin" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "Cut Satin Column" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "Embroider" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "Flip Satin Column Rails" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "Add Commands" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "Import Threadlist" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "100 file input" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "10O file input" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "BRO file input" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "DAT file input" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "DSB file input" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "DST file input" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "DSZ file input" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "EMD file input" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "EXP file input" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "EXY file input" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "FXY file input" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "GT file input" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "INB file input" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "JEF file input" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "JPX file input" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "KSM file input" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "MAX file input" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "MIT file input" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "NEW file input" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "PCD file input" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "PCM file input" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "PCQ file input" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "PCS file input" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "PEC file input" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "PES file input" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "PHB file input" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "PHC file input" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "SEW file input" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "SHV file input" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "STC file input" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "STX file input" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "TAP file input" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "TBF file input" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "U01 file input" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "VP3 file input" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "XXX file input" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "ZXY file input" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "Install add-ons for Inkscape" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "Add Layer Commands" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "Lettering" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "Attach Commands to Selected Objects" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "DST file output" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "EXP file output" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "JEF file output" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "PEC file output" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "PES file output" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "TXT file output" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "U01 file output" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "VP3 file output" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "Params" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "Print / Realistic Preview" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "Remove embroidery settings" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "Simulator" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "Stitch Plan Preview" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "Troubleshoot Objects" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

Extension "embroidery ZIP file output" failed to load because a dependency was not met.
Dependency:
  type: file
  location: extensions
  string: inkstitch/bin/inkstitch.exe

**Comment by kaalleen** [comment]
Hm, yes. It doesn't find any of the Ink/Stitch extensions because inkstitch.exe is missing. This is probably caused by your antivirus software. We have observed this issue quiet often.

**Comment by kaalleen** [comment]
Reference: #710
