### ISSUE TITLE
error trying to simuate fill-stitch.svg example

### ISSUE THREAD

**Issue by machow** [inkstitch/inkstitch#681]
Hey--thanks again for your work on inkstitch, I've been able to stitch a couple patterns!

I'm having a little trouble simulating the example SVG in the website's [fill-stitch tutorial](https://inkstitch.org/docs/stitches/fill-stitch/#what-it-is), since it raises a "Shape is not valid error". It looks like the path is big filled shape for the bear's head, with some patches differenced out.

Any idea what it might need to simulate / embroider?

![image](https://user-images.githubusercontent.com/2574498/80898660-0995f780-8cd4-11ea-805f-35f55471cb2c.png)

**Comment by kaalleen** [comment]
Oh yes, we are seeing this error a lot lately. It happens mostly on circle like shapes. It is a bit annoying, sorry for that. @lexelby is working on a solution, but it may take a while due to time issues.
For now you can try to move to nodes around a little, this will often solve the problem. Also use the troubleshoot extension to try to figure out which exact nodes are causing the trouble. Sometimes it helps to switch the node types around (smooth nodes, auto smooth, symetric, etc.)

**Comment by kaalleen** [comment]
Sorry for my too fast response. From only looking at the picture I thought it had a lot of circle like shapes and this was causing the issue. Actually there was an other error in the image (duplicate node). Thanks for bringing it up to our attention. I fixed it and pushed the updated version to our website.
