### ISSUE TITLE
Ink/Stitch is unable to launch extension dialogs

### ISSUE THREAD

**Issue by aloxyz** [inkstitch/inkstitch#699]
When trying to execute an extension option such as _Lettering_ or _Params_, nothing happens. By launching Inkscape in a bash shell this shows up:
`Can't Spawn!!! spawn returns: Failed to execute child process “” (No such file or directory)`
This happens with every option except _Embroider..._ and _Remove Embroidery Settings..._

**Comment by kaalleen** [comment]
We heard about this issue before and haven't fully understood why it is happening.
If you answer some questions we maybe can find the reason of it.
1. Which Inkscape version are you using (1.0?)
2. How did you install it?
3. Are you working on a linux system (or which other os)?
4. Which Ink/Stitch version are you working with?

If it's not too much of a trouble it would be nice, if you could test a newer development version such as e.g. this one https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-break-apart-v2

Since the last release we removed the stub.py file, so it is possible, that a newer release solves the issue. I suspect this to be happening because of a wrong python interpreter (Ink/Stitch uses python 2.7). You could change it in the preferences file, but it would be interesting, if a newer Ink/Stitch version would solve the issue.

**Comment by aloxyz** [comment]
My inkscape version is 1.0, installed via apt on Ubuntu GNU/Linux 20.04. I am working with the latest Ink/Stitch version.

**Comment by kaalleen** [comment]
Just as I thought. Also troubles with the developer version?

Thanks by the way for your translations, they will be included in Ink/Stitch soon ;)

**Comment by aloxyz** [comment]
I just did a fresh install of Ubuntu GNU/Linux 20.04 and that seems to have solved the problem for some reason. Albeit opening extension menus take a long time, i don't know if that's normal or not (no errors in bash). I'm happy that you appreciated my translation!
