### ISSUE TITLE
Print function in print preview not working

### ISSUE THREAD

**Issue by kaalleen** [inkstitch/inkstitch#707]
The 'print' and 'save as pdf' buttons in the print preview won't do their job anymore.

**Comment by LochanLoch** [comment]
under debian I can confirm that problem. Both versions from stable and the backport inkskape do no print.

**Comment by tyrosinase** [comment]
Oh hey, same here (buster, Inkscape 0.92, Ink/Stitch whatever-I-downloaded-a-few-days-ago).

But also I have both Simulate and Simulator so, uh, clearly I need to do a little cleanup around here.

**Comment by LochanLoch** [comment]
Little update while testing a bit around in InkStitch Version 1.26.2 there work the pdf export and print button. Not any more in 1.28.0

**Comment by tyrosinase** [comment]
Update! Neither the print nor the simulator work for me *when there is a problem with the embroidery*. Simulator gives the little spinner but doesn't actually throw the "path overlaps itself" or whatever until you cancel the simulation.

Once the problem is fixed it works fine.

(Although again, caveat, I didn't clean-install the new Ink/Stitch so it may just be me. I should fix that.)

**Comment by lexelby** [comment]
I just ran into this too.  How annoying!  I really wanted a PDF...

I seem to be unable to save/print even though my design doesn't have any issues/errors with Embroider or Simulator.

**Comment by lexelby** [comment]
Turns out that this was a casualty of v1.28.0.  Whoops!
