### ISSUE TITLE
SatinColumn Start/End Points

### ISSUE THREAD

**Issue by wwderw** [inkstitch/inkstitch#74]
Swapping the stitch order of a Satin Column is possible, but it's a pain and you lose all of your embroidery parameter settings.  It should be pretty easy to write an extension to swap the order.  Later on, this extension could be turned into a more generalized tool to set the starting/ending points for all kinds of embroidery objects, not just satin columns.

original issue description follows:

---------------------------------------------

I know we can't on the fly change start/end points of various embroidery objects.  However, given that we can predict run stitch start and end points due to the 1st and last node, could we do the same thing with SatinColumns?

Given the attached:

![satincolumn setup](https://user-images.githubusercontent.com/24878362/36114977-3b694822-0ff7-11e8-9deb-514f69fdd34f.png)

Do you think that would be possible?  Just something to help predict start/end points.  I don't necessarily know how we would be able to get it done for fills, but if we can help predict start/end points that would preclude the need to be able to have on the fly editing abilities for start/end points.

I know I used a simple shape for this example, but this should be able to be applied to any SatinColumn object regardless of shape (just so long as it doesn't confuse the extension for rendering stitches).

**Comment by lexelby** [comment]
Actually, the start and end point are completely deterministic, but this isn't documented well.  It always starts at point 1 and ends at point 4.

The real question is, what dictates which of the two rails are points 1 and 2?  Inkstitch looks at which of the two lines comes first in the path object.  The first one has points 1 and 2.

To change the order of the segments in a satin column, do Break Apart (ctrl-shift-K) and unselect them.  Then select them in order (start line and then end line) and do Combine (ctrl-k).  You'll have to set the satin column up again using Params because inkscape will have cleared the embroidery xml attributes.

The order of points 1 & 2 is dictated by the direction of the two lines.  There's an option in Inkscape's settings to show little red arrows as direction markers.

End result: you have complete control already, it just isn't very discoverable.  I was thinking of maybe adding an extension to reverse the order of the rails in a satin column; what do you think?

**Comment by wwderw** [comment]
> End result: you have complete control already, it just isn't very discoverable. I was thinking of maybe adding an extension to reverse the order of the rails in a satin column; what do you think?

I would say have to where it would reverse with a checkbox or something along those lines.

I had the object setup as shown in the screenshot, but it resulted in an opposite stitchout.  I would have thought that what was drawn first would be the first side, but it seems like I was getting different stitchouts.  For some, I also had the stitch angles for the more complex satin columns and I wasn't paying enough attention to see if that was playing a part in the result as well.

Something that makes it quick to reverse would be good.  Also, just in case someone forgets the order of the lines and this would keep from having to re-do the vectoring.

**Comment by lexelby** [comment]
Can I satisfy your need with a new extension, rather than a checkbox in Params?  I have in mind an extension that would handle this kind of ordering stuff and show a live preview like Params.  This would be a basic first step.

**Comment by wwderw** [comment]
When it comes to implementation, I'll go with whatever you think is best.

This is your wheelhouse.
