### ISSUE TITLE
Offtopic: CNC/lasers

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#745]
I bought and returned a Cricut Maker because I mistakenly thought that being able to have a gear-driven rotary cutter and knife blade would make up for the proprietary software and YOU GUYS I WAS SO WRONG

I didn't even get a chance to test it on some marine vinyl before they "accidentally" locked out all user-created SVGs. So anyway, I'm back to contemplating ways to cut vinyl that isn't my wobbly hands. I know lexelby cuts polyester patch material with a laser, but I'm not sure that'd work on marine vinyl - in part because it's thick, but also because while it's usually polyurethane over polyester, sometimes it's actually vinyl-vinyl and that can cause some tiny little problems with laser cutting. (Nothing major, just harmless hydrochloric acid fumes...)

Before I go get the Dremel and start experimenting, has anybody already figured out how to cut fabric with, say, one of these? https://www.sainsmart.com/products/sainsmart-genmitsu-cnc-router-3018-pro-diy-kit Because honestly I'd like one just to play with (with or without the laser), but if I can cut blanks with it then it's a no-brainer. And even if not, does anybody have a trusted site that compares these sorts of machines?

(On the 2D front, I do have an aging Cameo 1 which runs fine on https://github.com/fablabnbg/inkscape-silhouette but its gears are getting pretty worn and I'm pretty sure anything heavier than cardstock or vinyl-the-adhesive-kind-not-the-faux-leather-kind would be the end of it. I do wonder about newer Cameos though, but AFAIK they are all just the dragging-blade kind.)

**Comment by wwderw** [comment]
I use a Roland GX24 for my cutting needs.  To cut fabric, I use Madeira's Applique cut magic as backing and then cut on the Roland.

If running Linux, can setup the Roland as a printer with RAW HPGL and have it act as a "printer" directly in Inkscape or use InkCut for more control.  If you use the former option, everything would need to be setup by you (nesting, weeding box etc).

**Comment by lexelby** [comment]
Ooh, I'll have to check out that Madeira stuff.  I have a summacut d60 but when I tried to do fabric on it, the fabric ripped and frayed.  Does the Madeira stuff prevent that?

@tyrosinase Yeah, watch out for those vinyl fumes!  Aside from that, it can be hard to laser cut clear, white, or reflective stuff with these single-digit-wattage lasers, because they don't absorb enough light.

I have a 3018 clone, that's what my 2.5W laser is mounted on.  I've never even tried its milling capability.  No idea if you could cut vinyl with it but I doubt it, I would think it would tend to pull up and throw the vinyl.

I use inkstitch to create the g-code I use for lasering and I send it to the 3018 with bCNC.  Works pretty well.

I have had good luck cutting thick stuff on my silhouette portrait by making multiple passes.  Don't write your cameo off just yet.  Maybe try 10 passes with a fairly light pressure?  It might get through without dying.

Barring that, your best bet is probably a professional vinyl cutter.  I think you can get one for a couple hundred, barely more than a new Cameo.  Yes, they do use drag knives, but they're quite powerful, fast, and extremely accurate.  At least, my summacut is.

**Comment by wwderw** [comment]
> Ooh, I'll have to check out that Madeira stuff. I have a summacut d60 but when I tried to do fabric on it, the fabric ripped and frayed. Does the Madeira stuff prevent that?

It works very well, although they do not market it for this application specifically.  It will need a heat press or iron (although the heat press would be the best to use).

I also had to get the appropriate knife for fabric work as well.  At least for my Roland.  It may be different for Summa.

**Comment by tyrosinase** [comment]
My Cameo might just need torn down and rebuilt, but it's gotten rather loud over the years: https://photos.app.goo.gl/8dnUaC3YYAA9au7K9

And yeah, I'm really not sure a rotary tool is gonna cut before it just twirls the marine vinyl (I see "PU leather" used often, which I guess is what I should say to avoid confusion with signmaking vinyl) up, though possibly something like the adhesive mats the Cricuts use might make it possible.

I've never used the Madeira stuff but I've done a little with Heat-n-Bond which is maybe the same thing (I bet Madeira's is smoother though). The blade has to be very sharp, and that Inkscape extension I mentioned has a little "serif" that it does to try to orient the knife properly and that seems to work well.

I had not heard of InkCut, I may have to try that out. See, this is why I love the Cameo/Craftrobo. I helped relatives deal with Sure Cuts A Lot to bypass Cricut's early lock-in, I should have *known* they wouldn't have gotten any better over the years.

lexelby, how did you choose your 3018 clone? There's so many gibberish-named companies selling them, I feel like picking the one with the nicest website is not necessarily going to be the best way to find the most reputable seller but dang there's not much else to distinguish them.

**Comment by lexelby** [comment]
Ouch, that cameo is sick. :(  I'm amazed it still cuts properly.  I wonder if some "extra" piece broke off and got wedged...

I chose my 3018 clone by looking on ebay for the cheapest one that came with a laser and didn't have terrible seller reviews. ;)

... And I ended up regretting it a bit.  A few weeks into using it, the control board caught fire.  Yes, actual fire.  I believe they didn't tune the stepper motor drivers properly so they were drawing too much current and one of them burned out the board.

I ended up buying a basic Arduino grbl shield and a set of stepper drivers and rewiring the thing myself.  The motors and the cnc rig were all still fine.  It was much less difficult or expensive to get it up and running again than I had expected.  Just around $15 since I already had an old Arduino kicking around.  Happy to help if you run into a similar problem.

**Comment by tyrosinase** [comment]
It's sounded like that for a long time (admittedly the phone was right up in its grill) and works fine.

We have plenty of Arduinos around but dang, maybe I should just build one from scratch.

(Should probably get the 3d printers up and running again first...)

**Comment by lexelby** [comment]
Oh, hmm.  It may be fine then.  My silhouette has always made a somewhat alarming grindy noise as the little stepper motors quickly change directions.

And yeah, it's worth considering building your own.  There are also cnc kits, with all the rails and motors and whatnot.
