### ISSUE TITLE
Cannot open PES file

### ISSUE THREAD

**Issue by CELIAIMBERT** [inkstitch/inkstitch#761]
Je ne peus pas ouvrir mes fichiers format .PES dans inkscape pour modifier avec inkstitch.
la plus part des fichiers viennent du site Brother en telechargement gratuits.

**Comment by tyrosinase** [comment]
What happens when you try? I downloaded the one from http://blog.brothersews.com/projects/embroidered-outdoor-vest/ and Ink/Stitch opens it fine. Have you unzipped it first?

Que se passe-t-il lorsque vous essayez? J'ai téléchargé celui de http://blog.brothersews.com/projects/embroidered-outdoor-vest/ et Ink/Stitch l'ouvre bien. L'avez-vous décompressé en premier?

**Comment by CELIAIMBERT** [comment]
Bonjour,

Je vous joint le message d'erreur.

Le lun. 6 juil. 2020 à 00:38, Tyrosinase <notifications@github.com> a
écrit :
