### ISSUE TITLE
Gradient Fill

### ISSUE THREAD

**Issue by X3msnake** [inkstitch/inkstitch#78]
How hard would it be to implement the exponent algorithm used in interpolate as a modifier for the stitch spacing for Fill and Satin ?

![screenshot from 2018-02-20 01-41-22](https://user-images.githubusercontent.com/11083514/36403892-917c1b02-15df-11e8-9401-6a884d84dcab.png)

![screenshot from 2018-02-20 01-40-13](https://user-images.githubusercontent.com/11083514/36403890-90442f9a-15df-11e8-894f-dd8044acc4b9.png)

This would be very usefull for colour blending

![image](https://user-images.githubusercontent.com/11083514/36404082-b1472296-15e0-11e8-8ac2-af1e4c5e8399.png)

[image reference page](https://forum.embroideres.com/blogs/entry/73-embroidery-experience-blending-part-2-advanced-blending-techniques/)

**Comment by lexelby** [comment]
Definitely doable!  The math is easy.  The tricky bit is figuring out where the stitches in each row should fall, but it's definitely a solvable problem.  Great feature idea.

**Comment by wwderw** [comment]
That'll be a great way to quickly get out color blends.  The top row is a good translation of what some commercial programs do now.

The old way, we would have to break each section down and do it separately for the changes of density in the "levels".

**Comment by X3msnake** [comment]
#108

> BONUS CONTENT!
> 
> This version unlocks a hidden feature I used for gradient blending on this patch. If you use the XML editor to add the hidden setting embroider_end_row_spacing_mm.
> It isn't quite ready for prime-time, so I haven't added it to the UI yet. Notably, certain shapes with complicated holes seem to cause the autofill algorithm to run forever and never finish, and you have to kill the process manually. But for most shapes, it seems to do the job. Combine two such fills going in opposing directions and you'd get a gradient fill.
>
> by Lexelby

Here's a example

![image](https://user-images.githubusercontent.com/11083514/38469632-dc97b73c-3b4f-11e8-9044-c03d1f5d17ab.png)

**Comment by lexelby** [comment]
We had some discussion of gradients in #375.  I've renamed this to Gradient Fill to reflect what users really want out of this feature.

I've learned a bit from doing Auto-Route Satin and Lettering.  I wonder if the best way to implement this might be something like this:

1. User creates a fill shape with a standard SVG gradient on it.  That is, they can tweak the gradient however they like and they'll see it as a true gradient in Inkscape.
2. User runs an extension, Convert Gradient to Embroidery
3. Ink/Stitch breaks up the fill region into overlapping sections that use `embroider_end_row_spacing_mm` to make the gradient.

That way, the user can tweak it as needed.  Of course, we'd need to expose the "end row spacing" option in the Params window.

**Comment by ecc521** [comment]
Breaking up the object into multiple regions in order to apply a gradient fill feels like the wrong approach. I've done a bit of testing with embroider_end_row_spacing_mm, and it feels like a slightly tweaked version of it could work wonders. 

Right now, two of those fills in opposite directions don't work all that well - stitch density is much higher at the edges than in the center, leading to lots of white space, especially with higher end_row_spacing values. I'm also slightly concerned about how it does when the colors used in the gradient are vastly different. 

My thought are as follows:

Blend Strength - Similar to embroider_end_row_spacing_mm, however the total stitch density must be exactly half of what the object would be if it was solid (stitch density at any portion of the object [ex, 20% from top] must be the additive inverse of it's counterpart [ex, 20% from bottom]). Not sure exactly how you'd want to implement this - would probably require quite a bit of tweaking. 

Offset - portion of the shape that will omitted from the gradient (ex, .2 means the top 20% of the object will be entirely solid, and the bottom 20% entirely empty). This could be used when blending two heavily contrasting colors, to avoid a few stray threads looking really ugly. Default should probably be 0, but no higher than 1/3. 

This would allow for two identical shapes on top of each other to form a configurable gradient. All of this break-up could probably be done internally, as to allow for real gradient fill support. Shapes with more than 2 color stops could be broken apart internally (probably somewhat complex), using 2 additional gradients for every additional color stop.
