### ISSUE TITLE
When I create a square and click on params, this is what I get

### ISSUE THREAD

**Issue by felipesilvati** [inkstitch/inkstitch#783]
This is the project that I created:

![image](https://user-images.githubusercontent.com/33382449/90314971-0a9f0d80-deee-11ea-8930-3820f8c8ad8e.png)

This is what params preview is showing:

![image](https://user-images.githubusercontent.com/33382449/90314979-1985c000-deee-11ea-94c9-a6b63e459c5a.png)

Is this a problem or I am seeing the "Cursor moving" in the preview? I'm using Windows 10 Home Version 1909 with Inkscape 0.92.4 (5da689c313, 2019-01-14)

**Comment by tyrosinase** [comment]
Are you asking about the off-grid zigzags? That's underpathing. You can turn it off, and it will path using the outer edges of the fill (which may result in outlines separated from the fill in the actual stitchout because of pulling). Normally, unless you're using a fill that's less than full coverage for some reason (like for special-effect fills: https://silverseams.com/2020/08/special-effect-fills-with-ink-stitch/ ) the underpathing will be covered up.

**Comment by LochanLoch** [comment]
Or more controll with start fill and end fill commands like that test file ... rename txt to svg ;-)
[testfill00.svg.txt](https://github.com/inkstitch/inkstitch/files/5079195/testfill00.svg.txt) or the 
![2020-08-15_19-11-41](https://user-images.githubusercontent.com/66974900/90317872-a2bbe780-df2c-11ea-8c4a-1ad96ac3aca6.png)is enough to explain it.

**Comment by fukubei** [comment]
> Or more controll with start fill and end fill commands like that test file ... rename txt to svg ;-)
> [testfill00.svg.txt](https://github.com/inkstitch/inkstitch/files/5079195/testfill00.svg.txt) or the
> ![2020-08-15_19-11-41](https://user-images.githubusercontent.com/66974900/90317872-a2bbe780-df2c-11ea-8c4a-1ad96ac3aca6.png)is enough to explain it.

I'm having similar issues - and even with the start/stop fill commands it's still a bit all over the place, any ideas?
https://i.imgur.com/PdUf7nr.png
https://i.imgur.com/5Degusz.png

**Comment by kaalleen** [comment]
If you mean the zig-zag lines, it is possible to turn them off (@tyrosinase mentioned). Go into the params dialogue and disable "Underpath" in both tabs, Auto-Fill and Underlay. Underpath is wanted behaviour if you do not use a very loose fill stitch where it could show through. A dense fill stitch will cover these zig-zag lines and they are prefered about the method without underpath, because you will have running stitch around the outline of your fill and this might be visible in the end result.
