### ISSUE TITLE
Simulate command not working

### ISSUE THREAD

**Issue by terrybailey** [inkstitch/inkstitch#807]
When attempting to run the simulate on a very simple design I get
Traceback (most recent call last):

  File "D:\a\inkstitch\inkstitch\inkstitch.py", line 35, in <module>

AttributeError: 'module' object has no attribute 'Simulate'

I don't understand why it is trying to access "D:" as  there is no second drive on this machine.

**Comment by kaalleen** [comment]
Ink/Stitch is packaged with pyinstaller. That's why you see that unexpected path. I am sorry, that you never received an answer. I also suppose, that your question now is already outdated. I hope you managed to get Ink/Stitch working. I'll close the issue now. Please reopen if you have similar issues with the current version of Ink/Stitch... and sorry again!
