### ISSUE TITLE
Attempting to create a Satin Stitch using a font from Adobe

### ISSUE THREAD

**Issue by HTownEmbroidery** [inkstitch/inkstitch#839]
Hello! 

I am trying to use a satin stitch while using a particular font I got from adobe illustrator. I exported it as an SVG file and it seems that all of the nodes and such are on the letters alright! I am just having some trouble in understanding how do I go from a fill stitch to a satin stitch. I have read the wiki, watched the tutorial video, and read multiple articles and still don't seem to understand. All of the tutorials usually have to do with pathing but I am unsure how to replicate the path of these fonts or if that is even necessary given the fact that the nodes are already in the correct places!

I have attached the file I am trying to use a satin stitch for. If you could explain how I use the existing nodes from the SVG file to use a satin stitch that would be extremely helpful!

[HOUSTON Delicato.zip](https://github.com/inkstitch/inkstitch/files/5320612/HOUSTON.Delicato.zip)

Thank you for all your hard work on this helpful software!

**Comment by tyrosinase** [comment]
On 10/2/20 6:37 PM, HTownEmbroidery wrote:
> I am trying to use a satin stitch while using a particular font I got
> from adobe illustrator. I exported it as an SVG file and it seems that
> all of the nodes and such are on the letters alright! I am just having
> some trouble in understanding how do I go from a fill stitch to a
> satin stitch. I have read the wiki, watched the tutorial video, and
> read multiple articles and still don't seem to understand. All of the
> tutorials usually have to do with pathing but I am unsure how to
> replicate the path of these fonts or if that is even necessary given
> the fact that the nodes are already in the correct places!
>
> I have attached the file I am trying to use a satin stitch for. If you
> could explain how I use the existing nodes from the SVG file to use a
> satin stitch that would be extremely helpful!
>
> HOUSTON Delicato.zip
> <https://github.com/inkstitch/inkstitch/files/5320612/HOUSTON.Delicato.zip>
>
> Thank you for all your hard work on this helpful software!
>

I wrote a little tutorial on my blog that addresses this very issue:
https://silverseams.com/2020/03/monogramming-without-a-font/

It's pretty long as it is so I didn't go into all the details of
fine-tuning to minimize jump stitches and whatnot, but it should give
you a starting point.

**Comment by HTownEmbroidery** [comment]
Thank you for your response but I still am having trouble! Whenever I go to remove a node connection they are still connected by a newly created curved line. I have tried to break the path by doing what your article said but they ultimately stay connected. How can I turn my letter into two distinct lines like you did in order to create the satin stitch?
![Regular T](https://user-images.githubusercontent.com/72283184/94979516-cccf6600-04e8-11eb-8f8c-b0baf325c6a3.PNG)
![Curved T](https://user-images.githubusercontent.com/72283184/94979520-cf31c000-04e8-11eb-8812-ffd823d65620.PNG)

**Comment by tyrosinase** [comment]
In this case you want to remove the path between the nodes rather than removing the nodes. Click on the end segment (the base, and the two verticals at the ends of the upper serifs) and then click the "Delete segment between two non-endpoint nodes" to make a gap.

After that you'll want to end up with something like this. I separated the arms from the stem for clarity, don't do that in your actual letter, but: `Break Apart` your shape, and then `Combine` the step pieces and the arm pieces, fill in the segment shown in red, and make sure your rails are all going the proper direction. You probably want to start at the base of the stem and stitch upward, then do the arms. If it's a large letter, instead of just jumping to the far end of an arm you may want to do a little running stitch to reposition. If not, and the jump wants to go to the lower part of the serif, you can go into satin tools and do a flip rails so the jump stays where it'll be covered by the satin.

![bitmap](https://user-images.githubusercontent.com/9473609/94979994-27ba8a80-04f4-11eb-8820-c5aa7f93f292.png)
