### ISSUE TITLE
High Sierra: Encoding Error

### ISSUE THREAD

**Issue by alleycateckert** [inkstitch/inkstitch#892]
MacOS HIGH SIERRA

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
    stdout = stdout.decode(sys.stdout.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc6 in position 56: invalid continuation byte

**Comment by kaalleen** [comment]
Oh, I am sorry. This issue is well known to us. But we are not releasing any updates for High Sierra anymore. If you don't mind to use Ink/Stitch in English, I would suggest you use the English version (if you are not already using it). Encoding errors are seen more often in other languages. Mostly they disguise a more useful error message.

I am sorry, this might not be a big help.

**Comment by kaalleen** [comment]
The next version of Ink/Stitch will include a new and updated build for High Sierra fixing this error.
Therefore I will close this issue now. Please reopen if the error still comes up within the next (upcoming) Ink/Stitch version.
