### ISSUE TITLE
Params on Mac OS Catalina (Inkscape 1.0)

### ISSUE THREAD

**Issue by orianavn** [inkstitch/inkstitch#894]
New to Inkscape and Ink stitch.  When I open Params, dialog flashs 'Params working please wait' then screen blinks and nothing.  I've tried reinstalling Ink Stitch and Inkscape and no luck.  I've tried with my original file as well as just a filled circle.  Any ideas?
<img width="619" alt="Screen Shot 2020-11-17 at 5 42 34 PM" src="https://user-images.githubusercontent.com/10654078/99471858-4e921c00-28fc-11eb-9330-c1c59c15f950.png">

<img width="1440" alt="Screen Shot 2020-11-17 at 5 43 17 PM" src="https://user-images.githubusercontent.com/10654078/99471910-69fd2700-28fc-11eb-876a-ae4cb9e87a99.png">

**Comment by trashk** [comment]
I have the same issue in windows 10.  I have tried version 92.5 and 1.01, removed and reinstalled the apps and the extension folder and the params does nothing.

**Comment by trashk** [comment]
UPDATE: MY ISSUE SOLVED

I had the incorrect version for my OS (in particular I had the Linux version and I am using Windows).

It looks like Inkscape will add anything it finds in the extensions folder since it handles the menu configuration by XML which is real text flatfile based.  Double check that you've got the right stuff for your OS.  

Soudns stupid, but I literally just made that mistake.

Good luck!

TrashK
