### ISSUE TITLE
Recording German tutorial videos 

### ISSUE THREAD

**Issue by Tina-Chris** [inkstitch/inkstitch#897]
Dear developers 
I would like to offer to record tutorial videos in  German language with the most recent version. This is because I think that most persons tend to learn it easier on their mother tongue, than with foreign audio dubbed with subtitles. It's there any advice on how to do this? Through a YouTube  channel?  Send the videos to you to upload on the project page? 
I would like to cover the same topics as in the beginner series, and later move on to more difficult projects.

**Comment by LochanLoch** [comment]
not a DEV but like to see :-)

**Comment by stoffsuchti** [comment]
Would very much appreciate it to have that in German :) YAY.

**Comment by kaalleen** [comment]
Wow, thank you for your offer. This will be very helpful!
I can add you to the Ink/Stitch YouTube channel. All I need is an e-mail adress to which I can send the invitation. Afterwards you can upload your videos as you like.

**Comment by B-ellanna** [comment]
Thanks Kaalleen.
That's much better than a personal blog. Shall I use the "jingle" which
comes at the beginning of the English spoken tutorials for beginners? How
can I send the address in private?
Have a great day.




Kaalleen <notifications@github.com> schrieb am Fr., 27. Nov. 2020, 18:33:

**Comment by kaalleen** [comment]
> Shall I use the "jingle" which comes at the beginning of the English spoken tutorials for beginners?

If you want to use the intro I will search my computer for it and send it to you somehow. But you are free to create an other one if you prefer. We have no rules about it.

I just logged into my YouTube account and noticed that it doesn't trust me enough to make invitations at the moment. It could be a result of not using it for a long time. I try to regain trust, but it stated that it will take a week to do so. Maybe somebody else will be able to invite you a little bit faster @lexelby @wwderw @X3msnake ? Otherwise I will do it at a later time.

My contact: kaaallleeen [Klammeraffe] gmail.com

**Comment by lexelby** [comment]
Sure, it looks like I can do it.  Do I add them as a Manager or Owner?

I just need the email address to add.  You can send it to inkstitch [Klammeraffe] lex.gd

Today I learned a new German word :D

**Comment by kaalleen** [comment]
Thanks.

About the role... I think it really doesn't matter much. The only difference would be the ability to add and remove users.

> Today I learned a new German word :D

Ink/Stitch really becomes a learning platform for all of us :D
