### ISSUE TITLE
-No. 1- Geneva Simple Sans Rounded

### ISSUE THREAD

**Issue by Snake2021** [inkstitch/inkstitch#909]
I have a challange with the "1" within the text tool. 
Discribtion
"1" - no problem
"5" - no problem
"51" doesn´t work
"27.22.2020" - no problem
"27.11.2020" - doesn´t work 
Everytime a "1" follows any letter or number the tool isn´t able to transform ist correctly. 
I got the message: 
"1 (autosatin3): error: Satin column: A rung intersects a rail more than once. Each rung should intersect both rails once.
1 (autosatin3): error: Satin column: A rung intersects a rail more than once. Each rung should intersect both rails once."

**Comment by MK-12-20MM** [comment]
Just putting my observation with this..

I tried the 1 and cannot get it to work at all. I get the same error.  Looks to me the font is okay just that the auto-route that the lettering tool applies is causing the hickup. 

Looking at the font it works ok ..

![font](https://user-images.githubusercontent.com/10312448/101295564-0754c800-37e4-11eb-8a41-fae4275288a1.JPG)

Applying the auto-route satin causes an issue with the rungs or doing it manually causes similar results.  More difficulty is that the letter or text  is not written so you can't see what the problem is as the lettering tool exits.

![error](https://user-images.githubusercontent.com/10312448/101295648-7c280200-37e4-11eb-8209-966f997e3b5e.JPG)

**Comment by kaalleen** [comment]
I believe this has been fixed.

Ink/Stitch is more forgiving with rungs and shouldn't result into an error on this one.

Please reopen, if this is still an issue.
