### ISSUE TITLE
Commands applied to filled objects are duplicated

### ISSUE THREAD

**Issue by MarkMLl** [inkstitch/inkstitch#913]
Debian Buster with Inkscape 1.0.1 (from the backports repository) with Inkstitch 1.29.1. If a trim or pause command is applied to e.g. a filled rectangle where the stroke and fill are the same colour, a single command marker is shown. However when the document is exported to a .pes file or processed by Stitch Plan Preview the command is duplicated and separate command markers are shown for the fill and stroke, in addition an extra colour change command is inserted between the fill and stroke (with an extra thumbnail in the pec section) even though the colour is unchanged and this is interpreted by the machine as a spurious trim-and-pause command.

I have written a .pes parser and can supply dump files to illustrate this. I could probably fix the problem in a postprocess pass but I think it would be better done where the file was originally created.

As background, Brother support acknowledge that a trim is ignored by an Innovis-97E. A .pes file containing pauses appears to crash the machine during load from USB (reset triggered by watchdog timeout?) so the only way of to cut top/bottom tails is a colour change.

**Comment by lexelby** [comment]
Oh of course, this makes a lot of sense, because the stroke and fill are treated as separate "embroidery elements" and stitching for each is generated individually (including the trim). I'd never thought of that.

I'm gonna call this "working as expected".  A workaround to get the behavior I think you want is to duplicate the object (copy and then Paste In Place) and set one as only stroke and the other as only fill.
