### ISSUE TITLE
Params won't open

### ISSUE THREAD

**Issue by tray703** [inkstitch/inkstitch#963]
I have watch many videos followed all the instructions to what I see and can make out of them ;/. I have tried everything multiple times and the extension always shows in Inkscape but whenever I try to open params I get. messaging that says "params is working please wait" and nothing happens. It also doesn't give me the part that says embroider but im not sure if that has to come after params. SOMEONE HELP. I have a Big Sur Mac and I have even done the terminal part that it says on the website.

**Comment by kaalleen** [comment]
Hm, that's weired. I have no idea what is causing it. Maybe a macOS user can help us with this question?!
It could be a missing library or something like that. But usually we would get an error message in this case. On Linux we observed privilege issues. I don't know if they could cause something like this on an apple computer as well.

**Comment by JoSeaMor3** [comment]
I went through installing/uninstalling 3 times because the video instructions are based on older versions of Windows and the programs. I have tried finding the "unpacked" items to make params work, and it looks like everything was unpacked. Everything in the Extensions section of Inkscape is there, but greyed out. I am not a programmer, just someone who wants to learn how to turn original drawings into embroidery files. This is an ongoing issue based on youtube comments and unfortunately, for me not being a programmer, it hasn't been explained specifically where to go and how to find what I need to find.

**Comment by MK-12-20MM** [comment]
@JoSeaMor3 


I few people have had issues with extracting the extension and creating an additional folder within the extensions folder of Inkscape.  

Ensure your \AppData\Roaming\inkscape\extensions looks like this.  Alternatively you can extract Inkstitch in place in your downloads directory and just copy the files and place them in the \AppData\Roaming\inkscape\extensions folder.   Make sure to clean out your extensions folder to avoid duplicates. 

![Capture](https://user-images.githubusercontent.com/10312448/105845953-1f092b00-5fa1-11eb-9bd5-1ab0150c0bfc.JPG)

**Comment by JoSeaMor3** [comment]
So this is what I see because it doesn't loo exactly like yours, but when I open Inkscape > extensions and click on the file location, when it comes up it shows inkstitch. I've installed and uninstalled multiple times and this is as close as I got. Mine didn't say AppData, and I could not find it. So, I deleted it, re-extracted it to get the 3rd screenshot but it still doesn't show up when I open Inkscape, params is still greyed out. I truly appreciate your help. I cannot figure out what I'm doing wrong!
![inkstitich3](https://user-images.githubusercontent.com/78003263/105929241-29650c80-6015-11eb-8b65-e764b492e651.PNG)

[[](url)
![inkstitch1](https://user-images.githubusercontent.com/78003263/105926601-5662f080-6010-11eb-97d9-34440885b986.PNG)
![inkstitch2](https://user-images.githubusercontent.com/78003263/105926606-59f67780-6010-11eb-8415-50d8cf62f7a1.PNG)

](url)

**Comment by JoSeaMor3** [comment]
@MK-12-20MM THANK YOU! I have them in the right spot now and nothing greyed out! Now comes the test on if I can get my first inkscape drawing converted into a .pes file! All sorts of new hobbies going on here!

**Comment by Elmarievdm** [comment]
> I have watch many videos followed all the instructions to what I see and can make out of them ;/. I have tried everything multiple times and the extension always shows in Inkscape but whenever I try to open params I get. messaging that says "params is working please wait" and nothing happens. It also doesn't give me the part that says embroider but im not sure if that has to come after params. SOMEONE HELP. I have a Big Sur Mac and I have even done the terminal part that it says on the website.

Have you been able to solve this - I seem to have the same problem.

**Comment by kaalleen** [comment]
@Elmarievdm Do you have greyed out menu items? If so, make sure you do not have an extra folder when you extract your files, all the inx files will be placed directly inside the extensions folder. Beside of one folder named inkstitch.

**Comment by kaalleen** [comment]
The installation process should have become easier with the newest release. Hopefully it helps to resolve this issue.
If there are still trouble, please reopen.
