### ISSUE TITLE
unable to flip satin column rails

### ISSUE THREAD

**Issue by tate6** [inkstitch/inkstitch#992]
I'm working on a windows laptop (an acer swift if that needs to be said, I know absolutely nothing about computers or anything related. it's a miracle I can work this thing) my old laptop was also running windows and I never had this problem.

I have reinstalled the inkstitch pack, and just recently uninstalled and reinstalled inkstitch all together. it hasn't worked at all since I've been using this laptop (since new years of this year) wasn't a problem until I was given some work to do and now a major tool is just not available to me. both the hot key option and the drop down option are useless. anything helps!!

**Comment by Rrreutel** [comment]
You can flip the direction of a path line by selecting a single node on the (sub)path line you want to flip, then choose menu Path -> Reverse. Like this:

![path_reverse](https://user-images.githubusercontent.com/5664169/105640354-defd5780-5e7d-11eb-808e-e45c19ff8a03.png)

If the marker arrows for the subpath/rails are not showing (actually they are not showing in my small test) then you can temporarily set a line marker in order to see their direction like this:

![marker1](https://user-images.githubusercontent.com/5664169/105640207-0dc6fe00-5e7d-11eb-9c3f-1c1640e44aae.png)

PS github issues are generally not meant for support but for filing bug reports or feature requests. In this case it might actually be a bug that the direction marker is not showing on the subpaths, but I'm fairly new to Ink/Stitch myself, not sure.

**Comment by kaalleen** [comment]
> github issues are generally not meant for support but for filing bug reports or feature requests

We are fine with any type of questions our users have. Don't mind asking if you are in trouble ;)

I am not certain if we are talking about the flip satin columns function from Ink/Stitch or the reverse path function in Inkscape.
The flip satin columns option will do something that might not be immediately obvious but helpful when you carefully plan your stitch order. It will make the satin to start stitching on the other rail as it was before. Maybe this link will help you to see how it is functioning: https://inkstitch.org/docs/satin-tools/#flip-satin-column-rails

Is that not working anymore?

The other issue mentioned is about the reverse path function offered by Inkscape and will change the path direction. In Inkscape 1.0 there is a bug which was fixed in Inkscape 1.0.1. In Inkscape 1.0 it wasn't possible to change direction of only one subpath. So if you are using this Inkscape version you would need to break apart the satin column first in order to change the direction of only one side. It would be better to update to a newer Inkscape version in that case.

If you are not seeing the redlines have a look at this link here: https://inkstitch.org/docs/customize/#enabling-path-outlines--direction 

Also watch out for this symbol being enabled while in node editor mode (top right in the toolbar).
![path_outline](https://user-images.githubusercontent.com/36401965/105640941-77490b80-5e81-11eb-9012-de7e2115f163.png)

**Comment by tate6** [comment]
glad to know I'm not posting in the wrong spots lol, my issue is with the flipping the columns specifically with ink/stitch. in the past I was able to change the direction with either the hot key or the drop down menu option (picture added to help with any confusion) I'm able to see the redlines to show me what direction the stitches are going, but I don't have a way to change that. (if this still isn't clear, here's what I'm not able to do anymore exactly https://youtu.be/U7YtajKlftQ?t=367)

the reverse path option given by Rrreutel does work (life saver!!!) like the flip option I'm having problems with used to, but I would like to have inkstitch running without any of the problems that I'm having.

**Comment by kaalleen** [comment]
@tate6 we somehow ost focus on your issue. Were you able to solve it yourself?
